- test/core/test/timers.test.ts
The timeout were not small enough, and this test makes it looks like the full test suite is slow. This also skips the `timeout cyclic` test. We should find another way to test it that doesn't blocks the full suite
> test: speed up timers.test.ts

- package.json
- test/lit/test/basic.test.ts
After some testing it seems there is a problem on `happy-dom` with custom elements and `reactive-element` library.
`reactive-element` has a `DEV_MODE` flag that is initialized to `true` (`const DEV_MODE = true;`), that forces to eval the `localName` of the custom element (line 652 on `node_modules/.pnpm/@lit+reactive-element@1.0.2/node_modules/@lit/reactive-element/development/reactive-element.js`).
Since `happy-dom` uses `this.tagName.toLowerCase()` on the `localName` getter (line 112 on `node_modules/.pnpm/happy-dom@2.25.0/node_modules/happy-dom/lib/nodes/element/Element.js`), then we got the error `TypeError: Cannot read properties of null (reading 'toLowerCase')` because the `tagName` is missing from the custom element.
I will send also a PR to fix it on `happy-dom`.
> test: fix `lit`

- scripts/get-contributors.ts
According to the GitHub Rest API [doc](https://docs.github.com/en/rest/reference/repos#list-repository-contributors), add response data type to avoid any.
> chore: improve type definition to avoid any

- docs/api/index.md
I can see that a `test.skip` section is missing too. Let me know if want me to give it a go to add that as well.
> Fix API doc typos

- docs/main.css
Current behavior:
Expected behavior:
> Remove that wierd x-axis scrollbar in main page

- docs/guide/index.md
- packages/vitest/src/node/pool.ts
- scripts/get-contributors.ts
Since the repo moved to vitest-dev, this PR replaces `antfu-sponsors/vitest` with `vitest-dev/vitest`.
> chore: antfu-sponsors -> vitest-dev

- docs/guide/mocking-date.md
- packages/vitest/src/integrations/utils.ts
- test/core/test/date-mock.test.ts
Renaming mockdate methods to inline them with timer mocks.
Also now they should not confuse people coming from jest and using theirs `jest.setSystemTime` method, that works with timer mocks and not `Date`.
> refactor!: renaming mockdate methods

- pnpm-lock.yaml
- test/testing-lib-react/package.json
- test/testing-lib-react/src/App.test.tsx
- test/testing-lib-react/src/App.tsx
- test/testing-lib-react/src/hooks/useCounter.test.ts
- test/testing-lib-react/src/hooks/useCounter.ts
As per the title, added a simple useCounter example to the already existing react-testing-library setup.
Example was taken directly [from here](https://github.com/testing-library/react-hooks-testing-library) so I think it provides a solid starting point.
> feat(examples): added simple hook counter example

- packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts
When we use `pretty-format` to display the error messages. It not applying the plugins correctly. 
Pretty-format will search for a plugin reading the `$$typeof` from [Asymmetric object](https://github.com/facebook/jest/blob/main/packages/pretty-format/src/plugins/AsymmetricMatcher.ts#L92)
Test example:
```javascript
expect('string').not.toEqual(expect.any(Number))
```
Generate this diff message:
Now:
And with objects
Now:
> fix: asymmetric matcher diffting message

- docs/api/index.md
an is used before the word that begins with the vowel pronunciation
> docs(api/index.md): Grammatical errors

- package.json
It seems there was a renaming on the package name, and the scripts for `test:ci` and `test:all` are still filtering the old name, causing problem on windows.
> fix: update `vitest` filter on `test:*` scripts

- test/testing-lib-react/src/App.test.tsx
This example used fireEvent, though it is encouraged from the Testing Lib team to use userEvent.
> fix: testing lib react example to use userEvent

- packages/vitest/src/node/mocker.ts
How to reproduce:
Remove `__mocks__` directory over `/test/mocks/__mocks__`. Then run only `mocks` tests. You will see:
> Fix: when there are not __mocks__ folder

- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/chai/jest-utils.ts
- test/core/test/jest-expect.test.ts
Make `toStrictEqual` compatible with jest's version
https://jestjs.io/docs/expect#tostrictequalvalue
> fix: compatibility with `jest`'s `toStrictEqual`

- packages/vitest/src/coverage.ts
https://nodejs.org/api/deprecations.html#dep0147-fsrmdirpath--recursive-true-
> refactor: use fs.rm instead of the deprecated fs.rmdir

- test/core/test/serialize.test.ts
Hey :)
I was working to handle Array errors but I see @userquin fixed it with https://github.com/vitest-dev/vitest/pull/337 
So I add a test cases where an object has getter/setters attributes for output validation 👍🏽
> test: should handle object with getter/setter correctly

- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/index.ts
This change ensures that vite buildEnd hook is called and resources are cleaned up gracefully
> feat(cli): graceful close of vitest in watch mode

- packages/vitest/src/runtime/collect.ts
- test/core/test/only.test.ts
`test.only` and `describe.only` now have file scope
> fix: only mode with file scope

- packages/vitest/src/coverage.ts
Honestly, I'm not exactly sure what black magic is happening with C8 and the like, but as far as I understand this is a needed change. I don't think C8 was actually _doing_ any source mapping prior to this, because it cached the coverage map when `report.getCoverageMapFromAllCoverageFiles()` was called.
Here is what Vitest is generating for source maps:
[sourcemapthingy.zip](https://github.com/vitest-dev/vitest/files/7785683/sourcemapthingy.zip)
use this site to view it: https://sokra.github.io/source-map-visualization
You'll notice that the source mapping seems pretty much perfect, at least to me. I think any further issues with coverage are related to C8 itself.
> fix: C8 sourcemaps

- docs/guide/index.md
The script for printing help was pointing at `vite`, not `vitest`.
I also added the single-run option `--run` to the docs here.
> docs: updat cli section

- packages/vitest/src/node/execute.ts
- pnpm-lock.yaml
- test/cjs/package.json
- test/cjs/test/interpret-default.test.tsx
Should fix all `exports.default = {}` treated as `{ default: { default: {} } }` problems
Related: https://github.com/vitest-dev/vitest/issues/352, https://github.com/vitest-dev/vitest/issues/243
> fix: proxy nested default

- packages/vitest/src/index.ts
- packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/chai/jest-extend.ts
- packages/vitest/src/integrations/chai/types.ts
- packages/vitest/src/runtime/run.ts
- test/core/test/jest-expect.test.ts
Related: https://github.com/vitest-dev/vitest/issues/43
> feat: more expect compatible APIs

- docs/guide/index.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/runtime/collect.ts
- packages/vitest/src/types/config.ts
Related: https://github.com/vitest-dev/vitest/issues/280
CAC allows passing array as an argument only if you repeat option, like: 
```
vitest --findRelatedTests src/timeout.ts --findRelatedTests src/mockedA.ts
```
I personally think jest's way (using space as separator) is more convinient
> feat: findRelatedTests flag, to run only changed tests

- packages/vitest/src/plugins/mock.ts
Does what it says on the tin.
`hires: true` is important for code coverage.
> fix(mock): generating source map with `hires: true`

- packages/vitest/src/node/cli.ts
Tiny PR to allow defining `isolate` option with the CLI. Currently it can only be configured through a config file.
> feat(cli): add isolate option

- packages/ui/client/components/Navigation.vue
The navigation was not scrollable, which also prevented suites from being scrollable and thus cutting of long lists of tasks.
I noticed that the code mirror also cannot be scrolled vertically, but I didn't find a fix.
Adding `overflow-y: auto` to the appropriate element shows the scrollbar, but it's still not scrollable.
It may be an issue with the `CodeMirror` library.
> fix(ui): make navigation scrollable

- packages/ui/client/components/FileDetails.vue
- packages/ui/client/components/views/ViewModuleGraph.vue
- packages/ui/client/composables/module-graph.ts
This PR makes the module graph more stable by not recreating the graph model every time the component loads.
Node positions are only initialized if they were not set before, this approach saves them.
I also noticed that the provided graph data is invalid (in particular for the test `inline-snap.test.ts`.
Some modules list imports that are neither included in `externalized` nor `inlined`.
Those imports and all nodes without edges are filtered, for now, preventing crashes.
Node positioning can still be a bit unstable when opening the module graph view.
This is caused by the d3 simulation kicking in and re-applying all forces, including centering.
The same thing applies when (un-)focusing a node.
I'll update my library to make the alpha value of the simulation customizable sometime soon. …
> fix(ui): make module graph more stable

- packages/vitest/src/runtime/error.ts
- test/core/test/serialize.test.ts
When we parse a Error object without expected or actual. `processError` add any of both attributes with `'undefined'` as a value.
> Fix: do not add expected/actual attributes in a object when does not exist

- packages/vitest/src/runtime/error.ts
- test/core/test/__snapshots__/serialize.test.ts.snap
- test/core/test/serialize.test.ts
- test/fails/fixtures/stall.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
The serialization logic of error objects would mutate the error object in-place,
retaining its original constructor and leaving non-enumerable properties intact.
When an object of type `Error` is sent over a `MessagePort` an issue may occur
which resulted in the tests stalling. The exact reason as to why the tests get
stuck before this fix are unclear, but serializing the `Error` instance into
a plain object avoids the issue.
This commit changes the serialization logic to create a new object without
its original constructor and then copies over all properties to the clone, which
prevents the tests from stalling. An integration fixture is added in the `fails`
workspace to prevent regressions.
These changes make the custom `nameStr` and `stackStr` properties redundant,
as `name` and `stack` …
> fix: prevent tests from stalling if an error occurs (fix #374)

- packages/vitest/src/runtime/error.ts
This PR fix the serialization error from #407 since `expected` and/or `actual` can be both boolean/falsy, `nr ci`, `pnpm run test:all` and `vitest -o --api` stop working on windows, also with some memory error on node:
```shell
file:///F:/work/projects/quini/GitHub/antfu/vitest-main/packages/vitest/dist/diff-d71c4271.js:311
linesAndNewlines = value.split(/(\n|\r\n)/); // Ignore the final empty token that occurs if the string ends with a new line
^
TypeError: value.split is not a function
at Diff.lineDiff.tokenize (file:///F:/work/projects/quini/GitHub/antfu/vitest-main/packages/vitest/dist/diff-d71c4271.js:311:32)
at Diff.diff (file:///F:/work/projects/quini/GitHub/antfu/vitest-main/packages/vitest/dist/diff-d71c4271.js:32:39)
at diffLines …
```
> fix: broken expected and actual

- packages/vitest/src/runtime/error.ts
- test/core/test/jest-expect.test.ts
- test/core/test/serialize.test.ts
This reverts https://github.com/vitest-dev/vitest/pull/407 and https://github.com/vitest-dev/vitest/pull/409 because `null` or `undefined` could be `actual` or `expected` value.
Relates to https://github.com/vitest-dev/vitest/issues/411
> Revert: do not add expected/actual attributes in a object when does no exist

- packages/vitest/src/node/index.ts
We don't use Vite watch functionality in run mode and setting up file watcher takes considerable time:
Before:
| name   | time  |
|---|---|
|  vitest:vue | '4.147s ± 12.89%' |
| jest:vue | '4.629s ± 1.96%'  |
After:
| name | time |
|---|---|
| vitest:vue | '3.438s ± 1.84%' |
| jest:vue | '4.658s ± 3.04%' |
> perf: disable vite file watcher

- README.md
- Fixed links that were broken due to moving examples.
- Added a link to Svelte examples.
> docs: fix the link to Components testing

- packages/vitest/src/integrations/jest-mock.ts
It seems that the parameters `T` and `Y` were confused.
https://github.com/vitest-dev/vitest/blob/1a37c6eefc86df2cb723a3dde11cabfce65b361c/packages/vitest/src/integrations/jest-mock.ts#L20-L26
Test case:
```ts
const sum = vi.fn((a: number, b: number): string => `${a}${b}`)
```
Before:
```ts
sum.mock.calls //  string[]
sum.mock.results //  MockResult<[a: number, b: number]>[]
```
After:
```ts
sum.mock.calls; // [a: number, b: number][]
sum.mock.results; // MockResult<string>[]
```
> fix: Wrong argument in `JestMockCompatContext`

- packages/ui/client/composables/client.ts
- packages/ui/client/composables/module-graph.ts
- packages/vitest/src/api/setup.ts
- packages/vitest/src/api/types.ts
- packages/vitest/src/types/general.ts
Previously, the edges of a graph were not updated when a module was externalized (rewritten).
Closes #401
> fix(api): generate valid module graph

- packages/vitest/src/node/config.ts
Was scratching my head a bit not knowing why there were import issues when providing a string value for `setupFiles`. Looks like the TS defs show that it accepts a string value, however providing one, such as:
```ts
{
setupFiles: "./vitest.setup.ts"
}
```
would result in the following due to `Array.from("./vitest.setup.ts")`
```ts
resolved.setupFiles = [".", "/", "v", "i", ...]
```
The TS defs are listed here, so alternatively we could only accept string arrays, along with updating the docs.
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/types/config.ts#L145-L148
https://github.com/vitest-dev/vitest/blob/main/docs/config/index.md?plain=1#L232-L236
> fix(config): correctly parse string values for `setupFiles`

- packages/vitest/src/reporters/tap.ts
This marks skipped and todo tests as 'ok' instead of 'not ok'
> fix: make tap reporter compatible with mocha xunit transform

- packages/vitest/src/node/execute.ts
- packages/vitest/src/node/mocker.ts
- packages/vitest/src/types/general.ts
- test/core/__mocks__/timers.ts
- test/core/src/exec.ts
- test/core/test/mock-internals.test.ts
Automocking didn't work for node builtins, so I moved automocking before calling a module instead of after
Also `importMock` had cache, but I think it should be brand new every time you call it
Related: https://github.com/vitest-dev/vitest/issues/453
> fix: mock node builtins

- packages/vitest/src/integrations/jest-mock.ts
- test/core/test/jest-mock.test.ts
Test case
```ts
const SomeClass = vi.fn(() => {});
expect(SomeClass.mock.instances.length).toBe(0);
new SomeClass();
expect(SomeClass.mock.instances.length).toBe(1);
SomeClass.mockClear();
expect(SomeClass.mock.instances.length).toBe(0); // AssertionError: expected 1 to equal 0
```
> fix: `mockClear` doesn't clear `instances`

- packages/ui/client/components/FileDetails.vue
- packages/ui/client/components/views/ViewModuleGraph.vue
This PR re-adds the custom size for the graph container that is necessary because of its offset.
It also uses the new built-in automatic resizing.
> fix(ui): reduce graph container size

- docs/.vitepress/config.ts
- docs/guide/debugging.md
Just some basic documentation on how to setup a launch configuration to debug the currently selected test file in vitest.
Happy to expand if there are suggestions
> Add info how to setup debugging in VSCode

- docs/src/components/Home.vue
Bug on big screens(More than ~1940px)
> docs: Fix styles for "Sponsored by" block on homepage

- docs/config/index.md
- docs/guide/index.md
- packages/vitest/src/reporters/index.ts
- packages/vitest/src/reporters/json.ts
Fixes #108
Adds a JSON reporter, available with `--reporter json`.
It produces a JSON report of the test run in a similar format to the default Jest one (produced with `--json`, see https://jestjs.io/docs/cli#--json).
The Jest result format is defined [here](https://github.com/facebook/jest/blob/fe5e91c1b86323ab02b3de9d322b77e65a64e75a/packages/jest-test-result/src/types.ts#L58-L75).
Vitest JSON reporter uses a simplified version of this format:
```ts
interface TestResult {
displayName?: string
failureMessage?: string | null
skipped: boolean
status?: string
testFilePath?: string
}
interface AggregatedResult {
numFailedTests: number
numFailedTestSuites: number
numPassedTests: number
numPassedTestSuites: number
numPendingTests: number
numTodoTests: number
numPendingTestSuites: number …
```
> feat: json reporter

- packages/vite-node/src/client.ts
- packages/vite-node/src/utils.ts
- pnpm-lock.yaml
- test/cjs/package.json
- test/cjs/test/interpret-default.test.tsx
- test/cjs/test/lodash.test.ts
Fix #507 
the fix of #479 added this
```diff
function proxyMethod(name: 'get' | 'set' | 'has' | 'deleteProperty', tryDefault: boolean) {
return function(target: any, key: string | symbol, ...args: [any?, any?]) {
const result = Reflect[name](target, key, ...args)
+    if (typeof target.default !== 'object')
+      return result
if ((tryDefault && key === 'default') || typeof result === 'undefined')
return Reflect[name](target.default, key, ...args)
return result
}
}
```
but for some library like `lodash` that export function with additional property will cause error
not sure what is the best strategy to handle this case ( maybe detect with `Object.keys` ?)
> fix: improve cjs proxy

- examples/README.md
- examples/basic/README.md
- examples/basic/package.json
- examples/basic/test/__snapshots__/suite.test.ts.snap
- examples/basic/test/basic.test.ts
- examples/basic/test/suite.test.ts
- examples/basic/vite.config.ts
- pnpm-lock.yaml
Adds the example in https://vitest.dev/new to the examples folder, so we can point the starter to it and update it through github
> feat: basic example

- examples/README.md
- scripts/update-examples.ts
In examples page, when you click the *Play Online*, it opens up the example in Stackblitz. However, when user tries to edit something and save, there's generally a 5 second period where everything goes inactive for a while, then page reloads, forking the project. 
This is not great UX, hence this PR changes the behavior to fork when the project is being initialized
> chore: use fork for Stackblitz demo

- examples/react-testing-lib-msw/package.json
- examples/react-testing-lib/package.json
- examples/svelte/package.json
- examples/vue2/package.json
- examples/vue2/pnpm-lock.yaml
- pnpm-lock.yaml
Some examples rely on testing library break on stackblitz due to absence of jsdom. This PR adds JSDom as dev dependency to fix the issue.
Thanks to @patak-dev for the discussion on it
> test: fix examples deps

- examples/README.md
- examples/basic/package.json
- examples/lit/package.json
- examples/mocks/package.json
- examples/puppeteer/package.json
- examples/react-enzyme/package.json
- examples/react-mui/package.json
- examples/react-storybook-testing/package.json
- examples/react-testing-lib-msw/package.json
- examples/react-testing-lib/package.json
- examples/react/package.json
- examples/svelte/package.json
- package.json
- pnpm-lock.yaml
- scripts/update-examples.ts
This PR modifies the links for StackBlizt examples on docs to run the UI: `ruby`, `vitesse` and all `vue` will not run on UI, sometimes first run works but next runs fail on UI.
I also add a new script on root `package.json` to generate the `REAMDE.md` for the examples on docs.
@antfu You should remove some folders from your local examples directory, there are 2 examples missing: `solid` and `testing-library-jest-dom` (moved to `react-testing-lib`)
> feat: start tests with ui on stackblitz

- examples/README.md
- examples/basic/.stackblitzrc
- examples/lit/.stackblitzrc
- examples/mocks/.stackblitzrc
- examples/puppeteer/.stackblitzrc
- examples/react-enzyme/.stackblitzrc
- examples/react-mui/.stackblitzrc
- examples/react-storybook-testing/.stackblitzrc
- examples/react-testing-lib-msw/.stackblitzrc
- examples/react-testing-lib/.stackblitzrc
- examples/react/.stackblitzrc
- examples/ruby/.stackblitzrc
- examples/svelte/.stackblitzrc
- examples/vitesse/.stackblitzrc
- examples/vue-jsx/.stackblitzrc
- examples/vue/.stackblitzrc
- scripts/update-examples.ts
Adds a `.stackblitzrc` to each example so we can define what script should run (and later other options) in each of them, instead of having to maintain a separate list. This will also allow the SB folks to point a clean URL with a table on their side, and we can do updates without their intervention
> chore: .stackblitzrc in examples

- packages/vitest/src/coverage.ts
c8 v7.11.0 introduced an `extension` option, allowing to specify extensions that aren't covered by default (default are defined via https://github.com/istanbuljs/schema/blob/master/default-extension.js). It's currently possible to use with an explicit cast in `vite.config.ts` but exposing it would remove the need for this workaround.
See https://github.com/bcoe/c8/commit/ff01cd832a155494892b24c30c5a1c8f0169fd8e
> feat: allow extension option for coverage

- packages/vitest/src/coverage.ts
Adds default extensions for c8 coverage to include `.svelte` and `.vue` out of the box.
> feat: smarter default extensions for coverage

- docs/config/index.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/reporters/json.ts
- packages/vitest/src/types/config.ts
This allows to write the JSON report to a file (similar to what Jest does with `--outputFile`, see https://jestjs.io/docs/cli#--outputfilefilename)
Usage:
```
pnpm test:run -- --reporter json --output-file report.json
```
> feat: reporter output file

- packages/vite-node/package.json
`./vite-node.js` doesn't exist, when I run `pnpm install` will cause error.
> fix(vite-node): use .mjs instead of .js for cli

- docs/guide/index.md
added example Svelte project that use Vitest
> docs: add gridjs-svelte on projects using vitest

- packages/vitest/src/node/core.ts
This PR will fix the problem in https://github.com/vitest-dev/vitest/issues/277#issuecomment-1013925043.
> fix(vitest): respect process.exitCode when exit method is called

- packages/vite-node/src/utils.ts
- test/core/test/file-path.test.ts
Fixes #535
This PR updates `toFilePath` to handle first level catalog in unix system and adding a test file for it.
- The `dirname(root)` call will return `'/'` when `root` is first level catalog (eg. `root = '/folder'`) which is the root cause of this issue
- The test/implementation will run differently on Windows and Unix, so I put a simple `if(isWindows)` to separate the test
https://github.com/vitest-dev/vitest/blob/9626fdef58f1e2cd5d3a77d94194d01b3d7c1d81/packages/vite-node/src/utils.ts#L27-L43
> fix: improve file path handling in first level catalog (fix #535)

- packages/vitest/src/integrations/snapshot/client.ts
- packages/vitest/src/integrations/snapshot/port/utils.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/types/general.ts
- packages/vitest/src/utils/base.ts
- test/core/test/snapshot.test.ts
- test/core/test/utils.spec.ts
Current `deepMerge` is not suitable for common cases, it was designed with `jest-snapshot` in mind.
This pr splits `deepMerge` into to functions: one for snapshots, and one for common usage. Snapshot merge function will merge any objects so it can then be serialized, so types don't matter to it
> refactor: split deepMerge and deepMergeSnapshot

- docs/config/index.md
https://github.com/vitest-dev/vitest/blob/a1e2b068e8aa12d603cf0bb252347a7109614283/packages/vitest/src/constants.ts#L7
> docs: update `exclude` documentation to match the latest implementation

- packages/ui/client/components/CodeMirror.vue
- packages/ui/client/components/FileDetails.vue
- packages/ui/client/components/Modal.vue
- packages/ui/client/components/ModuleTransformResultView.vue
- packages/ui/client/components/views/ViewConsoleOutput.vue
- packages/ui/client/components/views/ViewEditor.vue
- packages/ui/client/components/views/ViewModuleGraph.vue
- packages/ui/client/directives/tooltip.ts
- packages/ui/client/styles/main.css
- Related to #526 
- fix: Make sure code editor cannot be blank even after several saves
- feat: Close Graph modal on escape key press
- feat: Render console tab more discrete + add info text when no logs is available 
- fix: Put graph code in readonly (no cursor)
> fix(ui): ui improvements

- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/core.ts
> fix: fix node crash under Windows (fix #582)

- docs/guide/features.md
`it` is missing from the import statement in the sample code, so it has been added. also, add import statement to `.concurrent`
> chore(docs): add "it" to the guides/features.md import statement

- packages/vitest/src/index.ts
- packages/vitest/src/integrations/chai/index.ts
- packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/jest-mock.ts
- packages/vitest/src/integrations/snapshot/client.ts
- packages/vitest/src/integrations/timers.ts
I am using `Vi` namespace since as I saw from others in discord, this is preferred way to use vitest
> feat: move matcher types to Vi namespace

- packages/vitest/src/node/core.ts
Fixes #442
What was happening with #442 is that `onChange` was called for a file. That adds it to `changedTests`. After that  `onChange` was triggered for a file in `.idea` folder. And because `changedTests` is not empty another rerun was scheduled.
https://github.com/vitest-dev/vitest/blob/2509e06cc7d94b1b0354867a3143babe65eeafa1/packages/vitest/src/node/core.ts#L285-L287
Fixed by returning from `handleFileChanged` indication whether `changedTests` was mutated and rerun it needed.
> fix: don't rerun more then needed in watch mode (fix #442)

- docs/api/index.md
- packages/vitest/src/index.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- test/core/test/jest-expect.test.ts
This PR does a few things:
- Fixes #598
- Uses the same algorithm for `toBe`, `toMatchObject` and `toEqual` that jest uses
- Removes assymetric support for chai equality - this removes ambiguity. Example: when you have an assymetric mathcher in `toEqual` and THE SAME object, but without assymetric matcher, in another `toEqual`, the test might fail for one, but not for the other because we call different equality functions for each one
- Rename `asymmetricEquals` to `jestEquals` to better represent what it is
> fix: toBe/toEqual/toMatchObject expect compatability

- packages/vitest/src/coverage.ts
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/worker.ts
Fixes #378
For now this is just a proof of concept.
~~Tested on fluent-vue and vitest reports incorrect coverage for it.~~ With detailed coverage enabled it is much better now.
~~It still reports wrong code lines though.~~
edit:
Coverage is almost the same as it would be if Vitest waited for all coverage files to finish writing to disk. Tested on fluent-vue.
With "wait for coverage to be written" fix:
File                    | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------|---------|----------|---------|---------|-------------------
All files               |   93.55 |    92.66 |   86.84 |   93.55 |                   
src                    |   93.64 |    96.92 |      88 |   93.64 |                   
TranslationContext.ts |     100 |      100 | …
> fix: collect coverage using node inspector (fix #378)

- packages/vitest/src/node/config.ts
Fixes #616
Options were merged here already: https://github.com/vitest-dev/vitest/blob/b9d092b5fb098ec9836d8e8ca9088c042f945457/packages/vitest/src/node/plugins/index.ts#L22
This causes reporters array to have duplicate entries.
> fix: do not merge options multiple times (fix #616)

- packages/vitest/src/runtime/run.ts
Fixes #620
Turns out there is no need to start inspector when inspecting local process
> fix: do not start node inspector (fix #620)

- packages/vitest/package.json
- packages/ws-client/package.json
- pnpm-lock.yaml
@d3lm deployed a fix for `ws` 8.4.1+ for StackBlitz. We should no longer need to fix the `ws` version to 8.4.0. We still need to release and confirm that SB works as expected.
I tested my reproduction (only using `ws`) and is now working:
https://stackblitz.com/edit/node-rw7h6i?file=index.mjs&terminal=start
> chore: update ws to 8.4.2

- docs/config/index.md
Closes #617.
Another solution would be to wrap the heading in a  `span`. But this would alter the DOM. Using `h4` directly does not work.
> docs: escape dot to prevent parsing of title as url

- .editorconfig
- .gitattributes
- packages/vitest/src/node/plugins/globalSetup.ts
- packages/vitest/src/node/plugins/index.ts
- test/global-setup/index.html
- test/global-setup/setupFiles/another-vite-instance.ts
- test/global-setup/test/global-setup.test.ts
- test/global-setup/vitest.config.ts
and add test launching a vite instance
suggested by @antfu on discord
related: #522
> refactor: use vite-node to load globalSetup 

- packages/vitest/package.json
- packages/vitest/src/integrations/timers.ts
- pnpm-lock.yaml
- test/core/test/date-mock.test.ts
- test/core/test/timers.test.ts
- test/reporters/tests/reporters.spec.ts
Fake timers are very intrusive and cause issues with promises.
This PR allows to call `vi.setSystemTime()` without enabling fake timers. This will mock just the current date using `mockdate`.
Fixes: #621
> feat: allow to mock date without fake timers (fix #621)

- package.json
- packages/ui/client/auto-imports.d.ts
- packages/vitest/LICENSE.md
- packages/vitest/rollup.config.js
- packages/vitest/src/index.ts
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- packages/ws-client/rollup.config.js
- pnpm-lock.yaml
- test/core/test/each.test.ts
- test/core/test/hoist-import.test.ts
- test/core/test/jest-expect.test.ts
- test/core/test/jest-mock.test.ts
- test/related/tests/not-related.test.ts
- test/related/tests/related.test.ts
- test/related/tsconfig.json
- test/reporters/custom-reporter.vitest.config.ts
- tsconfig.json
Check supported usages: https://github.com/vitest-dev/vitest/blob/eed0a2d467531cebfeb62690e130a1227bcfc3e0/test/core/test/each.test.ts
Note that the template literal usage from Jest is NOT supported intentionally. Mainly due to its lack of type safety and introduces too much complexity.
> feat: support `suite.each`, `test.each`, close #120

- packages/ui/client/components/TaskItem.vue
Currently, the white-space in time info (like `< 1ms`) can cause a line wrap in a task item.
This in turn results in a much higher item.
> fix(ui): prevent line wrapping for task items

- packages/ui/client/components/FileDetails.vue
Without the immediate trigger, the graph was not updated on initial load.
> fix(ui): make graph data watch immediate

- test/fails/test/__snapshots__/runner.test.ts.snap
It seems the expect result for `toBe` has changed and the snapshot has not be updated.
> chore(test-fails): update nested suite snapshot

- package.json
All test from `test/test-fails` are being executed on `test:ci` and should be excluded
> fix: exclude `test-fails` from `test:ci`

- packages/vite-node/src/client.ts
- packages/vite-node/src/server.ts
- packages/vitest/rollup.config.js
- packages/vitest/src/integrations/coverage.ts
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/coverage.ts
- packages/vitest/src/types/worker.ts
- pnpm-lock.yaml
- test/coverage-test/package.json
- test/coverage-test/src/Hello.vue
- test/coverage-test/src/utils.ts
- test/coverage-test/src/vue.shim.d.ts
- test/coverage-test/test/__snapshots__/vue.test.ts.snap
- test/coverage-test/test/vue.test.ts
- test/coverage-test/vitest.config.ts
- test/reporters/tests/custom-reporter.spec.ts
This reverts #584 - runtime coverage is not reporting functions that are not used as not covered.
Added manual soucemap adjustments because Vitest is prepending code to every file. 
Fixes #375
> fix: fix incorect coverage reporting (fix #375)

- packages/vitest/src/node/plugins/index.ts
> fix: do not mutate options to get api config (fix #616)

- packages/vitest/src/integrations/jest-mock.ts
- test/core/test/spy.test.ts
- test/reporters/tests/custom-reporter.spec.ts
Closes #637.
~~I'm pretty sure this should solve the error.
If I understand the current typing correctly, a method was required to be a constructor.
This should remove that constraint.
If we do want to spy on constructors I can add another overload declaration.~~
> fix: update spy type inference

- packages/vitest/src/integrations/coverage.ts
Projects using Cypress often have e2e spec files in a `cypress` directory that currently needs to be manually ignored.
This is the case for `create-vue` projects for example.
This commit adds `cypress/**` to the default excludes of the code coverage config.
> feat: ignore cypress files in coverage by default

- docs/guide/index.md
- package.json
- packages/ui/client/components/StatusIcon.vue
- packages/vitest/src/node/cli.ts
- packages/vitest/src/runtime/collect.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/config.ts
Closes #668.
This PR adds a new option `allowOnly`. If this option is `false`, suites and tests marked as `only` will fail.
By default, the option is disabled if `process.env.CI` is `true` and enabled otherwise.
> feat: add `allowOnly` option

- packages/vitest/src/integrations/coverage.ts
> fix: make takeCoverage call optional (fix #670)

- packages/vitest/src/node/create.ts
> fix: avoid calling buildStart twice (fix #679)

- packages/ui/client/components/views/ViewReport.vue
- packages/ui/client/styles/main.css
Closes #684 
This PR adds all failed tasks of a file to the report, instead of top-level tasks only.
It also fixes an overflow in a task's error message by making it scrollable.
> feat(ui): show all failed tasks in report

- README.md
The links in the readme point to an anchor that doesn't exist any more.
> docs: fix watch and coverage links

- packages/vitest/src/integrations/coverage.ts
> fix: use correct file paths in coverage reports (fix #691)

- packages/vitest/src/types/config.ts
The default behaviour of watch mode is true
But in jsDoc it shows false
> Docs: Update JSDoc watch mode default to true

- packages/vitest/src/node/pool.ts
Made adjustments to number of threads created. Vitest now uses more threads by default.
Implementation is just like in Jest:
> In single run mode, this defaults to the number of the cores available on your machine minus one for the main thread. In watch mode, this defaults to half of the available cores on your machine to ensure Jest is unobtrusive and does not grind your machine to a halt.
`minThreads` is the same as `maxThreads` for now because of https://github.com/Aslemammad/tinypool/issues/23. This will cause a really small slowdown if number of test files is less than number of CPU cores. When Tinypool is fixed to better handle `minThreads` and `maxThreads` in isolate mode `minThreads` can be adjusted.
This improved performance of https://github.com/EvHaus/jest-vs-jasmine tests …
> perf: use cpu cores more efficently

- packages/vitest/src/node/mocker.ts
> fix: can mock workspace files

- packages/vitest/src/index.ts
- test/core/test/basic.test.ts
Fixes #707
This originally comes from: 
```ts
interface TypeComparison {
(type: string, message?: string): Assertion;
instanceof: InstanceOf;
instanceOf: InstanceOf;
}
```
But we are overriding it, so
> fix: fixed typescript error when calling assertion

- packages/vitest/src/integrations/snapshot/port/state.ts
- test/snapshots/test/__snapshots__/shapshots.test.ts.snap
- test/snapshots/test/shapshots.test.ts
fix: #595
snapshot mulitline strings expected no use the method `prepareExpected` format, and the received formated.
the PR make their had the same behavior
> fix(snapshot): received add prepareExpected

- docs/config/index.md
- packages/vitest/src/constants.ts
- packages/vitest/src/index.ts
- packages/vitest/src/integrations/coverage.ts
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/types/config.ts
> feat: export default config to expand it

- packages/vitest/src/constants.ts
Fixes #718
This fixes the error `TypeError: target[key].push is not a function` that occurs when a config is defined with reporters.
This is because the deepMerge function tries to merge the given array of reporters with the default config, which is the string `"default"`.
By fixing the default config to be an array of reporters, only containing the default one, the issue is fixed.
> fix: default reporters should be an array

- .github/ISSUE_TEMPLATE/bug_report.yml
- docs/guide/index.md
- examples/README.md
- netlify.toml
- scripts/update-examples.ts
Using `?initialPath` we can reliably get the correct base for the UI.
@sheremet-va the PR also removes the links to the old playgrounds, vitest.dev/new for example was not pointing to the stacblitz.com/fork/github link that gives people the latest version.
> docs: StackBlitz playgrounds using initialPath

- packages/vitest/src/utils/base.ts
- test/core/test/utils.spec.ts
> fix: do not merge arrays (fix #725)

- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/general.ts
- packages/vitest/src/types/tasks.ts
- test/core/test/each.test.ts
Using readonly tuples makes it easy to type check their individual parts inside the test.
Resolves https://github.com/vitest-dev/vitest/issues/732
> feat: support readonly tuples as input to `.each`

- examples/vue/tsconfig.json
- examples/vue/vitest.config.ts
The `vite.config.ts` in the vue example is missing the correct type reference.
> docs(example): add missing type reference

- docs/.vitepress/config.ts
- docs/api/index.md
- docs/guide/migration.md
Adds a note about lack of DOM clean up when globals are off (as per https://github.com/vitest-dev/vitest/issues/682#issuecomment-1030984679), and restores the doc change added in https://github.com/vitest-dev/vitest/pull/467 which was removed.
> doc: start migration guide documentation for Jest

- examples/lit/test/basic.test.ts
- examples/puppeteer/test/basic.test.ts
- examples/react-testing-lib/src/components/input.test.tsx
- packages/vitest/src/types/tasks.ts
- test/fails/test/runner.test.ts
> fix: remove `describe` async support

- packages/vitest/src/index.ts
It was introduced in #702, but doesn't seem to have been implemented
> fix: add missing `defineConfig` helper

- examples/lit/test/basic.test.ts
- examples/puppeteer/test/basic.test.ts
- examples/react-testing-lib/src/components/input.test.tsx
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- test/fails/test/runner.test.ts
Reverts vitest-dev/vitest#746
Fix #703
> fix: `describe` async support

- packages/vitest/src/node/pool.ts
Only disable atomics in WebContainers. The perf diff isn't considerable (@Demivan shown around 0.75% for a quick test), but there is no reason to disable this in node env.
> perf: enable tinypool useAtomics in node env

- docs/api/index.md
- packages/vitest/src/index.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- test/core/test/jest-expect.test.ts
This adds a new assertion that replaces `expect(typeof actual).toBe('string')` with `expect(actual).toBeTypeOf('string')`
Please let me know where I need to add docs and/or tests, I'm very unfamiliar with the structure of the repo :sweat_smile: 
**Edit:**
Somehow there is a chai `typeOf` https://www.chaijs.com/api/assert/#method_typeof
But not sure how or if this is in any way accessible from vitest
> feat: add typeof assertion

- docs/config/index.md
- packages/vitest/src/index.ts
- packages/vitest/src/node/index.ts
> fix: move config related methods to 'vitest/node'

- docs/config/index.md
- docs/guide/migration.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/worker.ts
- test/core/test/env.test.ts
> feat: add VITEST_WORKER_ID env

- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/snapshot/chai.ts
- packages/vitest/src/integrations/snapshot/client.ts
- packages/vitest/src/integrations/snapshot/port/state.ts
- test/core/test/snapshot-inline.test.ts
> fix: fix error if toMatchInlineSnapshot is called on resolves/rejects

- packages/vitest/src/node/plugins/index.ts
- test/core/.env.local
- test/core/test/env.test.ts
Fixes https://github.com/vitest-dev/vitest/discussions/768
> fix: put envs from .env files on process.env

- packages/vitest/src/integrations/coverage.ts
- packages/vitest/src/types/coverage.ts
Fixes https://github.com/vitest-dev/vitest/issues/341.
> feat: coverage threshold

- docs/config/index.md
- docs/guide/index.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/create.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/types/config.ts
- test/core/test/basic.test.ts
> fix: set mode before running Vite

- examples/graphql/package.json
- examples/graphql/src/Fragment.gql
- examples/graphql/src/Query.gql
- examples/graphql/src/query.ts
- examples/graphql/test/query.spec.ts
- examples/graphql/vite.config.ts
- packages/vite-node/src/utils.ts
- pnpm-lock.yaml
> fix: remove ?import from query, so .[ext]$ checks will pass

- packages/vitest/src/utils/base.ts
- test/core/test/each.test.ts
- test/core/test/utils.spec.ts
> fix: add check to avoid converting 0 to undefined

- packages/vite-node/src/cli.ts
- packages/vite-node/src/client.ts
- packages/vite-node/src/types.ts
- packages/vitest/src/node/execute.ts
- packages/vitest/src/node/plugins/globalSetup.ts
- test/core/test/imports.test.ts
- test/core/vitest.config.ts
> fix: resolve import path for dynamic imports

- examples/README.md
- scripts/update-examples.ts
Run the examples update script to add the new graphql example.
Add a `noOnlinePlayground` list to the script so we can disable it for some examples, e2e doesn't currently work in StackBlitz for example
> docs: update examples, support no online playground

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/stdin.ts
> feat: allow changing name pattern during watch mode

- packages/vite-node/src/externalize.ts
- test/core/test/imports.test.ts
> fix: process "data:" in import correctly

- packages/vitest/src/runtime/context.ts
- packages/vitest/src/runtime/hooks.ts
- test/fails/fixtures/hook-timeout.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
Added suggestion like 
```
test timed out in 10ms.
Please pass timeout value as arg or configure globally with "testTimeout" in config, if this is a long-running test.
```
- hooks(beforeEach, afterEach...etc) timed out
- test timed out
> fix: add a suggestion to the error message of timeout

- docs/guide/mocking.md
The link to the `vi.mock()` API was directing to `vi.fn()`
> doc(fix): wrong link in module mocking docs

- packages/vitest/src/node/plugins/globalSetup.ts
- pnpm-lock.yaml
- test/global-setup-fail/fixtures/globalSetup/error.js
- test/global-setup-fail/fixtures/vitest.config.ts
- test/global-setup-fail/package.json
- test/global-setup-fail/test/runner.test.ts
- test/global-setup-fail/vitest.config.ts
When an error is thrown during global setup, the command does not end and does not show any error messages.
This PR adds try-catchs to prevent it.
refs #873
> fix: handle error during global setup

- examples/solid/package.json
- package.json
- packages/vitest/src/node/cli.ts
- pnpm-lock.yaml
- test/global-setup-fail/test/runner.test.ts
This PR adds a unhandled error handling which can catch more cases than this one.
https://github.com/vitest-dev/vitest/blob/4858541f36e65612a35cb7c5a0542aed03b23e30/packages/vitest/src/node/cli-api.ts#L70-L75
refs #873 
---
`solid-start` does not work with node 14 because it uses `stream/web` which is implemented node 16+.
https://github.com/solidjs/solid-start/blob/9ef4c5bff3aef765251f64268d7cf767d2acfd46/packages/start/runtime/devServer.js#L2
I have excluded from `pnpm test:ci`. Should I write some scripts to exclude it only from node 14?
> fix: unhandled error handler

- packages/vitest/src/utils/base.ts
- test/core/test/utils.spec.ts
- test/reporters/custom-reporter.vitest.config.ts
- test/reporters/tests/custom-reporter.spec.ts
Passing non array to reporters option like below did not effect.
```ts
defineConfig({
test: {
reporters: new ReporterClass()
}
})
```
This PR fixes this.
---
1. Here `{ reporters: [] }` and `{ reporters: new ReporterClass() }` will be deepmerged.
https://github.com/vitest-dev/vitest/blob/19f6052c41af12dfac2c5e4ffb3cc3d378143e89/packages/vitest/src/node/plugins/index.ts#L87-L92
1. Think about when `target = { reporters: [] }` and `source = { reporters: new ReporterClass() }`. Because `isMergableObject(new ReporterClass())` (Line 91) is `true` it tries to merge.
https://github.com/vitest-dev/vitest/blob/19f6052c41af12dfac2c5e4ffb3cc3d378143e89/packages/vitest/src/utils/base.ts#L91-L99
1. So `deepMerge([], new ReporterClass())` (Line 95) will be called. But since `isMergableObject([])` (Line …
> fix: passing non array to reporters option did not effect

- packages/vitest/src/types/reporter.ts
> fix: export Vitest type from 'vitest', fix #877

- docs/guide/index.md
This PR fixes a small typo in the CLI options: `depreciated` -> `deprecated`.
> docs: fix typo

- examples/react-enzyme/vite.config.ts
When I import the defineConfig from Vite it doesn't except test as an argument and I got the bellow error.
```
Argument of type '{ plugins: any[]; test: {}; }' is not assignable to parameter of type 'UserConfigExport'.
Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'
```
I don't know why this is happens but I manged to get it to work by changing the import library to vitest/config
> chore: update defineConfig to be imported from vitest

- packages/vitest/src/node/reporters/json.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
> fix: json reporter detects `skip` mode correctly

- test/core/test/jest-expect.test.ts
just added test for `expect.extend`.
(I posted about custom asymmetric matcher #881 )
> test: add test case for expect.extend

- packages/vitest/src/node/reporters/json.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/tasks.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/custom-reporter.spec.ts
- test/reporters/tests/reporters.spec.ts
Add the missing field `perfStats` to JSON TestResult compared to [Jest test result type](https://github.com/facebook/jest/blob/e0b33b74b5afd738edc183858b5c34053cfc26dd/packages/jest-test-result/src/types.ts#L101-L106). 
```js
{  
...
perfStats: {
end?: Milliseconds
runtime?: Milliseconds
start?: Milliseconds
},
...
}
```
> feat: add perfStats to json reporter

- packages/vitest/src/integrations/env/jsdom-keys.ts
Using the jsdom environment, some one of my dependencies has code such as `window instanceof Window` (specifically [recoil](https://github.com/facebookexperimental/Recoil/blob/304b468ef32c491e1ffa5726347028ff63b1b8bb/packages/shared/util/Recoil_Environment.js#L22)), and with vitest and jsdom it was giving a Window not defined error.
The jsdom environment should add the Window with a capital W interface to the global environment.
> fix: export Window interface in jsdom environment

- packages/vitest/src/index.ts
- packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts
- test/core/test/jest-expect.test.ts
During my migration from jest to vitest, I realized that there is no support for adding a generic type in arrayContaining to define the type of an array item. so I decided to make this contribution.
> feat: add optional generic on array containing

- docs/guide/index.md
We included `vitest` a few days ago on `@iconify/utils` package and will be also added to the rest of packages soon
EDIT: it is used only on `next` branch but `Vjacheslav Trushkin` is working to include `vitest`on the rest of packages and then will be merged to main.
@patak-dev on that repo I have `jest` and `vitest` configured to run on `cjs` and `esm` environments with the same codebase, just configuration: 
- https://github.com/iconify/iconify/blob/next/packages/utils/jest.shared.config.cjs
- https://github.com/iconify/iconify/blob/next/packages/utils/jest.config.cjs
- https://github.com/iconify/iconify/blob/next/packages/utils/jest.config.mjs
- https://github.com/iconify/iconify/blob/next/packages/utils/vitest.config.cjs
- https://github.com/iconify/iconify/blob/next/packages/utils/vit …
> docs: add `iconify` to the projects using `Vitest`

- docs/api/index.md
- packages/vitest/src/index.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- test/core/test/jest-expect.test.ts
Supporting array syntax when using toHaveProperty, I did have issues getting the typing right though had to resort to using as to assert that it won't be a string[] anymore. #937 explains more in detail the problem this PR addresses
> fix(expect): toHaveProperty support array syntax like jest (fix #937)

- packages/vitest/src/node/core.ts
This PR normalizes file filter paths on windows when determining what test files to run. I couldn't really find an appropriate place to add a test for this, but am happy to do so if you could point me in the right direction.
> fix: file filters on windows (fix #693)

- packages/vitest/src/integrations/snapshot/port/inlineSnapshot.ts
- test/snapshots/test/shapshots.test.ts
here is the issue #922 
and i notice when update inlineSnapshot, it will remove the end white space `trimEnd()`
and i add a test-case, it works
and i run all the tests, all done.
> fix: update inlineSnapshot should not remove end whitespace, close #922

- packages/vite-node/src/client.ts
- test/core/test/imports.test.ts
This change doesn't appear to break anything, but when my component is dynamically importing a vue component, I pass that result to defineAsyncComponent. Looking through the source code vue is expecting the property `Symbo.toStringTag` to be equal to 'Module' otherwise it won't look at the .default property to get the default component import. I am not sure if it is fine setting it for all exports but since vitest is esm first figured it would be fine to add.
> fix: add Module symbol to export object

- packages/vite-node/src/client.ts
- packages/vite-node/src/server.ts
- test/core/src/relative-import.ts
- test/core/test/imports.test.ts
If an imported file in a different directory is doing a dynamic import to a relative path that import is failing due to the relative import seeming to be from where we are running the tests from and not from where the file is imported from. I fixed this by just converting all relative imports with an extension to an absolute import. I don't see any issue with this, but I don't know the whole scope of this project.  All tests are passing and this fixed my issue for my use case.
> fix(vite-node): normalize relative paths to be from current working directory

- docs/config/index.md
- packages/vite-node/src/externalize.ts
- packages/vite-node/src/types.ts
- packages/vitest/src/types/config.ts
> fix(vite-node): don't fallback to cjs by default

- packages/web-worker/README.md
Just saw that the addon-web-worker had been published 🎉  , however I noticed the readme referenced a different library name so this PR fixes that up
> docs(web-worker): update readme

- README.md
**What**
The Getting Started URL on Readme is incorrect and are returning a 404 error. There's a missing / at the end.
**How it has been fixed**
I've added the missing /.
> docs: fixing Getting Started url on Readme

- docs/guide/index.md
> docs: improve options list

- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/reporters.spec.ts
Adds missing test cases for `outputFile` configuration.
I'm working on another bug fix and thought let's merge these ones first.
> test(reporters): add outputFile tests

- packages/vitest/src/node/reporters/json.ts
- packages/vitest/src/node/reporters/junit.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/reporters.spec.ts
> fix: prevent crashing when directory of `outputFile` does not exist

- packages/vitest/src/node/error.ts
- packages/vitest/src/types/general.ts
Address the first phase of https://github.com/vitest-dev/vitest/issues/832 when a stack trace is interpreted in case of errors in node if a source map is present it ensures the proper file is rendered in the test summary.
This PR doesn't address the full scope of the issue as it would be better (arguably?) to also show the test file names correspondent to the mapped source if present but I don't yet understand how that could be achieved because at the point test file names are rendered source maps are not yet parsed
---
After this PR the repro code produces:
While it still shows test files as before:
> fix: render original source if mapped in node

- docs/guide/index.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/types/config.ts
Currently, the doc is not consistent in Guide and Config
> docs: update doc on option.outputFile

- packages/vitest/src/node/cli-api.ts
- test/coverage-test/coverage-test/coverage.test.ts
- test/coverage-test/package.json
- test/coverage-test/test/coverage.test.ts
- test/coverage-test/vitest.config-coverage.ts
- test/coverage-test/vitest.config.ts
fix: #998
from https://nodejs.org/api/v8.html#v8takecoverage
> This method can be invoked multiple times during the lifetime of the process. Each time the execution counter will be reset and a new coverage report will be written to the directory specified by [NODE_V8_COVERAGE](https://nodejs.org/api/cli.html#node_v8_coveragedir).
~~This looks like NODE_V8_COVERAGE is reread every time `v8.takeCoverage` is executed.~~
`NODE_V8_COVERAGE` read once when nodejs start. 
> "It looks like the output is no different after removing that"
because thread enable test coverage run in sub-thread.
this PR restart Vitest when threads disabled.
> chore: coverage remove restart vitest

- packages/vitest/rollup.config.js
- packages/vitest/src/config.ts
- packages/vitest/src/defaults.ts
- test/reporters/custom-reporter.vitest.config.ts
- test/reporters/tsconfig.json
fix: #991
Does it look like typescript doesn't deeply compare two different modules(`vitest` / `vitest/config`)?
this PR make `vitest/config` deps vitest declare module and make it external vitest.
> fix: type error

- packages/ui/client/main.ts
With the latest update made here https://github.com/vitest-dev/vitest/pull/590 I get this error in the UI
This happens because we pass a router factory function to the `app.use` call instead of the actual router https://github.com/vitest-dev/vitest/blob/main/packages/ui/client/global-setup.ts#L22-L27
I'm new to Vue so I might be wrong here @JessicaSachs can you please take a look 🙏
close https://github.com/vitest-dev/vitest/issues/1008
> fix(ui): router plugin in ui

- docs/guide/debugging.md
The `--threads false` part is important, because the debugger
otherweise halts all worker threads upon start.
One would have to manually let those continue, which is quite annoying.
> docs: Add IntelliJ debug instructions

- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/chai/types.ts
- packages/vitest/src/runtime/run.ts
- test/core/test/jest-expect.test.ts
I find `expect.assertions` error message is inaccurate when it is asynchronous code.
The following example, it will throw a error that message is `Error: expected number of assertions to be 2, but got 0`.
But the accurate message is `Error: expected number of assertions to be 2, but got 3`.
```ts
test('assertions when asynchronous code', async() => {
expect.assertions(2)
await Promise.all([
expect(1).toBe(1),
expect(1).toBe(1),
expect(1).toBe(1),
])
})
```
> Reproduction: [https://stackblitz.com/edit/node-misjca](https://stackblitz.com/edit/node-misjca)
> fix: assertions error message

- docs/api/index.md
Adds more details and an example on how to use a factory function for mocked modules; specifically modules with a default export.
> docs: updates for `vi.mock` in the API section

- packages/vitest/src/integrations/env/utils.ts
- test/core/test/dom.test.ts
Fixes error when creating custom EventTarget, and calling `dispatchEvent` on it: https://discord.com/channels/917386801235247114/918057998914568213/957344537171345449
> fix: event target mismatch with global event

- packages/ui/client/components/views/ViewEditor.vue
- packages/ui/client/components/views/ViewReport.vue
- packages/ui/client/composables/error.ts
Moved the `useCodeError` logic to the `ViewEditor.vue` component from `error.ts` module, we would need to include `@unocss-include` on the `error.ts` module to style the elements created.
Anyway, on stackblitz I cannot make it working (missing links, it seems using oldest version), tested with `0.7.11` and `0.7.12` but still not working, it seems stackblitz doing strange things, for example: `taze` not showing `vitest 0.7.12`, I need to run `taze major`.
The repo I use with `0.7.12` with almost all core tests included: https://stackblitz.com/edit/vitejs-vite-nfjsbi
> fix(ui): open in IDE and error styles

- packages/vitest/src/node/reporters/json.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
In the current version(v0.7.11), the JSON reporter's output format deviates from jest's. See [Stackblitz example](https://stackblitz.com/edit/vitest-dev-vitest-gsjy9q?file=jest_output.json).
In PR https://github.com/vitest-dev/vitest/pull/489 json reporter is added, it implements the subset of jest's [AggregatedResult type](https://github.com/facebook/jest/blob/fe5e91c1b86323ab02b3de9d322b77e65a64e75a/packages/jest-test-result/src/types.ts#L58-L75). However, jest --json output is using [FormattedTestResults](https://github.com/facebook/jest/blob/fe5e91c1b86323ab02b3de9d322b77e65a64e75a/packages/jest-test-result/src/types.ts#L138-L154). 
And each object in `testResults` should represents a file rather than a test case.
> fix: align json output with jest's

- examples/vue-jsx/package.json
- examples/vue-jsx/vite.config.ts
- examples/vue/package.json
- examples/vue/vitest.config.ts
- examples/vue2/package.json
- examples/vue2/pnpm-lock.yaml
- examples/vue2/vitest.config.ts
- pnpm-lock.yaml
The VTU team got several reports of errors with happy-dom,
that developers tried after seeing it in the Vitest examples.
Switching to jsdom generally fixes the issue (and this is what create-vue uses as well).
This commit switches the Vue examples from happy-dom to jsdom.
> docs: use jsdom for vue examples

- README.md
- docs/src/components/Home.vue
Use the same scheme as Anthony: https://cdn.jsdelivr.net/gh/patak-dev/static/sponsors.svg
> chore: update patak sponsors image url

- packages/vitest/src/node/core.ts
Close https://github.com/vitest-dev/vitest/issues/1023
> fix: vitest run do not normalize paths on windows x64 platforms

- packages/vitest/src/node/core.ts
This PR fixes inconsistency with `globTestFiles` and `isTargetFile`.
fixes #981
fixes #982 
I actually tested with #981 and #982's reproduction and checked that it works.
> fix: inconsistency with globTestFiles and isTargetFile (fix #981, #982)

- packages/vite-node/package.json
- packages/vite-node/rollup.config.js
- packages/vitest/package.json
- packages/vitest/rollup.config.js
Avoid publishing inline sourcemaps to npm, just like Vite
> chore: don't publish sourcemaps

- docs/api/index.md
- docs/guide/migration.md
- docs/guide/mocking.md
- packages/vitest/src/integrations/vi.ts
- test/core/test/vi.spec.ts
This helper is meant to smooth migration from `jest`, where you could just put everything on `window` and expect it to be globally available.
Another possible solution: when the value is set on window, also put it on `globalThis` (we already put descriptor with `set` on global). But this wouldn't be possible on keys that are not in `jsdom-keys`
> feat: stubGlobals helper

- docs/config/index.md
- docs/guide/index.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/git.ts
- packages/vitest/src/types/config.ts
The code for getting files is based on jest implementation, but some of it was removed. Not sure how it will be working, if root and git is not the same? If someone can test in a monorepo, that would be cool. I am ashamed to admit, I am not familiar enough with git terminal commands 👀 
I was testing in in `tests/core` by changing code in `/src` and it worked fine. So i guess the solution should work for most people, using git.
I am getting the changed files and putting it into `related` array. Then the logic for related kicks in, and it tries to find tests based on related files. I have a guard `if (!related) { // find related }` in case `runTests` runs twice (bc of watch mode or else)
> feat: add commands to run tests depending on changed files

- docs/api/index.md
Fix a symbol error in https://vitest.dev/api/#test-each
> docs: fix a typo

- packages/ui/client/auto-imports.d.ts
- packages/ui/client/components/FileDetails.vue
- packages/vitest/src/runtime/setup.ts
- packages/vitest/src/types/general.ts
For context: 
The log spy currently uses a single buffer to collect all the logs from all the tests, when sending the logs to the reporters, there is no way of knowing which tests each of the logs correspond to, so as soon as are sent, all the logs that are collected in the corresponding tick are shown as corresponding to the current test:
This PR also separates the timers by tests, since otherwise we can lose logs:
PR #1086 by @sheremet-va fixed the identifier of the test to which the collected logs belong, but when they are sent we still have the problem that all the ones in the buffer are sent, so the logs of other tests will be included under the running test at tick.
This PR includes the current logic but separated by test, so that the logs are collected and included in their own …
> fix(logs): collect logs per test

- packages/vitest/src/node/plugins/index.ts
> fix: really disable deps optimization

- packages/ui/client/components/CodeMirror.vue
- packages/ui/client/components/FileDetails.vue
- packages/ui/client/components/IconButton.vue
- packages/ui/client/components/Navigation.vue
- packages/ui/client/components/TasksList.vue
- packages/ui/client/components/views/ViewEditor.vue
- packages/ui/client/components/views/ViewReport.vue
- packages/ui/client/composables/codemirror.ts
- packages/ui/client/styles/main.css
- packages/ui/package.json
- pnpm-lock.yaml
- fix disabled on `IconButton`: avoid get focus when it is disabled, just configured the disabled prop on the button
- added buttons for clearing search on navigation and suite panels. It also focus the input once cleared: the clear button on the task list also focus the input once clicked: https://streamable.com/ok3fa4 (on the video the button is shown/hidden, this PR just enable/disable the button)
- fix codemirror scrolls, when scrolling (on click for scroll on thumb) the editor jumps (on horizontal scroll it has a huge impact): I included simplescrolls addon, it requires a resize observer to refresh the scrolls
- fix min w/h for open in editor links on codemirror source code when error is present: https://streamable.com/kba255
- make vertical scroll usable with mouse …
> fix(ui): disabled icon buttons + codemirror scrolls + minor addons

- packages/vitest/src/utils/source-map.ts
`stackIgnorePatterns` was not working on windows.
This PR simply fixes it.
```
FAIL  expect.test.ts > hi
AssertionError: expected 2 to deeply equal 3
❯ expect.test.ts:4:16
2| 
3| test('hi', () => {
4|   expect(1 + 1).toEqual(3)
|                ^
5| })
6| 
❯ ../../../packages/vitest/dist/vendor-index.0d6b419a.js:82:26
❯ runTest ../../../packages/vitest/dist/entry.js:803:40
❯ async runSuite ../../../packages/vitest/dist/entry.js:868:13
❯ async runFiles ../../../packages/vitest/dist/entry.js:905:5
❯ async startTests ../../../packages/vitest/dist/entry.js:911:3
❯ async ../../../packages/vitest/dist/entry.js:938:7
❯ async withEnv ../../../packages/vitest/dist/entry.js:533:5
❯ async run ../../../packages/vitest/dist/entry.js:937:5
- Expected   3
+ Received   2
```
```
FAIL  expect.test.ts > hi …
```
> fix: hide ignored stacktrace on windows

- packages/vitest/src/node/plugins/mock.ts
- test/fails/fixtures/mock-import-proxy-module.test.ts
- test/fails/fixtures/proxy-module.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
> fix(mock-api): provide an explainatory error message when the mocks API hoisting doesn't work

- packages/vite-node/src/externalize.ts
Fixes #1096
We don't need to inline based on the filename alone anymore, since we use `isValidNodeImport` anyway, which is more accurate.
> fix(vite-node): remove unsafe checks for inlining dependencies

- examples/mocks/package.json
- examples/mocks/src/moduleWithSymbol.ts
- examples/mocks/test/automocking.spec.ts
- packages/vitest/package.json
- packages/vitest/src/integrations/spy.ts
- packages/vitest/src/runtime/mocker.ts
- pnpm-lock.yaml
this PR intends to resolve #1082  by updating automocking to fully support symbol indexed methods (specifically, fixing the root issue which occurs when trying to restore and later use such methods)
in a fresh project, i can get the below test snippet to fail for `vitest@0.9.0`. i can then get them to pass when linking vitest locally to this branch. however, when running the tests in `examples/mocks`, the below tests fail as the mock is not properly restored.
in a fresh project, the following will fail for `v0.9.0` and pass on this PR
in `log.ts` 
```typescript
const sym = Symbol('x')
const logger = {
warn() {
return this[sym]()
},
[sym]() {
return 'hello'
}
}
export default logger
```
and in `log.test.ts` 
```typescript
import { vi, test, expect } from 'vitest'
import logger from './log' …
```
> fix: make automocking aware of symbol indexed methods

- packages/vitest/src/index.ts
They were no longer exported since #1100 which was a breaking change in v0.8.5
Maybe some other types should be re-exported as well, like `MaybeMocked` and the deep versions?
> fix: re-export mock types

- docs/config/index.md
- docs/guide/index.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/reporters/json.ts
- packages/vitest/src/node/reporters/junit.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/utils/config-helpers.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/reporters.spec.ts
> feat: extend `config.outputFile` to allow objects, close #1068

- examples/basic/vite.config.ts
Fixes the broken link in the basic vitest example when opening in StackBlitz.
https://user-images.githubusercontent.com/50255197/162484340-d421a73f-5e02-44c4-a45a-91f89a39bb5a.mp4
> fix(dev): fix 404 configure vitest link in basic example

- package.json
If you run `pnpm run dev` on a shell and `cd test/web-worker && pnpm run test` in another, it will fail, since `vite-node` is not included on the `dev` script (if you haven't run `pnpm run build` before, for example on a fresh clone).
https://imgur.com/k8V1U0d
> fix: add `vite-node` to root `dev` script

- packages/ui/client/components/views/ViewReport.cy.tsx
- packages/ui/client/components/views/ViewReport.vue
- packages/ui/cypress/support/index.ts
- packages/ui/package.json
- pnpm-lock.yaml
This PR cleans up the tests for **`ViewReport.cy.tsx`** and begins to add faker in for more realistic test data.
There is one loss of coverage: we no longer check that a **b** tag is the element used in the DOM. For this, we should be using Percy for making sure that the styles are correct. Percy has a free, open-source plan.
> chore: cleaning up test for ViewReport.cy.tsx

- packages/vitest/src/node/reporters/junit.ts
- test/reporters/src/data.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
This line in [data.ts](https://github.com/ciddan/vitest/blob/5f70317748f316ed73b2604596ce3fb7486199a1/test/reporters/src/data.ts#L147) contains two control characters, visible in vs code:
That line is scrubbed by the new `removeInvalidXMLCharacters` function, ensuring that the XML output doesn't contain the control characters.
Reproduction [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-pepxpq?file=test_result%2Fjunit.xml).
Let the tests run and open test_result/junit.xml. The file contains disallowed characters, specifically in the <system-err> tag.
You can use any XML validator to check, such as the one from [w3schools](https://www.w3schools.com/xml/xml_validator.asp).
> fix: remove invalid xml characters in junit reporter output (fix #1144)

- package.json
- packages/ui/client/components.d.ts
- packages/vite-node/package.json
- packages/vitest/package.json
- packages/vitest/src/node/plugins/index.ts
- pnpm-lock.yaml
Should fix #553
Use the new `optimizeDeps.disabled: true` option, experimental in Vite >2.9.2, `entries` remains to help with older versions.
Also updated to vite@2.9.5
> fix: optimizeDeps.disabled

- packages/vitest/src/node/plugins/index.ts
It is not uncommon to shim `process.env` with an empty object in Vite projects. This doesn't allow us to put `import.meta.env` variables on it, while running tests.
This PR removes this edge case.
> fix: remove process.env edge case in defines

- packages/vitest/src/node/core.ts
Fixes #1161.
I'm not 100% sure whether `async runFiles()` is the correct place to clear snapshots, but it works.
Currently snapshots are only cleared in `async scheduleRerun(triggerId: string)`.
https://github.com/vitest-dev/vitest/blob/0c9137d9d3267be860a59c619e2eee981e51a64b/packages/vitest/src/node/core.ts#L319
> fix: reset snapshot state between test reruns

- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/error.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/node/reporters/default.ts
- packages/vitest/src/node/reporters/dot.ts
- packages/vitest/src/node/state.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/general.ts
- packages/vitest/src/types/reporter.ts
- packages/vitest/src/types/worker.ts
- packages/vitest/src/utils/source-map.ts
Closes: #1132, #884, #1201
Fixes: #1165, #1203
- Errors show full stacktrace, since it's really hard to debug errors without an actual stacktrace (sometimes it has none, or look at #1201)
- Unhandled errors don't exit process, but fail the whole suite
- Unhandled errors are shown after the summary with a warning
- Clarified error message for "Vitest was initialized with Native Node"
- If errors have custom properties, they are shown under "Serialized Error" - previously I wanted to show them like Node does, but it looks bad, if error has only one stack trace with a code frame, so I decided to split it
- If error has "cause", print the case as the error without a code frame
> feat: error log improvements

- .github/ISSUE_TEMPLATE/feature_request.yml
Fix the typo in the feature request issue template, where "Vite" is used instead of "Vitest."
> fix: typo in feature request template

- packages/vitest/src/node/reporters/json.ts
- test/reporters/src/data.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
> fix: todo assertion status in json output

- .eslintignore
- packages/vite-node/src/client.ts
- test/core/src/self/foo.ts
- test/core/src/self/index.ts
- test/core/test/self.test.ts
fix #1220 
exporting itself is wrong, but it can be exported by mistake, `vite` handles the export just fine.
note: eslint was crashing :D so I ignored the files for this specific test
> fix: self exported module call stack error

- docs/config/index.md
- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/node/reporters/default.ts
- packages/vitest/src/node/reporters/renderers/listRenderer.ts
- packages/vitest/src/node/reporters/verbose.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/types/tasks.ts
Not sure if I placed `heap` calculations in the right place tho :P
Also fixes #1187
> feat: add config option logHeapUsage

- packages/vitest/src/integrations/snapshot/port/utils.ts
- test/core/test/snapshot-inline.test.ts
Fixes #1134
There is one unrelated typo fix commit and one test regression commit. I'm happy to move those into separate PR if needed.
> fix(inline-snapshots): detect linebreaks

- packages/vitest/src/node/core.ts
Fixes #686
@antfu `u` updated obsolete snapshots, but still shows them tho, can you help me resolve this?
> fix: default to failed tests and unchecked snapshots when updating snapshots

- packages/vitest/src/integrations/snapshot/chai.ts
- packages/vitest/src/integrations/snapshot/client.ts
> fix: show custom error message if snapshot failed

- packages/vitest/src/integrations/chai/jest-matcher-utils.ts
- test/core/test/jest-matcher-utils.test.ts
Some custom matchers like those in `@testing-library/jest-dom` use `this.utils.diff` for the output. In Jest the order of arguments in that util is ["expected", then "received"](https://github.com/facebook/jest/blob/a5bb8848ba1cc6a764ef01b6c4144006922cc3a0/packages/jest-diff/src/index.ts#L68), so here I'm fixing the order of those arguments to match Jest's implementation.
Fixes #1239.
> Fix the order of arguments in the Jest matcher util

- packages/vitest/src/types/coverage.ts
This PR adds the missing C8 option [`src`](https://github.com/bcoe/c8/blob/49c45b3395e3354c2463cf40247c6c8eab4bbe1c/index.d.ts#L22) to the typing. The runtime code doesn't need to modify. 
[C8 README](https://github.com/bcoe/c8/blob/main/README.md) provides more information about this option.
> docs: add missing c8 option `src`

- examples/puppeteer/test/basic.test.ts
`server.httpServer.close` does not return a Promise.
Docs: https://nodejs.org/docs/latest-v14.x/api/net.html#net_server_close_callback
> fix: close node.js server correctly in the puppeteer example

- docs/guide/migration.md
> docs: add vue snapshot section in migration guide

- packages/vitest/src/runtime/entry.ts
Fixes #1263
Fixes #1207
Fixes #835
> feat: initialize environment only once for no-threads

- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/env/happy-dom.ts
- packages/vitest/src/integrations/env/utils.ts
- test/core/test/dom.test.ts
- test/core/test/happy-dom.test.ts
Fixes #1259
Also refactored shared state, so there is only one proxy to not create new objects every time for each global.
> fix: calling global functions in happy-dom, refactor sharing global state

- docs/config/index.md
- packages/vitest/src/types/config.ts
> feat: allow passing passWithNoTests, allowOnly inside config

- examples/mocks/__mocks__/zustand.ts
- examples/mocks/src/zustand-magic.ts
- examples/mocks/test/self-importing.test.ts
- packages/vitest/src/runtime/mocker.ts
> fix: clear mock from callstack, if mocked with factory

- packages/vitest/src/defaults.ts
- packages/vitest/src/integrations/timers.ts
- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/types/config.ts
- test/core/test/timers.test.ts
Allow passing option to `@sinon/fake-times`. Jest released it as a feature in the latest version, and I thought we could also allow it.
> feat: allow passing config to sinon/fake-timers

- docs/api/index.md
> docs: fix type api/expect.hasAssertions

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/stdin.ts
Press `f` and there is no response
> feat: press `f` to rerun only failed tests

- packages/vitest/src/utils/base.ts
- test/core/test/utils.spec.ts
> fix: skip props from prototype when cloning

- docs/guide/features.md
The return value of `fn.mock.results[1]` seems to be and object of the shape {value: 'world', ...rest}
> docs: fix mock return value

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/diff.ts
- packages/vitest/src/node/error.ts
- packages/vitest/src/node/reporters/renderers/utils.ts
- fixes #1292 where `process.stdout` can be `undefined` on Windows platform and with this I am now able to see the real unit test errors instead of Vitest itself throwing error
> fix: `process.stdout` could be undefined on Windows (fix #1292)

- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/utils.ts
- test/core/test/jest-expect.test.ts
The promise helpers, `.resolves` and `.rejects`, were throwing errors when the returned object could not be serialized. Additionally, the `.resolves` helper did not support a function argument even though a function was expected.
With a happy-path test for resolving a promise...
```ts
// example1.test.ts
await expect(() => Promise.resolve(1)).resolves.toEqual(1)
```
The following error occurs.
```
TypeError: obj.then is not a function
```
The test passes.
```
1 passed (1)
```
With an alternate-path test expecting a dynamic import (promise) to error...
```ts
// example2.ts
export default {}
```
```ts
// example2.test.ts
await expect(() => import('./example')).rejects.toThrowError()
```
The following error occurs.
```
TypeError: Cannot convert object to primitive value
```
The test passes. …
> fix: `.resolves` and `.rejects` expectations

- test/reporters/tests/utils.test.ts
wrong `DefaultReporter` import path:
```shell
test/single-thread test$ vitest "--allowOnly"
test/reporters test: (node:11992) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
test/reporters test: (Use `node --trace-deprecation ...` to show where the warning was created)
test/reporters test:  ❯ tests/utils.test.ts  (0 test)
test/reporters test:  √ tests/reporters.spec.ts  (14 tests) 71ms
test/reporters test: ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
test/reporters test:  FAIL  tests/utils.test.ts [ tests/utils.test.ts ]
test/reporters test: Error: [vite-node] Failed to load ../../../../vitest/packages/vitest/src/node/reporters/default
test/reporters test:  ❯ async tests/utils.test.ts:7:31 …
```
> fix(test:ci): reporters utils test is failing

- examples/README.md
The `react-storybook` example was moved from `react-storybook-testing` in 4b785138e1635fe641839bd70ecb318e6764a53b. This commit fixes a couple of links that were not updated accordingly.
> docs: fix link to react-storybook example

- packages/vitest/src/config.ts
Make `defineConfig()` accept a callback or promise that resolves to a config. This matches the signature of `defineConfig()` from Vite:
https://github.com/vitejs/vite/blob/0858450b2a258b216ae9aa797cc02e9a0d4eb0af/packages/vite/src/node/config.ts#L53-L64
Resolves #1301
> feat: add function/promise forms of defineConfig()

- packages/vite-node/src/cli.ts
fixed received arguments for change event.
ref: [chokidar](https://github.com/paulmillr/chokidar#api)
before:
after:
> fix(vite-node): fix received argument for change event

- examples/react/tsconfig.json
Since `vitest.config.ts` contains `test.globals: true`, the `vitest/globals` module is required in order to enable globals such as `test()` and `it()`.
> fix: add vitest/globals to types

- packages/vitest/src/node/config.ts
For example:
```js
{
test: {
setupFiles: ['@testing-library/jest-dom/extend-expect.js'],
},
}
```
> feat: support npm setup files

- docs/guide/mocking.md
The example in the docs had _two_ calls to `vi.advanceTimersToNextTimer()` before expecting the mock function to be called once. This resulted in the test failing (the mock function was called _twice_ instead of once, since the interval was executed twice).
Removing the duplicate call to `vi.advanceTimersToNextTimer()` fixes the test.
> docs(mocking): Fix Timers example

- packages/vite-node/src/client.ts
- packages/vite-node/src/utils.ts
- packages/vitest/src/runtime/mocker.ts
- test/core/src/dynamic-import.ts
- test/core/test/mock-internals.test.ts
fix #1294.
the reason for this issue is that when we resolve all mocks, store them in `mockMap`. it looks like below,
```javascript
{
'/node_modules/@wdio/logger/build/node.js': '/__mocks__/@wdio/logger.ts'
}
```
but when we actually import, the incoming path is `@wdio/logger`, it becomes `/@fs/${rootPath}/node_modules/@wdio/logger/build/node.js` after `resolveId` function. so the mock fails.
> fix: replace root when resolving dependency

- packages/vitest/src/integrations/env/utils.ts
- test/core/test/dom.test.ts
> fix: don't bind global classes

- packages/vitest/src/node/pool.ts
- packages/vitest/src/utils/index.ts
When an error was thrown from `pool.run`, vitest finished without any error messages.
This PR handles that error.
I found this while implementing https://github.com/vitejs/vite/pull/8049.
```text
RUN  v0.12.8 D:/documents/GitHub/vite
····*···---******************************---------··········***····································******···*********·····*·**··········***
```
There was no error message.
```text
RUN  v0.12.8 D:/documents/GitHub/vite
stderr | unknown test
"default" is imported from external module "path" but never used in "playground-temp/ssr-vue/src/entry-server.js".
················································---································································---------··················-----------··············································--·*········ …
```
> fix: handle error from pool.run

- packages/vitest/src/integrations/chai/jest-expect.ts
- test/core/test/jest-expect.test.ts
This PR fixes https://github.com/vitest-dev/vitest/pull/1172.
This was discovered in https://github.com/vitest-dev/vitest/pull/1172#issuecomment-1111950901 but never fixed.
> fix: toSatisfy never executes the matcher function

- test/global-setup/setupFiles/without-relative-path-prefix.ts
- test/global-setup/test/setup-files.test.ts
- test/global-setup/vitest.config.ts
Add integration test for #1347.
> test(config-setupFiles): add integration test

- packages/vitest/src/node/reporters/tap.ts
Fixing comment from @imcotton  https://github.com/vitest-dev/vitest/pull/445#discussion_r880760817
> fix: improve test name escaping in TAP reporters

- packages/vitest/src/runtime/rpc.ts
- packages/vitest/src/utils/timers.ts
- test/core/test/rpc.spec.ts
> fix: birpc using safe timers

- packages/vitest/src/node/plugins/index.ts
Vitest has it's own hrm implementation
Fixes #1363
> feat: disable Vite hmr in tests

- packages/vitest/src/integrations/snapshot/port/inlineSnapshot.ts
- test/core/test/snapshot-inline.test.ts
> fix: don't escape $ in snapshots, when not needed

- packages/vitest/src/node/pool.ts
After upgrading to 0.13.0 a coverage folder was generated although i didn't configure any code coverage.
> fix: Don't generate coverage folder when coverage is not enabled

- packages/vitest/config.d.ts
- packages/vitest/node.d.ts
Hello 👋
When consuming `vitest/config` from my own project which is using ESM (`"type": "module"`), `defineConfig` is seen as `any`.
I think this is because `vitest` is itself using ESM, so the types definition files have to use explicit paths when importing/exporting local files.
I think the issue was never detected before because the types definition files outside of `config.d.ts` and `node.d.ts` are all flattened and don't import/export local files.
I already encountered this issue here: https://github.com/tinyhttp/tinyhttp/pull/359
What's a bit strange in your case is that TypeScript seems to see the types, but `@typescript-eslint` can't (it relies in TypeScript itself for types resolution 🤔):
Anyway, I think if you are declaring your module as ESM and you are writing it in …
> fix(types): add explicit extension for ESM compatibility

- docs/config/index.md
The description of this field was opposite to its actual impact and the example below. Now they match.
> docs: fix `testNamePattern` description

- docs/api/index.md
[Link to the docs](https://vitest.dev/api/#test-fails).
1. The original example produces the following output to the console:
2. After changing the example according to the [rejects](https://vitest.dev/api/#rejects) assertion's description (adding `await` before `expect` and making the whole test asynchronous), the output to the console changes to this:
3. When changing `test.fails` to `test`, the output is the following:
If I understand correctly, in the example the assertion throws an error, that a promise is resolved instead of being rejected, but since we use `.fails` function, vitest will mark the test as passed. If so, it seems the output of the fixed example (2) is correct.
If I understand the idea of `test.fails` **incorrectly**, I think it will be useful to leave a note in the …
> docs: fix the example for `test.fails` function

- packages/vite-node/src/cli.ts
- packages/vite-node/src/types.ts
- packages/vite-node/src/utils.ts
Right now, when passing a single module with the new `--options` CLI flag, `cac` returns a string instead of an array. This causes a crash, trying to call `map` on it.
```
❯ ./packages/vite-node/vite-node.mjs --options.deps.inline="module" hello.js
file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:697
inline: (_b = (_a = serverOptions.deps) == null ? void 0 : _a.inline) == null ? void 0 : _b.map((dep) => {
^
TypeError: _b.map is not a function
at parseServerOptions (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:697:99)
at CAC.run (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:660:49)
at CAC.runMatchedCommand (file:///Users/antoine/Code/vitest/packages/vite-node/dist/cli.js:622:34)
at CAC.parse …
```
> fix(vite-node): Prevent crash when passing single module as options

- packages/vitest/src/integrations/spy.ts
Just allowing the correct typing to `spyOn` 
```ts
const a = {
call(a: 1) {
return a
}
}
a.call(1)
const ss = spyOn(a, 'call')
ss(1)
// @ts-expect-error invalid type
ss('2')
```
> types(SpyOn): Add callable typing

- docs/config/index.md
- packages/vite-node/src/cli.ts
- packages/vite-node/src/externalize.ts
- packages/vite-node/src/server.ts
- packages/vite-node/src/types.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/types/config.ts
Vite allows `true` for `noExternal`, so I added support to us
I am adding this logic to `ViteNode`, because it can be used outside of Vitest, and I think it can help Histoire in the future.
> feat(vite-node): respect ssr field, allow inlining everything

- packages/vitest/src/types/tasks.ts
Is they any need to force void. This stops doing inline source testing
Currently having to cast the type
> fix: repair TestFunction return type.

- docs/api/index.md
Hi maintainers 👋 
I found a tiny typo in the docs. I'd be happy to merge them!
The explanation for 'mockRestore' says "Does what `mockRestore` does", but this should be "Does what `mockReset` does" based on the code.
https://github.com/vitest-dev/vitest/blob/17dfd39e51b33a02458aaab8bf75d42dd680e72b/packages/vitest/src/integrations/spy.ts#L200-L201
> docs(api): fix the explanation for 'mockRestore'

- packages/vitest/package.json
Missing updates from https://github.com/vitest-dev/vitest/pull/1411
Caused runtime issue in https://github.com/vitejs/vite/pull/8474
> fix: correct export extension

- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/chai/jest-utils.ts
- test/core/test/jest-expect.test.ts
A PR for issue #1290.
We would like to have a message to remind users they should use deep equality checks, when object comparison fails with `toBe`. The error message would look like this now:
The implementation is similar to how [jest](https://github.com/facebook/jest/blob/main/packages/expect/src/matchers.ts#L85-L124) does it.
Unit tests
> feat: improve deep equality check failing message for toBe

- packages/vitest/src/node/error.ts
Fixes an error, described in #1452
> fix: don't fail when there is no source file defined in source map

- packages/ui/package.json
- pnpm-lock.yaml
The test I made on local to reproduce the problem result on multiple versions of vue: 3.2.33 and 3.2.37.
There is something weird with vite plugin vue 2.3.3 and the current version of vue on ui package: it is using 3.2.36 and I don't know why the vue dev dep is using 3.2.33, just updating to latest vue 3.2.37 the ui on local works via `vitest --ui` once run build script finish.
fix #1418
> fix(ui): update vue dependency conflict

- examples/mocks/src/has space in path.ts
- examples/mocks/test/spaced.spec.ts
- packages/vitest/src/utils/source-map.ts
> fix: can mock files with space in path

- packages/vitest/src/runtime/suite.ts
- test/core/test/each.test.ts
> fix: null inside test.each is not turned into an empty array

- packages/vitest/src/integrations/chai/constants.ts
- packages/vitest/src/integrations/chai/index.ts
- packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/chai/jest-extend.ts
- packages/vitest/src/runtime/context.ts
- packages/vitest/src/runtime/run.ts
- test/core/test/concurrent.spec.ts
> feat: bind expect state to context

- docs/api/index.md
These examples were fixed.
Otherwise, the call of `buyApples` "bleeds" the error thrown in the stack of the test.
> docs: add mising `async` to `resolves` and `rejects` example

- docs/config/index.md
- docs/guide/migration.md
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/worker.ts
- test/core/test/env.test.ts
`VITEST_POOL_ID` behaves more like jets's `JEST_WORKER_ID`. 
`VITEST_WORKER_ID` is still working like it worked before.
Closes #1469
> feat: introduce `VITEST_POOL_ID`

- packages/web-worker/src/pure.ts
- test/web-worker/src/eventListenerWorker.ts
- test/web-worker/test/init.test.ts
Previously `.addEventListener` would throw an error in the worker context:
```
TypeError: Cannot read properties of undefined (reading 'message')
```
Seems this was due to the unbound method assignment. Added a test to prove it
> fix(web-worker): ensure event listener functions are bound correctly

- docs/config/index.md
- packages/vitest/package.json
- packages/vitest/src/defaults.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/config.ts
- pnpm-lock.yaml
> feat: add `maxConcurrency` option

- packages/vitest/src/types/tasks.ts
#1521 touches briefly about this topic. Docs "Migration Guide" will come in another PR
> fix: align hooks return types with their behaviour

- packages/vitest/src/integrations/spy.ts
- packages/vitest/src/types/index.ts
Current types were names without much consideration about compatibility with Jest, or any actual thought behind it 👀 
I think we might as well align them with Jest. This is a breaking change
> feat!: rename mock types to match jest's

- packages/vite-node/src/utils.ts
- test/core/test/file-path.test.ts
I'm working on a devcontainer where the workspace path is `/workspace`. (which is default when configured from vscode)
When I run vitest spec including `expect(doc).toMatchInlineSnapshot()`, the test is passed successfully but it fails to update snapshots. The error log is like below.
```
$ /workspace/node_modules/.bin/vitest run src/ui/consultationEditorV2/utils/convert.test.ts
Debugger attached.
RUN  v0.15.2 /workspace
✓ src/ui/consultationEditorV2/utils/convert.test.ts (1)
Tests  1 passed (1)
Time  6.03s (in thread 13ms, 46366.64%)
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run. This might cause false positive tests.
Please, resolve …
```
> fix: toFilePath with abs path in root

- packages/vitest/src/integrations/snapshot/chai.ts
- test/core/test/__snapshots__/snapshot.test.ts.snap
- test/core/test/snapshot-inline.test.ts
- test/core/test/snapshot.test.ts
> fix: correctly create snapshot for rejected errors

- docs/config/index.md
- packages/vitest/LICENSE.md
- packages/vitest/package.json
- packages/vitest/src/integrations/env/edge-runtime.ts
- packages/vitest/src/integrations/env/index.ts
- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/types/config.ts
- pnpm-lock.yaml
- test/vite-edge/package.json
- test/vite-edge/test/edge.test.ts
- test/vite-edge/test/node.test.ts
- test/vite-edge/vitest.config.ts
add environment support for https://github.com/vercel/edge-runtime
`eval` and `new Function()` still works in vitest edge environment. 
#1470 might help to solve this problem
```js
// ❌ Fail
// Error name:    "EvalError"
// Error message: "Code generation from strings disallowed for this context"
it('should return the correct value', () => {
let val = eval('2 + 2');
expect(val).toBe(4);
});
```
> feat: support edge runtime

- docs/config/index.md
This is not obvious to new users, so I think we should add this tip on the docs.
> docs: add link to VIte options

- packages/vitest/src/node/pool.ts
if `os.cpu().length` returns odd number, vitest crashes like this:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
RangeError: Invalid array length
❯ new ThreadPool node_modules/tinypool/dist/esm/index.js:467:30
❯ new Tinypool node_modules/tinypool/dist/esm/index.js:739:31
❯ createPool node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:7057:16
❯ node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10406:21
❯ Vitest.runFiles node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10422:7
❯ Vitest.start node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10349:5
❯ startVitest node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:11095:5
❯ CAC.start …
```
> fix: crash with odd cpu counts

- docs/config/index.md
- docs/guide/cli.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/node/core.ts
- pnpm-lock.yaml
- test/related/force-rerun.vitest.config.ts
- test/related/package.json
- test/related/tests/force-rerun.test.ts
If forceRerunTriggers has globs in it then we use `micromatch` to see if there's a file in `related` that should trigger the whole test suite
Was going to write some tests for this, but not sure where they should go
Resolves: #1592
> feat: check related against `forceRerunTriggers`

- docs/api/index.md
- docs/config/index.md
- docs/guide/cli.md
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/index.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/node/sequencers/BaseSequencer.ts
- packages/vitest/src/node/sequencers/RandomSequencer.ts
- packages/vitest/src/node/sequencers/types.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/types/tasks.ts
- packages/vitest/src/utils/base.ts
- test/core/package.json
- test/core/test/random.test.ts
- test/core/test/sequencers.test.ts
- test/core/vitest.config.ts
Closes #1570
TODO
This PR adds a few new options to config:
1. `--shuffle` to CLI flags
2. `sequence` to options
- `sequencer` allows users to overwrite builtin logic for sharding and sorting 
- `shuffle` allows tests to be run in random order
- `seed` makes random order more deterministic
Also added `shuffle` flag to `describe` block to make only part of suite random. I've noticed we have some tests rely on running in the same order, so I though this option might be helpful.
> feat: make sequencer public, add option to run tests in random order

- docs/config/index.md
Minor docs PR to fix a typo:
> To get TypeScript working with the global APIs, add vitest/globals to the types ~~filed~~ field in your tsconfig.json
> docs: typo

- examples/mocks/src/example.ts
- examples/mocks/test/automocking.spec.ts
- packages/vite-node/src/client.ts
- packages/vite-node/src/hmr/hmr.ts
- packages/vite-node/src/utils.ts
- packages/vitest/src/runtime/mocker.ts
- packages/vitest/src/runtime/setup.ts
- packages/vitest/src/runtime/worker.ts
- packages/web-worker/src/pure.ts
- pnpm-lock.yaml
- test/vite-node/package.json
- test/vite-node/src/circular/a.ts
- test/vite-node/src/circular/b.ts
- test/vite-node/src/circular/index.ts
- test/vite-node/test/circular.test.ts
close https://github.com/nuxt-community/color-mode-module/pull/154
> fix(vite-node): self circular reference

- packages/vitest/src/node/cache/results.ts
- packages/vitest/src/node/core.ts
> fix: show error message when cache failed to parse

- packages/vitest/src/node/index.ts
- packages/vitest/src/node/sequencers/types.ts
- packages/vitest/src/types/config.ts
Fixed typo on Typescript interface.
Attempting to create custom sequencer by following docs, https://vitest.dev/config/#sequence. Docs are correct but codebase has a typo.
> - Type: `TestSequencerConstructor`
```diff
-TestSequencerContructor
+TestSequencerConstructor
```
> fix: `TestSequencerConstructor` typo

- packages/vitest/src/types/tasks.ts
- test/core/test/basic.test.ts
- test/core/test/run-if.test.ts
> fix(types): fix `test.each` and `describe.each` types

- packages/vitest/src/runtime/mocker.ts
- test/core/src/mockedC.ts
- test/core/test/mocked.test.ts
Previously classes weren't mocked properly because their prototypes were not being copied, so they lost all their methods. This PR rewrites the automocker to properly handle:
- Functions with properties (namely classes)
- Circular objects (also to handle classes, thanks JavaScript)
With these changes classes can now be properly automocked!
This fixes #1523.
> fix: mock properties of classes/functions (fix #1523)

- packages/vitest/src/defaults.ts
`create-vue` for example generates projects with a `dist` folder that stores the built assets. By default, the coverage does not exclude this directory until now.
> fix: exclude dist directory from default coverage

- packages/vitest/src/defaults.ts
Cypress v10 now has a dedicated file `cypress.config.js/ts` at the root of the project.
> fix: exclude cypress config from default coverage

- packages/vitest/src/integrations/env/edge-runtime.ts
- packages/vitest/src/integrations/env/happy-dom.ts
- packages/vitest/src/integrations/env/jsdom.ts
- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/utils/index.ts
> fix: works with yarn pnp

- docs/config/index.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/types/config.ts
- pnpm-lock.yaml
(Closes #1659)
This PR replaces the hardcoded `CLOSE_TIMEOUT` value for timeout on test teardown with a `teardownTimeout` setting. It retains the current default value of 1000 ms (1 second).
> feat: make close timeout configurable

- docs/guide/in-source.md
[link to vitest docs](https://vitest.dev/guide/in-source.html#production-build)  
[link to unbuild docs](https://github.com/unjs/unbuild#Configuration)
> docs: fix the example for in-source testing unbuild config

- packages/vitest/src/integrations/chai/jest-expect.ts
- test/core/test/jest-expect.test.ts
I'm not sure I implemented the fix in the right place, but it seems to fix the problem in #1675.
> fix: toHaveProperty with expect.any (fix: #1675)

- packages/vitest/src/integrations/snapshot/port/mockSerializer.ts
- packages/vitest/src/integrations/snapshot/port/plugins.ts
- test/core/test/__snapshots__/snapshot.test.ts.snap
- test/core/test/snapshot.test.ts
> feat: add mock snapshot serializer

- packages/ui/client/components/FileDetails.vue
Add small UI optimization for large module graph 
If the user never clicks on the graph tab, do not load the graph. 
Once they click on it once, we keep the graph loaded so the next time they load the tab it is at the same place.
Ui lags
https://user-images.githubusercontent.com/755469/180872288-e6812506-88a6-46b5-963e-9b3f529a8407.mp4
UI doesn't lag
https://user-images.githubusercontent.com/755469/180872305-f731ece1-a355-49e2-bb3e-18c333a0b499.mp4
Graph works as before
https://user-images.githubusercontent.com/755469/180876969-02939645-a5f1-43e8-911c-a04f7fd78e04.mp4
Fixes https://github.com/vitest-dev/vitest/issues/1602
> fix(ui): do not load graph if never displayed (fix #1602)

- packages/vitest/src/api/setup.ts
- packages/vitest/src/api/types.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/state.ts
- pnpm-lock.yaml
This PR tries to create an empty promise when vitest starts and then finishes it when vitest node (runningPromise) gets done! so when the client calls getPaths, it waits for files to be scanned. This also fixes some inconsistencies between the client and vitest node.
So `vitest --browser` should work (when It opens the browser automatically)!
> fix(browser): wait for files scanning in browser

- docs/config/index.md
- docs/guide/cli.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/node/cli.ts
- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/types/config.ts
I recently migrated a large project from Jest to Vitest.
During the migration, I encountered issues with unhandled errors due to race conditions (caused by poor tests that don't clean up their async React hooks).
Since there's a huge number of tests, without any way of knowing which tests cause these issues, I had to use `patch-package` to prevent Vitest from failing due to unhandled errors.
I am aware that this isn't the proper way, but there was no other way of getting around this issue.
With this PR, I propose a new config option for ignoring unhandled errors.
It's fittingly labelled `dangerouslyIgnoreUnhandledErrors`.
> feat: add option for ignoring unhandled errors

- examples/solid/vite.config.mjs
- packages/vitest/package.json
- packages/vitest/rollup.config.js
- packages/vitest/src/constants.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/loader.ts
- packages/vitest/src/types/loader.ts
- packages/vitest/suppress-warnings.cjs
This PR adds experimental loader and conditions, so native Node resolving algorithm knows about Vite's resolving algorithm.
This is a giant breaking change, but still should not affect a lot of people. This fixes issues when people applied custom conditions and they were working in Vite, but didn't work in Vitest, because it was imported from another library. This PR also allows applying `alias` to external libraries - this is useful for `preact`, for example.
We still don't allow mocking external libraries within another external library!
Closes #1638
> fix: apply Vite resolving algorithm to node_modules libraries

- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/runtime/mocker.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/utils/index.ts
- packages/web-worker/src/pure.ts
- test/core/test/utils.spec.ts
> fix: don't clear mocks with vi.resetModules, cache normalised mock paths

- docs/api/index.md
- packages/vitest/src/integrations/spy.ts
- packages/vitest/src/integrations/vi.ts
- test/core/test/vi.spec.ts
I'm not sure about the implementation, happy to get any feedback on this. Closes #1739.
> feat(types): add partial flag to mocked TypeScript helper (#1739)

- packages/vitest/src/integrations/env/utils.ts
- test/core/test/env-runtime.test.ts
> fix: correctly restore globals in env teardown

- packages/vitest/src/node/config.ts
Related #1758
Yarn recommends using `process.versions.pnp` to detect Yarn PnP: https://yarnpkg.com/advanced/pnpapi#processversionspnp
> fix: disable node loader for Yarn PnP

- package.json
- packages/vitest/rollup.config.js
- packages/vitest/src/defaults.ts
- packages/vitest/tsconfig.json
- shims.d.ts
- test/core/vitest.config.ts
- test/global-setup-fail/fixtures/vitest.config.ts
- test/global-setup-fail/vitest.config.ts
- test/global-setup/vitest.config.ts
- test/reporters/src/data.ts
- test/vite-config/vite.config.ts
- tsconfig.json
Reduces the bundle size (and time for `build`), since we no longer bundle the same `Vitest` type (and its dependencies).
Before:
```
➜ du -sh dist/                                              
1.5Mb    dist/
```
After:
```
➜ du -sh dist/
1.4Mb    dist/
```
Possible fix for #1619?
> fix: better bundling of types

- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- test/fails/fixtures/each-timeout.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
> feat: allow timeout in test.each

- packages/vitest/src/runtime/mocker.ts
- packages/vitest/src/utils/base.ts
- test/core/src/mockedC.ts
- test/core/test/mocked.test.ts
Sometimes while automocking we will encounter a property that, for some unknown reason, throws an error when you try to define it. Unfortunately I can't figure out _why_ it errors, so instead I have opted to quietly skip these unsettable properties. If that becomes a problem in the future this can be revisited, but I don't forsee it being an issue since these keys are mostly deeply internal prototype stuff that 99.999% of people don't even know exists, let alone want to mock. Plus, if you _really_ need to have this behavior you can always use `__mocks__` or just shim it inline yourself.
Fixes #1671
> fix: gracefully handle unsettable keys during automocking

- docs/api/index.md
- packages/vitest/src/runtime/chain.ts
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- test/core/test/each.test.ts
> feat: allow using todo/skip/concurrent with each

- packages/vitest/src/runtime/hooks.ts
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- test/core/test/local-context.test.ts
The second try for fixing #1798
Previous pr #1799
Related issue: #1660
> feat(types): better local test context support

- packages/vitest/src/node/logger.ts
- packages/vitest/src/node/reporters/tap.ts
> fix: tap reporter doesn't throw

- docs/guide/test-context.md
Add docs for how local test context works introduced in PR #1805, which is available since Vitest v0.21.1
> docs: clarify how to use local test context

- docs/guide/migration.md
- examples/mocks/test/factory.test.ts
- packages/vitest/src/runtime/mocker.ts
This should wrap up the loose ends on https://github.com/vitest-dev/vitest/issues/1763, so that it can be closed out.
> fix: handle undefined returns of module mocks, and update migration docs (#1763)

- docs/guide/cli.md
- packages/vitest/src/node/cli.ts
There was no mention in the documentation that you could turn off colors in the console output. I then dug into what libraries the cli was using and discovered picocolor was adding the colors and that it could be turned off by either assigning the `NO_COLOR` environment variable, or by passing a `--no-color` cli option. 
It made sense to expose the `--no-color` cli option so that users aren't forced into the environment variable route. This also adds an entry into the cli documentation to help users discover the feature.
> feat: Add --no-color to cli

- packages/vitest/src/node/reporters/junit.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/junit.test.ts
> fix(reporter-junit): remove trailing zeros in duration

- packages/coverage-istanbul/src/provider.ts
Fixes issue where `coverage: { reporters: 'text' }` crashes coverage report generation. String reporter is converted into array of characters and looped here:
https://github.com/vitest-dev/vitest/blob/14279d53e8b5b431a6b6c49dccd3b03696c5a489/packages/coverage-istanbul/src/provider.ts#L112
C8 is already converting string reporters into an array before looping them. Applied the same logic to istanbul.
https://github.com/vitest-dev/vitest/blob/14279d53e8b5b431a6b6c49dccd3b03696c5a489/packages/coverage-c8/src/provider.ts#L121
Error seen with string reporters:
```ts
test: {
coverage: {
provider: 'istanbul',
enabled: true,
reporter: 'text'
}
},
})
```
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
❯ Function.Module._resolveFilename …
```
> fix: convert string coverage reporters to array

- packages/vite-node/src/client.ts
- packages/vite-node/src/types.ts
This allows invalidating the tree from branches to the root, and leaving untouched branches to stay in cache.
In Vite's client, the HMR happens up to the closest HMR boundary (usually a dynamic import entry) and leaves the root entry untouched. While in Vite-Node, if we execute the same root entries multiple times, it will skip its branch evaluation. So in order to invalidate a nested branch module correctly, we need to invalidate all its importers down to the root.
> feat(vite-node): `moduleCache.invalidateDepTree` utiltity

- packages/vitest/package.json
- pnpm-lock.yaml
Tinyspy has had a couple updates, we should make sure they are included in the next vitest release. :)
> chore(deps): update tinyspy to 1.0.2

- packages/vitest/src/runtime/mocker.ts
- test/core/src/mockedD.ts
- test/core/test/mocked.test.ts
The ref ids start at 0. This was a problem because doing `if (refId)` would behave incorrectly if `refId === 0`, which is a valid state.
> fix: allow referring to first seen value while automocking

- packages/vitest/src/node/reporters/junit.ts
- test/reporters/src/data-for-junit.ts
- test/reporters/src/data.ts
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/reporters.spec.ts
When a error message has XML it made the junit reporter wasn't escaping when writing it to the log. 
This should fix #1823 
I don't love how i created `createSuiteHavingFailedTestWithXmlInError` to have an test case and welcome feedback.
> fix(reporter-junit): escape XML when in error message (fix: #1823)

- docs/config/index.md
I hit error:
```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
```
Because vitest.config.ts literally replaces vite config, it is not obvious from docs. And usually you want only augment vite config I suppose.
> docs: guide of extending vite config

- packages/vite-node/src/client.ts
- packages/web-worker/src/pure.ts
- test/web-worker/src/selfWorker.ts
- test/web-worker/src/selfWorkerDep.ts
- test/web-worker/test/init.test.ts
Worker and its dependencies should be invalidated every time it is created so that Worker module and its dependencies will be injected into a new `context` on the next creation.
fix #1873
Before PR:
After PR:
> fix: invalidate new worker and its dependencies (fix #1873)

- packages/vitest/src/runtime/error.ts
- test/core/test/serialize.test.ts
Fixes #1882
Fixes #1916
Closes #1892
> fix: improve error serialization

- packages/coverage-c8/src/provider.ts
- packages/vitest/src/node/core.ts
fix #1917 
Clean tmp dir before coverage-c8 report each time.
Same as:
https://github.com/bcoe/c8/blob/7f1069dcce6821a6794557b39d6a13f620c64bad/bin/c8.js#L31-L35
> fix: clean coverage-c8 tmp before reporting (fix #1917)

- docs/guide/snapshot.md
Documentation suggests using `vitest --updateSnapshot` to update snapshots. When doing so, `vitest` throws an error.
```node
file:///usr/local/share/.config/yarn/global/node_modules/vitest/dist/cli.mjs:432
throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
^
CACError: Unknown option `--updateSnapshot`
at Command.checkUnknownOptions (file:///usr/local/share/.config/yarn/global/node_modules/vitest/dist/cli.mjs:432:17)
at CAC.runMatchedCommand (file:///usr/local/share/.config/yarn/global/node_modules/vitest/dist/cli.mjs:630:13)
at CAC.parse (file:///usr/local/share/.config/yarn/global/node_modules/vitest/dist/cli.mjs:569:12)
at file:///usr/local/share/.config/yarn/global/node_modules/vitest/dist/cli.mjs:655:5
at ModuleJob.run …
```
> doc: fix option for updating snapshots

- examples/mocks/test/automocking.spec.ts
- packages/vitest/src/runtime/mocker.ts
- test/core/src/mockedC.ts
- test/core/test/mocked.test.js
- test/core/test/mocked.test.ts
This fixes a regression in 0.21.0.
Fixes #1899
> fix: automock getters and setters

- .github/workflows/ci.yml
- examples/lit/src/my-button.ts
- package.json
- pnpm-lock.yaml
Try to solve test ui hanging. Merge it if all went green.
> chore: workaround test-ui ci failure

- docs/guide/mocking.md
`timeOut` doesn't make sense since it's not code. Also, it should match formatting of "intervals".
> docs: update timer mocking section

- packages/vitest/src/integrations/chai/constants.ts
- packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts
- packages/vitest/src/integrations/chai/jest-expect.ts
- packages/vitest/src/integrations/chai/jest-extend.ts
- test/core/test/jest-expect.test.ts
While investigating #756 I noticed we put our global state using another symbol. Our state is also incompatible with jest, because we have local expects.
> fix: make globalThis more compatible with jest

- packages/vitest/src/runtime/mocker.ts
- test/core/test/unmock-import.test.ts
> fix: delete mock in moduleCache when unmock

- docs/config/index.md
- packages/coverage-istanbul/src/provider.ts
- packages/vitest/src/types/coverage.ts
- test/coverage-test/coverage-test/coverage.istanbul.test.ts
- test/coverage-test/src/untested-file.ts
- test/coverage-test/vitest.config.ts
Adds similar `all` option as [`c8`](https://github.com/bcoe/c8#checking-for-full-source-coverage-using---all) and [`nyc`](https://github.com/istanbuljs/nyc#common-configuration-options) have.
References from other projects:
- `c8`: https://github.com/bcoe/c8/blob/v7.12.0/lib/report.js#L187-L222
- `nyc`: https://github.com/istanbuljs/nyc/blob/v15.1.0/index.js#L186-L217
- `jest`https://github.com/facebook/jest/blob/v28.1.3/packages/jest-reporters/src/CoverageReporter.ts#L107-L222
> feat(coverage-istanbul): add "all" option

- docs/config/index.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/integrations/css/css-modules.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/plugins/cssEnabler.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/types/config.ts
- pnpm-lock.yaml
- test/css/package.json
- test/css/src/App.css
- test/css/src/App.module.css
- test/css/test/default-css.spec.ts
- test/css/test/non-scope-module.spec.ts
- test/css/test/process-css.spec.ts
- test/css/test/process-module.spec.ts
- test/css/test/scope-module.spec.ts
- test/css/test/utils.ts
- test/css/testing.mjs
- test/css/vitest.config.ts
Closes #1512
This PR implements the following logic:
- By default, CSS processing is disabled for every css file
- `module.*` exports a proxy in that case to not affect runtime (meaning, `styles.{value}` will always return a key with filename hash)
- If processing is enabled (`css.include`), css is processed and injected into DOM
- By default, `module.*` returns pseudo-scoped class names (`styles.module` always returns `_module_${filenameHash}`, `styles.someRandomValue` will return `undefined`)
- If you want to enable original scoped names (so production and tests generate the same names), use `css.modules.classNameStrategy: 'scoped'`
- Added `css.modules.classNameStrategy` option:
- `scoped` - use `css.modules.generateScopeName` from user config or fallback to default behaviour, this is …
> feat!: if not processed, CSS Modules return a proxy, scope class names by filename

- packages/vitest/src/node/error.ts
Display a diff of `actual`/`expected` when `showDiff` is undefined (as is the case for the AssertionError of node's assert).
Resolves https://github.com/vitest-dev/vitest/issues/1965
Ping @sheremet-va
> fix: show diff for errors that contain actual/expected without showDiff

- packages/vite-node/src/client.ts
- packages/vite-node/src/utils.ts
- test/core/test/module.test.ts
> fix: define default exports properties as named exports for ESM compatibility

- packages/ui/client/components/views/ViewReport.cy.tsx
- packages/ui/client/components/views/ViewReport.vue
close #1499
We were displaying the wrong line and column number in the web UI.
The correct values come from:
```js
const column = stack.sourcePos?.column  
const line  = stack.sourcePos?.line  
```
not from:
```js
const column = stack.column  
const line  = stack.line  
```
I have updated the existing cypress test.
> fix(ui): display correct line and column for web UI

- packages/vite-node/src/utils.ts
- packages/vitest/src/runtime/mocker.ts
- test/vite-config/src/src.ts
- test/vite-config/src/test/root.test.ts
> fix: correctly normalize mocked path, if file is named like the folder

- docs/.vitepress/style/vars.css
fix #1994 by darkening `--vp-c-text-dark-3`
It seems that only lang name and code line number (which does not exist in vitest docs) are affected by `--vp-c-text-dark-3` in light mode.
https://github.com/vuejs/vitepress/blob/b1511cf7b702a72b8fc79ff8190f9ae3c8fae2de/src/client/theme-default/styles/vars.css#L209
https://github.com/vuejs/vitepress/blob/b1511cf7b702a72b8fc79ff8190f9ae3c8fae2de/src/client/theme-default/styles/components/vp-doc.css#L415
Now in light mode:
> docs: fix contrast between lang name and code block

- examples/README.md
- examples/fastify/mockData.ts
- examples/fastify/package.json
- examples/fastify/src/app.ts
- examples/fastify/src/index.ts
- examples/fastify/test/app.test.ts
- pnpm-lock.yaml
Added fastify example.
Just with three way to test fastify applications with vitest.
> feat: added fastify example

- docs/guide/index.md
Allow users to copy the corresponding bash command depending on which package manager they are using. Accomplished this by separating the bash commands from the descriptive texts "with npm" "or with yarn" or "with pnpm"
> docs: add different package managers installations

- docs/guide/environment.md
I tested `jsdon` to confirm it does not work. When I tried it, I was prompted to install undefined. It does work when the value is `jsdom` so I made that change here.
Perhaps there should be some error handling for when an unknown environment is specified rather than letting it attempt to install undefined?
> docs: correct jsdom typo

- docs/api/index.md
Make the argument optional as described:
> Creates a spy on a function, though can be initiated without one.
> docs: fix `vi.fn` signature

- packages/vitest/src/runtime/run.ts
Since the fastest benchmark has a rank of 1, we should be sorting in ascending, not descending, order.
> fix(bench): rank sorting, fix #2006

- packages/vitest/src/runtime/map.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/benchmark.ts
- pnpm-lock.yaml
This addresses some parts of #2004 
- do not group benchmarks
- passing options to `bench` will work
> fix(bench): do not group benchmarks

- .gitignore
- docs/api/index.md
- docs/config/index.md
- docs/guide/features.md
- packages/vitest/src/node/reporters/benchmark/json.ts
- packages/vitest/src/types/benchmark.ts
- pnpm-lock.yaml
- test/benchmark/package.json
- test/benchmark/test.mjs
- test/benchmark/test/mode.bench.ts
Closes #1997
I've added minimum information that I could gather. @antfu @poyoho, please, if you have anything to add, feel free to push to this PR
> docs: add information about benchmarking

- docs/api/index.md
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- test/core/test/retry-only.test.ts
- test/core/test/retry.test.ts
...to all tests inside
close: #1998
> fix: propagate `describe` options

- docs/config/index.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/reporters/benchmark/json.ts
- packages/vitest/src/node/reporters/json.ts
- packages/vitest/src/node/reporters/junit.ts
- packages/vitest/src/types/benchmark.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/utils/config-helpers.ts
- pnpm-lock.yaml
- test/benchmark/package.json
- test/benchmark/test.mjs
- test/benchmark/vitest.config.ts
This should make test more stable, because we have `--retry` in CI. And also some QoL changes for using `vitest bench --reporter=`
> fix: move outputFile to benchmark, allow --reporter for benchmark

- packages/coverage-istanbul/src/provider.ts
Adds support for configuring `projectRoot` of `istanbul-reports`. This is something that `nyc` does as well: https://github.com/istanbuljs/nyc/blob/v15.1.0/index.js#L465. `c8` has similar PR open.
The `istanbul-reports` uses this internally for reporters `['clover', 'cobertura', 'lcovonly']`. Many third party tooling use the pure `lcov.info` when creating their own reports, e.g. SonarQube.
```
/workspaces/__vitest-monorepo-coverage
├── package.json
└── packages
├── a
|  ├── package.json
|  └── src
|     └── index.js
└── b
├── package.json
├── src
|  ├── add-and-double.js
|  └── add-and-double.test.js
└── vitest.config.js
```
```js
// packages/b/vitest.config.js
test: { coverage: { provider: "istanbul", reporter: 'lcovonly' } }
});
```
```sh
$ vitest run …
```
> fix(coverage): `istanbul-reports` to support `projectRoot`

- packages/vitest/src/node/cli-wrapper.ts
`--experimental-wasm-threads --wasm-atomics-on-non-shared-memory`
These node options cannot be enabled via the `NODE_OPTIONS` environment variable, only via cli flags. But using `node --experimental-wasm-threads --wasm-atomics-on-non-shared-memory vitest` only applies them to `cli-wrapper`, not to any subsequently spawned processes. The proposed change adds them to the list of flags that Vitest forwards to spawned processes.
> fix(cli): forward node wasm flags

- docs/api/index.md
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/benchmark.ts
- test/benchmark/test.mjs
- test/benchmark/test/mode.bench.ts
This continues to work of #2039.
> feat(benchmark): todo mode

- docs/api/index.md
example code does not match description
description output: `1, 2, 3`;
actual output: `1, 2`;
> docs: vi.runAllTimers example code

- docs/config/index.md
Adds missing documentation of #1883.
Default value comes from https://github.com/istanbuljs/test-exclude#optionsinclude.
> docs: description for coverage `include` option

- docs/guide/debugging.md
> fix(docs): use `type: node` in launch configuration to debug (fix #2080)

- docs/guide/debugging.md
Adds example of running `vitest` with debugger in the shell (without an IDE)
> docs: add instructions for debugging tests via terminal

- packages/vitest/src/integrations/snapshot/port/inlineSnapshot.ts
- test/core/test/inline-snap.test.ts
> feat(inline-snapshot): support comment

- .tazerc.json
- examples/lit/package.json
- examples/lit/test/basic.test.ts
- examples/lit/vite.config.ts
- packages/vite-node/package.json
- packages/vitest/package.json
- pnpm-lock.yaml
Given the fact that Vite 3 is out for about two months and most of the ecosystem is finished upgrading, we could drop the compact range for Vite to allow non-vite usage always to install Vite 3 as the dependency.
> fix!: drop support for Vite 2

- packages/coverage-istanbul/src/provider.ts
- test/coverage-test/coverage-test/coverage.istanbul.test.ts
- test/coverage-test/src/untested-file.ts
While looking into #2121 I noticed that sourcemaps of uncovered files' coverages are off. 
```bash
$ cd test/coverage-test
$ pnpm coverage:istanbul
$ npx live-server ./coverage
```
Before:
After:
> fix(coverage): fix sourcemaps of uncovered lines

- packages/vitest/package.json
In the [package.json](https://github.com/vitest-dev/vitest/blob/af3ad61791bd6c04838270d274417bc5001aefed/packages/vitest/package.json#L27) there is a `index.d.cts` declaration file defined for all packages that use CommonJS (`require`)
```json
"exports": {
".": {
"require": {
"types": "./index.d.cts",
"default": "./index.cjs"
},
"import": {
"types": "./dist/index.d.ts",
"default": "./dist/index.js"
}
},
```
Unfortunately this file is missing in the npm package:
> build: include *.d.cts files in npm package

- packages/vitest/src/types/tasks.ts
- test/core/test/basic.test.ts
This is still a function at runtime. But right now it shows a lot of function properties, like "arguments", "apply" and such, which bloats actual context.
> fix: don't show extra properties for test context

- packages/ui/client/components/dashboard/DashboardEntry.cy.tsx
- packages/ui/client/components/dashboard/DashboardEntry.vue
- packages/ui/client/components/dashboard/TestsFilesContainer.vue
> feat(ui): add tests summary in the dashboard

- packages/coverage-c8/src/provider.ts
> fix(coverage): reduce size of leftover v8 reports

- packages/vitest/package.json
- packages/web-worker/package.json
- packages/ws-client/package.json
Ensure all packages specify both `repository` and `repository.directory`, which helps package tooling to find the correct source files based on the npm package metadata.
> chore: add/update `repository` properties in `package.json`

- packages/vitest/src/node/core.ts
- test/benchmark/vitest.config.ts
- overwrite `benchmark.reporters` to empty array in `getSerializableConfig`, it makes custom reporter not throw `DataCloneError`
- add custom reporter test case in `@vitest/benchmark`
> fix: ignore benchmark.reporters in getSerializableConfig

- packages/vitest/src/node/reporters/base.ts
This renames the variable `shouldIgnore` to `shouldLog` as this is what the value of the variable is actually saying.
> chore: rename variable for clarity

- packages/vitest/src/node/stdin.ts
Goal: set inputNamePattern to RegExp source instead of string so the `testNamePattern` can be easily reused
Impact: when running the vitest in watch mode with --testNamePattern, when pressing t to re-run the filtered test, the suggested value is wrong and value cannot be reused because it has / /
1. actual filter: `role admin`
2. 1st t press, it suggest `/role admin/`
3. 2nd t press, it suggest `/\/role admin\//`
version: 0.24.3
cause:
using RegExp.toString() returns a valid regex string (with / at the beginning and the end of the string), but when this value is reused as RegExp constructor, it tries to covert the string value in to regex, causing the those / to be escaped.
simplified code to reproduce this issue
```typescript
// Actual
const reg1: RegExp|undefined = new RegExp("foo"); …
```
> fix(cli): set inputNamePattern to RegExp source instead of string

- packages/vite-node/src/cli.ts
- test/vite-node/package.json
fix: #1715
catch the code run error
> feat(vite-node): don't exit on uncaughtException in watch mode

- packages/vitest/src/node/reporters/utils.ts
- test/reporters/tests/utils.test.ts
fix: #2176
load the reporter file base on file system
> fix(reporter): load custom reporter using `executeFile`

- packages/vite-node/src/client.ts
- test/cjs/src/other.cjs
- test/cjs/src/other.d.cts
- test/cjs/test/named-default.test.ts
- test/stacktraces/test/runner.test.ts
> fix: improve compatibility with native Node CJS resolution

- packages/coverage-istanbul/src/provider.ts
- test/coverage-test/coverage-test/coverage.istanbul.test.ts
- test/coverage-test/src/Counter/Counter.component.ts
- test/coverage-test/src/Counter/Counter.vue
- test/coverage-test/src/Counter/index.ts
- test/coverage-test/test/vue.test.ts
- Fixes #2155
Vitest transforms files on-demand. Only files that are loaded are instrumented. `nyc`, `c8` and I think also `jest` instruments files before the test runner is even run. This introduces new issue for `istanbul`, where we may give it filenames that contain query parameters, e.g. `Counter.component.ts?vue&type=script&src=true&lang.ts`. These filenames end up as is in the coverage summaries and are used as filenames when writing reports in the file system. The HTML reporter of `istanbul-reports` generates links such as `<a href="Counter.component.ts?vue&type=script&src=true&lang.ts.html">` which cannot be opened on browser.
I added a test case where this issue can be reproduced, but as I have no experience in Vue, please check it thoroughly.
Before:
``` …
```
> fix(coverage): trim URL parameters from file paths in `istanbul` coverage

- packages/coverage-c8/src/provider.ts
- pnpm-lock.yaml
- test/coverage-test/coverage-test/c8/coverage-report/SFC.test.ts
- test/coverage-test/coverage-test/c8/coverage-report/math.test.ts
- test/coverage-test/coverage-test/c8/coverage-report/not-SFC/not-SFC.test.ts
- test/coverage-test/coverage-test/c8/coverage-report/utils.test.js
- test/coverage-test/coverage-test/coverage.c8.test.ts
- test/coverage-test/package.json
- test/coverage-test/src/coverage-report/SFC.vue
- test/coverage-test/src/coverage-report/math.ts
- test/coverage-test/src/coverage-report/not-SFC/not-SFC.ts
- test/coverage-test/src/coverage-report/not-SFC/not-SFC.vue
- test/coverage-test/src/coverage-report/utils.js
- test/coverage-test/vitest.config-c8-coverage.ts
- test/coverage-test/vitest.config-c8-internal-coverage.ts
- test/coverage-test/vitest.config.ts
This should fix https://github.com/vitest-dev/vitest/issues/1839 but only for C8, the problem still exists for istanbul provider
This will trim URL parameters from files (`?vue&type=script&src=true&lang.ts`) allowing them to be properly reported in text report and to be browsable in html report
Not sure what's the policy on tests for the c8 package
> fix(coverage): trim URL parameters from file paths in c8 coverage

- packages/vitest/src/runtime/rpc.ts
- packages/vitest/src/utils/timers.ts
> fix: prevent using mocks in rpc

- packages/vitest/src/node/error.ts
- packages/vitest/src/runtime/error.ts
- packages/vitest/src/runtime/worker.ts
- test/core/test/serialize.test.ts
> fix: show actual unhandled errors, serialize DOMErrors

- packages/vitest/src/node/reporters/utils.ts
- pnpm-lock.yaml
- test/reporters/deps-reporter.vitest.config.ts
- test/reporters/package.json
- test/reporters/reportPkg/index.js
- test/reporters/reportPkg/package.json
- test/reporters/reportTest2/custom-reporter-path.vitest.config.ts
- test/reporters/tests/custom-reporter.spec.ts
- test/reporters/tests/utils.test.ts
> fix: load deps reporter

- packages/vitest/src/node/error.ts
- packages/vitest/src/runtime/error.ts
- test/core/test/__snapshots__/serialize.test.ts.snap
- test/core/test/serialize.test.ts
> fix: don't serialize symbols and immutables

- packages/vitest/src/node/pool.ts
Fixes #2251
`-C` flag was introduced in 14.9.0, but `--conditions` in 12.19.0
> fix: use --conditions instead of -C

- packages/coverage-istanbul/src/provider.ts
- test/coverage-test/coverage-test/coverage.istanbul.test.ts
- test/coverage-test/src/implicitElse.ts
- test/coverage-test/test/coverage.test.ts
- test/coverage-test/vitest.config.ts
- Fixes #1887.
- Fixes #2239.
- Upstream issue https://github.com/istanbuljs/istanbuljs/issues/705.
- Upstream fix https://github.com/istanbuljs/istanbuljs/issues/706.
Adds a work-around for implicit else's branch coverages. There is a PR for the upstream issue but as `istanbul` packages do not update that often it might be worth to apply this work-around for now. This work-around is compatible with the upstream patch but should be removed once it is merged and released. 
The upstream issue has minimal reproduction setup which mimics vitest (esbuild, TS, istanbul packages).
> fix(coverage): `istanbul` provider to preserve implicit else

- examples/nextjs/package.json
- examples/react-storybook/package.json
- examples/react-testing-lib/package.json
- examples/react-testing-lib/src/App.test.tsx
- examples/react-testing-lib/src/components/input.test.tsx
- examples/react-testing-lib/src/hooks/useCounter.test.ts
- examples/react-testing-lib/src/main.tsx
- pnpm-lock.yaml
1. React 17 -> 18
2. `@testing-library/react` 12 -> 13
3. Remove `@testing-library/react-hooks`, its functions are now provided by `@testing-library/react`
4. Remove unnecessary `import ... from 'vitest'`, becaused globals are congfigured
> docs: update react-testing-lib example

- packages/vitest/src/runtime/context.ts
- packages/vitest/src/runtime/hooks.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/runtime/test-state.ts
- packages/vitest/src/types/tasks.ts
- test/core/test/on-failed.test.ts
```ts
import { expect, it, onTestFailed } from 'vitest'
it('on-failed', () => {
const square3 = 3 ** 2
const square4 = 4 ** 2
onTestFailed(() => {
console.log('Unexpected error encountered, internal states:', { square3, square4 })
})
expect(Math.sqrt(square3 + square4)).toBe(4)
})
```
It's common we use tests to debug our implementation. When debugging, we might want to inspect the intermediate state to see what is going on internally. While they are useful in debugging, it's could be noisy to print them when the test passes as expected.
Thus I propose to introduce an `onTestFailed` hook, so you can have a chance to execute some code before the test suite gets killed - **with access to the internal closure**. Like printing the state, doing some cleanup, or dumping something into the file …
> feat: `onTestFailed` hook

- packages/vitest/src/runtime/suite.ts
- test/core/test/each.test.ts
> fix: align `.each` behavior with jest

- packages/vitest/src/node/error.ts
- packages/vitest/src/types/general.ts
- test/stacktraces/fixtures/frame.spec.imba
- test/stacktraces/fixtures/vite.config.ts
- test/stacktraces/test/__snapshots__/runner.test.ts.snap
- test/stacktraces/test/runner.test.ts
This PR fixes https://github.com/vitest-dev/vitest/issues/2256
It displays the frame if present in the error instead of generating one. This matches Vite's behaviour
> feat: display error frame if present (like Vite)

- packages/vitest/src/node/reporters/benchmark/index.ts
- packages/vitest/src/node/reporters/benchmark/table/index.ts
- packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
- test/benchmark/package.json
- test/benchmark/test/only.bench.ts
- test/benchmark/vitest.config.ts
> feat: benchmark table report

- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/utils/index.ts
- pnpm-lock.yaml
Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>
Resolves #2153
I have added a `removeUndefinedValues` function which removes any undefined values passed by the user from userConfig so that default values can be applied.
> fix: remove undefined values in options

- packages/vitest/src/integrations/env/jsdom-keys.ts
- packages/vitest/src/integrations/env/utils.ts
Fixes #2289
Fixes #2276
Should also potentially fix all new similar issues, that one appears quite regularly. New tests are not required, because previous implementation was covered, and should still not fail.
> fix: always rewrite defined jsdom keys

- docs/config/index.md
- packages/vitest/src/node/config.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/config.ts
- test/core/test/hooks-list.test.ts
- test/core/test/hooks-parallel.test.ts
- test/core/test/hooks-stack.test.ts
Closes #2279
This PR adds an option `sequence.hooks` with possible values:
- `stack` will order "after" hooks in reverse order, "before" hooks will run in the order they were defined
- `list` will order all hooks in the order they are defined
- `parallel` will run hooks in a single group in parallel (hooks in parent suites will still run before the current suite's hooks)
I want to release this in 0.25.1 or 0.25.2, so we don't change the default behaviour, since it would be a breaking change.
@kristiandupont can you review this? It's possible that I misunderstood the idea
> feat: allow hooks to be executed in a stack or list

- packages/vitest/src/runtime/map.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/benchmark.ts
- test/benchmark/test/base.bench.ts
fix: #2284
`benchmark` will send by the worker. make sure `benchmark` should be a jsonify object
> fix: bench had options

- packages/vitest/src/integrations/chai/jest-utils.ts
- test/core/test/jest-expect.test.ts
> fix: dates are equal, if both are invalid

- packages/vite-node/src/client.ts
- test/cjs/src/default-function.cjs
- test/cjs/src/default-function.d.cts
- test/cjs/test/function-default.test.ts
Fixes #2320
Fixes #2318
Fixes https://github.com/fastify/fastify-autoload/pull/277
> fix: don't ignore properties, when put on a default function in CJS context

- packages/vitest/src/node/plugins/envReplacer.ts
- test/coverage-test/coverage-test/coverage.istanbul.test.ts
- test/coverage-test/src/importEnv.ts
- test/coverage-test/test/coverage.test.ts
Fixes #2332.
Possibly fixes #2214.
> fix(coverage): env-replacer to add filenames into sourcemaps

- packages/vitest/src/runtime/mocker.ts
- test/core/test/fixtures/mocked-dependency.ts
- test/core/test/unmock-import.test.ts
This PR implements the fix for #2351 suggested in https://github.com/vitest-dev/vitest/issues/2351#issuecomment-1320974209.
I've added a test to the existing `test/core/test/unmock-import.test.ts` suite, which involved adding a little fixture file. Let me know if you'd like any changes or adjustments to the tests for this fix!
> fix(mocker): clear automocked modules on unmock

- packages/vitest/src/node/cli.ts
This has been introduced by #2180. The change there will *always* set argv.dir, no matter if it's been there before or not. When it's not there, it will set it to undefined, which then will lead to vitest using the root as fallback instead of the config set in the config file, since CLI options override config options.
In our case, this config was essentially ignored since 0.24.4.
```js
import { defineConfig } from "vite"
root: "app/javascript",
test: {
dir: "spec/javascript"
}
})
```
with the only workaround of providing `dir` via CLI option.
Btw. I'd love to add tests, but I haven't found existing tests for this and didn't have too much time on my hands. Happy to take pointers and add them.
> fix(cli): Don't override config by setting cli options to undefined

- packages/vitest/src/node/core.ts
- test/core/test/.dot-folder/dot-test.test.ts
- test/fails/fixtures/.dot-folder/dot-test.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
- test/fails/test/runner.test.ts
I have added a test in a folder starting with `.` and manually verified that it's picked up. 
But it's not the right test as it won't fail even if `dot` is `false`. 
Is there an example test I can refer to ensure the path is picked up? Or somehow verify that that exact test was run?
fixes #2344
> fix: Detect tests in folders starting with `.` (fix #2344)

- docs/api/index.md
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- test/core/test/each.test.ts
> feat: test.each support string template

- packages/vitest/src/node/core.ts
> fix: exit with code 1, when type tests fail

- docs/guide/migration.md
Make the instructions clear, obvious, and copy/pastable.
Closes https://github.com/vitest-dev/vitest/issues/2366
> docs: Make Vue snapshot migration clear

- packages/vitest/src/runtime/mocker.ts
- test/core/test/mocked-circular.test.ts
Fixes #2381
This is an attempt to fix the issue described in #2381.
As suggested by @sheremet-va I removed the `moduleCache` Handling and only used `this.request`
```diff
-const mod = this.moduleCache.get(cacheKey)?.exports || await this.request(dep)
+const mod = await this.request(dep)
```
This alone did not fix the problem, as [this block](https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/src/client.ts#L204-L209) kicks in for the second request to the module and at that point we already have the Module-Symbol set on exports.
In order to fix this, it is necessary to already assign an empty exports object in the module cache for the mocked module. This way the second call to `requestWithMock()` would return this empty object, which later gets filled once the first call …
> fix(mocker): set cache before mocking to allow circular dependencies

- docs/config/index.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/types/config.ts
- test/core/vitest.config.ts
> feat: slow test threshold

- packages/browser/package.json
Running `pnpm rollup --help`: `--watch.include <files>     Limit watching to specified files`
> fix(browser): wrong path on dev:node script

- .vscode/settings.json
- docs/config/index.md
- docs/guide/coverage.md
- packages/vitest/src/types/coverage.ts
- adds **Ignoring code** section to guides
- adds clear descriptions for each coverage option
- ordered coverage options in a logical order
There have been many questions related to coverage options on Vitest Discrod and here on Github issues. Currently the available options are unclear as some options of both providers are not included in documentation. Instead of stating `C8Options`, the documentation should describe all `c8` options that are supported.
> docs(coverage): overall improvements

- docs/api/index.md
- packages/vitest/src/runtime/suite.ts
- packages/vitest/src/types/tasks.ts
- packages/vitest/src/utils/index.ts
- test/core/test/each.test.ts
> feat: format test tablename

- docs/config/index.md
Fixes `coverage.watermarks` section. Related to #2412, oops.
> docs(coverage): watermarks link correction

- packages/vitest/src/integrations/chai/jest-matcher-utils.ts
- test/core/test/basic.test.ts
fix: #2426 
config avoid escapeString
https://github.com/facebook/jest/blob/main/packages/pretty-format/src/index.ts#L147-L151
> fix: escape string

- packages/coverage-c8/package.json
- packages/coverage-istanbul/package.json
- packages/web-worker/package.json
- packages/ws-client/package.json
Rollup's watch mode doesn't seem to work on packages which explicitly set the included source. I think this has been working fine before but noticed that the packages were not reloading any more.
```
System:
OS: macOS 12.5
CPU: (8) arm64 Apple M2
Memory: 3.52 GB / 16.00 GB
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 19.1.0 - /opt/homebrew/bin/node
Yarn: 1.22.19 - /opt/homebrew/bin/yarn
npm: 8.19.3 - /opt/homebrew/bin/npm
Browsers:
Brave Browser: 107.1.45.133
Safari: 15.6
npmPackages:
vite: ^3.2.3 => 3.2.3
vitest: workspace:* => 0.25.3
```
> chore: fix rollup watch mode

- packages/vitest/src/runtime/suite.ts
- test/core/test/utils.spec.ts
Resolves #2420
this PR enhances `formatTitle` function by pretty-formatting individual objects.
also added test suite for `objectAttr` function.
> feat: format test objects (fix #2420)

- docs/config/index.md
- packages/vitest/src/node/reporters/junit.ts
- test/reporters/package.json
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/reporters/tests/reporters.spec.ts
> fix: add test attributes to "testsuites" in junit reporter

- packages/vite-node/src/client.ts
- packages/vite-node/src/types.ts
- packages/vitest/src/integrations/vi.ts
> fix: dynamicImportSettled also waits for nested imports

- packages/vite-node/src/client.ts
- packages/vite-node/src/server.ts
- packages/vite-node/src/source-map.ts
- packages/vite-node/src/utils.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/utils/source-map.ts
- test/stacktraces/vite.config.ts
> fix: always apply vite ssr source maps

- packages/coverage-c8/src/provider.ts
- packages/vite-node/src/client.ts
- packages/vite-node/src/server.ts
- packages/vite-node/src/types.ts
- packages/vite-node/src/utils.ts
- packages/vitest/src/node/core.ts
- test/shard/shard-test.test.ts
> fix: correctly resolve filename, when running code

- packages/vite-node/src/source-map.ts
> fix: move sourcemapping source out of the sourcemap

- docs/.vitepress/scripts/fetch-avatars.ts
- docs/package.json
- pnpm-lock.yaml
This PR increases avatars size to 100x100 when requested to github: avatars folder with avatars 60x60 size  ~540KB, with 100x100 ~1MB.
Also includes missing root script to `build + serve` docs without prefetching avatars.
EDIT: original github avatars size was 40x40.
> docs(fix): blurry avatars

- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/core.ts
Fixes #2393.
Changes the order of `Vitest.start()` (`src/node/core.ts`) call when server restarts.
<details>
<summary>Execution order before</summary>
- `cli::start`
https://github.com/vitest-dev/vitest/blob/b51cda3c4994c8e8168ec5b45aa9070b4c5905ff/packages/vitest/src/node/cli.ts#L118
- `plugins::setServer`
https://github.com/vitest-dev/vitest/blob/b51cda3c4994c8e8168ec5b45aa9070b4c5905ff/packages/vitest/src/node/plugins/index.ts#L172-L174
- `core::setServer`
https://github.com/vitest-dev/vitest/blob/b51cda3c4994c8e8168ec5b45aa9070b4c5905ff/packages/vitest/src/node/core.ts#L58
- `core::start`
https://github.com/vitest-dev/vitest/blob/b51cda3c4994c8e8168ec5b45aa9070b4c5905ff/packages/vitest/src/node/core.ts#L200
- Make change to configuration file
- `core::server.watcher-change` …
> fix: restart on config file change crashes

- packages/coverage-istanbul/src/index.ts
- test/coverage-test/coverage-test/__snapshots__/coverage.istanbul.test.ts.snap
- test/coverage-test/coverage-test/coverage.istanbul.test.ts
Adds snapshot test for `istanbul` provider's coverage result. This should provide confidence for future changes. I'll do same for `c8` some day.
While building the test case I encountered a bug:
When coverage is run with `threads: false`, it is possible that statement counts of coverage report are duplicated. The `coverageProvider.takeCoverage()` (Vitest's internal API, not V8) is called twice without resetting it in between. This can be reproduced in Vitest repository - revert the fix and run `test/coverage-test` tests.
> fix(coverage-istanbul): clear coverage map after use

- packages/vite-node/src/client.ts
- test/core/test/imports.test.ts
> fix: don't throw unhandled error, if import was caught

- packages/vitest/src/node/plugins/index.ts
- test/coverage-test/coverage-report-tests/__snapshots__/c8.report.test.ts.snap
- test/coverage-test/coverage-report-tests/istanbul.report.test.ts
- test/coverage-test/coverage-report-tests/utils.ts
- test/coverage-test/src/utils.ts
> fix(coverage): esbuild to preserve legal comments for ignore hints

- packages/vite-node/src/client.ts
- test/vite-node/src/deps.css
- test/vite-node/src/deps.ts
When I try to use TailwindCSS with SSR on vite-node, I got this error
```
/src/client/base.css:2
__vite_ssr_import_meta__.hot = __vite_ssr_import_0__.createHotContext("/src/client/base.css");const __vite_ssr_import_1__ = await __vite_ssr_import__("/@vite/client");
^
TypeError: Cannot set property hot of #<Object> which has only a getter
at /src/client/base.css:1:94
at ViteNodeRunner.directRequest
...
```
This patch fixed it
> Allow assigning new hotContext

- packages/vite-node/src/client.ts
- packages/vite-node/src/utils.ts
- test/core/test/imports.test.ts
Fixes https://github.com/histoire-dev/histoire/issues/409
> fix: improve "isInternalRequest" check

- packages/vitest/src/runtime/context.ts
There were are 3 places the word 'test' can appear in the 'long-running' warning. Only 2 of them were being replaced with 'hook'. Now all 3 of them are.
> fix: use correct word when printing "long-running" warning

- docs/api/index.md
- examples/mocks/src/moduleB.ts
- examples/mocks/test/factory.test.ts
- packages/vitest/LICENSE.md
- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/runtime/mocker.ts
- packages/vitest/src/types/mocker.ts
This could be helpful to avoid duplicating the path with `vi.importActual` to extend the existing imports.
> feat(mock): expose a `importOriginal` helper to the factory

- docs/api/index.md
We have a lot of questions about mocking, so I think we should update our documentation. Also added missing `vi.doMock` and `vi.doUnmock` methods.
> docs: update API mocking documentation

- docs/config/index.md
> docs: improve interpretDefault docs

- packages/ui/client/components/views/ViewEditor.vue
- packages/ui/client/components/views/ViewReport.cy.tsx
- packages/ui/client/components/views/ViewReport.vue
- packages/vitest/src/api/setup.ts
- packages/vitest/src/integrations/snapshot/port/inlineSnapshot.ts
- packages/vitest/src/node/error.ts
- packages/vitest/src/node/reporters/json.ts
- packages/vitest/src/node/reporters/junit.ts
- packages/vitest/src/typecheck/typechecker.ts
- packages/vitest/src/types/general.ts
- packages/vitest/src/utils/source-map.ts
Starting with [this PR](https://github.com/vitest-dev/vitest/pull/2248) included in [Vitest 0.25.0](https://github.com/vitest-dev/vitest/releases/tag/v0.25.0), Vitest api hasn't been parsing and returning the stacks when a test fails.
This is due to the removal of [this piece of code](https://github.com/vitest-dev/vitest/pull/2248/files#diff-d6bd07e0f22c35d34b1ed42ab42349ba26e7a1a063d3880961b4317ccd3c0b93L157).
A side effect of this is that the VSCode extension for Vitest doesn't show the error at the line where the assertion failure occurs, but rather on the failing test itself.
**Here is the bug in action:**
https://user-images.githubusercontent.com/4410247/209474578-402a6b6a-05d6-4dac-aa0f-d2e98f4a6df3.mov
As you can see, the error displays on the `it` block itself rather than on the …
> fix(api): make api parse error stacks and return sourcePos in onTaskUpdate

- packages/vite-node/src/client.ts
- packages/vite-node/src/types.ts
- packages/vitest/src/utils/import.ts
Fixes #2552
I am not sure, if we should reuse `moduleCache` here, @antfu what do you think? I initially wanted to use original ID and update mod path to `fsPath`, but it complicates things too much, I think.
> fix: start tracking module resolution as soon as possible for easier tracking

- examples/mocks/src/export-default-circle-b.ts
- examples/mocks/src/export-default-circle-index.ts
- examples/mocks/test/circular.spec.ts
- packages/vitest/src/runtime/mocker.ts
> fix: don't hang on mocking module with circular dependency

- packages/ui/client/components/views/ViewEditor.vue
- packages/ui/client/components/views/ViewReport.cy.tsx
- packages/ui/client/components/views/ViewReport.vue
- packages/ui/client/components/views/ViewReportError.vue
- packages/vitest/src/api/setup.ts
- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/node/reporters/json.ts
- packages/vitest/src/node/reporters/junit.ts
- packages/vitest/src/node/reporters/tap.ts
- packages/vitest/src/node/reporters/verbose.ts
- packages/vitest/src/runtime/collect.ts
- packages/vitest/src/runtime/run.ts
- packages/vitest/src/types/tasks.ts
- packages/vitest/src/utils/tasks.ts
- test/reporters/src/data-for-junit.ts
- test/reporters/src/data.ts
- test/reporters/tests/__snapshots__/html.test.ts.snap
- test/reporters/tests/html.test.ts
> feat!: deprecate "error" on result, store errors in "errors"

- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/utils/error.ts
- packages/vitest/src/utils/source-map.ts
With this change:
```
Duration  8.67s (transform 1.68s, setup 580ms, collect 1.59s, tests 5.41s)
```
Before the change:
```
Duration  16.21s (transform 1.70s, setup 29.17s, collect 1.64s, tests 5.34s)
```
We had a single `vi.mock` in `setupFiles`, that was called before each test, but was needed only in one test.
`this.getImporter` took 250-300ms, now it takes ~13ms. This fixes regression, when we added `support-source-map`.
> perf: improve vi.mock performance

- packages/browser/package.json
- packages/ui/client/components.d.ts
- packages/vite-node/package.json
- packages/vitest/LICENSE.md
- packages/vitest/package.json
- pnpm-lock.yaml
Do not bundle cac and picocolors, because they are used between our different packages and increase the overall size.
> chore: don't bundle cac and picocolors

- examples/mocks/src/external/default-function.cjs
- examples/mocks/test/external.test.ts
- examples/mocks/vite.config.ts
- packages/vite-node/src/client.ts
- packages/vitest/src/runtime/execute.ts
> fix: allow mocking CJS module with interoped default

- packages/coverage-c8/src/provider.ts
- packages/coverage-istanbul/src/provider.ts
- Helps preventing crashes where C8 provider causes `ENOTEMPTY` crashes. Mostly seen on Vitest's CI.
I think the root cause is that `require("v8").takeCoverage()` keeps writing the results to file system, and at the same time Vitest is trying to clean the directory. The directory may contain results from earlier run, or it is just being cleaned (#2144). Running `require("v8").stopCoverage()` before removing the directory does not help. To be honest I've never seen `stopCoverage` working correctly. 
I can reproduce the CI failures locally by running `test/coverage-tests` in loop. After ~5-7 `pnpm test` runs the process crashes exactly as it does on CI.
https://github.com/vitest-dev/vitest/blob/6b3e36d4e9fd029984ce0f6a723ddb3fdce92379/test/coverage-test/testing.mjs#L27-L28
```diff
async …
```
> fix: avoid random ENOTEMPTY errors

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/node/reporters/renderers/listRenderer.ts
- packages/vitest/src/node/reporters/renderers/utils.ts
- packages/vitest/src/runtime/collect.ts
- packages/vitest/src/typecheck/collect.ts
- packages/vitest/src/typecheck/constants.ts
- packages/vitest/src/typecheck/parse.ts
- packages/vitest/src/typecheck/typechecker.ts
- packages/vitest/src/types/tasks.ts
- packages/vitest/src/utils/collect.ts
- packages/vitest/src/utils/tasks.ts
- test/typescript/failing/fail.test-d.ts
- test/typescript/test/__snapshots__/runner.test.ts.snap
- test/typescript/test/runner.test.ts
> refactor: make ids in typecheck suites more reliable, store errors in array

- packages/vite-node/src/externalize.ts
- packages/vite-node/src/utils.ts
- packages/vitest/src/node/plugins/cssEnabler.ts
- test/core/test/imports.test.ts
> fix: always inline assets and modules with special queries

- packages/coverage-c8/package.json
- packages/coverage-c8/src/provider.ts
- pnpm-lock.yaml
CSS files are not empty anymore, so coverage started failing.
This filters out `.css` virtual files.
> fix(coverage): validate extension, when reporting c8 coverage

- docs/api/index.md
Result of #2262. Adds a missing alias for `.toThrowError` and adds a note about `.rejects` being required to test async throws.
> chore: Add info to toThrowError docs

- packages/coverage-c8/src/provider.ts
- test/coverage-test/test/no-esbuild-transform.test.js
- test/coverage-test/testing.mjs
- Fixes #2627
The source map may be missing `sourcesContent` when
- it is run through Vitest's mock plugin, which uses `magic-string`
- it is written in Javascript and not processed with `esbuild`, so that `esbuild` is not there the one adding `sourcesContent`
In practice this means that test files written in Javascript that use `vi.mock` are currently crashing c8 provider. 
This seems to be a bug in `magic-string`. I'll open a PR there next.
- https://github.com/Rich-Harris/magic-string/blob/69b13c7a09af742e4f31cf419e8f96e6db32ab5a/src/MagicString.js#L168
- https://github.com/Rich-Harris/magic-string/blob/69b13c7a09af742e4f31cf419e8f96e6db32ab5a/index.d.ts#L38
We could use `includeContent: true` here, but as these are test files we don't really need the sources. With that flag we can …
> fix(coverage): prevent c8 from crashing on invalid sourcemaps

- packages/vitest/src/node/plugins/index.ts
> fix: change Vite root, if test.root is used

- examples/mocks/package.json
- examples/mocks/test/nested-default.spec.ts
- packages/vite-node/src/client.ts
- packages/vitest/src/runtime/mocker.ts
- packages/vitest/src/utils/base.ts
- pnpm-lock.yaml
> fix: don't use ownKeys, when interoping a module

- packages/expect/src/jest-expect.ts
- test/core/test/jest-expect.test.ts
Previously the error message when failing a negated `toHaveBeenCalled` or `toHaveBeenCalledWith` expectation was duplicated. This commit removes the duplication.
The error occurs because `formatCalls` already appends to the message, so appending the result of `formatCalls` to the message results in the original message being duplicated.
Please let me know if the tests are not sufficient enough. I tried matching the complete error message but I was not able to match against the newline character. Also the error message contains some color codes which are a bit hard to test.
> fix(tests): cut duplicate error in negated toHaveBeenCalled

- packages/coverage-istanbul/src/provider.ts
Documentation already states this option is exposed by API. 
https://github.com/vitest-dev/vitest/blob/09d6222669433423a916d086022972761415d245/docs/config/index.md?plain=1#L610-L615
Defaults come from
https://github.com/vitest-dev/vitest/blob/09d6222669433423a916d086022972761415d245/packages/vitest/src/defaults.ts#L38-L40
> fix(coverage): istanbul provider to use `coverage.extension`

- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/worker.ts
- test/core/test/basic.test.ts
Closes #2615
Users should not rely on "process.exit" in their test code, because it will exit Vitest process. It should be mocked in the best case scenario.
> feat: show error, when process.exit is called

- packages/vitest/src/integrations/env/utils.ts
- test/core/test/dom.test.ts
- test/core/test/happy-dom.test.ts
> fix: document.defaultView references the same window as the global one

- docs/api/index.md
- packages/vitest/src/integrations/mock/timers.ts
- packages/vitest/src/integrations/vi.ts
- test/core/test/timers.test.ts
> feat: add runAllTimersAsync from sinonjs

- packages/coverage-c8/src/provider.ts
- packages/coverage-istanbul/src/provider.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/types/coverage.ts
- Fixes #2628
Description of the changes: https://github.com/vitest-dev/vitest/issues/2628#issuecomment-1378365261
Three watch mode related coverage fixes:
- fix(coverage): always print reporter name
- fix(coverage): report on watch mode manually triggered re-runs
- fix(coverage): watch mode to use `coverage.all` only when all tests are run
There are no test cases for watch mode and I'm not sure how those could be implemented at the moment so here's screen capture of manual testing:
https://user-images.githubusercontent.com/14806298/212475460-47fec4d6-1fdd-4f0f-969b-b6f06eb7f10d.mov
> fix(coverage): watch mode to use `coverage.all` only when all tests are run

- packages/ui/client/composables/client/index.ts
- packages/ui/vite.config.ts
fix: #2675
I always send the 'open' signal, but the status also error. 
now force setting status 'OPEN'
> fix(ui): don't show "connecting" screen in html reporter

- packages/vitest/src/utils/collect.ts
Currently it fails, but doesn't show the error
> fix: show error in the terminal, if "only" flag is used

- packages/vitest/rollup.config.js
- test/coverage-test/package.json
- test/coverage-test/test/configuration-options.test-d.ts
Adds typings tests for coverage options. I'm building another coverage related feature, and run into so many internal typing errors that I decided to refactor internal typings quite much. Before refactoring the typings, some tests should be in place.
> test: add typing tests for coverage

- packages/vitest/src/node/pool.ts
Pass cpu and heap profiling related NodeJS execution args to `worker_threads` / `tinypool`. Currently when profiling Vitest performance, the executed tests are excluded from the cpu profile. The main thread's `execArgv` are not passed to `tinypool` options.
- https://nodejs.org/api/process.html#processexecargv
- > The `process.execArgv` property returns the set of Node.js-specific command-line options passed when the Node.js process was launched.
- https://nodejs.org/api/worker_threads.html#new-workerfilename-options
- > `execArgv` `<string[]>` List of node CLI options passed to the worker. [...] By default, options are inherited from the parent thread.
Some examples to demonstrate what exactly ends up in `process.execArgv` and `process.argv` when running Vitest:
<details>
```bash
$ node …
```
> fix: cpu and heap profiling options for workers

- packages/vitest/src/node/pool.ts
> fix: don't terminate workers on Node 14 to not trigger fatal error

- packages/expect/src/jest-extend.ts
- test/core/test/jest-expect.test.ts
> fix: allow custom async matchers

- .github/actions/setup-and-cache/action.yml
- .github/workflows/ci.yml
Adds caching for browser testing libraries binaries. 
Vite has a bit similar setup for Playwright but I think using Node for resolving the version number is more readable. https://github.com/vitejs/vite/blob/f2ee219e2f4d1a6ac09221dfb7807a684847c595/.github/workflows/ci.yml#L85-L106
Each binary is in their own caches, using OS and library version number as cache keys.
> ci: cache cypress, playwright, puppeteer

- packages/ui/node/reporter.ts
if htmlDir already exists the previous code would not create the assets dir, this can cause ENOENT errors whenever htmlDir exists, but assets does not - for instance when outputing junit and html to the same parent folder
```
vitest --reporter junit html --outputFile.html tests/ --outputFile.junit tests/junit.xml
```
I don't understand why the previous code was checking existsSync before mkdir -p. My best guess is performance, but it's not going to have a significant effect.
> fix: ENOENT assets when htmldir exists

- packages/coverage-c8/src/provider.ts
- packages/coverage-istanbul/src/provider.ts
- packages/vitest/src/config.ts
- packages/vitest/src/defaults.ts
- packages/vitest/src/types/coverage.ts
- test/coverage-test/test/configuration-options.test-d.ts
- Split from #2690. This one will be blocked by `c8` for a while so let's merge this separately.
Fixes multiple internal typing violations of coverage typings. Reduces the amount of `as` type assertions used to trick `tsc`. Typings are now actually correct and respond the runtime values.
- Tested intellisense manually on locally linked project
- `test/coverage-test/test/configuration-options.test-d.ts` is passing
> refactor: internal coverage typings

- packages/coverage-c8/package.json
- packages/coverage-c8/src/provider.ts
- pnpm-lock.yaml
Log warning message when `@vitest/coverage-c8` is used in Stackblitz environment. For some time users have been reporting that coverage reports are empty when using `c8`. Stackblitz's web containers do not implement every NodeJS API, e.g. [`v8`'s `takeCoverage`](https://nodejs.org/api/v8.html#v8takecoverage).
Uses same versions of `std-env` and `picocolors` as `vitest` package does so that dependencies are shared.
> fix(coverage): c8 to log warning when run in Stackblitz

- packages/vitest/src/node/reporters/base.ts
- packages/vitest/src/runtime/setup.node.ts
> fix: send stderr header log to stderr

- packages/runner/src/run.ts
- test/fails/fixtures/hooks-called.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
- test/fails/test/runner.test.ts
> fix: call afterAll, if beforeAll failed

- .github/ISSUE_TEMPLATE/bug_report.yml
Include `@vitest/*` packages in `envinfo`. Helps narrowing down issues like https://github.com/vitest-dev/vitest/issues/2716 where users have different versions of `vitest` and other `@vitest/*` packages running.
> chore: bug reports to include `@vitest/*` packages versions

- docs/guide/cli.md
Without passing `--run` to `vitest related`, if it runs in non-ci environments, it causes the `lint-staged` command not to exit because of `vitest` watch mode. In the docs, suggest using the mentioned xargument to prevent probable issues.
> docs(cli): suggest `--run` flag when using `vitest related` with `lint-staged`

- packages/vite-node/src/server.ts
**Resolves**:
https://github.com/nuxt/nuxt/issues/15651
https://github.com/nuxt/nuxt/pull/18447
There may be a legitimate reason to use cache for `timestamp: 0`; if so, please feel free to resolve differently.
> fix(vite-node): don't cache modules with `timestamp: 0`

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/reporters/base.ts
This PR contains couple of fixes and features related to watch mode and filename+testname pattern filters. As each fix/feat builds on top of the other one, here is a single PR containing all. Commits are ready for rebasing (instead of squashing) as well. 
- `fix: watch mode's filename pattern to persist on unrelated file changes`
- Fixes #2728
- `fix: watch mode's filename pattern to persist re-run of failed tests, snapshot updates and testname filter changes`
- Fixes cases where filename pattern was ignored when:
- user pressed `f` to run failed test cases only
- user pressed `u` to update failed snapshots
- user pressed `t` to apply new testname filter
- In all of the cases above the action was also performed against files that did not match the filename pattern
- `fix: dont incorrectly …
> fix: watch mode's filename pattern to persist on unrelated file changes

- packages/coverage-istanbul/src/provider.ts
While looking into other watch mode related issue I noticed that istanbul provider may crash when Vitest has run no tests. These cases may come up for example when filename pattern doesn't match any files.
```
TypeError: coverageMap.files is not a function or its return value is not iterable
```
I can't find a clear place where to add test case for this. I think we need to setup some watch mode tests next.
> fix(coverage): istanbul crashes when no tests were run

- packages/vite-node/src/client.ts
- test/cjs/src/prototype.cjs
- test/cjs/src/prototype.d.cts
- test/cjs/test/prototype.test.ts
- test/esm/src/prototype.d.mts
- test/esm/src/prototype.mjs
- test/esm/test/prototype.spec.ts
- test/esm/vite.config.ts
> fix: cjs exports has Object.prototype instead of null

- packages/vite-node/src/hmr/hmr.ts
When using vite-node HMR, the callbacks registered with:
```ts
if (import.meta.hot) {
import.meta.hot.on("vite:beforeFullReload", () => {
console.log("full reload");
server.close();
});
}
```
are duplicated/accumulated on each reload (logs below after 4 saves):
```bash
> vite-node --watch src/index.ts
listening on port 4000
full reload
listening on port 4000
full reload
full reload
listening on port 4000
full reload
full reload
full reload
listening on port 4000
full reload
full reload
full reload
full reload
listening on port 4000
```
This change ensures that if for the same event, two callbacks are identical, the old one is replaced with the new one.
We can't use reference identity check unfortunately as the identity of the callback change between reloads, hence the usage of …
> fix: duplicate callbacks in vite-node HMR

- docs/guide/coverage.md
- test/coverage-test/coverage-report-tests/__snapshots__/c8.report.test.ts.snap
- test/coverage-test/coverage-report-tests/c8.report.test.ts
- test/coverage-test/coverage-report-tests/utils.ts
- test/coverage-test/src/utils.ts
When writing this part of the guide initially I thought c8's ignore hints would not work, as their regexp is very strict and does not allow additional content such as `@preseve` keywords.
The ignore hints don't work with `@vitest/coverage-istanbul` since esbuild strips the comments before code is instrumented. Istanbul uses ignore hints to check whether coverage counters should be placed in given code block.
With `@vitest/coverage-c8` the coverage filtering is done after the coverage report has been collected. The exclusion is done by comparing results to the actual sources where original comments are in place. `v8-to-istanbul` used by `c8` uses ignore hints to see whether uncovered lines should be marked as covered.
> docs(coverage): c8 ignore hints actually work

- packages/vitest/src/node/core.ts
All tests appear to pass, but "FAIL" is displayed by the file watcher.
```
$ npx vitest typecheck --config ./config/vitest.ts
Testing types with tsc and vue-tsc is an experimental feature.
Breaking changes might not follow semver, please pin Vitest's version when using it.
DEV  v0.28.3 /Users/mascii/repoName
✓ __tests__/testName.types.spec.ts (1)
Tests  1 passed (1)
Type Errors  no errors
Start at  03:20:47
Duration  2.49s
FAIL  Tests failed. Watching for file changes...
press q to quit
```
```typescript
// ./config/vitest.ts
test: {
globals: true,
typecheck: {
include: ["__tests__/**/*.types.spec.ts"],
ignoreSourceErrors: true,
},
},
});
```
> fix: do not include source files in `onWatcherStart` when `typecheck.ignoreSourceErrors` is true

- packages/vitest/rollup.config.js
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/index.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/runtime/execute.ts
- packages/vitest/src/runtime/mocker.ts
- packages/vitest/src/runtime/setup.node.ts
- packages/vitest/src/runtime/worker.ts
- packages/web-worker/src/runner.ts
This gives a small boost to performance, because we only inline a small portion of the codebase. (it was quite small since 0.27.0, but now it's even smaller!)
> perf: don't inline Vitest entry

- packages/vitest/src/node/error.ts
- packages/vitest/src/utils/tasks.ts
> fix: always display serialized error, even if it doesn't have stack

- packages/expect/src/jest-expect.ts
- test/core/test/fn.test.ts
Fixes: https://github.com/vitest-dev/vitest/issues/2849
> fix(expect): check for no 'throw' type in toHaveReturned

- docs/api/index.md
- docs/api/vi.md
- docs/config/index.md
- docs/guide/features.md
- docs/guide/migration.md
- docs/guide/mocking.md
- docs/guide/snapshot.md
- docs/guide/testing-types.md
As it's not within the scope of this PR, might I also suggest that the URLs to the docs within Vitest exceptions are also fixed (or redirected) accordingly?
> docs: fix broken links

- packages/vite-node/README.md
- packages/vite-node/src/cli.ts
In order to fix https://github.com/vitest-dev/vitest/issues/2554, I added a `--script` option to `vite-node` so it can be used in shebang! 🎊 
The code is a bit weird because `cac` does not interpret options passed before positional arguments correctly (see [here](https://github.com/cacjs/cac/issues/25)) so I had to play with this and `process.argv` ordering to have it right.
Another limitation in this implementation is that passing other options in the shebang to `vite-node` won't work, as I expect exact indexes in order to figure out what are the arguments to forward.
It's not perfect but I think it's good enough to unblock people like me as a start. 👍
> feat: add --script option to vite-node

- docs/api/expect.md
- packages/expect/src/jest-expect.ts
- packages/vitest/src/types/global.ts
- test/core/test/jest-expect.test.ts
Fixes https://github.com/vitest-dev/vitest/issues/2804
> fix(expect): accept array index as number in toHaveProperty

- packages/vitest/src/runtime/entry.ts
- test/single-thread/package.json
- test/single-thread/test/a.test.ts
- test/single-thread/test/b.test.ts
- test/single-thread/test/timeout.ts
- test/single-thread/vitest.config.ts
Fixes #2845
When `--no-threads` is enabled, we always need to restore mocks that were defined in a test file.
> fix: clear mocks between tests

- docs/config/index.md
- docs/guide/coverage.md
- packages/vitest/src/integrations/coverage.ts
- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/types/coverage.ts
- test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
- test/coverage-test/coverage-report-tests/custom.report.test.ts
- test/coverage-test/coverage-report-tests/utils.ts
- test/coverage-test/custom-provider.ts
- test/coverage-test/package.json
- test/coverage-test/test/configuration-options.test-d.ts
- test/coverage-test/testing.mjs
- test/coverage-test/vitest.config.ts
- Fixes #2797
Custom coverage providers cannot be Javascript objects anymore. The configuration of `test.coverage.provider` needs to be serializable so that it can be passed to `worker_threads`. Now custom providers are path to a file on file system.
❗ This introduces breaking change to `coverage.provider` API, but it seems that it has never really worked for custom providers.
> fix(coverage): custom providers to work inside worker threads

- docs/config/index.md
- packages/coverage-c8/package.json
- packages/coverage-c8/src/provider.ts
- packages/coverage-c8/src/takeCoverage.ts
- packages/vitest/src/integrations/coverage.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/types/coverage.ts
- test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
- test/coverage-test/custom-provider.ts
- test/coverage-test/test/configuration-options.test-d.ts
Breaking changes:
- `vitest` and `@vitest/coverage-c8` versions must match as the `CoverageProviderModule` introduces new APIs and c8-provider starts to use these. 
- Removes `CoverageProvider.onBeforeFilesRun`. Custom coverage providers should use  `CoverageProviderModule.startCoverage` instead.
Currently Vitest is using [`NODE_V8_COVERAGE`](https://github.com/nodejs/node/blob/main/doc/api/cli.md#node_v8_coveragedir) environment variable to generate V8 coverage reports for `@vitest/coverage-c8`. We've used this environment variable to trigger Node to start writing JSON reports to `<reports-dir>/tmp`. 
These reports contain coverage results of all run code, including Node's internal `node:<module>` and unnecessary third party `**/node_modules/**` packages. In addition the results contain …
> feat!: coverage-c8 to use V8 profiler directly instead of `NODE_V8_COVERAGE`

- docs/api/expect.md
- docs/api/index.md
- docs/guide/features.md
- docs/guide/snapshot.md
docs: update Snapshot section to provide details on how to use with concurrent test
close #2729
> docs: update snapshot section to provide details on how to use with concurrent test

- docs/guide/debugging.md
Reverts vitest-dev/vitest#2085
NDB is no longer supported 😢
> Revert "docs: add instructions for debugging tests via terminal"

- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/worker.ts
- packages/vitest/src/utils/base.ts
- packages/vitest/src/utils/test-helpers.ts
In preparation for #2854
Tests are no longer running in the same worker if they don't share the same environment. This means that they don't share the same module cache and global scope, which should help with isolation. After PR is merged, tests in some projects will take longer to run, but the difference should be insignificant.
This also allows us to add "browser"/"node" conditions based on the environment in the future (we can safely pass `--conditions` to "worker" option).
> feat!: always run separate environments in isolation

- docs/guide/ide.md
Hi! In WebStorm, we have added proper support for Vitest, https://www.jetbrains.com/webstorm/whatsnew/#version-2022-3-vitest-support. We would like to update the documentation on your side to provide up-to-date information about the state of Vitest support in JetBrains IDEs
> docs: add information about built-in support for Vitest in JB IDEs

- packages/vite-node/src/cli.ts
Add CLI support for setting the vite mode e.g.
```bash
vite-node -m bar foo.ts
```
Tested using:
```bash
echo "console.log('mode', import.meta.env.MODE)" > foo.ts && node dist/cli.mjs -m bar foo.ts && rm foo.ts
echo "console.log('mode', import.meta.env.MODE)" > foo.ts && node dist/cli.mjs --mode bar foo.ts && rm foo.ts
```
Side-catch: I couldn't commit without resolving the eslint errors so I fixed those too:
```bash
121:38  error  Unexpected mix of '&&' and '?:'. Use parentheses to clarify the intended order of operations  no-mixed-operators
122:13  error  Unexpected mix of '&&' and '?:'. Use parentheses to clarify the intended order of operations  no-mixed-operators
127:36  error  Unexpected mix of '&&' and '?:'. Use parentheses to clarify the intended order of operations …
```
> feat(vite-node): cli option for vite mode

- docs/api/vi.md
- packages/vitest/src/runtime/mocker.ts
- pnpm-lock.yaml
- test/core/test/do-mock.test.ts
- test/core/test/fixtures/increment.ts
fix: #2870 
[unmock-import.test.ts](https://github.com/vitest-dev/vitest/blob/609185bdc5027fba743ddbd5cb942faaed277cb8/test/core/test/unmock-import.test.ts#L29) has covered the changes for `vi.doUnmock`, so I only add tests for `vi.doMock`.
> fix: cleanup last mocked cache when call vi.doMock

- docs/guide/comparisons.md
I know it is not the job for Vitest docs to create an exhaustive list of framework competitors, however I think adding WebdriverIO as an alternative for Cypress makes sense as it promotes the use of web standards and gives an alternative that is not driven by a cooperation.
> docs: add WebdriverIO to framework comparison section

- packages/coverage-c8/src/provider.ts
- packages/vite-node/package.json
- packages/vite-node/src/client.ts
- packages/vite-node/src/server.ts
- packages/vite-node/src/source-map-handler.ts
- packages/vite-node/src/source-map.ts
- packages/vite-node/src/types.ts
- packages/vitest/LICENSE.md
- pnpm-lock.yaml
Replacing `source-map-support` package with our custom implementation. Also replacing `source-map` package with `@jridgewell/trace-mapping`. This should reduce the size of the package considerably and make `new Error().stack` a bit faster.
> feat: use custom source-map-support implementation

- docs/config/index.md
- packages/vite-node/src/client.ts
- packages/vite-node/src/externalize.ts
- packages/vite-node/src/server.ts
- packages/vite-node/src/types.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/create.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/runtime/execute.ts
- packages/vitest/src/runtime/loader.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/types/worker.ts
- packages/vitest/src/utils/base.ts
- packages/web-worker/src/utils.ts
- tsconfig.json
This PR adds `deps.experimentalOptimizer` option to enable Vite optimizer. It bundles dependencies which makes them faster to import.
Benchmarks on M1 Macbook Air from #579:
Before:
After (notice "collect"):
> First run:
> Second run:
There are a few caveats though. The first run will be slower than subsequent runs because we need to wait until dependencies are bundled (it's still faster than without the optimizer). So it's strongly recommended to have a shared cache for `node_modules/.vitest` folder (or the one you specify in `config.cacheDir`) in your CI environment. This optimization works only in `jsdom`/`happy-dom` environments. `node` and `edge` environments use Vite's SSR optimizer.
> feat: add an option to enable Vite optimizer

- docs/config/index.md
- packages/coverage-c8/rollup.config.js
- packages/coverage-c8/src/provider.ts
- packages/coverage-istanbul/rollup.config.js
- packages/coverage-istanbul/src/provider.ts
- packages/vitest/coverage.d.ts
- packages/vitest/package.json
- packages/vitest/rollup.config.js
- packages/vitest/src/coverage.ts
- packages/vitest/src/types/coverage.ts
- packages/vitest/src/utils/coverage.ts
- pnpm-lock.yaml
- test/coverage-test/coverage-report-tests/__snapshots__/c8.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
- test/coverage-test/coverage-report-tests/generic.report.test.ts
- test/coverage-test/test/__snapshots__/vue.test.ts.snap
- test/coverage-test/vitest.config.ts
- tsconfig.json
- Closes https://github.com/vitest-dev/vitest/issues/1241
- Adds new exported module to `vitest/coverage` entrypoint.
.
> feat(coverage): automatic threshold updating

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/plugins/index.ts
- Fixes issues where configuration file changes were not reloaded in watch mode, https://github.com/vitest-dev/vitest/pull/2886#issuecomment-1436519446
The `options` here is mutated by multiple Vite hooks.
https://github.com/vitest-dev/vitest/blob/b67a5fbdf9940191573c5f90d94be7a2ecb26a36/packages/vitest/src/node/plugins/index.ts#L155-L161
Once it has been initialized by first server setup, the `deepMerge` will take previous values of `options` instead of using the fresh `viteConfig`. This PR will restore the `options` back to initial values when in watch mode.
Tested watch mode locally in linked project by changing `test.reporters` and `test.coverage.provider`. I don't think Vitest has any watch mode related tests set so just manual testing for now.
> fix: reload changed configuration file on watch mode

- docs/config/index.md
- align headings of object-like properties to same level
- prefix coverage options with `coverage.` to align with other similar options
> docs: align heading levels of object-like properties

- packages/coverage-c8/src/takeCoverage.ts
- test/coverage-test/testing.mjs
- Fixes https://github.com/vitest-dev/vitest/issues/2928
Added a failing test case by introducing `isolate` into the coverage test configurations. The `{ isolate: false, singleThread: true }` triggers the reported error message.
> fix(coverage): c8 provider to work when isolate:false

- pnpm-lock.yaml
- test/watch/fixtures/example.test.ts
- test/watch/fixtures/example.ts
- test/watch/fixtures/math.test.ts
- test/watch/fixtures/math.ts
- test/watch/fixtures/vitest.config.ts
- test/watch/package.json
- test/watch/test/file-watching.test.ts
- test/watch/test/stdin.test.ts
- test/watch/test/utils.ts
- test/watch/vitest.config.ts
Adds test cases for some watch mode related features.
Found a way to avoid `node-pty` by patching `process.stdin` of the sub process.
> test: watch mode

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/plugins/index.ts
> fix: optimize dependencies in setup files

- docs/guide/migration.md
Me and a colleague of mine were confused at first when we didn't find a vi.requireActual method, even when searching the documentation. This should hopefully clear things up for other people migrating from jest.
> docs(migration): mention "vi.importActual"

- packages/vitest/src/runtime/rpc.ts
- Fixes https://github.com/vitest-dev/vitest/issues/2938
I can reproduce the reported issue 99% of the times when running a local project. The changes of this PR fix the bug completely.
I was chasing this bug with debugger for long time but I think I finally got it. It's some kind of race condition caused by `setTimeout` and `worker_threads` exiting.
ConsoleLogSpy uses `setTimeout` to group users' test cases' `console.log` calls. The `rpcDone` does not flush setTimeout's. It simply exits before `schedule` gets to run the logging. 
https://github.com/vitest-dev/vitest/blob/bce5a9f8a8572805317ec336bb4289d18606679c/packages/vitest/src/runtime/setup.node.ts#L59-L74
https://github.com/vitest-dev/vitest/blob/bce5a9f8a8572805317ec336bb4289d18606679c/packages/vitest/src/runtime/rpc.ts#L44-L49
> fix: console log not visible

- packages/vitest/src/node/pool.ts
`execArgv` is spread twice. Likely caused by a merge conflict during #2772.
@sheremet-va was this change intentional https://github.com/vitest-dev/vitest/commit/7bf54505a127b976c7e69cbec25cbb2c5bc6219e#diff-c381e6de43a918512ead544ce9b936666a7066fdfddd83c19221b433a01e4ee4R33-R45?
```diff
- ...conditions,
+ ...execArgv,
```
Should this be `...conditions` instead?
> fix: remove duplicate execArgv when deps.registerNodeLoader: true

- packages/vitest/src/runtime/rpc.ts
- packages/vitest/src/runtime/setup.node.ts
- test/core/test/dom.test.ts
- test/watch/test/stdout.test.ts
- Fixes cases where test cases `setTimeout` and `setInterval` could run after environment's teardown was already run
- This bug is only in `main` branch and is not part of any Vitest release. Caused by https://github.com/vitest-dev/vitest/pull/2943.
- Adds test case for #2943
When test run has finished and test environment (jsdom, happydom, custom...) has run its teardown, the `setInterval` and `setTimeout` set by tests may still be running. This was seen on CI where React's 16ms batch runs occasionally ran after JSDOM's `window.close()` was called.
<details>
<summary>Example error log from CI</summary>
```
✓ __tests__/Home.test.tsx  (1 test) 225ms
stderr | unknown test
Warning: React has detected a change in the order of Hooks called by Image. This will lead to bugs and errors if not …
```
> fix: prevent running test cases timers after environment teardown

- docs/guide/cli.md
- packages/vitest/src/node/pool.ts
Adds [bench](https://vitest.dev/guide/features.html#benchmarking-experimental) command to [CLI](https://vitest.dev/guide/cli.html#commands) documentation.
Closes #2807
> docs: add bench command to cli documentation

- docs/guide/migration.md
close: #2831 
Not add the notes of `replaceProperty` with the global object, maybe it's not hard to search how to do it in Vitest.
> docs: add notes about migrating replaceProperty

- packages/spy/src/index.ts
```ts
import { vi, type Mocked } from 'vitest';
type Subject = {
doSomething(x: string): boolean;
};
const mockedSubject: Mocked<Subject> = {
doSomething: vi.fn().mockReturnValue(true),
};
```
This snippet results in the following error when type checking:
```
error TS2322: Type 'Mock<any[], any>' is not assignable to type 'MockInstance<[x: string], boolean> & ((x: string) => boolean)'.
Type 'Mock<any[], any>' is not assignable to type 'MockInstance<[x: string], boolean>'.
The types of 'mockName(...).mock' are incompatible between these types.
Type 'MockContext<any[], any>' is not assignable to type 'MockContext<[x: string], boolean>'.
Type 'any[]' is not assignable to type '[x: string]'.
Target requires 1 element(s) but source may have fewer.
10  doSomething: …
```
> fix(types): use `any` as default value for TArgs in vi.fn()

- packages/vitest/src/node/error.ts
- packages/vitest/src/node/plugins/index.ts
- pnpm-lock.yaml
- test/config/fixtures/test/example.test.ts
- test/config/package.json
- test/config/test/failures.test.ts
- test/config/test/utils.ts
- Preparation for https://github.com/vitest-dev/vitest/pull/2983#discussion_r1130697960
Minimal repro with `0.29.2` to show the silent fail:
```sh
$ pnpm run watch --shard 1/2
> example-project@1.0.0 watch /x/vitest-example-project
> vitest watch "--shard" "1/2"
 ELIFECYCLE  Command failed with exit code 1.
```
With fix:
```sh
$ pnpm run watch --shard 1/2
> example-project@1.0.0 watch /x/vitest-example-project
> vitest watch "--shard" "1/2"
Error: You cannot use --shard option with enabled watch
 ELIFECYCLE  Command failed with exit code 1.
```
> fix: config errors not visible

- packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
- packages/vitest/src/node/reporters/renderers/dotRenderer.ts
- packages/vitest/src/node/reporters/renderers/listRenderer.ts
- Fixes https://github.com/vitest-dev/vitest/issues/2602
Reduces the workload of expensive `renderTree` by bailing out once enough lines to fill the screen has been constructed. I think this fixes #2602 completely as `wrap-ansi` and related dependencies of `log-update` are not called that much anymore. The [`log-update` already limits the printed rows to fit the screen](https://github.com/sindresorhus/log-update/blob/91822b659b249238602e8a69394fdcef63231f5c/index.js#L20-L33) but as it's using `slice-ansi` for this it is slow. We can help it by reducing the passed rows ourselves as we already know "what makes a row" and don't need to care about ANSIs when reducing the rows.  
Using the reproduction case from https://github.com/vitest-dev/vitest/issues/579#issuecomment-1462503600 as …
> perf(reporters): overall improvements

- docs/guide/debugging.md
- packages/vitest/src/node/cli-wrapper.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/runtime/child.ts
- packages/vitest/src/runtime/inspector.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/types/config.ts
- test/config/test/failures.test.ts
- test/config/test/utils.ts
- Fixes https://github.com/vitest-dev/vitest/issues/1867
This solution doesn't utilize NodeJS **CLI arguments** `--inspect` or `--inspect-brk`, but mimics how they work. 
We can only open inspector in a single `worker_thread` or `child_process` at a time so `threads: false` or `singleThread: true` is required. IDEs may do their own magic which allows debugging multiple `worker_threads`, e.g. VSCode's `autoAttachChildProcesses`.
When these flags are used, it's not possible to debug the main thread. But Vitest users should never need to do that, right?
Minimal demo for testing inspector with `worker_threads` and `child_process`: https://gist.github.com/AriPerkkio/ffd517437c50e64ccdc875b5e3553089
> fix: --inspect to work inside workers

- packages/vite-node/src/client.ts
- packages/vitest/src/utils/index.ts
- test/core/test/utils.spec.ts
- test/stacktraces/fixtures/reset-modules.test.ts
- test/stacktraces/test/__snapshots__/runner.test.ts.snap
> fix: show correct line numbers in stack trace when using vi.resetModules()

- docs/config/index.md
- docs/guide/debugging.md
- packages/vitest/src/node/cli.ts
- Closes https://github.com/vitest-dev/vitest/issues/1771
Exposes `testTimeout` configuration option to be configured via CLI, e.g. `vitest run --test-timeout=50000`.
> feat: `--test-timeout` CLI argument

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/types/general.ts
- packages/vitest/src/utils/base.ts
- packages/web-worker/src/utils.ts
I noticed we have a poor TS performance in the repo for quite some time now. I decided to check the performance on PC with 64GB, and it took a few seconds to update autocomplete 👀 
`tsc --generateTrace` showed that `deepMerge` takes _a lot of_ time to process in the `pools/child.ts` file:
Now it's a lot better:
We don't really use the `deepMerge` type merging, so I decided to just remove it.
> chore: fix typescript performance

- docs/config/index.md
- packages/vitest/src/node/pool.ts
- packages/vitest/src/node/pools/child.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/utils/test-helpers.ts
- pnpm-lock.yaml
- test/mixed-pools/package.json
- test/mixed-pools/test/child-specific.child_process.test.ts
- test/mixed-pools/test/threads-specific.threads.test.ts
- test/mixed-pools/vitest.config.ts
In preparation for #2999
This is mainly to allow running browser tests alongside Node.js tests with JSDOM
> feat: add an option to control Vitest pool with filepath

- packages/vitest/package.json
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/pools/threads.ts
- packages/vitest/src/node/state.ts
- pnpm-lock.yaml
- Related to #2008
- Enabled in https://github.com/tinylibs/tinypool/issues/49
Include names of the test files that prevent Worker from terminating. This will help users to identify which test files are causing their Vitest process to hang. **This does not fix** process hangs but just helps debugging them. 
For example with `trpc` repository there are two test cases which can make the process hang. If these two test cases are excluded from the test run, the process never hangs. I'm not familiar with trpc's codebase but I was able to spot that those two test cases are the only ones that use Miniflare which could be the root cause (?) in their case. Ideally this feature would allow users to spot these kind of differences from their test cases and narrow down the root cause. 
Example log …
> feat: process timeout to log names of stuck test files

- packages/vitest/src/runtime/mocker.ts
- test/core/test/mocked-public-key.test.ts
> fix: mocking value proxy filter Symbol static properties

- packages/vitest/src/node/reporters/junit.ts
- test/reporters/src/data-for-junit.ts
- test/reporters/tests/__snapshots__/html.test.ts.snap
- test/reporters/tests/__snapshots__/json.test.ts.snap
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
> fix: escape XML in error stack trace when using junit reporter

- packages/browser/package.json
vitest v0.29.4 was just released, but trying to install `@vitest/browser` currently fails because its peer-dependency is set to vitest `>= 0.30.0`
Maybe this is on purpose, but this PR would avoid passing `--force` or `--legacy-peer-deps` when installing the browser package:
```
npm ERR! Could not resolve dependency:
npm ERR! peer vitest@">=0.30.0" from @vitest/browser@0.29.4
npm ERR! node_modules/@vitest/browser
npm ERR!   dev @vitest/browser@"0.29.4" from the root project
npm ERR!   peerOptional @vitest/browser@"*" from vitest@0.29.4
npm ERR!   node_modules/vitest
npm ERR!     dev vitest@"0.29.4" from the root project
```
> fix(browser): relax vitest peer dependency

- packages/browser/package.json
- packages/browser/src/client/main.ts
- packages/vitest/src/integrations/vi.ts
Refactor `vi`, so `vi.someName` can be passed down without losing a context.
It also throws an error, if the user tries to call mock API without having access to the mocker. Related: #3046
> feat: allow accessing "vi" methods without context, don't fail when mocker is not available

- docs/guide/browser.md
I believe the `you dot-syntax` wording here is an incomplete typo:
https://github.com/vitest-dev/vitest/blob/1531c4208d8a8c54cec9f4d48a17af28345792e2/docs/guide/browser.md?plain=1#L54-L58
This PR attempts to fix said typo, but follows the existing `dot notation` sentences for consistency:
- https://github.com/vitest-dev/vitest/blob/1531c4208d8a8c54cec9f4d48a17af28345792e2/docs/config/index.md?plain=1#L683-L687
- https://github.com/vitest-dev/vitest/blob/1531c4208d8a8c54cec9f4d48a17af28345792e2/docs/config/index.md?plain=1#L1271-L1275
> docs: fix typo in browser mode guide

- docs/guide/cli.md
- docs/guide/index.md
The CLI options table was moved from `index.md` to `cli.md` in https://github.com/vitest-dev/vitest/commit/f741c7e6fba449893049526f5ab48d81ab50cf5a, but the `[cac's dot notation]` reference link was left behind in `index.md`.
> docs: fix cac's dot notation reference link

- packages/vitest/src/types/global.ts
closes https://github.com/vitest-dev/vitest/issues/3052
> fix: add generic to expect.objectContaining type

- packages/vitest/src/api/setup.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/error.ts
- packages/vitest/src/utils/base.ts
- packages/vitest/src/utils/source-map.ts
- test/fails/fixtures/primitive-error.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
> fix: do not fail, when primitive error is thrown

- packages/utils/src/helpers.ts
- test/core/test/utils.spec.ts
Fixes a very, very edge case I ran into with Vitest's `clone`, where a class is proxied in a way that exposes its getters as enumerable properties.
```ts
const dataSym = Symbol.for('MyClass.data')
class MyClass {
constructor(obj) {
this[dataSym] = obj
return new Proxy(this, {
ownKeys() {
return Reflect.ownKeys(obj);
},
getOwnPropertyDescriptor(target, p) {
return {
...Reflect.getOwnPropertyDescriptor(obj, p),
enumerable: true,
};
}
});
}
get a() {
return this[dataSym].a
}
get b() {
return this[dataSym].b    
}
}
```
```ts
deepClone(new MyClass({a: 1, b: 2}))
```
Previously:
```
TypeError: Cannot set property a of #<MyClass> which has only a getter
```
New Behavior: clones properly
> fix: handle cloning proxied classes w/ enumerable getters

- docs/api/vi.md
Documentation elaboration for issue #3058.
I wasn't sure if also adding a note about **idempotence** here would be useful.  I didn't want to cloud the documentation with philosophy, even though this is a critical philosophy and practice.
> docs: elaboration for resetModules

- packages/vitest/src/node/config.ts
This is expected behavior, when you run something in the terminal as `vitest --reporter=../path.js`
> fix: resolve reporters passed down to the CLI relative to the running directory

- package.json
CI runs tests twice. One with default arguments and once with `--no-threads`. Test cases like `test/coverage` and `test/watch` do not respect such arguments coming from CLI. They run exactly the same on both test runs.
- Coverage tests are already testing multiple combinations, including all threading options
- Watch mode tests are using `execa` and do not pass the thread options at all
> ci: reduce running duplicate tests

- packages/vite-node/package.json
- packages/vitest/package.json
- packages/ws-client/package.json
BREAKING CHANGE: Node.js 14.16.0 and 14.17.0 are not supported anymore.
Vite only supports 14.18.0 as minimum as discussed [here](https://github.com/vitejs/vite/pull/12332)
Fixes #2956
> fix!: only support Node.js 14.18.0 or newer

- packages/coverage-c8/package.json
- packages/coverage-istanbul/package.json
BREAKING CHANGE: Coverage packages require latest vitest
- Fixes https://github.com/vitest-dev/vitest/issues/3125
- Context https://github.com/vitest-dev/vitest/pull/3040#discussion_r1155944848
When users are using `vitest@0.29.7` and `@vitest/coverage-*@0.29.8`, Vitest is unable to import the provider. As fix, they should update to `vitest@0.29.8` as well.
> feat!: bump coverage packages vitest peer dependency

- packages/vite-node/src/server.ts
- packages/vite-node/src/source-map.ts
- test/stacktraces/fixtures/error-in-deps.test.js
- test/stacktraces/fixtures/foo.js
- test/stacktraces/test/__snapshots__/runner.test.ts.snap
- test/stacktraces/test/runner.test.ts
- test/vite-node/src/foo.js
- test/vite-node/test/server.test.ts
- Fixes https://github.com/vitest-dev/vitest/issues/3004
> fix: stack trace point to incorrect file (#3004)

- packages/ui/client/composables/client/static.ts
- packages/ui/node/reporter.ts
- packages/ui/package.json
- packages/ui/vite.config.ts
- pnpm-lock.yaml
- test/reporters/tests/html.test.ts
Hi! We are trying to use html reporter in our CI and I mentioned that html.meta.json weighs 35mb for us.
So I think it makes sense to gzip it. After compression with gzip level 9 it weighs 3mb.
> feat: gzip html reporter's metadata

- docs/config/index.md
- packages/vitest/src/integrations/chai/index.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/types/config.ts
> feat: add chai config

- packages/vitest/src/runtime/runners/benchmark.ts
There is a critical bug in `vitest bench` that causes the benchmarks to run in parallel. This defeats the whole point of having a benchmark because the results are all over the place. This PR makes each `bench` to run in sequence and in isolation to produce accurate results.
I also want to mention that `tinybench` (the library `vitest bench` depends on for benchmarking) has also made sequential benchmarks the only default.
This PR partially fixes the umbrella issue #2004
> fix: run benchmarks sequentially (fix #2004)

- packages/snapshot/src/port/state.ts
- packages/snapshot/src/port/utils.ts
This make it easy for testing across OS.
> fix(snapshot): normalize EOL for `toMatchFileSnapshot`

- packages/snapshot/environment.d.ts
- packages/snapshot/manager.d.ts
- packages/utils/package.json
- packages/utils/src/descriptors.ts
- packages/utils/src/diff.ts
- packages/utils/src/external.d.ts
> fix: publish utils and snapshot .d.ts files for typescript

- packages/vitest/src/config.ts
- packages/vitest/src/node/pools/threads.ts
- packages/vitest/src/node/workspace.ts
- packages/vitest/src/runtime/entry.ts
- packages/vitest/src/runtime/runners/benchmark.ts
- packages/vitest/src/runtime/worker.ts
- packages/vitest/src/utils/base.ts
- packages/vitest/src/utils/index.ts
> fix: import performance from perf_hooks and AggregateError from utils

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/workspace.ts
> fix: allow workspace without a config in the root

- packages/vite-node/src/server.ts
- packages/vite-node/src/source-map.ts
- packages/vitest/src/typecheck/collect.ts
- packages/vitest/src/typecheck/typechecker.ts
- test/vite-node/test/server.test.ts
> fix: use relative paths in source map's "sources" field

- packages/coverage-c8/src/provider.ts
- packages/coverage-istanbul/src/provider.ts
- packages/vitest/src/utils/coverage.ts
- Fixes https://github.com/vitest-dev/vitest/issues/3179
No breaking changes as `perFile` of `updateThresholds` is optional flag and defaults to false. 
Tested manually in locally linked project. The current test cases are only checking that `thresholdAutoUpdate` updates the values but doesn't exactly check what values there are.
https://github.com/vitest-dev/vitest/blob/baf902a20b5fdedc095828c081a32ce2baeb2197/test/coverage-test/coverage-report-tests/generic.report.test.ts#L67
> fix(coverage): `thresholdAutoUpdate` to work with `perFile`

- docs/api/vi.md
As I was reading this example, I noticed that the naming of `obj` is rather generic given that one would expect students to understand what an object is. 
Given that the example talks about apples in a contextual way, the suggestion to replace `obj` with `cart` should help improve comprehension for people analyzing the code example.
Happy to chat more if people have questions!
> docs: improve spyOn example with a contextual example

- packages/vitest/src/node/core.ts
- test/global-setup/globalSetup/another-vite-instance.ts
- test/global-setup/globalSetup/default-export.js
- test/global-setup/globalSetup/named-exports.js
- test/global-setup/globalSetup/ts-with-imports.ts
> fix: don't call global setup teardown twice

- examples/mocks/test/error-mock.spec.ts
- packages/vitest/src/runtime/mocker.ts
Error message contains an outdated link:
The change modifies the URL to go to https://vitest.dev/api/vi.html#vi-mock
> docs: updated "vi.mock" documentation link

- .github/workflows/ci.yml
The `test-browser-safari` job keeps failing on CI. Some dependency updates on `pnpm i` and `packages/browser` loads `rollup@2.79.1` which fails to parse import assertions.
Normally `pnpm i` does not update lockfile on CI but I guess that `sudo` part skips it.
> ci: test-browser-safari to not update lockfile

- packages/vitest/src/integrations/coverage.ts
- Closes #3213
In the issue's reproduction case the `@vitest/coverage-c8` does not provide `default` export which causes `coverageModule` to be `undefined`. This makes `core.ts` to think that coverage is disabled.
As solution we should fail whole process if default export is missing.
> fix(coverage): throw error if fail to load built-in provider

- packages/coverage-c8/src/takeCoverage.ts
Vitest should log warning when `@vitest/coverage-c8` is used on Stackblitz: #2735. This broke during #2786 as `takeCoverage` creates a `Promise` that never resolves in Stackblitz where the webcontainers don't implement the Session/Profiler API completely.
This was reported as broken in #3220:
> Vitest hangs when generating coverage in StackBlitz  
Tested in Stackblitz Codeflow.
> fix(coverage): stackblitz hangs with c8

- .github/actions/setup-and-cache/action.yml
The script that parses package versions for cache keys broke after #3211 as `pnpm@8` uses different structure in `pnpm-lock.yaml`. 
Before with `pnpm@7`:
https://github.com/vitest-dev/vitest/blob/b1624db5d3baf26f7e1c69b23cf4c1335562ccde/pnpm-lock.yaml#L258
Now:
https://github.com/vitest-dev/vitest/blob/ddfeb0cfffb4bdf5cacf1bb757ba142d59ae61a6/pnpm-lock.yaml#L346-L348
This PR updates the version parsing patterns and adds a new step for CI to check that versions were somewhat successfully resolved.
> ci: fix cache restore keys on `pnpm@8`

- packages/coverage-c8/package.json
- packages/coverage-c8/src/provider.ts
- pnpm-lock.yaml
- test/coverage-test/coverage-report-tests/__snapshots__/c8.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
- test/coverage-test/coverage-report-tests/generic.report.test.ts
- test/coverage-test/package.json
- test/coverage-test/src/function-count.ts
- test/coverage-test/test/coverage.test.ts
- Fixes #3237
Users may see changes in their coverage summary's `functions` and `branches`. Previously these have included some generated code that should not have ended up in the coverage report. Now the `branch` and `function` counts should correspond the source files.
> fix(coverage): c8 to ignore vite's generated helpers

- packages/coverage-c8/src/provider.ts
- pnpm-lock.yaml
- test/workspaces/coverage-report-tests/check-coverage.test.ts
- test/workspaces/coverage-report-tests/vitest.config.ts
- test/workspaces/package.json
- test/workspaces/src/math.ts
- test/workspaces/vitest.config.ts
> fix(coverage): workspaces c8 source maps

- docs/config/index.md
- packages/vitest/src/types/coverage.ts
- test/coverage-test/test/configuration-options.test-d.ts
- Closes #3253
Exposes `coverage.watermarks` to `c8` provider in typings. The implementation already works as `c8` seems to support these even though they haven't documented it: https://github.com/bcoe/c8/blob/2f36fe9d00bf2f3b869ce890ed11416304c903fe/lib/report.js#L71
> feat(coverage): watermarks for c8

- packages/spy/src/index.ts
- test/core/test/jest-mock.test.ts
Fixes: #3260
The issue currently with `vi.fn` and providing an initial mock implementation (i.e. `vi.fn(() => true)`) is that the provided implementation does not get set by the `enhanceSpy` wrapping. This means that while `stub` is extended to provide the supporting functions that are added by `enhanceSpy`, the state of `implementation` is left `undefined`.
We could go down the path of adding extra parameters and such to `enhanceSpy`, but if we simply call `mockImplementation` during `vi.fn` we can follow the existing logic and have consistent behaviour, allowing the mocked implementation to follow the behaviour we expect.
I've added a test for both the provided implementation and no-implementation cases, as well as updated the other testing / snapshots to reflect this change.
Would love …
> fix(spy): update to set initial implementation through normal logic (fixes #3260)

- docs/.vitepress/config.ts
add activeMatch option in nav config , it can highlight the nav title In the same place
> docs: add nav config activeMatch

- docs/config/index.md
- Closes #3285
Related to #3163.
> docs: specify release version for `--bail` option

- packages/vitest/suppress-warnings.cjs
this pr fix #3270 by adding another message to the suppression set in suppress-warning.cjs
> fix: warning suppression broken (fix #3270)

- docs/.vitepress/style/vars.css
> docs: fix light mode code block style bug

- packages/vitest/src/node/pkg.ts
Changes `ensurePackageInstalled` to also check relative to a file within the `vitest` package. That way, packages like `vitest` that maybe installed as nested dependencies can still be resolved by the `require.resolve` inside `isPackageExists`.
This is my first PR in vitest (hello! happy to be here!). Left a couple of questions inline. 😄 
Fixes #3112.
> fix(vitest): also check for vite relative to vitest package

- .eslintrc
- docs/api/expect.md
- docs/guide/extending-matchers.md
- packages/expect/src/jest-asymmetric-matchers.ts
- packages/expect/src/jest-expect.ts
- packages/expect/src/jest-extend.ts
- packages/expect/src/state.ts
- packages/expect/src/types.ts
- packages/vitest/src/integrations/chai/index.ts
- packages/vitest/src/runtime/runners/test.ts
- packages/vitest/src/types/global.ts
- packages/vitest/src/types/index.ts
- test/core/test/jest-expect.test.ts
This PR removes `Vi` namespace that was used only to declare expect matches. All declarations are moved to `@vitest/expect` package and are exported.
To extend `expect` types, augment a `@vitest/expect`'s `Assertion` interface inside an ambient declaration or right in the file where you extend it:
```ts
interface CustomMatchers<T = any> {
toBeFoo(): T
}
declare module '@vitest/expect' {
interface Assertion<T = any> extends CustomMatchers<T> {}
interface AsymmetricMatchersContaining extends CustomMatchers {}
}
```
The change should be very minor:
```diff
- declare namespace Vi {
+ declare module '@vitest/expect' {
interface Assertion<T = any> extends CustomMatchers<T> {}
interface AsymmetricMatchersContaining extends CustomMatchers {}
}
```
As a library author, you can still provide an old …
> feat!: move assertion declarations to expect package

- docs/guide/filtering.md
Not only test files whose file names contain keywords will be executed, but also test files whose paths contain keywords will also be executed. So I thought it would be better to add an example where the path contains keywords.
> docs: filtering update demo

- docs/api/expect.md
in `expect.stringMatching` and `expect.stringContaining` code block, correct variable usage errors
> docs(expect): correct code block mistake

- packages/vitest/src/node/stdin.ts
- test/watch/test/stdin.test.ts
In debugging, we may need to change the `node_modules` files, but it does not automatically trigger a re-run of the test.
>  Besides, I think press `enter` is a better way to execute rerun. but the `enter` has been used in rerun all tests.
> feat(watch): press `r` should rerun current pattern tests

- packages/vite-node/src/types.ts
This is a small change to the type of `resolveId`. I believe it is only ever awaited, which means it should be safe to synchronously return an id.
I didn't think it was worth adding `@vitest/utils` to benefit from the `Awaitable` type but happy if you think otherwise.
(Might we also want to allow `void`?)
> fix(vite-node): allow returning id not wrapped in promise

- packages/vitest/src/node/core.ts
- packages/vitest/src/node/reporters/junit.ts
- test/config/package.json
- test/config/test/failures.test.ts
- test/config/test/utils.ts
- test/config/vitest.config.ts
- test/coverage-test/coverage-report-tests/generic.report.test.ts
- test/coverage-test/testing.mjs
- Fixes #3330 
- Adds test case for #3131
> fix(reporter): prevent deleting test reports stored in coverage directory

- packages/spy/src/index.ts
- test/core/test/jest-mock.test.ts
> fix: correctly restore vi.fn implementation

- packages/vitest/src/typecheck/parse.ts
- test/typescript/test/__snapshots__/runner.test.ts.snap
- test/typescript/test/runner.test.ts
- test/typescript/test/vitest.custom.config.ts
- test/typescript/tsconfig.custom.json
> fix(typecheck): correctly resolve custom tsconfig path

- docs/advanced/api.md
- packages/vitest/src/node/cli-api.ts
> docs: synchronize startVitest API with docs

- .github/ISSUE_TEMPLATE/bug_report.yml
- examples/README.md
- netlify.toml
- scripts/update-examples.ts
There is currently an issue with the UI not loading if `initialPath` doesn't end in `/`. This PR fixes the online examples while this is being reviewed.
> chore: update StackBlitz initialPath

- packages/vitest/src/node/workspace.ts
- pnpm-lock.yaml
- test/filters/fixtures/test/dont-run-this.test.ts
- test/filters/fixtures/test/example.test.ts
- test/filters/fixtures/test/filters.test.ts
- test/filters/package.json
- test/filters/test/testname-pattern.test.ts
- test/filters/vitest.config.ts
- Fixes #3344
Example of test case failure without PR changes:
```
/root/to/vitest/test/filters
└── fixtures
└── test
├── dont-run-this.test.ts
├── example.test.ts
└── filters.test.ts
```
Running pattern `filter` in `/root/to/vitest/test/filters/fixtures`:
```
FAIL  test/testname-pattern.test.ts > match by pattern that also matches current working directory
Error: Snapshot `match by pattern that also matches current working directory 1` mismatched
❯ test/testname-pattern.test.ts:24:18
22| 
23|   const output = await runVitest(filter)
24|   expect(output).toMatchInlineSnapshot('"pass: test/filters.test.ts"')
|                  ^
25| })
26| 
- Expected  - 1
+ Received  + 1
- `"pass: test/filters.test.ts"
+ `"fail: test/dont-run-this.test.ts␊
```
> fix: exclude `cwd` from test name filter

- packages/vitest/src/node/state.ts
> fix: check error type before modifying it

- packages/utils/src/source-map.ts
- test/core/test/snapshot-inline-(parentheses).test.ts
fix #3370 
Previously, we use `urlLike.replace(/[()]/g, '')` to remove all parentheses in `urlLike`, this will also remove parentheses in file path (`D:\...\snapshot-inline-(parentheses).test.ts:10:8`). We should remove only the leading and trailing parentheses (`(file:///D:/.../index.js:585:15)`).
-----
<a href="https://stackblitz.com/~/github.com/pacexy/vitest/tree/pacexy%2Fissue3370"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github.com/pacexy/vitest/tree/pacexy%2Fissue3370)._
> fix: `toMatchInlineSnapshot` fails when file path includes parentheses (fix #3370)

- packages/spy/src/index.ts
- test/core/test/jest-mock.test.ts
> fix: stop spying on a method, when it's restored

- packages/browser/src/node/esmInjector.ts
- packages/browser/src/node/index.ts
- packages/ui/client/auto-imports.d.ts
- test/core/test/injector-esm.test.ts
> fix(browser): keep default export when rewriting exports

- examples/mocks/test/automocking.spec.ts
- packages/vitest/src/runtime/mocker.ts
> fix: don't restore methods in automocked dependencies

- packages/vitest/src/node/reporters/renderers/dotRenderer.ts
> fix: dot reporter scrollback buffer spam

- examples/mocks/src/main.js
- examples/mocks/test/circular.spec.ts
- packages/vite-node/src/client.ts
Both `main.js` and `mock(./src/B)` will import `A`, resulting in a pending state all the time.
fix: https://github.com/vitest-dev/vitest/issues/2008#issuecomment-1542554048
> fix(vite-node): circular import stuck

- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/stdin.ts
- Fixes #3373
When `CTRL + c` is pressed once Vitest will start to gracefully stop the tests. If the key is pressed again it'll forcefully exit the process. 
When running in non-watch mode, the underlying dependencies (`signal-exit`, I think) seem to take over the `SIGINT` handling and `process.exit()` calls. During the first `SIGINT` they'll let our listener to run without exiting the process. On the second `SIGNINT` their own listener kicks in and stops the process.
> fix: gracefully exit when first `SIGINT` is received

- packages/vitest/src/node/error.ts
- test/core/test/diff.test.ts
- partially fixes issue #3266 (following this maintainer [comment](https://github.com/vitest-dev/vitest/issues/3266#issuecomment-1539326843))
- previously spec filename link were shown in yellow, I changed the color to cyan making easier to find (same as Jest)
- also remove yellow color from test code highlight, simply reverting to default text color
I find this change to be easier to read, especially in dark mode, the link color that is much quicker to find compare to before since everything used to be yellow.
See before/after below (left/right), the biggest difference is obviously in dark mode because of the contrast
> fix(cli): improve colors used when erroring

- packages/vitest/src/node/workspace.ts
- packages/vitest/src/typecheck/typechecker.ts
- test/typescript/test/__snapshots__/runner.test.ts.snap
- test/typescript/test/runner.test.ts
- test/typescript/test/vitest.empty.config.ts
- test/typescript/tsconfig.empty.json
> fix(typecheck): show tsc errors not related to test files

- packages/vite-node/src/client.ts
- test/core/test/imports.test.ts
This PR would...
- Coerce `dep` to string using the string coercion algorithm in `import(dep)`
Need to use `` `${s}` `` instead of `"" + s` in order to get the right hint in `Symbol.toPrimitive`
> ```js
> const obj2 = {
>   [Symbol.toPrimitive](hint) {
>     if (hint === "number") {
>       return 10;
>     }
>     if (hint === "string") {
>       return "hello";
>     }
>     return true;
>   },
> };
> console.log(+obj2); // 10        — hint is "number"
> console.log(`${obj2}`); // "hello"   — hint is "string"
> console.log(obj2 + ""); // "true"    — hint is "default"
> ```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toPrimitive#description
closes  #3429 
-----
<a href="https://stackblitz.com/~/github.com/jcbhmr/vitest/tree/jcbhmr%2Fissue3429">< …
> fix(vite-node): coerce to string in import(dep)

- packages/expect/src/utils.ts
- test/core/test/jest-expect.test.ts
> fix: `rejects` & `resolves` breaks with thenable objects

- packages/ui/package.json
- packages/vitest/package.json
- packages/ws-client/package.json
- pnpm-lock.yaml
- test/core/test/mock-internals.test.ts
- Fixes https://github.com/vitest-dev/vitest/discussions/3457#discussioncomment-6021760
- Related to https://github.com/vitest-dev/vitest/issues/903
- Related to https://github.com/vitest-dev/vitest/issues/2230
- `birpc` changes https://github.com/antfu/birpc/pull/8
When users mock `Math.random` and do not correctly restore it back to original implementation, Vitest will freeze due to `birpc` being unable to pass messages.
It's wrong to not restore mocks after test execution but it's also bad to freeze the test runner.
Minimal reproduction:
```js
beforeEach(() => {
// Math.random is mocked but not restored after test
vi.spyOn(Math, 'random').mockReturnValue(0.1)
})
test('Math.random is mocked', () => {
expect(Math.random()).toBe(0.1)
})
```
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled …
```
> fix: prevent `birpc` timeouts when `Math.random` mock is not restored

- packages/spy/src/index.ts
- test/core/test/vi.spec.ts
- closes #3461
Happy for any feedback.
> fix(types): fix `PartialMock` with async TReturns

- packages/runner/src/suite.ts
- test/core/test/timeout.spec.ts
- test/fails/fixtures/test-timeout.test.ts
- test/fails/test/__snapshots__/runner.test.ts.snap
> fix(runner): suite timeout does not take effect

- packages/runner/src/utils/error.ts
- packages/utils/src/helpers.ts
- test/core/test/error.test.ts
- test/core/test/utils.spec.ts
> fix: assertion diff message now handle non writable property correctly

- packages/vitest/src/node/core.ts
- Related to https://github.com/vitest-dev/vitest/issues/2008#issuecomment-1533226906
Log informative warning when something prevents Vite server from exiting. This is only done when pool (tests/workers) have successfully exited. If workers are stuck we'll log the name of the stuck test file as before: #3031.
This only adds more logging and does not solve the root cause. The root cause is typically in third party code so I'm still not sure how those cases could be caught. 
Minimal reproduction:
```js
import chokidar from "chokidar";
plugins: [
{
name: "bad-plugin-preventing-vite-from-exiting",
configureServer() {
chokidar.watch("./").on("all", () => {});
},
},
],
test: {
reporters: ["verbose"],
},
});
```
```sh
> …
```
> fix: extend logging of process timeout errors

- packages/runner/src/suite.ts
- test/core/test/propagate-options-nested-suite.test.ts
> fix(runner): suite options do not propagate to nested suites (fix: #3467)

- examples/mocks/src/main.js
- examples/mocks/test/circular.spec.ts
- packages/vite-node/src/client.ts
Reverts #3418
`mod.importers.has(importee)` is always true because we add "importee" to importers a few lines prior
> revert: "fix(vite-node): circular import stuck" #3418

- packages/vite-node/src/externalize.ts
- test/core/projects/inline-lib/index.js
- test/core/projects/inline-lib/package.json
- test/core/test/inlined.test.ts
- test/core/vitest.config.ts
> fix(vite-node): deps.inline doesn't work

- test/bail/test/bail.test.ts
- test/coverage-test/testing.mjs
- test/fails/vite.config.ts
- test/public-api/tests/runner.spec.ts
- test/public-api/vitest.config.ts
- test/watch/test/file-watching.test.ts
- test/watch/vitest.config.ts
- tsconfig.json
The typecheck tests of `test/coverage-test` can run into error if `test/watch/test/stdin.test.ts` is running at the same time. The watch test is creating a file that is picked up by typecheck tests and is deleted during the test. This error also came up on CI randomly.
```
RUN  v0.31.3 /x/vitest/test/coverage-test
...
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Typecheck Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: error TS6053: File '/x/vitest/test/watch/fixtures/cancel.test.ts' not found.
The file is in the program because:
Matched by …
```
> test: prevent typecheck conflict between watch and coverage tests

- docs/.vitepress/config.ts
- docs/guide/common-errors.md
- packages/vite-node/src/client.ts
- packages/vitest/src/runtime/execute.ts
- packages/vitest/src/runtime/mocker.ts
- packages/web-worker/src/shared-worker.ts
- packages/web-worker/src/worker.ts
- test/core/test/imports.test.ts
- test/core/test/unmock-import.test.ts
- test/web-worker/test/init.test.ts
- test/web-worker/test/sharedWorker.spec.ts
- test/web-worker/vitest.config.ts
Previously, if we could not resolve the path we just passed it down to `server.transformRequest` in hopes that it would work. However, this is not how it actually works in Vite - the frontend part will throw an error if the path is not resolvable during the transform phase.
This leads to several issues:
- People expect that Vitest takes `tsconfig.json` into account, but it doesn't (`src/file` is not resolved into `<root>/src/file.ts`, we just pass it down without an importer to `server.transformRequest` and it is resolved relative to root by accident)
- Coverage receives unresolved URL (`<root>/src/file` is not a valid path, it doesn't have an extension)
- This creates duplicate entries in the module graph for the same module (it's possible to have both `<root>/src/file.ts` and `src/file` …
> feat!: throw an error, if module cannot be resolved

- packages/ui/client/components/Navigation.vue
There was a few bugs on original PR including html coverage:
- run all test button must call `onRunAll` instead `runAll` function 
- once coverage enabled checked, if coverage visible we should navigate to dashboard
EDIT: we can improve this, but we'll need to include more logic and a new ref to refresh/reload coverage iframe page, it seems the cache headers are ok.
closes #3504
> fix(ui): navigate to dashboard when re-running tests from coverage page

- packages/vitest/src/node/hoistMocks.ts
- test/core/test/injector-mock.test.ts
> fix(mocker): respect namespace import when hoisting vi.mock

- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/plugins/utils.ts
- packages/vitest/src/node/plugins/workspace.ts
- test/core/test/define.test.ts
- test/core/vitest.config.ts
> fix: automatically remove define related configuration

- packages/vitest/src/runtime/child.ts
Fixes https://github.com/vitest-dev/vitest/issues/3578
> fix: import `performance` from `perf_hooks` (fix #3578)

- packages/vitest/src/node/error.ts
This fixes a typo in the current configuration suggestion in the error output. 
`deps.inline` has type `(string | RegExp)[] | true`.
> fix: Typo in config suggestion

- docs/config/index.md
- packages/runner/src/suite.ts
- packages/runner/src/types/runner.ts
- packages/vitest/src/node/cli.ts
- packages/vitest/src/types/config.ts
> feat: add `concurrent` option to `sequence` config

- docs/guide/testing-types.md
Removed duplicate `test.each` in `testing-types.md` file.
Replaced it with only remaining test method that's not mentioned here.
Please double check and correct me if I'm wrong!
> docs(testing-types): replace duplicate test.each

- packages/utils/src/diff/index.ts
- packages/utils/src/error.ts
- test/core/test/jest-expect.test.ts
- test/reporters/tests/__snapshots__/html.test.ts.snap
> fix: show diff correctly

- packages/vitest/src/node/stdin.ts
- Watch mode should be cancellable using any key that Vitest tracks
- Track `h` key for cancelling on-going test run
- Fixes #3612 completely
Tested manually. We have test case for testing cancelling with `c` key but testing all of these would be slow and flaky.
> fix(watch): cancel using `h` key

- packages/utils/src/diff/diffLines.ts
- packages/utils/src/diff/diffStrings.ts
- test/browser/specs/runner.test.mjs
- test/browser/test/failing.test.ts
> fix(browser): correctly print diff

- docs/guide/extending-matchers.md
Interfaces `Assertion` and `AsymmetricMatchersContaining` must be imported from `'vitest'` for correct module augmentation. Otherwise, it will declare whole new interfaces.
> docs: update extending-matchers.md

- packages/browser/src/client/rpc.ts
- packages/vitest/src/runtime/rpc.ts
Some applications defend themselves by freezing their intrinsics. The assignments to `Math.random` break in such an environment.
https://github.com/vitest-dev/vitest/pull/2254/ in 2022 started the assignments to fix compatibility with birpc but it looks like there's a better solution now in https://github.com/vitest-dev/vitest/pull/3460 landed last week. (h/t @mhofman) 
This removes the assignments.
> fix: compat with frozen Math

- docs/api/index.md
- packages/runner/src/run.ts
- packages/runner/src/suite.ts
- packages/runner/src/types/tasks.ts
- packages/vitest/src/node/reporters/renderers/listRenderer.ts
- test/core/test/propagate-options-nested-suite.test.ts
- test/core/test/repeats.test.ts
- test/core/test/retry-only.test.ts
- test/core/test/retry.test.ts
- test/failing/fixtures/expects/soft.test.ts
> refactor(core)!: make the default value of `retry` and `repeats` 0

- packages/coverage-v8/src/provider.ts
- test/coverage-test/.gitignore
- test/coverage-test/coverage-report-tests/__snapshots__/c8.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
- test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
- test/coverage-test/src/dynamic-files.ts
- test/coverage-test/test/coverage.test.ts
- test/coverage-test/testing.mjs
- Fixes #3646
- This only affects files that are `require()`'d and are included in coverage
- Dynamic files that are `import()`'d work already
Using the reproduction case from #3646 (:wave: @vekunz), we can now see the actual coverage of the generated file and don't crash. The branches and functions of the report look a bit weird but those are just the CJS wrapper added by `esbuild` (via `module-from-string`).
```
RUN  v0.32.2 /x/y/vitest-coverage-error
Coverage enabled with v8
✓ src/importModule.spec.js (1)
✓ do something
Tests  1 passed (1)
Start at  11:15:13
Duration  185ms (transform 13ms, setup 0ms, collect 9ms, tests 10ms, environment 0ms, prepare 48ms)
% Coverage report from v8
--------------------------|---------|----------|---------|---------|------------- …
```
> fix(coverage): `v8` to prevent crash on dynamic CJS files

- packages/browser/src/node/esmInjector.ts
- test/core/test/injector-esm.test.ts
Basically cherry-picking https://github.com/vitejs/vite/pull/13635
Fixes #3671
> fix(browser): transform superclass identifier

- test/failing/vite.config.ts
- test/fails/vite.config.ts
- test/public-api/vitest.config.ts
- test/reporters/vitest.config.ts
- test/watch/vitest.config.ts
https://vitest.dev/config/#chaiconfig-truncatethreshold#:~:text=Set%20it%20to%200%20if%20you%20want%20to%20disable%20truncating%20altogether.
> chore: update truncateThreshold value

- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/stdin.ts
- Fixes https://github.com/vitest-dev/vitest/issues/3569
Instead of listening for `SIGINT`, let's listen for keypress and decide how to handle `CTRL` + `c`. The `process.on("SIGINT")` seems to be too difficult to handle: https://github.com/vitest-dev/vitest/issues/3569#issuecomment-1600330892.
https://github.com/vitest-dev/vitest/assets/14806298/51099026-4727-44e7-96e1-6620da7a6a09
Windows + Powershell:
https://github.com/vitest-dev/vitest/assets/14806298/8c884681-2b03-40d1-9e08-9f286c02359d
> fix: `CTRL+C` to terminate run

- CONTRIBUTING.md
- Adds a mention of `VITE_NODE_DEPS_MODULE_DIRECTORIES` to local linked Vitest
- Related to https://github.com/vitest-dev/vitest/pull/3471
> docs: local package linking

- packages/vitest/src/node/cli-api.ts
- packages/vitest/src/node/stdin.ts
- pnpm-lock.yaml
- test/coverage-test/testing.mjs
- test/run/fixtures/example.test.ts
- test/run/fixtures/example.ts
- test/run/fixtures/math.test.ts
- test/run/fixtures/math.ts
- test/run/fixtures/vitest.config.ts
- test/run/package.json
- test/run/test/tty.test.ts
- test/run/vitest.config.ts
- Fixes https://github.com/vitest-dev/vitest/pull/3642#issuecomment-1610938603
- This bug is not part of Vitest releases. It only exists in `main`. No user has run into this.
Clean up the stdin listeners when not in watch mode. Otherwise `ctx.close()` timeouts.
> fix: run mode stuck in TTY terminals

- packages/browser/src/client/main.ts
- packages/browser/src/client/rpc.ts
- packages/vitest/src/runtime/rpc.ts
- test/coverage-test/test/coverage.test.ts
Removes manual mock of `process`. This change unblocks https://github.com/vitest-dev/vitest/pull/3648
> refactor(browser): remove process mock

- docs/api/index.md
- packages/vitest/src/runtime/benchmark.ts
- packages/vitest/src/types/benchmark.ts
- test/reporters/fixtures/function-as-name.bench.ts
- test/reporters/tests/function-as-name.test.ts
Like #3497, but for benchmark API.
> feat: support use function/class as `bench` name

- packages/expect/src/jest-expect.ts
Currently we only say "it's not X times" but not saying why, which make it less useful as users would need to print the `.mock.calls.length` themselves.
> fix: print actual number for `toBeCalledTimes`

- .github/workflows/ci.yml
- Fixes failing CIs
The API does not return download link for Stable+x64+Linux: https://edgeupdates.microsoft.com/api/products
> ci: fix `browser-actions/setup-edge` setup

- packages/vitest/src/integrations/env/jsdom-keys.ts
This PR adds `SubmitEvent`, `DOMRectReadOnly` and `DOMRect` to the JSDom living keys so that they are available in tests when running in the JSDom environment.
- `SubmitEvent` was added to the living interfaces in version 21.1.0 (see [commit](https://github.com/jsdom/jsdom/commit/79c351bc5a#diff-192ca7362e7fb7c4aeae2fa4d091fc7fc66238b69bc2da2ca4e45e73b7511c03)) 
- `DOMRectReadOnly` and `DOMRect` were added to the living interfaces in version 22.1.0 (see [commit](https://github.com/jsdom/jsdom/commit/c9d6b72500#diff-192ca7362e7fb7c4aeae2fa4d091fc7fc66238b69bc2da2ca4e45e73b7511c03))
> Add missing JSDom living keys

- packages/vitest/package.json
- packages/vitest/src/node/pools/threads.ts
- pnpm-lock.yaml
- test/env-mixed/fixtures/project/test/happy-dom.test.ts
- test/env-mixed/fixtures/project/test/jsdom.test.ts
- test/env-mixed/fixtures/project/test/node.test.ts
- test/env-mixed/fixtures/project/test/workspace-project.test.ts
- test/env-mixed/fixtures/vitest.config.ts
- test/env-mixed/fixtures/vitest.workspace.ts
- test/env-mixed/package.json
- test/env-mixed/test/mixed-environments.test.ts
- test/env-mixed/vitest.config.ts
- Fixes https://github.com/vitest-dev/vitest/issues/3659
- Requires: https://github.com/tinylibs/tinypool/pull/63
- Enables: https://github.com/vitest-dev/vitest/pull/3491
When running files with threads enabled, make sure workers are recycled when ever environment options or workspace changes. 
Also noticed that when running tests of workspace through `startVitest` Node API, the logger does not include project names in log entries.
> fix: isolate workers between envs and workspaces

- docs/api/mock.md
per the comment on #3634 this is expected, so this adds a little more clarity about the expected behavior in the relevant docs entry.
> docs: describe mock result behavior with promises

- docs/config/index.md
- packages/vitest/src/defaults.ts
- packages/vitest/src/types/coverage.ts
- test/fails/test/runner.test.ts
- Continues #3453
- It makes more sense to have reports not generated when test failures occur
- `coverage.reportOnFailure` is now `false` by default
> feat!: disable `coverage.reportOnFailure` by default

- docs/guide/cli.md
It's not clear that you need both flags in order to run a specific seed. Adding another example clarifies this.
> docs(cli): add --sequence flag example

- docs/api/index.md
- packages/runner/src/suite.ts
- packages/runner/src/types/tasks.ts
- test/core/test/sequential.test.ts
> feat: support `describe.sequential`

- packages/vitest/src/config.ts
Ported from https://github.com/vitejs/vite/pull/13792
Fully fixes issues like https://github.com/vuejs/create-vue/issues/317 and https://github.com/vuejs/create-vue/issues/313
For easy reproduction, please refer to https://github.com/sodatea/viteste-define-config-bug-repro
I didn't include a test in this PR because:
1. The reproduction is a bit complicated, it only fails on the very latest Vite versions, but updating Vite would mess up the lockfile.
2. By not updating the dependencies, we can make sure that this fix is compatible with older versions of Vite, too.
> fix: port the latest `defineConfig` type from vite

- docs/config/index.md
I was using globs in the external option, which I noticed had no effect. After switching to regexes it started working.
I looked at [this code ](https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/src/externalize.ts#L141-L150) and tried to explain what the option is doing and make it more clear that strings are not simply checked against the id, but rather the `moduleDirectories`.
> docs: Clarify external option

- packages/coverage-v8/src/provider.ts
- test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
- test/coverage-test/src/Counter/index.ts
- Fixes https://github.com/vitest-dev/vitest/issues/3783
Currently the `getSources` does not find source map for some Vue files since `fetchCache` contains entries with query parameters, but v8 coverage reports contain plain filenames. This is exactly the same situation that we've fixed for `@vitest/coverage-c8` and `@vitest/coverage-istanbul` before. 
- The 114d6272fe44e9fdc15ab1069b6550a855c5ea34 modifies the test case enough to make the issue reproduced.
> fix(coverage): v8 provider to pick source maps without url query params

- packages/vitest/src/node/core.ts
- test/watch/fixtures/force-watch/trigger.js
- test/watch/fixtures/vitest.config.ts
- test/watch/test/file-watching.test.ts
> fix: forceRerunTriggers correctly triggers a rerun

- packages/vite-node/src/server.ts
- packages/vitest/src/node/config.ts
> fix(vite-node): always treat node_modules as modulesDirectory

- packages/coverage-istanbul/package.json
- packages/coverage-v8/package.json
- pnpm-lock.yaml
Update `@vitest/coverage-istanbul` package's dependency range for `istanbul-lib-instrument` so that new major is allowed. This requires releasing new version of `@vitest/coverage-istanbul`. 
- https://github.com/istanbuljs/istanbuljs/releases/tag/istanbul-lib-instrument-v6.0.0
Also updates `istanbul-lib-report` to new patch version. This does not require releasing as semver range already allows end users to update their transitive dependencies.
- https://github.com/istanbuljs/istanbuljs/releases/tag/istanbul-lib-report-v3.0.1
Ref. https://github.com/vitest-dev/vitest/discussions/3786
> fix(coverage): update `istanbul-lib-instrument` to v6 to fix vulnerable dependency

- docs/config/index.md
- packages/vitest/src/node/reporters/junit.ts
Add some partial config for https://github.com/vitest-dev/vitest/issues/3691
It would be helpful if some want don't want the `filePath` to be in the `className ` in Junit reporter
> feat: support config junit reporter className with env

- packages/vitest/src/types/config.ts
Noticed conflict between actual default value and IDE's JSDOC hover info. 
https://github.com/vitest-dev/vitest/blob/1cd4eb0f1b568bdc6977fcdeb33ffb0b9dbd23dc/packages/vitest/src/defaults.ts#L70
> docs: fix `teardownTimeout` default JSDOC value

- packages/vite-node/src/utils.ts
- test/core/src/esm/esm.js
- test/core/src/esm/package.json
- test/core/test/imports.test.ts
- test/core/vitest.config.ts
> fix(vite-node): normalize drive letter to keep the same reference to a module

- packages/vitest/src/node/logger.ts
- Fixes #3608
Mac's Terminal App does not reset scrollback buffer when `\x1Bc` (RIS) is printed. Similar report is found from here: https://github.com/xtermjs/xterm.js/issues/3315.
As fix, let's explicitly print `ESC 3J` to erase scrollback.  
Tested on
- Windows 11 21H2, virtualized on MacOS
- Powershell
- CMD
- Git Bash
- VS Code Terminal
- MacOS
- VS Code Terminal
- Warp
- Terminal App
> fix(watch): clear screen on all terminals

- docs/config/index.md
- examples/preact-testing-lib/index.html
- examples/preact-testing-lib/package.json
- examples/preact-testing-lib/src/App.less
- examples/preact-testing-lib/src/App.test.tsx
- examples/preact-testing-lib/src/App.tsx
- examples/preact-testing-lib/src/hooks/useCount.test.ts
- examples/preact-testing-lib/src/hooks/useCount.ts
- examples/preact-testing-lib/src/main.less
- examples/preact-testing-lib/src/main.tsx
- examples/preact-testing-lib/test/setup.ts
- examples/preact-testing-lib/tsconfig.json
- examples/preact-testing-lib/tsconfig.node.json
- examples/preact-testing-lib/vite.config.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/create.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/plugins/utils.ts
- packages/vitest/src/node/plugins/workspace.ts
- packages/vitest/src/node/workspace.ts
- packages/vitest/src/types/config.ts
- pnpm-lock.yaml
> feat: add preact example, remove optimizer experimental status, enable by default

- packages/vitest/src/node/pools/vm-threads.ts
- Not included in https://github.com/vitest-dev/vitest/pull/3203
- Ref. https://github.com/tinylibs/tinypool/pull/58
> fix: pass `--experimental-vm-worker-memory-limit` to `tinypool`

- packages/vitest/rollup.config.js
Currently we bundle `@vitest/utils/source-map` alongside vitest by mistake.
> fix: don't bundle utils' source-map entry

- packages/vitest/src/node/config.ts
Currently, even in watch mode, Vitest determines the memory limit based on all available memory. This PR halves it if tests are running in watch mode.
> fix: reduce the memory consumption when running --experimental-vm-threads

- packages/vitest/src/runtime/execute.ts
- packages/vitest/src/runtime/external-executor.ts
- pnpm-lock.yaml
- test/test-utils/index.ts
- test/test-utils/package.json
- test/vm-threads/package.json
- test/vm-threads/src/external/default-cjs.cjs
- test/vm-threads/src/external/export-default-cjs.js
- test/vm-threads/src/external/export-nested-default-cjs.js
- test/vm-threads/src/external/nested-default-cjs.cjs
- test/vm-threads/src/external/package-null/package-null.js
- test/vm-threads/src/external/package.json
- test/vm-threads/src/external/primitive-cjs.cjs
- test/vm-threads/test/require-cjs.test.js
- test/vm-threads/vitest.config.ts
- This PR fixes the crash that was happening if there was no `package.json` nearby.
- This PR fixes the crash that was happening if the default CJS export was a primitive.
- This PR enabled default interop (check `__esModules` and `exports.default`) in files imported inside node_modules.
> fix: don't crash when using --experimental-vm-threads, interop CJS default inside node_modules

- packages/vitest/src/node/config.ts
`totalmem` returns `undefined` in Stackblitz, which fails `stringToBytes` because it expects a number
> fix: don't crash if total memory is not supported

- docs/config/index.md
- packages/vite-node/src/server.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/pools/rpc.ts
- packages/vitest/src/node/pools/vm-threads.ts
- packages/vitest/src/node/workspace.ts
- packages/vitest/src/runtime/execute.ts
- packages/vitest/src/runtime/external-executor.ts
- packages/vitest/src/runtime/vm/commonjs-executor.ts
- packages/vitest/src/runtime/vm/esm-executor.ts
- packages/vitest/src/runtime/vm/utils.ts
- packages/vitest/src/runtime/vm/vite-executor.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/types/rpc.ts
- pnpm-lock.yaml
- test/vm-threads/package.json
- test/vm-threads/src/external/css/empty.css
- test/vm-threads/src/external/css/processed.css
- test/vm-threads/src/external/css/processed.module.css
- test/vm-threads/test/import-external-css-assets.test.js
- test/vm-threads/vitest.config.ts
Fixes #3862
New `--experimental-vm-threads` allows us to process `.css` files and assets inside Node.js modules without manually inlining them. We can give better performance inside this pool by enabling CSS and asset processing without asking people to manually inline the whole library.
Unfortunately, other pools cannot support this until [Node.js loader](https://github.com/nodejs/loaders) is standardized (the development is very fast, we can't keep up with the changes to be honest).
TODO:
> feat: allow importing CSS and assets inside external dependencies

- docs/guide/migration.md
Hey 👋  
Reading through the migration docs I found the section on "Jasmine APIs" very confusing. This reads to me like "there is a difference between `expect.any` in Jest and you need to migrate to something on the linked to page".
But this isn't the case as far as I know. The assymetric matchers, i.e. `expect.any` `expect.anything` etc work exactly the same. There is also nothing in the Jest documentation regarding exporting anything from their forked Jasmine package.
Most Vitest and Jest users will have no idea what Jasmine even _is_ or what it does.
Maybe someone can clarify what we're trying to say here? Otherwise better to just remove it since this is not actionable. 😄
> docs: remove section about jasmine from migration page

- docs/guide/index.md
The docs talk about TypeScript's `triple slash commands` but they are called `triple slash directives` in TypeScript's docs.
> docs: Fix incorrect word in getting started docs

- docs/guide/migration.md
This PR slightly updates the [Migration Guide](https://vitest.dev/guide/migration.html) to use header markup instead of bolded text for the subheaders. It's more accessible and easier to link to specific sections with headers:
> docs(migration guide): use headers instead of bold text

- packages/vitest/src/integrations/env/index.ts
- test/env-custom/vitest-environment-custom/package.json
Sourcing from https://github.com/danielroe/nuxt-vitest/pull/290#issuecomment-1678093293
While triaging issue I discovered that there's an issue with loading a pure ESM custom environment. It fails with the following issue:
```
Error: Cannot find module '/Users/daniel/code/vitest-environment-nuxt/playground/nuxt' imported from /Users/daniel/code/vitest-environment-nuxt/node_modules/.pnpm/vitest@0.34.1_happy-dom@10.8.0_jsdom@22.1.0/node_modules/vitest/dist/vendor-environments.443ecd82.js
❯ new NodeError node:internal/errors:387:5
❯ finalizeResolution node:internal/modules/esm/resolve:330:11
❯ moduleResolve node:internal/modules/esm/resolve:907:10
❯ defaultResolve node:internal/modules/esm/resolve:1115:11
❯ nextResolve node:internal/modules/esm/loader:163:28
❯ ESMLoader.resolve …
```
> fix(vitest): use esm module resolution to resolve env

- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/plugins/utils.ts
- packages/vitest/src/node/plugins/workspace.ts
- test/core/test/env-jsdom.test.ts
Fixes #3933 
Fixes #3948 
Fixes #3860
> fix(vitest): allow rewriting process.env.NODE_MODE when using web transform mode

- packages/vite-node/src/client.ts
- packages/vite-node/src/utils.ts
- packages/vitest/src/node/plugins/ssrReplacer.ts
- test/core/test/env.test.ts
> fix: define process variable and using import.meta.env together did not work

- packages/runner/src/utils/tasks.ts
This will probably not have an impact on test times because the reporter runs on a separate thread but should help with some flickering. Maybe it has an effect on lower end devices but hey why waste CPU cycles anyway right?
> perf(dot-renderer): speed up getTests

- packages/snapshot/src/port/inlineSnapshot.ts
- test/core/test/inline-snap.test.ts
- test/snapshots/test-update/snapshots-inline-js.test.js
- test/snapshots/test/__snapshots__/shapshots.test.ts.snap
- test/snapshots/tools/inline-test-template.js
> fix: update inline snapshot correctly

- packages/vitest/src/runtime/vm.ts
- test/core/test/fixtures/timers.suite.ts
- test/core/test/timers-jsdom.test.ts
- test/core/test/timers-node.test.ts
> fix: don't crash when calling useFakeTimers in VM pool

- packages/browser/src/client/snapshot.ts
- packages/snapshot/src/manager.ts
- packages/snapshot/src/port/utils.ts
- packages/snapshot/src/types/environment.ts
- packages/ui/client/components/views/ViewEditor.vue
- packages/ui/client/composables/client/static.ts
- packages/utils/src/source-map.ts
- packages/vitest/src/api/setup.ts
- packages/vitest/src/api/types.ts
- packages/vitest/src/integrations/browser/server.ts
- packages/vitest/src/node/create.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/plugins/utils.ts
- packages/vitest/src/node/plugins/workspace.ts
- pnpm-lock.yaml
- test/restricted/package.json
- test/restricted/src/math.js
- test/restricted/tests/basic.spec.js
- test/restricted/vitest.config.ts
- test/restricted/vitest.setup.js
With 0.34.0 we now process files without SSR flag which requires the file to be inside the workspace/project root. Sometimes this is not the case, like with setup files.
This PR allows importing files outside of the root directory but inside the config directory.
Fixes #3953
Fixes part of #3948
This PR also restricts what can be accessed with websocket connection that's established for Vitest UI.
TODO:
> fix: restrict access to file system via API

- packages/vitest/src/node/plugins/cssEnabler.ts
- test/css/test/process-inline.spec.ts
- test/css/testing.mjs
As per the vite docs here: https://vitejs.dev/guide/features.html#disabling-css-injection-into-the-page
Using the 'inline' query parameter for CSS has different semantics than regular css imports and the expected return value should be a string as the default export.
Fixes: #3954
> fix: don't mock css-module if inline is specified

- docs/guide/coverage.md
- packages/ui/client/composables/navigation.ts
- packages/ui/node/index.ts
If you provide `subdir` option in the html coverage reporter, Vitest UI  Coverage will not work since the `index.html` is inside the `subdir` and not in the `reportsDirectory`.
This PR configures properly the middleware when `subdir` is configured and the client will check also for `subdir` option to change the url.
This PR also updates the `Vitest UI` subsection in the Coverage docs.
From this discussion: https://github.com/vitest-dev/vitest/discussions/3916
To check Vitest UI Coverage is working:
- build Vitest: run `pnpm run build` from root folder
- change `'html'` in the `coverage.reporter` list with  `['html', { subdir: 'somepath' }]` in `test/core/vitest.config.ts` configuration file
- change to `test/core` folder (`cd test/core`) and run `pnpm vitest --open --ui …
> fix(ui): add support for ui coverage with subdir option

- docs/api/index.md
- docs/guide/test-context.md
- packages/runner/src/context.ts
- packages/runner/src/errors.ts
- packages/runner/src/run.ts
- packages/runner/src/suite.ts
- packages/runner/src/types/tasks.ts
- packages/utils/src/helpers.ts
- packages/vitest/src/node/state.ts
- test/core/test/skip.test.ts
> feat(vitest): allow calling `skip` dynamically

- packages/utils/src/error.ts
- test/core/test/jest-expect.test.ts
> fix(expect): correctly show async matcher diff

- packages/vitest/src/integrations/env/happy-dom.ts
- packages/vitest/src/types/config.ts
- packages/vitest/src/types/happy-dom-options.ts
- packages/vitest/src/utils/test-helpers.ts
- test/core/test/happy-dom-custom.test.ts
- test/core/test/happy-dom.test.ts
This PR forwards the `environmentOptions` to `happy-dom` integration.
It follows the same principle defined in the `jsdom` integration
https://github.com/vitest-dev/vitest/blob/f4e6e99fa3a81fd7a97fb9b435da367dddba7fa4/packages/vitest/src/integrations/env/jsdom.ts#L32
> Reference: https://github.com/capricorn86/happy-dom/wiki/Getting-started#usage
Closes #3903 
Closes #3905
> fix: pass environmentOptions to happy-dom integration

- docs/config/index.md
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/plugins/optimizer.ts
- packages/vitest/src/node/plugins/utils.ts
- packages/vitest/src/node/plugins/workspace.ts
- packages/vitest/src/node/workspace.ts
Currently, optimizer doesn't work when `--api` or `--ui` is not passed down (this is happening because Vitest incorrectly extended optimizer configuration from Vite). This should be resolve separately before releasing 1.0.0.
Closes #3861
> fix(vitest): correctly resolve optimizer status

- docs/config/index.md
- packages/vitest/src/defaults.ts
When running the coverage report in a Vitest workspace will `all: true`, the `vitest.workspace.ts` file is analyzed for the coverage generation.
This PR adds the potential file names (from [docs](https://vitest.dev/guide/workspace.html#defining-a-workspace)) to the default coverage excludes.
> fix: add workspace config files to default coverage excludes

- docs/.vitepress/config.ts
- docs/advanced/reporters.md
- packages/vitest/package.json
- packages/vitest/reporters.d.ts
- packages/vitest/rollup.config.js
- packages/vitest/src/node/reporters/index.ts
- packages/vitest/src/public/reporters.ts
> feat(vitest): export all reporters in `vitest/reporters`

- packages/vite-node/rollup.config.js
- packages/vite-node/src/hmr/emitter.ts
Fixes #3704
Partial revert of #3291
The initial externalization happened because we had misalignment with Vite HMR types once in a while, but later it turned out that these types were not publically available, so we are reverting it back.
> fix(vite-node): inline HMR types

- packages/vitest/src/runtime/external-executor.ts
- packages/vitest/src/runtime/vm/vite-executor.ts
> chore: cleanup typos, remove any in VM executor

- docs/config/index.md
As discussed in [this comment](https://github.com/vitejs/vite/issues/13950#issuecomment-1670085440), it's not trivial to understand how to merge a vite config defined as a function. Here's what I added concerning it:
> docs: add example for merging vite config defined as a function

- packages/expect/src/jest-utils.ts
- packages/web-worker/src/utils.ts
- test/web-worker/test/init.test.ts
- test/web-worker/test/jsdom.test.ts
- test/web-worker/test/sharedWorker.spec.ts
- test/web-worker/vitest.config.ts
> fix(web-worker): don't rely on browser API when it's not provided

- packages/coverage-istanbul/package.json
- packages/coverage-istanbul/src/provider.ts
- packages/coverage-v8/src/provider.ts
- packages/vitest/src/node/core.ts
- pnpm-lock.yaml
Fixes https://github.com/vitest-dev/vitest/discussions/4013.
When using coverage reporters which don't output anything to terminal, there is no need to log the info message.
-  The `test/fails` has a test case that is verifying this info message
> fix(coverage): log info only when terminal reporter is used

- packages/vitest/src/integrations/vi.ts
Allow passing down `vi.{method}` and chaining its result:
```ts
function chainable(fn: () => VitestUtils) {
fn().useRealTimers()
}
chainable(vi.useFakeTimers)
```
> fix(vitest): "vi" doesn't rely on context

- packages/vite-node/src/server.ts
- packages/vite-node/src/source-map.ts
- packages/vite-node/src/utils.ts
Discovered when debugging nuxt/nuxt#20446, if the root starts with the same path as something being resolved - for example if the root is `/app` and we are resolve the id `/app.vue` then we were not correctly prefixing the root directory to the incoming id.
In actual fact this PR is not required to fix the linked issue, which can be resolved entirely in vite (for which I have opened https://github.com/vitejs/vite/pull/14241). But I do think it is safer to test with trailing slash to ensure that we are indeed talking about files _within_ the directory and not within a sibling directory with a similar name.
> fix(vite-node): check more precisely for root/base paths

- packages/vitest/src/node/cache/index.ts
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/plugins/utils.ts
We now use a different cache directory per project in the workspace this way we don't wind up accidentally deleting the cache directory from one project as the next one starts running.
I'm using a hash of the project name as the basis for constructing the cache sub-directory. Using a hash here is primarily done as a way to avoid sanitizing the project name to remove characters that aren't valid directory names and dealing with collisions for similarly named projects that contain invalid characters ("Foo<" and "Foo>" might both sanitize to "Foo_") for example.
A potential downside to using project name (hashed or not) is that workspaces which don't define project names for their projects will fall back to using an index as the project name. As a result, changing the order of the projects …
> fix: resolving dep optimizer issues with workspace

- packages/vitest/src/integrations/browser/server.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/workspace.ts
> fix: don't process config file twice

- packages/vite-node/src/source-map.ts
In Vite 5, the `map` type is `SourceMap | { mappings: '' }` and the new `{ mappings: '' }` type trips up TypeScript. This PR handles the typecheck fail from[ vite-ecosystem-ci](https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6069325893/job/16463576124#step:8:795)
Disable whitespace when reviewing the git diff, as I'm only wrapping `if ('sources' in map) { ... }` between the affected code.
> chore: update sources type for vite 5

- packages/runner/src/utils/collect.ts
- test/filters/test/testname-pattern.test.ts
> fix(runner): incorrect test name pattern matching

- packages/vite-node/README.md
I noticed a few minor typos/grammatical mistakes in the vite-node README. Here are some proposed amendments to address them.
> docs: fix typos/grammar in vite-node README

- docs/guide/index.md
This PR removes the bellow warning when running docs.
> docs: remove `log` language warning

- packages/ui/client/components/views/ViewReport.vue
- packages/vitest/src/api/setup.ts
When the caller has no access to an API, the API will throw an error instead of doing nothing. Currently we have a problem with snapshots in browser that we were not able to caught because of this.
> fix(vitest): show error when calling API on files that user has no access to

- packages/runner/src/utils/collect.ts
- test/filters/test/testname-pattern.test.ts
This reverts commit b5bf32907fae8b8b4508689a32205f94056a721e.
Reverting looks like the most straightforward option to me. Once WebStorm 2024.1 is released, the original commit can simply be merged again.
> fix(runner): restore leading space in `testNamePattern` (#4103)

- docs/config/index.md
Add docs for onConsoleLog.
Close #3632
> docs: add onConsoleLog

- docs/config/index.md
- packages/coverage-istanbul/src/provider.ts
- packages/vitest/src/types/coverage.ts
- test/coverage-test/test/configuration-options.test-d.ts
Add support for passing `100: true` for `@vitest/coverage-istanbul`
Close #3566
> feat(coverage): add `coverage['100']` to istanbul provider

- docs/api/vi.md
- packages/vitest/src/integrations/mock/timers.ts
- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/integrations/wait.ts
- test/core/test/wait.test.ts
- test/core/test/waitFor.test.ts
Partial closes - #4061
The `waitFor` function was inspired by https://github.com/testing-library/web-testing-library/pull/2.
Currently only supports `timeout` and `interval` options. I think this is enough, Let me know if you need to add any other options!
> feat(vitest): support `vi.waitFor` method

- packages/snapshot/src/port/inlineSnapshot.ts
- test/snapshots/test-update/snapshots-inline-js.test.js
- test/snapshots/test/__snapshots__/shapshots.test.ts.snap
- test/snapshots/tools/inline-test-template.js
- Undesired behavior happens when you use multiple `expect(...).toMatchInlineSnapshot()` methods within same `it` or `test` block and you mix method with shape object with placeholders as 1st argument and method without that.
- Vitest either doesn't update any inline snapshot or it may update even wrong inline snapshot under rare curcumstances.
> fix(inline-snapshot): support mix of normal/with placeholders snapshots

- packages/vitest/src/integrations/env/index.ts
- packages/vitest/src/runtime/child.ts
- packages/vitest/src/runtime/vm.ts
- packages/vitest/src/runtime/worker.ts
- test/env-custom/vitest-environment-custom/index.ts
- test/env-custom/vitest-environment-custom/package.json
Related https://github.com/danielroe/nuxt-vitest/pull/290
> feat(vitest): allow using unprocessed environment files

- docs/.vitepress/scripts/fetch-avatars.ts
- docs/.vitepress/scripts/transformHead.ts
Hi, this PR aims to make a minor improvement to the documentation. We are implementing concurrent image downloading to enhance performance and resource management. Additionally, we are adding the 'as' attribute to the `link rel="prefetch"` element, following the reference provided here: https://web.dev/codelab-two-ways-to-prefetch/#prefetch-the-product-page-with-lesslink-rel=prefetchgreater.
> docs: Concurrent image downloading and `as` an attribute for prefetch links

- .github/workflows/bench.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
I noticed that the [job](https://github.com/vitest-dev/vitest/actions/runs/6079780651/job/16492779749?pr=4071) failed because @action/checkout3
> chore: upgrade @action/checkout to 4

- docs/api/vi.md
- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/integrations/wait.ts
- test/core/test/wait.test.ts
close: https://github.com/vitest-dev/vitest/issues/4061
A question for we need to strict the returns value for callback?
> feat(vitest): support `vi.waitUntil` method

- packages/vitest/src/runtime/vm/commonjs-executor.ts
- test/vm-threads/test/module.test.js
> perf: use lazy require in vm pool

- packages/vitest/src/types/happy-dom-options.ts
Simply adds optional `navigator` property with optional `userAgent` subproperty to `HappyDOMOptions`.
happy-dom [release v12.0.0](https://github.com/capricorn86/happy-dom/releases/tag/v12.0.0) added a setting allowing the userAgent to be changed, as well as updating the default.
For example, the following configuration can be used but currently needs a `@ts-ignore`(a workaround for https://github.com/mui/mui-x/issues/10374):
```
environmentOptions: {
happyDOM: {
settings: {
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
navigator: {
userAgent: 'Mozilla/5.0 (linux) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/22.1.0',
},
},
},
},
```
- [-] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or …
> fix: Update HappyDOMOptions to be compatible with v12

- examples/mocks/test/factory.test.ts
- packages/expect/src/jest-expect.ts
- test/core/test/jest-expect.test.ts
> fix: print value shape when .resolves and .rejects fails

- packages/vitest/src/node/plugins/workspace.ts
- test/workspaces/globalTest.ts
- test/workspaces/space_1/test/env-injected.spec.ts
- test/workspaces/space_1/vite.config.ts
> fix(vitest): inject "define" in workspaces

- packages/ui/rollup.config.js
I just did a little simplification. `map` + `flat` can be replaced by single `flatMap`.
> fix: use flatMap instead of map_flat in rollup config

- packages/ui/client/components/views/ViewReport.cy.tsx
- packages/ui/client/components/views/ViewReportError.vue
close https://github.com/vitest-dev/vitest/issues/3675
> fix: correctly render ansi diff

- packages/expect/src/jest-expect.ts
- test/core/test/jest-expect.test.ts
> fix(expect): improve the error message when nothing is thrown when ing `toThrow`

- packages/vitest/src/node/pools/threads.ts
- packages/vitest/src/node/pools/vm-threads.ts
- packages/vitest/src/utils/memory-limit.ts
We found an issue running vitest in self-hosted github action runners where they use as MAX_THREADS the number of CPUs available in the node instead of respecting the resources.limits assigned to the pod.
Introduced in v19.4.0, v18.14.0, [`os.availableParallelism()`](https://nodejs.org/api/os.html#osavailableparallelism) allow us to estimate of the default amount of parallelism a program should use instead of using [`os.cpus`](https://nodejs.org/api/os.html#oscpus) .
> os.cpus().length should not be used to calculate the amount of parallelism available to an application. Use [os.availableParallelism()](https://nodejs.org/api/os.html#osavailableparallelism) for this purpose.
A similar work was already done in another libs like https://github.com/jestjs/jest/pull/13738.
> chore: update threadsCount logic to use availableParallelism

- docs/api/vi.md
I was trying to make some tests that required mocking the system date, and noticed the docs refer to `vi.restoreCurrentDate()` which does not exist.
The documentation of `setSystemTime()` includes in its example `vi.useRealTimers()`, so I don't think another function is needed.
> fix: Remove reference to vi.restoreCurrentDate() from doc (does not exist)

- packages/runner/src/fixture.ts
- packages/runner/src/run.ts
- test/core/test/test-extend.test.ts
close: #4165 
I noticed that the previous implementation of teardown was incorrect, in playwright, teardown is executed before `afterAll` hook.
1. Correct teardown implement (should be called teardown before calling `afterAll` hook, follow the rule by the playwright)
2. Each fixture of the same `test.extend` instance is setup only once
The following example describes the execution order
```ts
describe('fixture in nested describe', () => {
interface Fixture {
foo: number
bar: number
}
const fooFn = vi.fn(() => 0)
const fooCleanup = vi.fn()
const barFn = vi.fn(() => 0)
const barCleanup = vi.fn()
const nestedTest = test.extend<Fixture>({
async foo({}, use) {
await use(fooFn())
fooCleanup()
},
async bar({}, use) {
await use(barFn())
barCleanup()
},
})
beforeEach<Fixture>(({ foo }) => { …
```
> fix(runner): the fixture of `test.extend` should be init once time in all test

- .github/workflows/ci.yml
- docs/api/vi.md
- docs/config/index.md
- docs/guide/debugging.md
- package.json
- packages/ui/package.json
- packages/vitest/package.json
- packages/vitest/src/api/setup.ts
- packages/vitest/src/integrations/mock/timers.ts
- packages/vitest/src/integrations/vi.ts
- packages/vitest/src/node/pools/child.ts
- packages/vitest/src/runtime/child.ts
- packages/vitest/src/runtime/rpc.ts
- packages/vitest/src/runtime/vm.ts
- packages/vitest/src/types/child.ts
- packages/vitest/src/types/worker.ts
- packages/ws-client/package.json
- packages/ws-client/src/index.ts
- pnpm-lock.yaml
- test/bail/test/bail.test.ts
- test/config/fixtures/test/fake-timers.test.ts
- test/config/test/failures.test.ts
- test/core/test/fixtures/timers.suite.ts
- test/setup/tests/setup-files.test.ts
- test/test-utils/index.ts
- test/ui/setup.ts
- test/ui/test/html-report.spec.ts
- test/ui/test/ui.spec.ts
- Many projects are unable to use `node:worker_threads` and are forced to use a single `node:child_process` via `--no-threads`. That's stable, but slow. This PR allows using multiple `node:child_process` for running tests similarly as `--threads` does.
- https://github.com/vitest-dev/vitest/issues/3143
- https://github.com/vitest-dev/vitest/issues/3106
- https://github.com/vitest-dev/vitest/issues/3816
- https://github.com/tinylibs/tinypool/issues/48
- Ref. https://github.com/tinylibs/tinypool/issues/64
`useFakeTimers()` no longer automatically mocks `process.nextTick`. Users can still mock it by explicitly specifying `useFakeTimers({ toFake: ['nextTick'] })`.
Mocking `process.nextTick` by using `useFakeTimers({ toFake: ['nextTick'] })` is no longer supported when running in …
> feat!: support multiple parallel `child_process`

- docs/api/vi.md
Updates documentation for `vi.doMock` to be clearer that it only mocks subsequent dynamic imports (e.g. using `await import`)
See #4166 for more context
> docs: vi.doMock includes that it mocks subsequent dynamic imports

- .eslintrc
- examples/basic/test/__snapshots__/suite.test.ts.snap
- examples/mocks/test/error-mock.spec.ts
- examples/react/test/__snapshots__/basic.test.tsx.snap
- examples/vitesse/test/__snapshots__/basic.test.ts.snap
- examples/vue-jsx/test/__snapshots__/case.test.ts.snap
- examples/vue/test/imports.test.ts
- examples/vue2/test/__snapshots__/basic.test.ts.snap
- examples/vue2/test/__snapshots__/script-setup.test.ts.snap
- packages/snapshot/src/port/inlineSnapshot.ts
- packages/snapshot/src/port/state.ts
- test/browser/test/mocked.test.ts
- test/core/test/__snapshots__/mocked.test.ts.snap
- test/core/test/__snapshots__/snapshot.test.ts.snap
- test/core/test/diff.test.ts
- test/core/test/injector-esm.test.ts
- test/core/test/injector-mock.test.ts
- test/core/test/inline-snap.test.ts
- test/core/test/jest-expect.test.ts
- test/core/test/snapshot.test.ts
- test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
- test/fails/test/__snapshots__/runner.test.ts.snap
- test/reporters/tests/__snapshots__/reporters.spec.ts.snap
- test/snapshots/test/__snapshots__/shapshots.test.ts.snap
- test/stacktraces/test/__snapshots__/runner.test.ts.snap
- test/typescript/test/__snapshots__/runner.test.ts.snap
- test/workspaces-browser/package.json
This changes the output for snapshots:
1. Quotes are no longer escaped:
```diff
expect({ foo: 'bar' }).toMatchInlineSnapshot(`
Object {
-    \\"foo\\": \\"bar\\",
+    "foo": "bar",
}
`)
```
2. One-line snapshots now use "`" quotes instead of ':
```diff
- expect('some string').toMatchInlineSnapshot('"some string"')
+ expect('some string').toMatchInlineSnapshot(`"some string"`)
```
This is a breaking change, but it's long overdue. If you prefer the old behavior or want to have more time to migrate, you can keep escaping with this config:
```ts
test: {
snapshotFormat: {
escapeString: true,
},
},
})
```
> feat!(snapshot): make snapshots more visually pleasing

- packages/runner/src/types/tasks.ts
- test/core/test/test-extend.test.ts
Partial close - #3915.
1. Better `any` type supports
2. Add the `InferFixturesTypes` helper type, which can get fixtures type from `TestApi`
3. Some improvement
```ts
interface TypesContext {
number: number
array: number[]
string: string
any: any
boolean: boolean
}
const myTest = test.extend<TypesContext>({
number: 1,
array: [1, 2, 3],
async string({ }, use) {
await use('string')
},
async any({}, use) {
await use({})
},
boolean: true,
})
// The type is equal
TypesContext === InferFixturesTypes<typeof typesTest>>
```
> feat(runner): improve text.extend types

- packages/browser/package.json
- packages/browser/src/node/index.ts
- pnpm-lock.yaml
resolves: https://github.com/vitest-dev/vitest/issues/3299
The browser runner indiscriminately applies pollyfills for node builtin modules. This PR removes completely removes the dependence on `modern-node-polyfills`.
> deps(browser): remove modern-node-polyfills package

- packages/vitest/src/node/cli.ts
- packages/vitest/src/runtime/child.ts
> feat: include "vitest" in the process name

- packages/vitest/src/runtime/child.ts
- packages/vitest/src/runtime/vm.ts
- packages/vitest/src/runtime/worker.ts
- pnpm-lock.yaml
- test/env-custom/package.json
- test/env-custom/vitest-environment-custom/index.ts
Fixes https://github.com/danielroe/nuxt-vitest/pull/290
> fix: correctly resolve external dependencies loaded by custom environments

- docs/advanced/runner.md
- packages/browser/src/client/runner.ts
- packages/runner/src/context.ts
- packages/runner/src/hooks.ts
- packages/runner/src/index.ts
- packages/runner/src/map.ts
- packages/runner/src/run.ts
- packages/runner/src/suite.ts
- packages/runner/src/test-state.ts
- packages/runner/src/types/runner.ts
- packages/runner/src/types/tasks.ts
- packages/runner/src/utils/tasks.ts
- packages/snapshot/README.md
- packages/snapshot/src/client.ts
- packages/vitest/src/integrations/chai/index.ts
- packages/vitest/src/integrations/snapshot/chai.ts
- packages/vitest/src/integrations/snapshot/client.ts
- packages/vitest/src/runtime/benchmark.ts
- packages/vitest/src/runtime/runners/benchmark.ts
- packages/vitest/src/runtime/runners/index.ts
- packages/vitest/src/runtime/runners/test.ts
- packages/vitest/src/suite.ts
- packages/vitest/src/types/benchmark.ts
- packages/vitest/src/types/tasks.ts
- test/core/src/custom/gardener.ts
- test/core/test/custom.test.ts
This is a breaking change. Previous support for custom tasks has been rewritten a little bit.
Fixes #3404
1. Methods on custom runner that referenced "test" now mention "task" (`onAfterRunTest` is now `onAfterRunTask` and so on, `onBeforeRun` and `onAfterRun` are now named `onBeforeRunFiles` and `onAfterRunFiles`). They now also accept tasks with type "custom" (the shape of the object is identical)
2. To collect custom tasks you now need to call `getCurrentSuite().task()` instead of `getCurrentSuite().custom()`. It now accepts a second arguments which are options. You can pass down handler as `handler` instead of saving it using `setFn`. If you used `createChainable` before, you can spread `this` in options instead of calling `custom.call(this)` - this now has no effect, it no longer …
> fix!(runner): correctly process custom tasks, update runner hooks naming

- packages/vitest/src/integrations/env/jsdom.ts
- test/core/test/environments/jsdom.spec.ts
This adds the following Nodejs/Web globals into the JSDOM environment, as they are otherwise unavailable when running with `experimentalVmThreads` enabled:
- `fetch`
- `Request`
- `Response`
- `BroadcastChannel`
- `MessageChannel`
- `MessagePort`
> fix: add multiple globals in VM+JSDOM (fix #4199)

- docs/config/index.md
- packages/vitest/src/node/config.ts
- packages/vitest/src/node/workspace.ts
- packages/vitest/src/types/config.ts
> fix: ignore "plugins" field in snapshotFormat option

- package.json
- packages/expect/index.d.ts
- packages/expect/package.json
- packages/expect/rollup.config.js
- packages/expect/src/types.ts
- packages/vitest/package.json
- packages/vitest/src/integrations/chai/chai-subset.d.ts
- packages/vitest/src/types/global.ts
- patches/@types__chai@4.3.6.patch
- pnpm-lock.yaml
Fixes #2118
By the way, this is how Cypress fixes it 😄
> fix(vitest): inline chai types instead of using @types/chai

- packages/vite-node/src/server.ts
- packages/vitest/src/node/core.ts
- packages/vitest/src/node/plugins/utils.ts
- packages/vitest/src/node/pool.ts
- packages/vitest/src/node/pools/child.ts
- packages/vitest/src/node/pools/threads.ts
- packages/vitest/src/node/pools/vm-threads.ts
Fixes #2392
Fixes #3426 (At least it should)
> fix(vitest): deduplicate vitest when running globally or in a workspace

- docs/guide/environment.md
- packages/vitest/src/integrations/env/index.ts
- pnpm-lock.yaml
- test/env-custom-file/custom.ts
- test/env-custom-file/package.json
- test/env-custom-file/test/base.test.ts
- test/env-custom-file/vitest.config.ts
> fix(vitest): failed to load custom environment from js/ts file

- packages/runner/src/fixture.ts
- packages/runner/src/run.ts
- test/core/test/test-extend.test.ts
Fixes: https://github.com/vitest-dev/vitest/issues/4165#issuecomment-1748025159
Fixes: #4251
This PR will change initialize fixtures behaviour, the fixture needs to be initialized for each test.
> fix(runner): fixture needs to be initialized for each test

- package.json
- packages/browser/src/client/main.ts
- packages/browser/src/client/rpc.ts
- packages/expect/package.json
- packages/runner/src/index.ts
- packages/vitest/package.json
- packages/vitest/src/api/setup.ts
- packages/vitest/src/api/types.ts
- packages/vitest/src/browser.ts
- packages/vitest/src/runtime/entry-vm.ts
- packages/vitest/src/runtime/setup.node.ts
- patches/@sinonjs__fake-timers@11.0.0.patch
- patches/@sinonjs__fake-timers@11.1.0.patch
- pnpm-lock.yaml
> fix(browser): improve error handling and don't rely on Node.js builtin modules in browser mode

- .eslintrc
- packages/vitest/src/node/plugins/index.ts
- packages/vitest/src/node/plugins/normalizeURL.ts
- packages/vitest/src/node/plugins/ssrReplacer.ts
- packages/vitest/src/node/plugins/workspace.ts
Reference: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6427695997/job/17453756565
> fix(vitest): support assets in new URL in Vite 5

- docs/config/index.md
It wasn't clear to me where the options go and I think this change would help clarify. I think the main reason for the confusion is that
```
test: {
exclude: [..]
}
```
Reads as "test the files in this section", not "specify your testing options here". The term "options" is also used below, but not above making it unclear where the options go. Hopefully this will help others in the same situation as me.
> Make it more explicit where options go
