packages/ui/package.json, pnpm-lock.yaml
=> fix: missing dev dependencies for ui package

CONTRIBUTING.md
=> docs: remove write access section in contributing.md

docs/config/index.md, packages/vitest/src/node/index.ts, packages/vitest/src/types/config.ts
This is a handy option when you bootstrap a new project and it doesn't have tests yet. Wasn't sure where to add tests for this? Let me know if there is anything else you need me to do
=> feat: add --passWithNoTests option

docs/guide/comparisons.md
I wrote up some additional information about browser-based vs node-based testing tools and explained Cypress's role as a complimentary tool to Vitest.
=> docs: additional cypress + vitest comparison content

docs/.vitepress/config.ts, docs/guide/features.md, docs/guide/mocking-timers.md, packages/vitest/src/integrations/timers.ts, packages/vitest/src/integrations/utils.ts, test/core/test/timers.test.ts
I've removed unsupported timers API and documented supported API :)
=> docs: faking timers api

docs/config/index.md
Current behavior:
Expected behavior:
=> docs: fix json code highlighting

packages/ui/client/components/Suites.vue, packages/ui/node/index.ts, packages/ui/node/utils.ts
Update the code in UI package to the latest core code.
=> feat(ui): update ui package to latest code

packages/vitest/src/reporters/error.ts
actual and excepted were inverted in the error output
=> fix: error reporter, inverted actual/expected

packages/vitest/src/reporters/error.ts
Apply two passes to know before formatting if we are in compact mode
Clean up some of the logic, looks better to me now
=> fix: cleaner compact error output

CONTRIBUTING.md
Based on the Vite contributing guide
=> chore: extend contributing guide

packages/ui/client/components/Navigation.vue, packages/ui/client/components/Suites.vue, packages/ui/client/components/TestSuite.vue, packages/ui/package.json
=> feat(ui): optimize status ui behavior

docs/guide/index.md
git clone will create a vitest folder, which should be cd vitest
=> doc:  error cd path

packages/ui/client/App.vue, packages/ui/client/components.d.ts, packages/ui/client/components/Files.vue, packages/ui/client/components/Navigation.vue, packages/ui/client/components/Suites.vue, packages/ui/client/components/TestFile.vue, packages/ui/client/context.ts, packages/ui/client/utils.ts, packages/ui/node/utils.ts
=> feat(ui): add task list for ui plugin

docs/config/index.md
Add missing options to the config reference (and reorder to respect types/config.ts)
=> docs: update config reference

packages/ui/client/components/ConnectionOverlay.vue
=> fix(ui): reverse the connecting animation

pnpm-lock.yaml, test/react-enzyme/components/Button.tsx, test/react-enzyme/package.json, test/react-enzyme/test/Button.test.tsx, test/react-enzyme/tsconfig.json, test/react-enzyme/vite.config.ts, test/react-enzyme/vitest.setup.ts
PR contains setup and test case for using react enzyme with vitest
=> test: add react enyzme test example

packages/vitest/src/integrations/chai/jest-expect.ts, packages/vitest/src/integrations/jest-mock.ts
=> feat: add spy name to assertion messages

packages/vitest/src/index.ts, packages/vitest/src/integrations/chai/jest-expect.ts, packages/vitest/src/integrations/snapshot/chai.ts, test/core/test/__snapshots__/snapshot.test.ts.snap, test/core/test/snapshot.test.ts
Related: https://github.com/vitest-dev/vitest/issues/43
=> feat: last jest compatible APIs

packages/ui/client/components/views/ViewModuleGraph.vue, packages/ui/client/main.ts, packages/ui/client/pages/index.vue, packages/ui/package.json, pnpm-lock.yaml
This PR replaces the static columns with resizable split panes.
=> feat(ui): use splitpanes for resizable sidebars

packages/ui/client/components/FileDetails.vue, packages/ui/client/components/views/ViewModuleGraph.vue, packages/ui/client/composables/module-graph.ts, packages/ui/package.json, pnpm-lock.yaml
This PR makes module graphs fully stable (both node positions and graph settings) while on the same file.
Closes #386
=> fix(ui): make module graph stable while on the same file

packages/vitest/src/reporters/renderers/listRenderer.ts
=> fix(list-reporter): remove limit of list items

packages/vitest/src/runtime/run.ts
Ensure `updateTask` updates packs by id to prevent duplication. Addresses an issue mentioned in #374
=> fix: deduplicate packs in `updateTask`

bench/src/bench.ts, bench/src/github.ts
This will run the benchmark twice. It will run once for current commit and once for base branch commit. And will produce result like this - https://github.com/Demivan/vitest/pull/6#issuecomment-1004631257
=> chore: update benchmark to display delta

examples/ruby/components/Test.component.vue, examples/ruby/config/vite.json, examples/ruby/package.json, examples/ruby/test/components/Test.spec.ts, examples/ruby/vite.config.js, packages/vitest/src/node/config.ts, packages/vitest/src/node/execute.ts, packages/vitest/src/runtime/worker.ts, packages/vitest/src/types/config.ts, pnpm-lock.yaml
=> fix: respect base

packages/vitest/src/plugins/mock.ts, test/core/test/hoist-import.test.ts
=> fix: hoist vitest import

package.json, packages/vitest/src/reporters/index.ts, packages/vitest/src/reporters/tap.ts
=> feat: test anything protocol reporter

packages/vitest/src/index.ts, packages/vitest/src/integrations/chai/index.ts, packages/vitest/src/runtime/run.ts
=> feat(expect): add getState support

packages/ui/client/components/Modal.vue, packages/ui/client/components/views/ViewModuleGraph.vue, packages/ui/client/composables/module-graph.ts, packages/ui/package.json, pnpm-lock.yaml
Nodes are now selected via double-click and the resizing behavior of the simulation is improved.
=> fix(ui): improve graph behavior

packages/vitest/src/reporters/index.ts, packages/vitest/src/reporters/tap-flat.ts, packages/vitest/src/reporters/tap.ts
For better compatibility with reporters from: https://github.com/sindresorhus/awesome-tap#reporters
=>  feat: add flat version of tap reporter

docs/guide/mocking-modules.md
As per GitHub discussion at https://github.com/vitest-dev/vitest/discussions/466
=> docs: update to automocking algorithm docs

packages/ui/client/components/views/ViewModuleGraph.vue, packages/ui/client/composables/module-graph.ts, packages/ui/package.json, pnpm-lock.yaml
This PR updates `d3-graph-controller` to v2.1.0.
There hasn't been a functional change, just some API refinement with additional configurations options.
=> chore(ui): update deps

packages/vitest/src/integrations/snapshot/port/inlineSnapshot.ts, packages/vitest/src/plugins/mock.ts, packages/vitest/src/utils/index.ts, test/core/test/mocked.test.js
=> fix(mock): vi.mock with line breaks in arguments 

docs/main.css
https://github.com/vuejs/vitepress/pull/496
=> fix(docs): info custom block in dark

packages/ui/client/components/views/ViewEditor.vue
=> fix(ui): clear history after editor initialization

docs/config/index.md, packages/vitest/src/node/reporters/index.ts, packages/vitest/src/node/reporters/junit.ts, packages/vitest/src/node/reporters/tap-flat.ts, packages/vitest/src/node/reporters/tap.ts, packages/vitest/src/node/reporters/utils/indented-logger.ts, packages/vitest/src/utils/tasks.ts
=> feat: add JUnit reporter

packages/vitest/src/coverage.ts
=> fix: expose c8 "all" option

packages/vitest/src/node/reporters/junit.ts, packages/vitest/src/node/reporters/tap.ts
=> fix: don't use string.replaceAll

package.json, packages/vite-node/package.json, packages/vitest/package.json, pnpm-lock.yaml
Fixes https://discord.com/channels/917386801235247114/917386801235247117/933075512467816478, includes https://github.com/vitejs/vite/pull/6548
=> chore(deps): update vite to v2.7.13

packages/vitest/src/node/core.ts
=> fix: cleanup before exiting process

packages/vitest/package.json, packages/ws-client/package.json, pnpm-lock.yaml
The dep got updated again to 8.4.2, @d3lm is working on fixing the WC issue
=> fix: revert to ws 8.4.0 until WebContainers issue is resolved

docs/guide/features.md, docs/guide/index.md, examples/lit/package.json, examples/mocks/package.json, examples/puppeteer/package.json, examples/react-testing-lib-msw/package.json, examples/react-testing-lib/package.json, examples/react/package.json, examples/svelte/package.json, examples/vitesse/package.json, examples/vue/package.json, examples/vue2/package.json, test/cjs/package.json, test/core/package.json, test/coverage-test/package.json, test/fails/package.json, test/global-setup/package.json, test/single-thread/package.json, test/snapshots/package.json
=> docs: use vitest run mode for coverage examples (fix #602)

packages/ui/package.json
=> chore(ui): add package.json repository to @vitest/ui

packages/ui/client/components/ConnectionOverlay.vue, packages/ui/client/components/StatusIcon.vue, packages/ui/client/components/TaskItem.vue, packages/ui/vite.config.ts, test/core/test/lot-of-tests.test.ts
Virtual scroll cannot be used.
Performance issue mostly caused by tooltips.
Fixes #604
=> fix(ui) : unstable UI with a lot of tests

packages/vitest/src/node/stdin.ts
=> refactor: bold shortcuts help

packages/vitest/src/runtime/collect.ts, test/core/test/test-name-pattern.test.ts, test/core/vitest.config.ts
=> fix: validate that nested and default tasks match `testNamePattern`

docs/guide/index.md
add `spring-easing` to the set of projects using vitest
=> docs: add `spring-easing` to the set of projects using vitest

examples/mocks/package.json, packages/vitest/package.json, pnpm-lock.yaml
=> fix: update tinyspy with a fix for class mocks (fix #645)

packages/vitest/src/runtime/error.ts
Fixes #654
Not a clean solution.
If someone knows how to make it serialize error properly - that would be a better solution.
=> fix: add a fallback if error fails to serialize (fix #654)

docs/guide/index.md
Repo: https://github.com/bytedance/bytemd
=> docs: add bytemd to projects

packages/vitest/src/integrations/vi.ts
=> chore: fixed typo

docs/guide/index.md
- Fix a typo Vite => Vitest
Docs link: https://vitest.dev/guide/#overview
=> docs: Fix a typo Vite => Vitest in Getting Started page

packages/vitest/src/node/config.ts
=> fix: issue a warning in conflicting envs

packages/vitest/src/integrations/chai/jest-expect.ts
=> chore: fix message of toBeLessThan and toBeLessOrEqual

docs/config/index.md
=> docs: fix default value of hookTimeout

docs/guide/comparisons.md, docs/guide/features.md, docs/src/components/FeaturesList.vue
=> docs: minor edits

packages/vitest/src/index.ts
=> fix: change return type of expect.any(...) to any

docs/api/index.md
=> doc: add it.fails

packages/vitest/config.d.ts, packages/vitest/package.json, packages/vitest/src/config.ts
=> fix: add config.d.ts && change defineConfig function type

docs/guide/index.md, packages/vitest/src/node/cli.ts, packages/vitest/src/runtime/collect.ts
=> fix: testNamePattern matches against full name (fix #838)

packages/vitest/src/runtime/suite.ts, packages/vitest/src/types/tasks.ts, test/core/test/each.test.ts
=> fix: improve types of test.each

packages/ui/client/components/TaskTree.vue, packages/ui/client/components/TasksList.vue
=> fix(ui): search error (fix #848)

packages/vite-node/src/utils.ts
=> fix: correctly remove import query from url

docs/guide/index.md
Not affiliated in any way. Just saw that @PuruVJ [tweeted about it](https://twitter.com/puruvjdev/status/1483068973617139719).
=> Add https://github.com/PuruVJ/neodrag to 'Projects using Vitest'

packages/vite-node/src/client.ts, packages/vitest/src/integrations/coverage.ts, test/core/test/strict.test.js
=> fix: enable strict mode by default

docs/api/index.md, docs/guide/index.md, examples/mocks/test/factory.test.ts, examples/react-testing-lib-msw/src/ApolloClient.ts, packages/vite-node/src/client.ts, packages/vite-node/src/server.ts, packages/vite-node/src/types.ts, packages/vitest/src/node/mocker.ts, packages/vitest/src/runtime/collect.ts
Shameless self-plug (I'm the maintainer of [`svelte-multiselect`](https://github.com/janosh/svelte-multiselect)).
Also noticed a few typos while browsing through the code.
=> docs: add `svelte-multiselect` to projects using Vitest

examples/vue/test/imports.test.ts, examples/vue/tsconfig.json, packages/vite-node/src/client.ts, test/core/test/imports.test.ts
=> fix: resolve dynamicly imported modules to be the same as statically

packages/vitest/src/integrations/chai/jest-expect.ts
=> fix: dont'call fn twice in toThrow

packages/vitest/src/index.ts, packages/vitest/src/integrations/chai/index.ts, packages/vitest/src/integrations/chai/jest-asymmetric-matchers.ts, packages/vitest/src/integrations/chai/jest-extend.ts, test/core/test/jest-expect.test.ts
=> feat: create asymmetric matchers when extending expect

examples/README.md
These three were moved to tests.
=> docs: remove outdated examples

packages/vitest/src/node/cli.ts, packages/vitest/src/node/diff.ts, packages/vitest/src/node/error.ts, packages/vitest/src/types/config.ts
=> feat: outputTruncateLength option

docs/api/index.md, pnpm-lock.yaml
This PR adds `test.each` and `describe.each` to the documentation.
=> docs: Add test.each and describe.each to the documentation

docs/config/index.md
=> docs: improve typescript setup explaination, close #1019

packages/vitest/src/node/config.ts
=> fix: inlining vitest in cnpm

docs/api/index.md
When I looked at the document, I saw this sentence. It seems that he shouldn't appear here
=> docs: remove redundant description

docs/api/index.md
1. fix incorrect anchors
2. fix incorrect Vi API in code demo
=> docs: review Vi in docs/api/index.md

docs/api/index.md
=> docs: fix typo

docs/api/index.md
=> docs: typos

docs/api/index.md
Just fixed a typo and some grammatical inelegances I stumbled upon while reading the api reference.
=> chore: typo

docs/api/index.md, packages/vitest/rollup.config.js, packages/vitest/src/index.ts, packages/vitest/src/integrations/chai/jest-expect.ts, packages/vitest/src/integrations/spy.ts, packages/vitest/src/integrations/vi.ts, packages/vitest/src/runtime/mocker.ts, test/core/test/jest-mock.test.ts
=> fix: typescript allows new Spy, add lastCall support for spy

packages/vitest/src/runtime/setup.ts
=> fix: get taskId before scheduling console

packages/vitest/src/integrations/chai/jest-expect.ts, packages/vitest/src/integrations/chai/jest-matcher-utils.ts, packages/vitest/src/node/diff.ts, packages/vitest/src/node/error.ts
Closes #871
Closes #870
Other assertion have only one possible way of showing diff and we already do that
=> feat: show all spy calls on assertion error

docs/config/index.md, packages/vitest/src/integrations/snapshot/client.ts, packages/vitest/src/integrations/snapshot/manager.ts, packages/vitest/src/node/config.ts, packages/vitest/src/node/core.ts, packages/vitest/src/node/pool.ts, packages/vitest/src/runtime/run.ts, packages/vitest/src/types/config.ts, packages/vitest/src/types/snapshot.ts, packages/vitest/src/types/worker.ts, test/core/test/moved-snapshot.test.ts, test/core/test/moved-snapshot.test.ts.snap, test/core/vitest.config.ts
=> feat: add resolveSnapshotPath option

packages/vitest/src/node/core.ts
=> fix: rerun tests on --changed, if test was changed

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
=> fix: Issue Template docs link

packages/vitest/src/node/create.ts, pnpm-lock.yaml, test/vite-config/package.json, test/vite-config/src/index.html, test/vite-config/src/test/root.test.ts, test/vite-config/vite.config.ts
=> fix: config.root priority

packages/vitest/src/types/tasks.ts, test/core/test/each.test.ts
=> fix: types for EachFunction are missing awaitable return (fix: #1181)

packages/vitest/src/types/config.ts
=> fix(types): autocomplete built-in reporters

packages/vitest/src/node/reporters/base.ts
Just fixing a very minor spelling issue
=> fix(error message): spelling

packages/vitest/src/integrations/env/jsdom-keys.ts
=> fix: add animation frame methods to global

test/fails/test/__snapshots__/runner.test.ts.snap, test/fails/test/runner.test.ts
=> test: fix "fails" tests

docs/api/index.md
=> docs: fix api/expect.toHaveReturnedWith procuct -> product

packages/vite-node/src/client.ts, test/core/src/module-cjs.ts, test/core/src/module-esm.ts, test/core/test/module.test.ts
=> fix: make exports prop of proxy point to exports object

docs/api/index.md
=> docs: fix comments api/beforeEach

docs/guide/index.md
docs: add tdesign to projects using Vitest
=> docs: add tdesign to projects using Vitest

packages/vitest/src/integrations/env/happy-dom.ts, packages/vitest/src/integrations/env/jsdom.ts, packages/vitest/src/integrations/env/utils.ts, test/core/test/dom.test.ts, test/core/test/happy-dom.test.ts
=> fix: simplify globals access, fix global != global

packages/vitest/src/runtime/error.ts
=> fix: don't crash on DOMError

packages/vitest/src/node/config.ts
Related pull request: #1312.
close #1346
=> fix(config-setupFiles): add local file fallback for NPM setup files

docs/api/index.md
=> chore: fix each demo

docs/guide/index.md
cz-git using vitest
- inquirer plugin test
- core module unit test
- custom configuration loader test
github: https://github.com/Zhengqbbb/cz-git
website: https://cz-git.qbenben.com/
=> docs: add cz-git using vitest

docs/api/index.md, examples/vue/components/AsAsync.vue, examples/vue/test/as-async.test.ts, examples/vue/tsconfig.json, packages/vitest/src/integrations/vi.ts, test/core/test/vi.spec.ts
=> feat: add dynamicImportSettled utility function

docs/guide/ide.md
=> docs: add WebStorm plugin support for Vitest

packages/vitest/src/integrations/snapshot/port/utils.ts
=> fix: skip writing snap file, if content didn't change

packages/vitest/package.json, pnpm-lock.yaml
Fixes #1076
See repro: https://github.com/sheremet-va/vitest-types-bug
=> fix: add @types/node to dependencies

docs/guide/comparisons.md
Fix a typo/misspelling in `docs/guilds/comparasions.md`
=> chore:typo

packages/vitest/src/integrations/snapshot/client.ts, packages/vitest/src/runtime/run.ts
=> fix: don't mark skipped snapshots as obsolete

packages/vite-node/src/utils.ts
=> fix: replace ?& with ? when normalizing id

docs/guide/mocking.md
https://discord.com/channels/917386801235247114/918057998914568213/989819450737950760
Why not? 🤔
=> docs: add mocking cheat sheet

docs/api/index.md
=> docs: add information about asymmetric matchers

bench/package.json, bench/src/bench.ts, package.json, pnpm-lock.yaml
Also fix the `copySync`  from `fs-extra` in `bench.ts` module.
=> chore: fix bench on windows

packages/vitest/src/node/reporters/base.ts
=> fix: show full path to UI in terminal

packages/vitest/src/node/state.ts
=> fix: filter out invalid files

packages/vitest/src/constants.ts
closes #1528
vite PR: https://github.com/vitejs/vite/pull/8729
This feature needs Vite 3
=> feat: support cts and mts config

packages/vitest/src/integrations/env/utils.ts
=> fix: use jsdom MessageEvent

examples/README.md, examples/playwright/index.html, examples/playwright/package.json, examples/playwright/src/index.ts, examples/playwright/test/basic.test.ts, examples/playwright/tsconfig.json, examples/playwright/vitest.config.ts, pnpm-lock.yaml
According to issues and questions, Playwright is used with Vitest. Playwright is becoming increasingly popular so an usage example with Vitest makes sense.
=> feat: add Playwright example

packages/vitest/src/node/error.ts
This seems to fix the identation issue in #1679.
=> fix: code frame tabs indent (fix: #1679)

examples/react-testing-lib/src/App.test.tsx, examples/react-testing-lib/vite.config.ts, packages/vite-node/src/client.ts
=> fix!: add CSS styles to DOM

package.json, packages/vitest/rollup.config.js, packages/vitest/src/integrations/env/edge-runtime.ts, packages/vitest/src/integrations/env/happy-dom.ts, packages/vitest/src/integrations/env/jsdom.ts, pnpm-lock.yaml, test/coverage-test/package.json
Reverting to `importModule`.
Fixes #1709
Reopens #899
=> fix: don't resolve test env import when transforming files

packages/vitest/src/integrations/env/utils.ts, pnpm-lock.yaml, test/core/test/dom.test.ts
=> fix(jsdom): use jsdom ArrayBuffer instead of Node, if jsdom is enabled

packages/vitest/src/integrations/spy.ts
=> fix(types): fix MockedClass typeParams

packages/vitest/src/runtime/loader.ts
=> fix: don't throw in Node 18.6

packages/vitest/src/types/coverage.ts
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
=> feat: Add missing per-file option on coverage

packages/vitest/src/integrations/chai/jest-expect.ts, test/core/test/toHaveProperty.test.ts
=> fix: toHaveProperty should judge object own property

packages/vitest/src/node/plugins/index.ts
=> fix: plugins don't think it's watch mode

packages/vite-node/src/client.ts, test/core/test/module.test.ts
=> fix: Symbol.toStringTag on Module is non-enumerable

docs/api/index.md
Hi,
Here is initial version of the Docs improvement. Sorry for the delay.
=> docs: improve (describe|test).only description

packages/vitest/src/node/stdin.ts
=> fix: clear pattern when rerun all tests

docs/.vitepress/config.ts
I choosed `#729b1a` as a theme-color hence it looks nice in dark mode and white mode too, and that colour in presents in Vitest js logo too.
Ref-: https://github.com/vuejs/docs/pull/1870
=> docs: update theme-color

packages/coverage-istanbul/src/provider.ts, packages/vitest/src/types/coverage.ts
=> feat: add include option in istanbul coverage

packages/ui/client/auto-imports.d.ts, packages/vitest/LICENSE.md
run `build` location will generate the change.
=> chore: build generated files

packages/vitest/src/integrations/snapshot/chai.ts
Small thing.
Sorry to take your time with such a small contribution.
=> chore(chai): fix spelling

docs/api/index.md
=> docs: grammar

examples/mocks/__mocks__/extension.js.ts, examples/mocks/test/has-extension.spec.ts, packages/vitest/src/runtime/mocker.ts, pnpm-lock.yaml
=> fix(mocker): correctly mock libraries with extension in their name

CONTRIBUTING.md, README.md, docs/.vitepress/components/FeaturesList.vue, docs/config/index.md, docs/guide/features.md, docs/guide/mocking.md
This PR tries to add benchmarking to the readme and mentions tinybench as an underlying tool.
=> docs: benchmarking and tinybench

packages/vitest/src/integrations/env/utils.ts
=> fix(jsdom): use jsdom Blob instead of Node, if jsdom is enabled

packages/vitest/src/runtime/run.ts
=> fix(bench): throw root cause

packages/vitest/src/node/cli.ts
=> fix(cli): normalize argument path

examples/playwright/package.json, examples/playwright/src/index.ts, examples/playwright/test/basic.test.ts, pnpm-lock.yaml
- Update deps to have at least Playwright 1.28
- Improve example to use Testing Library inspired locator
=> chore: update Playwright example

packages/vitest/src/node/plugins/mock.ts, test/core/test/tab-effect.spec.mjs
=> fix: tab effect vi.mock

packages/vitest/src/node/stdin.ts
=> feat: suspend process

packages/vitest/src/node/reporters/json.ts, test/reporters/fixtures/all-passing-or-skipped.test.ts, test/reporters/fixtures/all-skipped.test.ts, test/reporters/fixtures/some-failing.test.ts, test/reporters/tests/json.test.ts
=> fix: correct test files status in json reporter (fix #2417)

docs/guide/index.md
=> docs: install global

packages/ui/client/components/views/ViewReport.vue
=> fix: expected reversed with actual

packages/vitest/src/node/error.ts
=> fix: pass down diff options

examples/react-storybook/package.json, examples/react-storybook/public/mockServiceWorker.js, examples/react-testing-lib-msw/package.json, pnpm-lock.yaml
`headers-polyfill` in `msw` upgrades `msw`'s version due to a dependency problem.
Closes: #2328
=> chore(deps): update msw  v0.49.2

packages/vitest/src/node/core.ts, packages/vitest/src/typecheck/collect.ts, packages/vitest/src/typecheck/typechecker.ts
=> fix: show list of tests when typechecking

packages/vitest/src/runtime/mocker.ts
=> fix: return mock path only when mocked

packages/vitest/src/node/pool.ts
=> fix: terminate workers, when closing process

docs/api/index.md
SkipIf was not yet in the api for describe
=> docs: add describe.skipIf documentation

packages/vitest/src/runtime/setup.ts, test/core/src/file-css.css, test/core/src/file-sass.sass, test/core/src/file-scss.scss, test/core/test/require.test.ts
This is usually happens inside UI libraries
=> fix: mock css files imported with "require"

packages/vitest/src/node/plugins/index.ts
=> fix: don't start watching files in "run" mode

packages/vitest/src/node/core.ts
=> fix: show correct number of tests in test summary

docs/guide/coverage.md
Improve [coverage document](https://vitest.dev/guide/coverage.html).
=> docs: change link style and correct TypeScript

docs/api/vi.md
=> docs: typo

packages/expect/src/jest-asymmetric-matchers.ts
=> fix: setup correct utils inside asymmetric matchers

packages/vite-node/src/client.ts, test/core/test/imports.test.ts
=> revert: always provide importer when resolving id

docs/guide/debugging.md
Added description and screenshot how to debug Vitest tests with JavaScript Debug Terminal
=> docs: added hint to debug via JavaScript Debug Terminal

docs/advanced/runner.md, docs/api/expect-typeof.md, docs/api/vi.md, docs/config/index.md, docs/guide/environment.md, docs/guide/mocking.md, packages/runner/src/types/runner.ts, packages/vite-node/src/server.ts, packages/vitest/src/defaults.ts, packages/vitest/src/integrations/snapshot/env.ts, packages/vitest/src/integrations/snapshot/port/inlineSnapshot.ts, packages/vitest/src/integrations/snapshot/port/state.ts, packages/vitest/src/integrations/snapshot/port/utils.ts, packages/vitest/src/integrations/vi.ts, packages/vitest/src/node/reporters/base.ts, packages/vitest/src/node/reporters/benchmark/table/tableRender.ts, packages/vitest/src/node/reporters/renderers/listRenderer.ts, packages/vitest/src/runtime/loader.ts, packages/vitest/src/typecheck/typechecker.ts, packages/vitest/src/types/coverage.ts, packages/web-worker/src/utils.ts, test/core/test/imports.test.ts, test/core/test/serialize.test.ts, test/core/test/stubs.test.ts, test/snapshots/tools/generate-inline-test.mjs, test/web-worker/test/postMessage.test.ts
This was a trial run for [a CLI I made](https://github.com/Lioness100/rspell) :)
=> docs: fix typos

docs/guide/snapshot.md
Blog post: https://jestjs.io/blog/2022/08/25/jest-29
=> docs: jest <29.0.0 has config printBasicPrototype set to true

docs/guide/snapshot.md
Fixes: https://github.com/vitest-dev/vitest/issues/2853
=> docs: difference from jest in snapshots with custom messages

packages/vitest/src/integrations/snapshot/port/utils.ts
=> feat: add a link to the comment at the top of the snapshot file

packages/vitest/src/node/plugins/index.ts
=> fix: don't mark setupFiles as test files, if experimentaOptimizer is used

docs/.vitepress/config.ts
=> docs: add i18n link

packages/vitest/src/node/config.ts, packages/vitest/src/node/core.ts, test/coverage-test/testing.mjs
- Fixes #3041
Tested manually as couldn't find good spot for test case. Not that critical feature so it should be fine.
=> fix: report coverage even when no tests found

docs/api/vi.md, docs/guide/browser.md
In this PR we add the motivation section so users understand the reason behind the browser mode feature and why it's different than other environemnts.
=> docs: add the motivation section for more context

packages/vitest/src/node/config.ts
=> fix: convert '--single-thread' and '--inspect' cli args to boolean

docs/api/expect.md, docs/guide/extending-matchers.md
Hey team,
- I'm not sure if it was outdated or something else, but the method shown wasn't working. After trying many things, I actually found someone doing that elsewhere on Github.
- A typo on below
=> docs: update extend matcher

docs/api/expect.md, docs/api/index.md
=> docs: add `chaiConfig` note

packages/vitest/src/types/global.ts, test/core/test/jest-expect.test.ts
=> fix: allow augmenting jest namespace for custom assertions

packages/browser/package.json, pnpm-lock.yaml
This should fix the vite-ecosystem-ci fail.
https://discord.com/channels/804011606160703521/1098838358660239360/1098884420905226261
=> chore(browser): bump modern-node-polyfills

docs/config/index.md
Add missing "includeSource" option in Config Reference.
=> docs(config): add "includeSource" option

docs/guide/coverage.md
=> chore: add details to coverage docs

packages/runner/src/utils/error.ts
=> fix: make sure thrown error is an object

packages/ui/client/composables/client/static.ts
=> fix: support application/x-gzip metadata in html report

packages/ui/node/index.ts
=> fix(ui): don't cache coverage assets

packages/vitest/src/node/cli.ts, packages/vitest/src/node/config.ts
=> fix: the cli option is passed to coverage.exclude

packages/vite-node/src/externalize.ts
sync https://github.com/vitejs/vite/pull/13294
=> feat: image type add apng

docs/api/expect.md
=> docs: update `expect.soft` related documentation

packages/utils/src/display.ts
This currently prevents me from using lib checks in my tsconfig.json.
=> fix: util import

packages/vite-node/src/client.ts, packages/vite-node/src/externalize.ts, packages/vite-node/src/utils.ts, test/core/src/cjs/promise-export.js, test/core/test/builtin.test.ts, test/core/test/imports.test.ts
=> fix(vite-node): improve import handling

packages/vitest/src/node/error.ts
=> fix(node): guard error info

packages/vitest/src/integrations/env/utils.ts
=> fix: don't overwrite Node.js URL global

docs/guide/index.md
=> docs: clarify how config file works

packages/vitest/src/integrations/vi.ts
=> docs: fix unstub function name in vi function description

packages/vitest/src/runtime/execute.ts, packages/vitest/src/runtime/external-executor.ts, packages/vitest/src/runtime/vm/commonjs-executor.ts, packages/vitest/src/runtime/vm/esm-executor.ts, packages/vitest/src/runtime/vm/file-map.ts, packages/vitest/src/runtime/vm/types.ts, packages/vitest/src/runtime/vm/utils.ts
=> refactor: split executor based on module resolution

packages/vitest/src/node/error.ts
=> fix: update module warning as it is moved into server config

packages/ui/client/composables/summary.ts
close: #3881
These codes come from here https://github.com/vitest-dev/vitest/blob/34a203e353ec79601040f4f8f712c15ae59e9145/packages/vitest/src/node/reporters/base.ts#L231-L232
=> fix(ui): incorrect duration time in vitest ui

packages/vitest/rollup.config.js
=> fix: build not generated `execute.d.ts`

docs/advanced/reporters.md
Related PR: #3965
I had changed it but forgot to push to origin
=> docs: fix typo related to reporters

packages/vitest/package.json
- Since the last patch, we rely on a feature of Vite 3.1.0, so we need to upgrade requirements
- Beta for Vite 5 is released, so we should support it
=> build: support Vite 5.0 and bump minimum to 3.1

packages/vite-node/README.md
=> chore(vite-node): update `ViteNodeServer` options link

packages/vitest/src/node/plugins/optimizer.ts
=> fix(vitest): only override ssr.optimizer instead of the whole ssr object

package.json, pnpm-lock.yaml
=> chore: update some dependencies

packages/vitest/src/integrations/env/happy-dom.ts
=> fix: use the nodejs console in happy-dom v11

packages/vitest/src/node/plugins/index.ts, packages/vitest/src/runtime/setup.node.ts
=> fix(vitest): set SSR env only when transformMode is ssr

docs/config/index.md
Fix for the lint errors on the onConsoleLog example.
=> fix(docs): fix lint errors on onConsoleLog example

docs/.vitepress/components/Contributors.vue, docs/.vitepress/components/HomePage.vue, packages/ui/client/styles/main.css
Hi, this PR contains minor improvements:
1. Adding `scroll-behavior: smooth` CSS for a smoother user experience.
2. Adding `decoding="async"` for `<img />` elements to decode images asynchronously, allowing other content to be rendered before image decoding completes.
=> Enhancements for a Smoother User Experience: Smooth Scrolling and Asynchronous Image Decoding 📱

packages/vitest/src/integrations/env/happy-dom.ts
=> fix(happy-dom): catch errors in happy-dom

packages/vitest/src/integrations/env/utils.ts, test/core/test/env-jsdom.test.ts, test/core/test/environments/node.spec.ts
=> fix: overwrite global URL with environment's

packages/vitest/src/suite.ts
=> feat(vitest): expose getBenchFn, getBenchOptions

packages/vitest/package.json, pnpm-lock.yaml
=> fix(vitest): make @types/node optional

packages/spy/package.json, pnpm-lock.yaml
=> chore: update tinyspy

packages/vite-node/src/server.ts
=> fix(vite-node): have a separate cache for web/ssr transforms

package.json, pnpm-lock.yaml
=> chore: upgrade rollup dependencies

.eslintignore, docs/guide/common-errors.md, docs/guide/in-source.md, docs/guide/migration.md
=> docs: improve migration guide, replace diff with !code

packages/vitest/src/types/pool-options.ts
Please check that I fixed the typo correctly and it is indeed `child_process` and not `child_processes`
=> docs: fix typo in `pool-options.ts`

docs/.vitepress/contributors.ts
Remove unnecessary ts assertions in `contributors` file
=> chore(contributors): remove unnecessary ts assertions

packages/browser/package.json, packages/browser/src/node/esmInjector.ts, packages/coverage-v8/package.json, packages/coverage-v8/src/provider.ts, packages/vitest/package.json, packages/vitest/src/node/hoistMocks.ts, packages/vitest/src/node/plugins/ssrReplacer.ts, pnpm-lock.yaml
Explanation: https://github.com/Rich-Harris/magic-string/pull/255
=> chore: update magic-string to use "hires: boundary"

test/setup/tests/console-setup.test.ts
fix test case failing https://github.com/vitest-dev/vitest/actions/runs/6415689743/job/17418034019
=> test: fix case failing in windows

packages/vitest/src/integrations/vi.ts
Export the `VitestUtils` interface,
This is to allow end user to type their function with it.
=> fix: export VitestUtils interface

packages/vitest/src/runtime/runners/benchmark.ts
Passing the correct task name to `tinybench` task
- [ x Changes in changelog are generated from PR name. Please, make sure that it explains your changes in an understandable manner. Please, prefix changeset messages with `feat:`, `fix:`, `perf:`, `docs:`, or `chore:`.
=> refactor: improve benchmark implementation

docs/guide/cli.md
=> docs: update pool and poolOptions in cli documentation

docs/guide/index.md
=> docs: add bun to vitest installation

docs/config/index.md
Small typo in the config page. --brower.headless=false -> --browser.headless=false
=> docs: typo on config page

docs/api/expect.md
This change resolves #4343 by adding the missing values.
=> docs: added missing falsy values.

packages/vitest/src/node/cli-api.ts, packages/vitest/src/node/stdin.ts
- Fixes https://github.com/vitest-dev/vitest/issues/3928
=> fix(cli): do not capture `stdin` when in run mode

docs/guide/migration.md
=> docs: Update migration.md

packages/utils/package.json, pnpm-lock.yaml
=> chore: update loupe

examples/react-testing-lib-msw/package.json, examples/react-testing-lib-msw/src/ApolloClient.ts, examples/react-testing-lib-msw/src/App.test.tsx, examples/react-testing-lib-msw/src/App.tsx, examples/react-testing-lib-msw/src/mocks/handlers.ts, packages/vitest/src/integrations/env/jsdom.ts, pnpm-lock.yaml, test/core/test/environments/jsdom.spec.ts
=> chore: update msw example to use v2

packages/vitest/LICENSE.md, packages/vitest/package.json, pnpm-lock.yaml
Updates `log-update` for performance improvement of `wrap-ansi`:
- https://github.com/chalk/wrap-ansi/pull/51
- https://github.com/sindresorhus/log-update/commit/8d6379c45f16a208c3ba2e199bdc2b574817c45c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R51
Relates to https://github.com/vitest-dev/vitest/issues/2602.
=> perf: update `log-update` v9

packages/vite-node/src/types.ts, packages/vitest/src/node/workspace.ts
=> fix: don't bundle import from rollup

.eslintrc, docs/guide/test-context.md, test/core/test/fixture-initialization.test.ts
=> chore: add test for fixture example from the docs

docs/api/vi.md, docs/guide/cli.md, packages/snapshot/README.md
=> docs: prefer .js extension in the documentation

docs/config/index.md, packages/vitest/src/node/pool.ts, packages/vitest/src/node/pools/child.ts, packages/vitest/src/node/pools/threads.ts, packages/vitest/src/node/pools/vm-threads.ts, packages/vitest/src/types/pool-options.ts, pnpm-lock.yaml, test/run/allowed-exec-args-fixtures/allowed-exec-argv.test.ts, test/run/allowed-exec-args-fixtures/vitest.config.ts, test/run/exec-args-fixtures/forks.test.ts, test/run/exec-args-fixtures/threads.test.ts, test/run/exec-args-fixtures/vmThreads.test.ts, test/run/no-exec-args-fixtures/no-exec-argv.test.ts, test/run/no-exec-args-fixtures/vitest.config.ts, test/run/package.json, test/run/test/exec-args.test.ts
=> feat(vitest): expose execArgv to the different pools

packages/vitest/src/typecheck/parse.ts
=> fix: support typechecking with Yarn PnP

docs/.vitepress/config.ts
The edit page link just send to the md page instead editing page.
=> docs: update edit page link

examples/react-testing-lib-msw/src/App.test.tsx, test/coverage-test/testing.mjs, test/watch/test/file-watching.test.ts, test/watch/test/stdin.test.ts, test/watch/vitest.config.ts
Disable some flaky tests on CI. These have been failing for long time and aren't reproducible locally. I don't think there are any open bug reports that describe similar issues that these flaky tests could relate to.
=> test: disable flaky tests on CI

packages/vitest/index.cjs
=> fix(vitest): throw an error if vitest is imported using require()

packages/vitest/rollup.config.js
=> chore: have chunks in a separate folder

packages/vitest/src/config.ts, test/config/package.json, test/config/test/config-types.test-d.ts, test/config/tsconfig.json
=> fix(vitest): use correct type for defineProject to allow usage in mergeConfig

docs/.vitepress/components/ListItem.vue, docs/.vitepress/scripts/pwa.ts, docs/.vitepress/style/main.css
=> docs: update styles for features animations

docs/guide/mocking.md
=> docs: update msw example

packages/browser/src/client/main.ts
=> fix(browser): wait until vite finishes prebundling of vitest dependencies

packages/expect/src/jest-extend.ts, packages/expect/src/types.ts
=> fix(expect): don't fail when using jest expect

examples/react-testing-lib-msw/tsconfig.json, examples/react-testing-lib/tsconfig.json
A type error occurs in the examples using testing-library. According to [@testing-library/jsdom](https://github.com/testing-library/jest-dom#with-typescript), We need to make additional settings in `tsconfig.json`. So I add it.
=> fix(example): resolve type error

docs/.vitepress/contributors.ts
=> docs: add member information for Dunqing

docs/api/assert-type.md, docs/api/expect-typeof.md, docs/guide/testing-types.md
=> docs: mention --typecheck flag in docs

packages/vitest/src/integrations/mock/date.ts, test/core/test/date-mock.test.ts
fixes: https://github.com/vitest-dev/vitest/issues/4579
=> fix: date prototype when using setSystemTime

packages/vitest/src/integrations/env/jsdom-keys.ts, test/core/test/environments/happy-dom.spec.ts
=> fix(vitest): correctly support CSS variable when using happy-dom

docs/guide/snapshot.md
Fixes grammar for one sentence.
=> chore: Fix snapshot.md "escape" grammar

docs/api/expect.md
diabetic people can eat pineapples
=> docs: remove ableist test example

docs/api/index.md
This PR adds missing documentation for `describe.runIf`.
=> docs(api): add docs for describe.runIf

docs/guide/mocking.md
=> docs: add section about mocking methods inside the same file

packages/vitest/src/integrations/browser/server.ts
=> fix(browser): respect "server" option in vite config

netlify.toml, package.json, pnpm-lock.yaml
=> docs: set node to 20, update tsx

packages/vitest/src/node/pkg.ts
* "dep" may not be easily understood by everyone
* "Can not" is a grammar error
=> fix: improve grammar in "Missing dep" error

docs/package.json, examples/sveltekit/package.json, package.json, packages/ui/package.json, packages/vite-node/package.json, packages/vitest/package.json, pnpm-lock.yaml
Vitest v1.0 has been released and we can update the Vite version to v5.0.0
=> chore: update vite to latest

docs/api/vi.md
This PR modifies a sentence in the `vi.mock` documentation as an attempt to make it a little clearer.
I also would like to take this opportunity to thank the team. The transition from Jest to Vitest is super easy for me. Keep up the great work! :)
=> docs: improve phrasing of a sentence in the vi.mock section

packages/browser/package.json, packages/browser/providers.d.ts, packages/browser/rollup.config.js, packages/ui/package.json, packages/utils/package.json
This PR just fix some wrong package exports, I'm reviewing the rest of packages (the rest seems to be fine):
- `@vitest/browser`
- `@vitest/ui`
- `@vitest/utils`
**@vitest/browser**
**@vitest/browser with this PR**:
**@vitest/ui**
**@vitest/ui with this PR**:
**@vitest/utils**
**@vitest/utils with this PR**:
=> fix: package exports

packages/spy/src/index.ts
typo in `mockImplementation` docs example code
=> fix typo in `mockImplementation` docs example code

packages/vitest/src/node/workspace.ts
=> fix: correctly reset provided values

docs/config/index.md, docs/guide/cli.md, packages/vitest/src/node/cli.ts, packages/vitest/src/node/config.ts, packages/vitest/src/node/core.ts, packages/vitest/src/node/plugins/workspace.ts, packages/vitest/src/node/workspace.ts, packages/vitest/src/types/config.ts, test/config/fixtures/workspace/nested/e2e.projects.js, test/config/fixtures/workspace/project-1/calculator-1.test.ts, test/config/fixtures/workspace/project-2/calculator-2.test.ts, test/config/test/workspace.test.ts, test/workspaces/vitest.workspace.ts
=> feat: add --workspace option, fix root resolution in workspaces

packages/vite-node/src/client.ts, packages/vitest/src/runtime/execute.ts
=> fix: don't fail if `inline: true` is set

packages/vitest/src/runtime/execute.ts
=> chore: always externalize vitest

docs/guide/snapshot.md
I just spotted some arguments are missing from `printer`. It might work but at least now it's type error.
This also align with the test I added sometime ago:
https://github.com/vitest-dev/vitest/blob/72940429073978b8f988f9aa1e1299a6c8405cae/test/core/test/snapshot-custom-serializer.test.ts#L24-L37
=> docs: fix custom snapshot serializer example

docs/config/index.md
If I use this example I get this error in VSCode
No overload matches this call.
=> Fix No overload matches this call.

docs/.vitepress/config.ts, docs/config/index.md, docs/guide/improving-performance.md
=> docs: add "improving performance" to guide list

docs/api/expect.md, docs/api/index.md, docs/api/vi.md, docs/config/index.md
=> docs: use Badge to display versions

pnpm-lock.yaml
=> ci: fix failing ci

docs/guide/improving-performance.md
Fixes rendering of note block in newly introduced chapter on performance.
=> docs: fix rendering of note

packages/spy/src/index.ts, test/core/test/jest-mock.test.ts
=> fix(spy): don't allow Promise in mockImplementation

packages/runner/src/suite.ts, test/core/test/nested-test.test.ts
=> chore(runner): update better error message for nested test

packages/browser/src/client/main.ts, packages/vitest/src/api/setup.ts, test/browser/specs/filter.test.mjs, test/browser/vitest.config.mts
- Closes https://github.com/vitest-dev/vitest/issues/4226
I added a quick workaround similar to child/forks pool, such as:
https://github.com/vitest-dev/vitest/blob/8842faa1ae0024851753b12d10b441250e484eca/packages/vitest/src/runtime/child.ts#L97-L108
=> fix(browser): fix `testNamePattern` config

examples/vitesse/src/auto-import.d.ts, packages/vitest/src/node/workspace.ts
=> feat: support case-insensitive path matching in cli (fix #3567)

docs/config/index.md, docs/guide/coverage.md, packages/coverage-istanbul/src/provider.ts, packages/coverage-v8/src/provider.ts, packages/ui/node/index.ts, packages/vitest/src/types/coverage.ts, pnpm-lock.yaml, test/coverage-test/coverage-report-tests/generic.report.test.ts, test/coverage-test/custom-reporter.cjs, test/coverage-test/package.json, test/coverage-test/test/configuration-options.test-d.ts, test/coverage-test/vitest.config.ts
- Closes https://github.com/vitest-dev/vitest/issues/4150
=> feat(coverage): custom reporter support

packages/vitest/src/runtime/console.ts, pnpm-lock.yaml, test/config/fixtures/console-color/basic.test.ts, test/config/fixtures/console-color/vitest.config.ts, test/config/package.json, test/config/test/console-color.test.ts
- Closes https://github.com/vitest-dev/vitest/issues/4965
=> fix(vitest): check color support for intercepted console logging

docs/guide/features.md
- Fixes https://github.com/vitest-dev/vitest/issues/4977
- Related to https://github.com/vitest-dev/vitest/pull/4172
=> docs: rewrite mention of old `--no-threads` option

packages/vitest/package.json, pnpm-lock.yaml
- Fixes https://github.com/vitest-dev/vitest/issues/4982
- Ref. https://github.com/tinylibs/tinypool/pull/81
=> fix(forks): set correct `VITEST_POOL_ID`

packages/runner/src/index.ts, packages/vitest/src/suite.ts
=> feat(vitest): expose getHooks & setHooks

docs/guide/common-errors.md, packages/vitest/src/node/pools/threads.ts, packages/vitest/src/node/pools/vmThreads.ts
Include common work-around for the logged errors so that users don't need to look for it themselves. I've already lost count of how many times `--pool=forks` has resolved similar issues. Related to #3077.
=> fix(threads): mention common work-around for the logged error

docs/guide/index.md
=> docs: add ant-design-web3 using vitest

packages/vitest/src/node/pool.ts
=> fix(vitest): don't run typecheck tests in browser if both are enabled

packages/vitest/src/node/plugins/utils.ts
=> fix: don't optimize react/jsx-runtime by default when running in Node

packages/vitest/src/node/reporters/junit.ts, test/reporters/fixtures/better-testsuite-name/space-1/test/base.test.ts, test/reporters/fixtures/better-testsuite-name/space-2/test/base.test.ts, test/reporters/fixtures/better-testsuite-name/vitest.config.ts, test/reporters/fixtures/better-testsuite-name/vitest.workspace.ts, test/reporters/tests/junit.test.ts
=> fix(reporters): testsuite name should include project root in Junit output

packages/vitest/src/node/core.ts, test/workspaces/vitest.workspace.ts
- closes https://github.com/vitest-dev/vitest/issues/5040
=> fix(vitest): handle function config inside `defineWorkspace`

docs/config/index.md, packages/vitest/jsdom.d.ts, packages/vitest/package.json, test/core/test/environments/jsdom.spec.ts
=> fix(vitest): add types for the new global `jsdom` variable

docs/.vitepress/contributors.ts
As reminded by @sheremet-va, adding myself here finally. Thanks team!
=> chore: update team members in doc

packages/browser/package.json, packages/ui/package.json
- Alternative of https://github.com/vitest-dev/vitest/pull/5167
=> chore: replace run-p with pnpm run

docs/.vitepress/components/HomePage.vue, docs/.vitepress/config.ts, docs/.vitepress/contributors.ts, docs/.vitepress/scripts/fetch-avatars.ts, docs/.vitepress/style/main.css, docs/config/file.md, docs/config/index.md, docs/team.md
=> docs: add team emeriti and update the sidebar and navigation

packages/utils/src/error.ts, test/core/test/diff.test.ts
- closes https://github.com/vitest-dev/vitest/issues/5181
=> fix(utils): fix asymmetric matcher diff inside array

docs/guide/migration.md
Stumbled on this one while migrating from Jest and thought it would save people some debugging when the behavior change is documented. If you guys can provide more context on why the change was required, that would be great (honestly, I always found the Jest behavior unintuitive).
=> docs: update jest migration section with promise mock result

.github/workflows/ci.yml, pnpm-lock.yaml
- Fixes https://github.com/vitest-dev/vitest/issues/5187
=> ci: use latest edgedriver

docs/guide/cli.md
a small addition to the `changed` flag
=> a small addition to the `changed` flag

examples/react-testing-lib/src/components/Spinner.test.tsx, examples/react-testing-lib/src/components/Spinner.tsx
=> test: add inline snapshot tests for react

packages/ui/client/composables/summary.ts
this PR fix test duration time after discussion in this thread https://discord.com/channels/917386801235247114/1208024121611517973
=> fix(ui): fix tests duration time

packages/vite-node/README.md
Just corrected a grammar error on vite-node's README. `The engine "that" powers Vitest and Nuxt 3 Dev SSR`
=> docs: README: fixed grammar error

docs/.vitepress/contributors.ts
I just noticed that I was already in team emeriti side..
=> chore(docs): update team page

CONTRIBUTING.md
The `bug` label was removed, and there is no plugin vue here.
There is also no waiting for Evan to merge a feature 😅
=> chore: update workflow diagrams

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/issue-labeled.yml
I think this would a nice addition to help issue authors creating reproductions.
=> chore: add "examples" link to bug report issue template

packages/vitest/src/node/cli/cli-config.ts, test/core/test/cli-test.test.ts
=> fix: repeatable `--project` option

docs/guide/index.md
Update the URL to the vscode extension (replacing the deprecated one).
https://vitest.dev/guide/#ide-integrations
=> docs: update vscode extension url

docs/api/index.md
=> docs: fix reference to context onTestFailed

packages/runner/src/types/tasks.ts
=> fix(types): pass correct type for suite factory

docs/guide/index.md
=> docs: fix support node typo

packages/vitest/src/integrations/vi.ts
=> fix(vitest): initiate FakeTimers on demand

docs/api/assert.md
Pretty self explanatory - fixed a typo and a grammar issue I came across while reading through.
=> docs: Fix minor typos

packages/utils/src/display.ts
`!fn.name` already contains `fn.name === ''`.
=> refactor: remove unnecessary condition

docs/config/index.md, packages/vitest/src/node/workspace.ts
=> docs: improve "provide" documentation

docs/.vitepress/components.d.ts, docs/.vitepress/components/Version.vue, docs/.vitepress/config.ts, docs/.vitepress/theme/index.ts, docs/api/index.md, docs/package.json, pnpm-lock.yaml
=> docs: fix Badge display

packages/vitest/src/node/plugins/index.ts
=> fix(vitest): watch the output directory correctly

examples/README.md
I just noticed the link is missing.
=> chore: run `docs:examples` to add nestjs link

docs/guide/index.md, docs/vite.config.ts
I don't know why, but this fixes it for me 🤔
=> docs: fix hydration mismatch

docs/config/index.md
=> docs: add a warning about aliasing

.github/workflows/ci.yml
https://github.com/nodejs/node/releases/tag/v22.0.0
Node.js version 22 has been released, we can add this to the system environment where the tests are run.
=> ci: test on Node.js 22

packages/vitest/src/node/pools/rpc.ts
=> fix: hash the name of the file when caching

packages/ui/client/composables/client/index.ts
=> feat(ui): sort items by file name

test/config/vitest.config.ts, test/reporters/vitest.config.ts, test/watch/vitest.config.ts
=> ci: use forks pool for CLI tests

docs/api/expect.md, docs/api/index.md, docs/api/vi.md, docs/config/index.md, docs/guide/browser.md, docs/guide/coverage.md, docs/guide/environment.md, docs/guide/extending-matchers.md, docs/guide/features.md, docs/guide/migration.md, docs/guide/reporters.md, docs/guide/test-context.md, docs/guide/testing-types.md, docs/guide/ui.md
This PR removes version badges (fixes #5719) and adds a migration guide from v1 to v2 (only mentions changes merged so far).
=> docs: remove version badges

docs/guide/using-plugins.md
Closes #4821
This PR updates the Plugins section to guide users to the Vite docs.
=> docs: update plugins page

docs/config/index.md, packages/vitest/src/types/config.ts
=> feat: allow augmenting config.test.env

packages/ui/client/components/FileDetails.vue, packages/ui/client/components/TaskItem.vue, packages/ui/client/composables/client/static.ts, packages/ui/node/reporter.ts, packages/vitest/src/api/setup.ts, packages/vitest/src/api/types.ts, packages/vitest/src/utils/graph.ts, test/reporters/tests/__snapshots__/html.test.ts.snap
=> fix(ui): show correct module graph and project name in a Vitest workspace

packages/vitest/src/node/workspace.ts
=> fix!: do not exit process if global setup has failed

packages/vitest/src/node/plugins/workspace.ts
=> fix: remove process.exit if workspace project failed to be created

packages/browser/src/client/client.ts, packages/browser/src/client/orchestrator.ts, packages/browser/src/client/tester.ts, packages/browser/src/client/utils.ts, packages/runner/src/types/tasks.ts, packages/ui/client/components/FileDetails.vue, packages/ui/client/components/TasksList.vue, packages/ui/client/pages/index.vue, packages/vitest/src/api/setup.ts, packages/vitest/src/api/types.ts, packages/vitest/src/node/core.ts, packages/vitest/src/node/pools/browser.ts, packages/vitest/src/node/reporters/base.ts, packages/vitest/src/node/state.ts, packages/vitest/src/types/reporter.ts, test/browser/src/button.css, test/browser/src/createNode.ts, test/browser/test/dom.test.ts
=> feat(browser): do not reload the page during watch mode

test/browser/package.json
This PR simplifies run the browser ui tests adding 2 scripts (for playwright and webdriverio providers)
=> chore(browser): add browser ui scripts to run root browser tests

packages/browser/src/client/orchestrator.ts, packages/browser/src/client/tester.ts, packages/browser/src/client/unhandled.ts, packages/browser/src/node/index.ts, packages/vitest/src/node/pools/browser.ts
=> fix(browser): use iframe id instead of calculating it from filenames

packages/vitest/src/utils/coverage.ts, test/coverage-test/option-tests/thresholds-auto-update.test.ts, test/coverage-test/testing-options.mjs
- Fixes https://github.com/vitest-dev/vitest/issues/5803
=> fix(coverage): `thresholds.autoUpdate` to support `mergeConfig`

packages/browser/src/client/orchestrator.ts, packages/browser/src/node/index.ts, packages/browser/src/node/providers/preview.ts, packages/ui/client/components/TasksList.vue, packages/vitest/src/node/pools/browser.ts, packages/vitest/src/utils/serialization.ts
=> fix(browser): always clean up iframes on rerun

packages/vitest/package.json, pnpm-lock.yaml
=> chore(deps): update `tinypool` to v1

packages/browser/src/node/index.ts, packages/vitest/src/integrations/browser/server.ts, packages/vitest/src/node/index.ts, packages/vitest/src/node/pool.ts
=> fix(browser): specify entries for correct deps optimization

docs/config/index.md, packages/browser/src/node/index.ts, packages/vitest/src/node/cli/cli-config.ts, packages/vitest/src/node/workspace.ts, packages/vitest/src/types/browser.ts, test/browser/vitest.config.mts
=> feat!: rename indexScripts to orchestratorScripts

packages/browser/src/node/index.ts
=> fix(browser): don't optimize Vitest dependencies

packages/browser/src/client/runner.ts, packages/browser/src/client/tester.ts
=> fix(browser): show correct prepare time

packages/utils/package.json
=> fix(utils): package exports

packages/ui/package.json, pnpm-lock.yaml
=> chore: remove @vitejs/plugin-vue-jsx

packages/coverage-istanbul/package.json, packages/coverage-istanbul/src/provider.ts, packages/coverage-v8/package.json, pnpm-lock.yaml, test/coverage-test/testing.mjs
- Fixes https://github.com/vitest-dev/vitest/discussions/5096
- Ref. https://github.com/istanbuljs/test-exclude/releases/tag/test-exclude-v7.0.0
- Ref. https://github.com/istanbuljs/test-exclude/issues/53
=> fix(deps): update vulnerable `test-exclude` to v7

packages/vitest/src/types/config.ts
=> docs: Fix typo in config types doc

docs/advanced/api.md, docs/guide/cli-table.md, packages/vitest/src/node/core.ts
=> fix(vitest): expose `provide` to the public API

packages/vite-node/src/source-map-handler.ts, packages/vitest/src/node/error.ts, packages/vitest/src/node/state.ts
=> chore: fix some comments

packages/runner/src/utils/tasks.ts
=> chore(runner): export `isAtomTest` utility

packages/vitest/src/node/pools/forks.ts, packages/vitest/src/node/pools/rpc.ts, packages/vitest/src/node/pools/vmForks.ts
=> fix(vitest): cache fs code only for forks pool

test/core/test/wait.test.ts
=> test: fix fakeTimers error

packages/vitest/src/node/error.ts, packages/vitest/src/node/logger.ts, packages/vitest/src/node/reporters/base.ts, packages/vitest/src/node/reporters/verbose.ts, test/reporters/fixtures/error-props/basic.test.ts, test/reporters/tests/default.test.ts, test/reporters/tests/verbose.test.ts
=> fix: print error properties only in verbose reporter

packages/browser/src/client/tester/logger.ts, test/browser/specs/runner.test.ts
=> refactor(browser): prefer pretty-print for objects

docs/guide/features.md
=> docs: add paragraph about --standalone

docs/config/index.md, packages/vitest/src/types/config.ts
=> fix(types): mark pool options as not available in project config

packages/browser/src/node/plugin.ts
=> fix(browser): remove "util" warning

packages/ui/client/components/StatusIcon.vue, packages/ui/client/components/explorer/ExplorerItem.vue
Check description: this will also prevent doing extra work, we only need mode, status and failed snapshot, all these props available in the explorer item
=> chore(ui): make `StatusIcon` props stable

packages/ui/client/composables/explorer/types.ts, packages/ui/client/composables/explorer/utils.ts
The logic for testing if a node is a test node is wrong: the type shouldn't be FileTreeNode
=> chore(ui): include test and custom types

packages/ui/client/shim.d.ts
Check `ErrorEntry.vue` in some editor.
=> chore(ui): augment Error adding `VITEST_*` entries

packages/ui/client/components/views/ViewReport.vue
=> chore(ui): remove vue sfc imports from vue files

packages/ui/client/components/FileDetails.vue
The icon will use always the spinner, I'm going to add `typecheck`  script via `vue-tsc --noEmit`: using old task prop, this PR just uses proper props.
**NOTE**: any task mode inside `idsMap`  or `filesMap` are `run`, `StatusIcon` sfc will configure proper icon using `mode`, `result.state` and `failed snapshot`.
=> fix(ui): `FileDetails` title status icon not being updated

packages/ui/client/composables/client/index.ts, packages/ui/client/composables/explorer/tree.ts, packages/ui/client/composables/explorer/utils.ts
=> chore(ui): cleanup old optimization code

packages/ui/client/components/explorer/Explorer.vue, packages/ui/client/composables/explorer/collector.ts, packages/ui/client/composables/explorer/search.ts
=> feat(ui): add initializing explorer logic

packages/ui/explorer.md
=> chore(ui): add `explorer.md` overall behavior

docs/api/mock.md, packages/spy/src/index.ts, test/core/test/jest-mock.test.ts
=> feat(spy): collect mock.contexts

packages/browser/src/client/tester/tester.ts
This was added to retry if optimization failed. Optimization now should always be finished _before_ we run this function.
=> fix(browser): remove hacky retry

docs/guide/browser.md, packages/browser/src/client/channel.ts, packages/browser/src/client/orchestrator.ts, packages/browser/src/client/tester/runner.ts, packages/browser/src/node/plugin.ts, packages/browser/src/node/pool.ts, packages/vitest/package.json, packages/vitest/src/create/browser/creator.ts, packages/vitest/src/create/browser/examples.ts, packages/vitest/src/node/cli/cac.ts, packages/vitest/src/node/index.ts, packages/vitest/src/types/browser.ts, test/config/fixtures/bail/test/second.test.ts, test/config/test/bail.test.ts, test/test-utils/index.ts
=> feat(browser): add "init" command for browser tests

docs/guide/browser.md, packages/browser/providers/playwright.d.ts, packages/browser/src/node/cdp.ts, packages/browser/src/node/commands/clear.ts, packages/browser/src/node/commands/click.ts, packages/browser/src/node/commands/dragAndDrop.ts, packages/browser/src/node/commands/fill.ts, packages/browser/src/node/commands/hover.ts, packages/browser/src/node/commands/keyboard.ts, packages/browser/src/node/commands/screenshot.ts, packages/browser/src/node/commands/select.ts, packages/browser/src/node/commands/type.ts, packages/browser/src/node/providers/playwright.ts, packages/vitest/src/types/browser.ts
=> fix(browser): make userEvent more stable when running in parallel

docs/config/index.md
Check title: missing in the original PR #5948 when logic added
=> docs(config): include html reporter auto-enable in `includeTaskLocation`

packages/browser/src/client/tester/runner.ts, packages/vitest/src/node/error.ts, packages/vitest/src/node/logger.ts, packages/vitest/src/node/reporters/base.ts, packages/vitest/src/types/global.ts, test/browser/specs/runner.test.ts
=> fix(browser): print screenshot path alongside the test error message

.github/workflows/ci.yml
- Ref. https://github.com/nodejs/node/issues/53648
https://github.com/vitest-dev/vitest/blob/d7f23d08c4a5420bb0b6483c7e3dc87a1ae8eeaf/test/config/test/exec-args.test.ts#L5-L26
=> ci: lock node version for worker tests

docs/guide/browser.md, eslint.config.js, packages/browser/context.d.ts, packages/browser/src/node/commands/screenshot.ts, test/browser/test/dom.test.ts
=> feat: add an option to return base64 from page.screenshot

docs/guide/migration.md
=> docs: add more migration steps

examples/sveltekit/package.json, package.json, pnpm-lock.yaml
Closes #5901
(I think I accidentally installed it when updating eslint config to make {} auto fix work)
=> chore: remove prettier since we never used it

docs/.vitepress/contributors.ts
=> docs: update team page

packages/vite-node/src/cli.ts, test/vite-node/.env.local, test/vite-node/src/cli-print-env.js, test/vite-node/test/cli.test.ts
=> fix(vite-node): expose all envs from .env file, not just with a prefix `VITE_`

docs/guide/mocking.md, packages/vitest/src/runtime/execute.ts, packages/vitest/src/runtime/external-executor.ts, packages/vitest/src/runtime/mocker.ts, packages/vitest/src/runtime/vm/file-map.ts, packages/web-worker/src/utils.ts
=> docs: add mock fs section

packages/browser/src/client/tester/mocker.ts, packages/browser/src/client/tester/msw.ts, packages/browser/src/node/resolveMock.ts, packages/browser/src/node/types.ts, test/browser/fixtures/mocking/mocking-dep.test.ts, test/browser/fixtures/mocking/vitest.config.ts
=> fix(browser): correctly mock optimized cjs dependencies

packages/ui/package.json, pnpm-lock.yaml
=> fix(ui): move virtual scroller to dev dependencies

packages/runner/src/types/tasks.ts, packages/vitest/src/node/state.ts
Introduced in https://github.com/vitest-dev/vitest/pull/5663
Tested locally, need to add test to repo later
=> fix(vitest): print only running files, not every file

packages/vitest/src/node/workspace.ts
=> fix(browser): correctly inherit browser config in a workspace

packages/web-worker/package.json
- Fixes https://github.com/vitest-dev/vitest/issues/6059
=> fix(web-worker): peer dependency version on `vitest`

docs/.vitepress/config.ts, docs/api/mock.md, docs/guide/cli-table.md, docs/guide/features.md, packages/vitest/src/node/cli/cli-config.ts
=> docs: add env documentation

packages/browser/src/client/tester/msw.ts, packages/browser/src/client/vite.config.ts, packages/browser/src/node/plugin.ts, packages/browser/src/node/server.ts
=> perf(browser): don't import msw if no modules are mocked

packages/browser/src/node/plugin.ts
=> fix(browser): remove @vitest/runner > pretty-format from prebundling because it doesn't exist

docs/guide/index.md
The previous wording is confusing. It seems to describe the `npx` behavior incorrectly and is difficult to comprehend (e.g., the word 'either' is used without 'or' to follow).
=> docs: improve the npx description clarity

packages/browser/src/node/plugin.ts
=> fix(browser): don't panic if @vitest/browser is installed outside of project root

test/test-utils/index.ts, test/watch/test/reporter-failed.test.ts
=> test: make watcher tests more stable on Mac OS

docs/guide/migration.md
=> docs: add currentTestName difference

packages/coverage-istanbul/src/constants.ts, packages/coverage-istanbul/src/index.ts, packages/coverage-istanbul/src/provider.ts, packages/coverage-istanbul/tsconfig.json, packages/coverage-v8/src/index.ts, packages/coverage-v8/src/provider.ts, packages/coverage-v8/src/takeCoverage.ts, packages/coverage-v8/tsconfig.json, packages/snapshot/src/client.ts, packages/snapshot/src/env/node.ts, packages/snapshot/src/manager.ts, packages/snapshot/src/port/inlineSnapshot.ts, packages/snapshot/src/port/rawSnapshot.ts, packages/snapshot/src/port/state.ts, packages/snapshot/src/port/utils.ts, packages/snapshot/tsconfig.json, packages/spy/src/index.ts, packages/spy/tsconfig.json
=> refactor: enable isolatedDeclarations in snapshot and spy packages

packages/browser/src/client/tester/tester.ts
=> fix(browser): set global filepath

packages/expect/src/jest-matcher-utils.ts, packages/utils/src/diff/index.ts, packages/utils/src/error.ts, test/core/test/__snapshots__/jest-expect.test.ts.snap, test/core/test/diff.test.ts, test/core/test/environments/jsdom.spec.ts, test/core/test/jest-expect.test.ts, test/core/test/replace-matcher.test.ts
=> fix: show a difference between string characters if both values are strings

packages/browser/rollup.config.js
=> fix(browser): don't bundle `afterEach` cleanup hooks in node entrypoint

docs/guide/snapshot.md
Grammar fixes and clarity adjustments.
Grammar and clarity in docs.
=> docs: Typos fixed and clarity improved.

docs/guide/workspace.md
This should make it a bit clearer on how to reuse a base config file in our workspaces since implicitly they don't inherit from anything.
=> docs: add information to the workspace docs on how to use extends

docs/guide/mocking.md, packages/vitest/src/runtime/mocker.ts, pnpm-lock.yaml, test/core/__mocks__/fs.cjs, test/core/__mocks__/fs/promises.cjs, test/core/package.json, test/core/src/read-hello-world.ts, test/core/test/file-path.test.ts, test/core/test/mock-fs.test.ts
=> fix(vitest): correctly resolve mocked node:* imports in __mocks__ folder

packages/browser/rollup.config.js, packages/browser/src/node/plugin.ts, test/browser/test/another.test.ts
=> fix(browser): don't inject empty `process` global

.github/workflows/ci.yml, test/ui/package.json
=> ci: combine test-browser tests, don't run tests when only docs are changed

packages/runner/src/collect.ts
- Fixes https://github.com/vitest-dev/vitest/issues/6185
=> fix: `testNamePattern` adds leading space

docs/advanced/reporters.md, packages/vitest/src/node/reported-workspace-project.ts, packages/vitest/src/node/reporters/index.ts, packages/vitest/src/node/reporters/reported-tasks.ts
=> docs: add reported tasks docs

packages/vitest/src/node/core.ts
=> chore: remove unnecessary await

packages/vite-node/src/cli.ts
=> fix(vite-node): disable watcher if hmr is disabled

docs/guide/browser/assertion-api.md, docs/guide/browser/index.md, docs/guide/browser/interactivity-api.md, packages/browser/src/node/plugin.ts, packages/vitest/src/create/browser/creator.ts, packages/vitest/src/create/browser/examples.ts, pnpm-lock.yaml, test/browser/fixtures/locators/blog.test.tsx, test/browser/fixtures/locators/vitest.config.ts, test/browser/package.json, test/browser/tsconfig.json
=> docs: add vitest-browser packages to Browser Mode examples

examples/react/test/basic.test.tsx, test/browser/test/userEvent.test.ts, test/ui/test/ui.spec.ts
=> test: make react example more stable

docs/config/file.md, docs/guide/in-source.md, docs/guide/index.md, docs/guide/reporters.md, examples/basic/vite.config.ts, examples/lit/vite.config.ts, examples/preact/vite.config.ts, examples/react/vitest.config.ts, examples/solid/vite.config.mjs, examples/typecheck/vite.config.ts
=> docs: replace `reference types="vitest"` with vitest/config

.github/renovate.json5, packages/vitest/package.json, pnpm-lock.yaml
As discussed in https://github.com/vitest-dev/vitest/pull/5713
https://npmgraph.js.org/?q=@antfu/install-pkg - 1 dependency
https://npmgraph.js.org/?q=@antfu/install-pkg@0.3.1 - 17 dependencies
=> chore(deps): upgrade @antfu/install-pkg

.github/workflows/ci.yml, packages/browser/src/client/tester/unhandled.ts, packages/vitest/src/integrations/env/jsdom.ts
We previously relied on test/coverage to fail as an indirect typechecking step, but it now has `ignoreSourceErrors`.
=> ci: return typecheck step

.github/workflows/ci.yml, package.json, pnpm-lock.yaml
- Disable permissions for security reasons
- Merge typecheck and lint job
- Add `changelogithub` to dependencies instead of installing it on every release
- Add https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash to lint github actions
=> ci: disable permissions, run typecheck with lint 

packages/vitest/package.json, pnpm-lock.yaml
Fixes a timeout issue that some users of `install-pkg` were hitting
=> chore: upgrade to install-pkg 0.4.0

.github/workflows/ci.yml, test/config/test/exec-args.test.ts
=> ci: skip exec args tests for node >20.15

packages/vitest/src/node/pool.ts, packages/vitest/src/node/spec.ts, packages/vitest/src/node/workspace.ts, packages/vitest/src/public/node.ts, test/core/test/sequencers.test.ts
=> refactor: deprecate WorkspaceSpec in favor of TestSpecification

packages/vitest/src/api/setup.ts, packages/vitest/src/api/types.ts, packages/vitest/src/node/core.ts, packages/vitest/src/node/spec.ts, packages/vitest/src/node/types/reporter.ts, packages/vitest/src/public/index.ts, packages/vitest/src/runtime/types/utils.ts
=> refactor: rename serialized spec, add toJSON to test spec implementation

docs/guide/mocking.md
=> docs: typo in mocking guide

.github/workflows/ci.yml, package.json, packages/vitest/package.json, pnpm-lock.yaml, test/cli/test/network-imports.test.ts
=> chore: update types/node and run tests on Node 22

packages/browser/src/node/index.ts, packages/browser/src/node/plugin.ts, packages/vitest/src/public/node.ts
Closes [#6387](https://github.com/vitest-dev/vitest/issues/6387)
=> fix(browser): exclude missed packages from optimization, print help message

test/core/vitest.workspace.ts
=> ci: disable vmThreads test for now

packages/browser/package.json, pnpm-lock.yaml
=> fix(browser): define mocker as a dependency

packages/browser/src/node/plugin.ts
=> fix(browser): optimize vitest-browser-vue correctly

packages/mocker/README.md
The links on the mockers README aren't working. This PR fixes them.
https://www.npmjs.com/package/@vitest/mocker
=> docs: fix links in mocker README

packages/runner/src/run.ts, test/reporters/tests/__snapshots__/junit.test.ts.snap
- Closes https://github.com/vitest-dev/vitest/issues/4820
=> fix(runner): mark tests as skipped when `beforeAll` failed

docs/guide/index.md
Though it might be intuitive to many, I still feel it would be helpful to add the pronunciation of `vitest` so people like me who are often conscious of making the right pronunciation, can be helpful to them :)
=> docs: add the pronounciation of vitest :)

docs/guide/improving-performance.md
- Ref. https://github.com/vitest-tests/test-sharding/pull/1
=> docs: apply breaking changes of `actions/upload-artifact@v4` to example

docs/advanced/pool.md, docs/advanced/runner.md, docs/guide/in-source.md
=> docs: link the regular guide from the advanced page

docs/api/vi.md
=> docs: clarify vi.setSystemTime

docs/guide/filtering.md
I wanted to know where to change the default, when reading about it.
=> Link to default config for test timeout

docs/advanced/api.md
=> docs: mention `state.getFiles` API

docs/api/expect.md
=> docs: clarify expect.toMatchFileSnapshot

.github/workflows/cr.yml
=> chore: specify "release" job name in CR

packages/vitest/src/node/pools/forks.ts, packages/vitest/src/node/pools/rpc.ts, packages/vitest/src/node/pools/threads.ts
=> chore: remove unused code

packages/browser/context.d.ts
=> fix(browser): provide aria role intellisense

docs/guide/workspace.md
Improve clarity and consistency in the workspace configuration documentation.
=> docs: update workspace.md

packages/browser/src/node/plugin.ts
=> fix(browser): don't override the esbuild option in the browser mode

docs/api/index.md
The documentation lacks configuration instructions for the relevant options.
=> docs: bench `Options` type add `throws` description

test/cli/test/list.test.ts
Just spotted `test.each` arguments are not used here.
=> test: use list cli args from `test.each`

docs/config/index.md
Update invalid link on document
=> docs: update invalid link

docs/guide/debugging.md
Use vitest run configuration instead of node for a better integration
Use vitest run configuration instead of node for a better integration
=> docs: debugging in intellij

docs/package.json, packages/ui/package.json, pnpm-lock.yaml, test/core/package.json, test/coverage-test/package.json
Split from https://github.com/vitest-dev/vitest/pull/6360
I thought it was failing before and I was going to debug it, but CI is passing now :smiley:
=> chore(deps): update vue

packages/expect/src/jest-expect.ts, test/core/test/jest-expect.test.ts
=> fix(expect): correct behavior of `toThrowError` with empty string parameter

CONTRIBUTING.md, package.json
A minor update to replace invalid commands. Also suggested `pnpm build` first since `pnpm dev` gives errors on first run.
=> chore: update repo setup instruction in CONTRIBUTING.md

packages/browser/src/client/tester/msw.ts
=> fix(browser): ignore non mocked msw requests

docs/guide/debugging.md
replace "ran" with "run" for past participle accuracy
=> docs: Update debugging.md grammar

docs/api/index.md, packages/vitest/src/node/reporters/base.ts
Add `TaskResult` field information description in the documentation.
=> docs: add bench test case `TaskResult` type description

docs/config/index.md
=> docs: changing -> editing

packages/browser/package.json, pnpm-lock.yaml
=> chore(deps): update msw to 2.6.0

docs/api/index.md
=> docs: remove outdated note

docs/guide/workspace.md
=> docs: clarify that workspace ccan be used to specify several configs

packages/vitest/src/runtime/config.ts
It doesn't actually affect it
Fixes #6684
=> fix: remove `sequence.concurrent` from the `RuntimeConfig` type

packages/vitest/src/integrations/env/happy-dom.ts
=> fix(vitest): use fetch() implementation from happy-dom

packages/ui/vite.config.ts
- closes https://github.com/vitest-dev/vitest/issues/6661#issuecomment-2462395800
=> fix(ui): remove crossorigin attributes for same origin assets

docs/api/mock.md, packages/spy/src/index.ts
=> docs: improve "Mock Functions" page

docs/api/vi.md
It removes the mention of `Axios` which comes from nowhere.
=> docs: update example of "vi.importActual"

packages/expect/src/utils.ts
This PR is fixing a typo I found in the code
=> fix: Fix typo onFullFilled -> onFulFilled

docs/.vitepress/components.d.ts, docs/.vitepress/components/OldDocument.vue, docs/.vitepress/style/vars.css, docs/.vitepress/theme/index.ts, packages/coverage-istanbul/src/provider.ts, packages/coverage-v8/src/provider.ts
=> feat(docs): show a warning in v1 docs

docs/.vitepress/components.d.ts, docs/.vitepress/components/OldDocument.vue, docs/.vitepress/style/vars.css, docs/.vitepress/theme/index.ts
=> feat(docs): show a warning in v0 docs

docs/guide/browser/index.md
=> docs(browser): add vanilla example

.github/workflows/ci.yml, packages/vitest/LICENSE.md
Hopefully this helps https://github.com/vitest-dev/vitest/pull/7016#discussion_r1875064078
CI error example https://github.com/vitest-dev/vitest/actions/runs/12226366045/job/34101502077
=> ci: check LICENSE.md diff

README.md
It's common for logos to link to their home page, and the place I naturally look to get to a products documentation.
Since GitHub images have to link somewhere, they might as well link somewhere useful. 🤷‍♂️
=> chore: link to home page from logo

packages/pretty-format/package.json, packages/pretty-format/src/plugins/ReactElement.ts, pnpm-lock.yaml
As React 19 became stable, we should probably write in this way so renovate won't mess up the versions.
=> chore(deps): tweak `react-is` version for pretty-format

test/core/test/__snapshots__/jest-expect.test.ts.snap
- Fixes https://github.com/vitest-dev/vitest/pull/7022#issuecomment-2527497931
=> test: update snapshots

packages/browser/providers/playwright.d.ts, packages/browser/providers/webdriverio.d.ts, test/dts-playwright/src/basic.test.ts, test/dts-playwright/tsconfig.json, test/dts-playwright/vite.config.ts
- Closes https://github.com/vitest-dev/vitest/issues/7099
=> fix(browser): fix provider options types

.github/workflows/ci.yml, packages/ui/client/auto-imports.d.ts
- follow up to https://github.com/vitest-dev/vitest/pull/7051
I think we can simply diff everything since build shouldn't change any source. This allows catching `packages/ui/client/auto-imports.d.ts` changes.
=> ci: validate build artifact changes

packages/vite-node/README.md
Simply updates the repo link in the README.
=> chore: update nuxt repo link

docs/advanced/api/test-suite.md
=> docs: update test-suite.md

docs/advanced/api/test-module.md
=> docs: update test-module

.vscode/settings.json, docs/advanced/api/vitest.md, docs/guide/browser/config.md
=> docs: fix small typos

docs/config/index.md, docs/guide/cli-generated.md, docs/guide/debugging.md, packages/vitest/src/node/cli/cli-config.ts
- Related to https://github.com/vitest-dev/vitest/issues/7158
=> docs: disabling timeout when debugging

packages/vitest/config.d.ts, packages/vitest/src/integrations/chai/config.ts, pnpm-lock.yaml, test/dts-config/package.json, test/dts-config/tsconfig.json, test/dts-config/vite.config.ts
- closes https://github.com/vitest-dev/vitest/issues/6379
I added a test which was failing on main. I also confirmed the repro is fixed with the pre-release https://stackblitz.com/edit/stackblitz-starters-gksg4mkw?file=index.ts
=> fix: fix missing chai types

packages/browser/src/node/plugin.ts, packages/vitest/src/node/project.ts, packages/vitest/src/node/specifications.ts, packages/vitest/src/node/watcher.ts
=> refactor: mark internal isCached* methods

packages/vitest/src/node/core.ts, packages/vitest/src/node/stdin.ts
=> fix: `cancelCurrentRun` awaits `runningPromise`

docs/guide/mocking.md
Fixed option typo in MSW listen method.
A simple typo in the description of the `onUnhandledRequest` option.
=> docs: Update mocking.md

packages/vite-node/src/utils.ts, test/config/test/node-sqlite.test.ts
- Closes https://github.com/vitest-dev/vitest/issues/7177
I copied the list from https://github.com/vitejs/vite/blob/da0caf5f9f25ed1803bfed0193b1d8d7b6a71631/packages/vite/src/module-runner/evaluatedModules.ts#L128-L133
=> fix(vite-node): fix mandatory node prefix

docs/api/vi.md
=> docs: clarify that imports are not available in vi.hoisted

docs/guide/mocking.md
- Related https://github.com/vitest-dev/vitest/discussions/7205
Some people might be confused where this `resolve` comes from, so I added an explicit import
=> docs: tweak alias example

docs/guide/browser/locators.md
=> docs(locators): update provider config link

packages/ui/node/reporter.ts, packages/ui/node/tsconfig.json, tsconfig.base.json
=> refactor: fix tsconfig file in ui

docs/guide/workspace.md, packages/vitest/src/node/project.ts, packages/vitest/src/node/workspace/resolveWorkspace.ts, test/config/fixtures/workspace/browser/workspace-with-browser.ts, test/config/fixtures/workspace/config-extends/repro.test.js, test/config/fixtures/workspace/config-extends/vitest.config.ts, test/config/test/workspace.test.ts
=> fix(workspace): `extends: true` correctly inherits all root config properties

packages/vitest/src/public/runners.ts
=> fix: export `VitestRunner` type from `vitest/runners`

netlify.toml
-----
<a href="https://stackblitz.com/~/github.com/iiio2/vitest/tree/chore/bump-node-version-on-netlify"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/iiio2/vitest/tree/chore/bump-node-version-on-netlify)._
=> chore: use node v22 on netlify

docs/advanced/api/reporters.md, packages/vitest/src/node/project.ts, packages/vitest/src/node/types/reporter.ts, test/browser/specs/runner.test.ts, test/browser/vitest.config.mts, test/core/test/injector-mock.test.ts
=> feat(api): add onBrowserInit event

docs/guide/migration.md
=> docs: more migration changes in v3

docs/.vitepress/config.ts
=> docs: add v2 to the list of versions

packages/expect/src/types.ts, test/core/test/jest-expect.test.ts
- close https://github.com/vitest-dev/vitest/issues/2866
=> fix(expect): fix `expect().resolves/rejects` chain typings

docs/.vitepress/contributors.ts
=> docs: add VoidZero org to Vladimir and Hiroshi

docs/guide/browser/index.md
You can't actually use `expect.element` with `toMatchInlineSnapshot`
=> docs: fix marko browser example

packages/vitest/src/typecheck/collect.ts
I accidentally reverted the fix in #7069
=> fix(typechecking): support typechecking parsing with Vite 6

docs/guide/mocking.md
For reference https://mswjs.io/docs/network-behavior/websocket/
I created `:::code-group` to make it shorter
=> docs: add WebSocket to `msw` features

docs/guide/features.md
Following this example in the docs didn't work, it should be `--coverage` or it won't include the merged coverage results.
=> docs: adjust example for merging sharded results with coverage

docs/api/vi.md
clear extra comma from the docs - does what it says on the tin 🙂
=> docs(vi): remove extra comma

docs/guide/migration.md
I was hesitant to add this as https://vite.dev link, but now https://v6.vite.dev is available, so I added it here.
=> docs: add vite 6 migration guide link

packages/browser/context.d.ts
Fixes https://github.com/vitest-dev/vitest-browser-svelte/issues/7
=> fix(browser): relax locator selectors methods

docs/guide/environment.md
Update import source from `vitest` to `vitest/environments`
as Environment is marked deprecated in `vitest`
=> docs: Update Environment import source

.github/renovate.json5
Fiddling with renovate config. Maybe this helps bumping playwright all together.
=> ci: seprate playwright renovate group

docs/.vitepress/config.ts, docs/guide/examples/promise-done.md, docs/guide/migration.md, eslint.config.js
=> docs: fix fakeTimers migration example and remove //

SECURITY.md
=> chore: SECURITY.md

packages/vitest/src/node/browser/sessions.ts
=> fix(browser): cleanup timeout on resolve and give more information in the error

docs/guide/browser/interactivity-api.md
=> docs: update `@testing-library/user-event` link

docs/api/vi.md
Describe more clearly the meaning of different types of parameters of `waitFor`. Otherwise, you can only check the code to determine its specific meaning.
=> docs: describe waitFor parameters more clearly

docs/guide/index.md
Updated "provided a official" to be "provided an official"
=> docs: fixed typo

packages/mocker/src/node/redirect.ts
Synchronize vite-node related code
https://github.com/vitest-dev/vitest/blob/f71004ffa379fc290031e628857ea4f3fb5d44c8/packages/vite-node/src/utils.ts#L82-L87
=> fix(mocker): include more modules to prefix-only module list

test/browser/fixtures/user-event/keyboard.test.ts, test/browser/specs/runner.test.ts
Refining assertions for https://github.com/vitest-dev/vitest/pull/7489
=> test: tweak browser non US key input test

packages/browser/src/client/orchestrator.ts, test/browser/test/dom.test.ts, test/browser/test/viewport.test.ts
=> fix: use browser.isolate instead of config.isolate

packages/browser/src/client/public/error-catcher.js, packages/vitest/src/node/error.ts, packages/vitest/src/runtime/execute.ts, test/browser/fixtures/unhandled/throw-unhandled-error.test.ts, test/browser/specs/unhandled.test.ts
=> fix(browser): print related test file and potential test in unhandled errors

packages/vitest/src/node/cli/cac.ts, test/core/test/cli-test.test.ts
=> fix: correctly split the argv string

docs/guide/browser/config.md
=> docs: Fix default screenshots directory in docs

docs/config/index.md
Let me know if you prefer I open a PR later with more of these fixes combined.
=> docs: Unify description of max/minForks for both types of fork poolOptions

CONTRIBUTING.md
Replaced `\n` with `<br/>` for proper [line breaks in Mermaid](https://mermaid.js.org/syntax/sequenceDiagram.html#line-breaks), ensuring correct rendering in the documentation.
=> chore: correct Mermaid line breaks

docs/guide/test-context.md
- Closes https://github.com/vitest-dev/vitest/issues/7611
=> docs: `test.extend` example to destructure context

.github/renovate.json5
Related
- https://github.com/vitest-dev/vitest/pull/6801
- https://github.com/vitest-dev/vitest/pull/7455
- https://github.com/vitest-dev/vitest/pull/7642
It looks like none of my intent really worked as `pnpm exec playwright install` failed in https://github.com/vitest-dev/vitest/pull/7642 :cry: How about starting from simple one and see how it goes?
=> chore: remove renovate special rules for playwright, test and examples

packages/vitest/src/runtime/runners/test.ts, test/config/fixtures/get-state/a.test.ts, test/config/fixtures/get-state/b.test.ts, test/config/fixtures/get-state/c.test.ts, test/config/fixtures/get-state/vitest.config.ts, test/config/test/get-state.test.ts
- Closes https://github.com/vitest-dev/vitest/issues/7638
=> fix: fix `getState().testPath` during collection with no isolation

docs/advanced/api/reporters.md, docs/advanced/api/test-project.md, docs/advanced/api/test-specification.md, docs/advanced/api/vitest.md, docs/advanced/guide/tests.md, docs/guide/browser/locators.md, docs/guide/browser/multiple-setups.md, docs/guide/browser/playwright.md, packages/expect/src/jest-expect.ts, packages/vitest/src/api/check.ts, packages/vitest/src/integrations/mock/timers.ts, packages/vitest/src/node/reporters/summary.ts, packages/vitest/src/node/specifications.ts, packages/vitest/src/node/workspace/resolveWorkspace.ts, test/config/test/browser-configs.test.ts, test/config/test/failures.test.ts, test/coverage-test/fixtures/test/isolation-1-fixture.test.ts, test/reporters/tests/test-run.test.ts, test/snapshots/test/inline-multiple-calls.test.ts, test/snapshots/test/jest-image-snapshot.test.ts
=> chore: fix various typos

test/reporters/tests/default.test.ts
- Fixes conflict caused by 2 reporter related PRs merged at the same time
=> test: update reporter snapshot

docs/guide/cli.md
=> docs: benchmark url fix

docs/guide/test-context.md
=> docs:Fix default fixture value in doc

.github/renovate.json5
It looks like `examples` and `test` is ignored by `"config:base"`.
I think I found a way to debug renovate config locally and here is how:
```sh
$ export RENOVATE_GITHUB_COM_TOKEN=(...your github token...)
$ RENOVATE_CONFIG_FILE=.github/renovate.json5 LOG_LEVEL=debug pnpm dlx renovate --platform=local --print-config
...
INFO: Full resolved config and hostRules including presets (repository=local)
"config": { ... }
...
DEBUG: Matched 81 file(s) for manager npm: docs/package.json, examples/basic/package.json, examples/fastify/package.json, examples/in-source-test/package.json, examples/lit/package.json, examples/profiling/package.json, examples/sveltekit/package.json, examples/typecheck/package.json, examples/workspace/package.json, package.json, packages/browser/package.json, …
```
=> ci: include `examples` and `test` on renovate

pnpm-lock.yaml, test/typescript/package.json, test/typescript/test-d/test.test-d.ts
I was reviewing https://github.com/vitest-dev/vitest/issues/957 and spotted a giant dependency used for testing https://github.com/vitest-dev/vitest/pull/3670.
I replaced it with a minimal repro as this also helps understand what was the issue.
=> test: replace googleapis with minimal repro

packages/vitest/src/node/plugins/normalizeURL.ts
Extracted the necessary part of #7509 to make rolldown-vite work with Vitest. (IIUC the other parts are related to types or tests)
=> feat(vitest): support rolldown-vite in NormalizeUrlPlugin

packages/browser/src/client/tester/tester.ts, packages/browser/src/client/tester/utils.ts, packages/browser/src/client/utils.ts, packages/runner/src/context.ts, packages/runner/src/types/runner.ts, test/browser/fixtures/timeout-hooks/hooks-timeout.test.ts, test/browser/fixtures/timeout-hooks/vitest.config.ts, test/browser/specs/runner.test.ts, test/browser/test/failing.test.ts
=> fix(browser): correctly calculate timeout in hooks when actions are performed

packages/browser/src/node/plugins/pluginContext.ts, packages/mocker/src/node/dynamicImportPlugin.ts, packages/mocker/src/node/esmWalker.ts, packages/mocker/src/node/hoistMocksPlugin.ts, packages/mocker/src/node/resolver.ts, packages/vitest/src/node/viteLogger.ts, test/core/test/injector-esm.test.ts, test/core/test/injector-mock.test.ts
=> refactor: remove direct imports from rollup

packages/vitest/src/runtime/utils.ts
- Related https://github.com/vitest-dev/vitest/discussions/7684
=> chore: tweak "vitest" import error message

docs/api/index.md
=> docs: show both test options examples

packages/coverage-v8/src/index.ts
- Required for https://github.com/vitest-dev/vitest/issues/7660 but does not fix it completely
- For Deno we'll need to wait for `session.post` calls to invoke their callback arguments: https://github.com/denoland/deno/issues/27003#issuecomment-2749048890
=> fix(coverage): `await` profiler calls

test/core/test/hooks.test.js
This is failing from time to time https://github.com/vitest-dev/vitest/actions/runs/14279710351/job/40027727582?pr=7799#step:8:1145 probably because CI gets slow with many tests running and it goes over tight 200ms.
=> test: tweak timeout to fix flake

eslint.config.js, packages/mocker/src/node/hoistMocksPlugin.ts, test/core/test/injector-mock.test.ts, test/core/test/mocking/already-hoisted.test.ts
- Closes https://github.com/vitest-dev/vitest/issues/7756
=> fix: fix already hoisted mock

packages/vitest/src/node/cli/cli-config.ts
=> docs: `browser.provider` link

docs/api/expect.md
=> docs: clarify `expect` docs

docs/guide/browser/config.md
=> docs: clarify the custom provider API is experimental

docs/api/index.md
=> docs: update onTestFailed first argument

package.json, pnpm-lock.yaml, scripts/build-utils.js
`oxc-transform` was initially `peerDependencies` of `unplugin-isolated-decl`, but it's been moved to `dependencies`, so we can remove from our deps.
=> chore(deps): remove unused dep oxc-transform

test/browser/test/userEvent.test.ts
=> ci: update locator for uploading files test

packages/vitest/src/runtime/runners/test.ts, test/cli/test/retry-clear-mocks.test.ts
Fixes https://github.com/vitest-dev/vitest/issues/7664
=> fix: reset mocks on test retry/repeat

docs/guide/browser/commands.md, packages/browser/src/node/commands/fs.ts
=> fix(browser): resolve FS commands relative to the project root

docs/guide/testing-types.md
Fix documentation in testing-types.md
toEqualTypeof => toEqualTypeOf
=> Fix toEqualTypeOf in testing-types.md

packages/vitest/src/node/pools/typecheck.ts, test/cli/fixtures/list/type.test-d.ts, test/cli/test/__snapshots__/list.test.ts.snap, test/cli/test/list.test.ts
=> fix(typecheck): don't panic during `vitest list` command

docs/api/index.md
Just some minor improvements to documentation text to make it clearer/more natural.
=> docs: minor prose improvements to it.for documentation

packages/coverage-istanbul/src/provider.ts
- Closes https://github.com/vitest-dev/vitest/issues/7879
=> fix(coverage): istanbul provider to not use Vite preserved query params

docs/guide/in-source.md
Just a small typo/mistake on the filename, this part describes a change to Vite config's, not Vitest's
=> docs: /guide/in-source: fix config filename for Production build section

.vscode/settings.json, package.json, pnpm-lock.yaml
=> chore(deps): update eslint packages

packages/utils/src/error.ts, packages/utils/src/source-map.ts, packages/vitest/src/node/logger.ts, packages/vitest/src/node/plugins/mocks.ts, packages/vitest/src/node/printError.ts, packages/vitest/src/node/reporters/github-actions.ts, packages/vitest/src/node/reporters/junit.ts, test/cli/test/print-error.test.ts, test/core/test/injector-mock.test.ts, test/reporters/tests/__snapshots__/junit.test.ts.snap
=> fix: ignore non-string `stack` properties

packages/vitest/src/node/cli/cac.ts, packages/vitest/src/node/cli/cli-config.ts, packages/vitest/src/node/config/resolveConfig.ts, packages/vitest/src/node/core.ts, packages/vitest/src/node/create.ts, packages/vitest/src/node/plugins/index.ts, packages/vitest/src/node/plugins/publicConfig.ts, packages/vitest/src/node/plugins/workspace.ts, test/cli/fixtures/public-api/vitest.config.ts, test/cli/test/public-api.test.ts, test/config/fixtures/bail/vitest.config.ts, test/config/fixtures/browser-no-config/vitest.config.ts, test/config/test/bail.test.ts, test/config/test/browser-configs.test.ts, test/config/test/failures.test.ts, test/core/test/cli-test.test.ts, test/coverage-test/utils.ts, test/test-utils/index.ts
=> fix: apply browser CLI options only if the project has the browser set in the config already

test/coverage-test/fixtures/configs/vitest.config.configure-vitest-hook.ts, test/coverage-test/test/include-exclude.test.ts
- Wrote tests while debugging Storybook + coverage related issue
- Unfortunately everything seems to work fine, so here's just the tests, no fixes 🙃
=> test(coverage): verify `configureVitest` can modify coverage include/exclude

docs/guide/browser/interactivity-api.md, docs/guide/browser/locators.md, packages/browser/context.d.ts
* Fixes typo in "contenteditable"
* Adds inline code formatting for each keyword
=> docs: fix typo, improve formatting

packages/browser/src/node/pool.ts, packages/vitest/src/node/reporters/default.ts
=> fix(browser): run tests serially if provider doesn't provide a mocker

docs/guide/browser/index.md, packages/vitest/src/create/browser/creator.ts, packages/vitest/src/create/browser/examples.ts
This mainly adds `preact` as an available browser testing library
=> Add `vitest-browser-preact`

packages/vitest/package.json, pnpm-lock.yaml
=> chore(deps): `tinypool` v1.1.0

docs/guide/improving-performance.md
This rephrases the explanation for [Sharding](https://vitest.dev/guide/improving-performance.html#sharding) in the "Importing performance" guide of Vitest's docs.
The reason for this is that the current explanation is a bit misleading. Despite mentioning
> Test sharding means running a small subset of test cases at a time.
Vitest will, in fact, split test _files_ into shards, not test cases. I believe we can improve the explanation to be more accurate and also draw attention to that characteristic in a sidenote.
=> docs(performance): clarify the way sharding works

docs/guide/common-errors.md
Closes #7987 
- remove outdated section in common errors documentation
=> docs: remove section outdated

packages/vitest/src/public/index.ts
=> fix(expect): export `DeeplyAllowMatchers`

packages/vitest/src/node/plugins/workspace.ts
=> fix: run only the name plugin last, not all config plugins

docs/guide/coverage.md
=> docs(coverage): small typos

docs/advanced/runner.md, packages/browser/src/client/tester/rpc.ts, packages/browser/src/node/project.ts, packages/browser/src/node/projectParent.ts, packages/browser/src/node/rpc.ts, packages/runner/src/types/tasks.ts, packages/ui/client/components/dashboard/ErrorEntry.vue, packages/ui/client/components/views/ViewEditor.vue, packages/ui/client/components/views/ViewReportError.vue, packages/ui/client/composables/client/state.ts, packages/ui/client/composables/error.ts, packages/utils/src/index.ts, packages/utils/src/source-map.ts, packages/utils/src/types.ts, packages/vitest/src/node/logger.ts, packages/vitest/src/node/printError.ts, packages/vitest/src/node/reporters/base.ts, packages/vitest/src/node/reporters/tap.ts, packages/vitest/src/node/types/browser.ts, packages/vitest/src/node/types/config.ts, packages/vitest/src/public/index.ts, packages/vitest/src/typecheck/typechecker.ts, packages/vitest/src/types/general.ts, test/reporters/src/data.ts
=> fix!: replace deprecated ErrorWithDiff with TestError

packages/vitest/src/public/index.ts, test/coverage-test/fixtures/custom-provider.ts, test/coverage-test/test/configuration-options.test-d.ts
=> fix!: remove deprecated coverage options in favor of `vitest/node` exports

packages/vitest/src/public/index.ts, test/cli/custom.ts, test/core/vitest-environment-custom/index.ts
Use `vitest/environments` instead
=> fix!: remove deprecated internal helpers and environment exports

test/core/test/wait.test.ts
=> test: wait longer in waitFor test

docs/api/expect.md
https://github.com/vitest-dev/vitest/blob/176133ed0cc5c8d04d0faa2e58d4a4f9cf3b78a6/packages/vitest/src/types/global.ts#L42-L46
=> docs: update poll parameter type

test/reporters/tests/test-run.test.ts
=> test: print onUserConsoleLog separetly from test run

docs/.vitepress/config.ts, docs/guide/browser/index.md
This PR documents browser mode for Qwik. It does not add any new API's or functionality from the vitest side, it is a community integration.
More extensive context and conversation with the vitest maintainers in the vitest discord chat here:
https://discord.com/channels/917386801235247114/1384961291566841856
=> docs: add qwik integration to vitest browser mode

packages/vitest/src/node/config/resolveConfig.ts, test/config/test/failures.test.ts
=> fix: forbid setting environment to `browser`

packages/runner/src/suite.ts, packages/vitest/src/runtime/benchmark.ts, test/browser/fixtures/timeout-hooks/hooks-timeout.test.ts, test/cli/fixtures/browser-multiple/basic.test.js, test/cli/fixtures/fails/no-assertions.test.ts, test/cli/test/group-order.test.ts, test/core/test/task-collector.test.ts, test/reporters/fixtures/long-loading-task.test.ts, test/watch/test/workspaces.test.ts
=> feat(runner)!: set mode to `todo` if no function is passed down to `test` or `describe`

packages/coverage-v8/src/index.ts
- Continues https://github.com/vitest-dev/vitest/pull/7943 (cannot re-open that for some reason)
=> refactor(coverage): use `node:inspector/promises`

packages/coverage-istanbul/package.json, packages/coverage-istanbul/src/provider.ts, pnpm-lock.yaml
=> chore(dev-deps): update `@types/istanbul-lib-instrument`

packages/vitest/src/node/printError.ts, packages/vitest/src/node/test-run.ts
=> chore: don't call onStackTrace twice

packages/vitest/package.json, packages/vitest/src/typecheck/typechecker.ts, pnpm-lock.yaml, pnpm-workspace.yaml, test/coverage-test/fixtures/configs/vitest.config.multi-transform.ts, test/coverage-test/package.json, test/workspaces/package.json, test/workspaces/vitest.config.ts
Repository got archived (https://github.com/ampproject/remapping). Development continues under the new handle. Seems that only new handle will receive new updates/fixes as 4 patch versions are posted diffing from ampproject/remapping. Unfortunately touching lockfile in inevitable with this 😢
=> chore: migrate to `@jridgewell/remapping` from `@ampproject/remapping`

docs/guide/migration.md
=> docs: modernize jest migration guide

docs/.vitepress/config.ts, docs/guide/migration.md, packages/vitest/src/node/config/resolveConfig.ts
=> docs: add more info about workspace migration

test/cli/test/config-loader.test.ts
- Node has enabled typestripping by default in latest 22
- Fixes CI failures
=> test: update type-strip feature version check

packages/browser/context.d.ts, packages/browser/src/client/tester/locators/index.ts
=> fix(browser): `locator.element()` returns `HTMLElement` or `SVGElement`

packages/vitest/package.json, pnpm-lock.yaml
=> chore: remove `pretty-format` from dev dependencies

.github/workflows/publish.yml
Use trusted publisher, see also https://github.com/e18e/ecosystem-issues/issues/201
ref https://github.com/vitejs/vite/commit/5433a85fa439b39b2c6f3e5ffaf1cba0c96f435c
Requires package owner to
1. Connect your GitHub repository to your existing npm package at `https://www.npmjs.com/package/<your-package>/access`
2. Safely remove npm tokens
3. [optional] Disallow tokens for publishing
=> ci: use trusted publisher

packages/vitest/package.json, pnpm-lock.yaml
- https://github.com/tinylibs/tinypool/releases/tag/v2.0.0
- Speeds up Vitest's main thread ~5ms
=> perf: update `tinypool` to `v2.0.0`

docs/guide/browser/commands.md, docs/guide/browser/config.md, docs/guide/browser/index.md, docs/guide/browser/interactivity-api.md
=> docs(browser): remove mentions of old browser/providers/*

packages/browser/src/node/plugin.ts
=> fix(browser): don't import from `vite` directly

packages/vitest/src/node/stdin.ts, packages/vitest/src/node/watch-filter.ts, test/cli/fixtures/path-filter/basic.test.ts, test/cli/fixtures/path-filter/vitest.config.ts, test/cli/test/path-filter.test.ts
=> feat: display test "path" when filtering

packages/vitest/LICENSE.md, packages/vitest/package.json, packages/vitest/src/create/browser/creator.ts, packages/vitest/src/node/create.ts, packages/vitest/src/node/plugins/publicConfig.ts, pnpm-lock.yaml
`empathic` is smaller and has zero dependencies (compared to 5), helps with a smaller bundle size and has less licenses to bundle.
The find up function should work similarly
=> refactor: replace find-up with empathic

docs/advanced/api/vitest.md, packages/vitest/src/node/core.ts
=> feat(api): add `getSeed` method

packages/ui/client/auto-imports.d.ts, packages/ui/client/components/Navigation.vue, packages/ui/client/components/views/ViewEditor.vue, packages/ui/client/composables/codemirror.ts, packages/ui/client/composables/navigation.ts
=> fix(ui): keep the same tab open when clicking on different tests

packages/browser/src/node/commands/screenshot.ts
=> fix(browser): stop creating unnecessary directories when taking screenshots

docs/guide/browser/visual-regression-testing.md
=> docs: fix visualn regression example
