vitest-dev/vitest

docs/config/index.md
packages/vitest/src/defaults.ts
test/coverage-test/testing-options.mjs
test/coverage-test/vitest.config.ts
test/workspaces/vitest.config.ts

Fixes https://github.com/vitest-dev/vitest/issues/2674. 
There's more reasoning on the linked issue, but overall `all: true` is better default.

feat!: enable `coverage.all` by default

---

README.md
docs/.vitepress/components/FeaturesList.vue
docs/.vitepress/config.ts
docs/config/index.md
examples/README.md
examples/marko/components/Hello.marko
examples/marko/package.json
examples/marko/test/__snapshots__/basic.test.ts.snap
examples/marko/test/__snapshots__/hello.test.ts.snap
examples/marko/test/basic.test.ts
examples/marko/test/hello.test.ts
examples/marko/vitest.config.ts
packages/vitest/src/defaults.ts
packages/vitest/src/types/coverage.ts
pnpm-lock.yaml

* Adds Marko to the list of supported frameworks (with an example).
* Enables code coverage for Marko files by default.

feat: add Marko example and include code coverage for Marko files

---

packages/vitest/src/node/hoistMocks.ts
test/core/src/rely-on-hoisted.ts
test/core/test/hoisted-async-simple.test.ts
test/core/test/hoisted-simple.test.ts

Currently `vi.hoisted` is not hoisted if it's assigned to another variable and there are no `vi.mock/vi.unmock` inside the file.

fix(vitest): correctly hoist `vi.hoisted` if assigned

---

packages/browser/package.json
packages/coverage-istanbul/package.json
packages/coverage-v8/package.json
packages/ui/package.json
packages/web-worker/package.json

Sub-packages to require v1 or v1-beta version of Vitest as peer dependency.

fix!: set `vitest` peer dependency range for sub packages

---

packages/vitest/src/defaults.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/pool.ts
packages/vitest/src/types/config.ts

Fixed a type issue in the config file, where pool and poolMatchGlob should use `Exclude<T>` to exclude type `"browser"` instead of `Omit<T>`.

fix(config): type issue of `pool` and `poolMatchGlobs` in defineConfig

---

packages/utils/src/error.ts
packages/utils/src/helpers.ts
test/core/test/jest-expect.test.ts

fix(jest-expect): `Object.freeze` breaks `toEqual`

---

packages/runner/src/suite.ts
test/core/test/nested-test.test.ts

fix(runner): nested tests should throw errors

---

packages/vite-node/src/hmr/hmr.ts

https://github.com/vitejs/vite/pull/14518 added support for `import.meta.hot.off` in vite 5. Without this it's causing the ecosystem-ci to fail on build: https://github.com/vitejs/vite-ecosystem-ci/actions/runs/6529244403/job/17726630802#step:8:1218
I used `@ts-ignore` so the typecheck passes in both vite 4 and vite 5
After running the `pnpm test:ci` locally, I'm getting fails for:
```
test/run test:  × test/tty.test.ts > run mode does not get stuck when TTY
test/run test:    → expected 'The CJS build of Vite\'s Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.\n' to be '' // Object.is equality
test/run test: ⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯
test/run test:  FAIL  test/tty.test.ts > run mode does not get stuck when TTY …
```

feat: support import.meta.hot.off for vite 5

---

examples/playwright/test/basic.test.ts
examples/puppeteer/test/basic.test.ts

When running browser tests in parallel, there is a potential issue where multiple instances may attempt to use the same port for communication. This port conflict can lead to scenarios where a test instance communicates with the wrong port, causing inaccurate results or failures in test execution.
To mitigate the issue, this pull request introduces a solution that ensures each test instance receives a unique port for communication. This is achieved by assigning a constant port value to each instance, preventing conflicts and enhancing the reliability of parallel test execution.

fix: address conflicts in port usage for browser-related test suites.

---

packages/vitest/src/node/core.ts
packages/vitest/src/node/globalSetup.ts
packages/vitest/src/node/workspace.ts

Previously Vitest ignored the global setup inside a root config if there was a workspace defined, and the main config was not in the workspace configuration.
This reverts the behaviour to the one we had before the rewrite of global setup.

fix(vitest): run globalSetup from the root config even if it's not in a workspace

---

packages/browser/src/client/runner.ts
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/node/pools/child.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vm-threads.ts
packages/vitest/src/runtime/runners/index.ts
packages/vitest/src/types/rpc.ts
packages/vitest/src/types/worker.ts
pnpm-lock.yaml
test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
test/coverage-test/coverage-report-tests/generic.report.test.ts
test/coverage-test/custom-provider.ts
test/coverage-test/package.json
test/coverage-test/src/multi-environment.ts
test/coverage-test/test/ssr.test.ts
test/coverage-test/test/web.test.ts
test/coverage-test/vitest.config.ts
test/workspaces/coverage-report-tests/check-coverage.test.ts
test/workspaces/globalTest.ts
test/workspaces/package.json
test/workspaces/space-multi-transform/src/multi-transform.ts
test/workspaces/space-multi-transform/test/project-1.test.ts
test/workspaces/space-multi-transform/test/project-2.test.ts
test/workspaces/vitest.config.ts
test/workspaces/vitest.workspace.ts

- Fixes https://github.com/vitest-dev/vitest/issues/3888
- Fixes https://github.com/vitest-dev/vitest/issues/3251
This introduces breaking change as coverage providers now expect Vitest to pass `transformMode` in `AfterSuiteRunMeta`. But if this is included in v1 releases/beta releases, users won't notice anything as long as they don't mix `vitest@v1` and `@vitest/coverage-<provider>@0.x.x` packages.
I also ran into https://github.com/bcoe/c8/issues/172 in `test/workspaces`. V8 reports two different counts of blocks (branches) when run with different inputs.
https://github.com/vitest-dev/vitest/blob/9112cc96b4fe7f9db096ca83bee81ec7165e0710/test/workspaces/src/math.ts#L2-L9
This can't be fixed on our side - at least not without AST analysis or with hacky solutions like …

fix!(coverage): use `transformMode` and workspace project based source maps

---

docs/config/index.md
packages/utils/src/source-map.ts
packages/vitest/src/node/error.ts
packages/vitest/src/node/reporters/json.ts
packages/vitest/src/node/reporters/junit.ts
packages/vitest/src/node/reporters/tap.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/types/config.ts
test/stacktraces/fixtures/error-with-stack.test.js
test/stacktraces/test/__snapshots__/runner.test.ts.snap
test/stacktraces/test/runner.test.ts

This change introduces a new optional configuration parameter, `onStackTrace`. If included, each frame of each error stacktrace encountered during the test run will be tested by the provided function. If the test fails, the frame will be omitted from the displayed trace.
The only real note is that this might not give enough information for more complex situations (e.g. filtering that depends on the error, or the other frames).
Fixes #1999.

feat: filter stacktraces (fix #1999)

---

packages/vitest/src/utils/coverage.ts
test/coverage-test/coverage-report-tests/generic.report.test.ts
test/coverage-test/vitest.config.ts

fix(coverage): `thresholdAutoUpdate` to detect zero limits

---

packages/vitest/package.json
packages/vitest/src/runtime/runners/benchmark.ts
packages/vitest/src/types/config.ts
pnpm-lock.yaml

This way we can change the instance of `tinybench` by inherting `NodeBenchmarkRunner` and overriding `importTinyBench`.
But unfortunately, `@codspeed/tinybench-plugin` is incompatible with `vitest`. We need still to wait for `codespeed` to support `vitest`.  I see them doing it. https://github.com/CodSpeedHQ/codspeed-node/pull/26
close: #4081

feat(benchmark):  move importTinybench to runner

---

packages/vitest/src/node/cli-api.ts
packages/vitest/src/node/create.ts
packages/vitest/src/node/pool.ts
packages/vitest/src/node/workspace.ts
test/config/fixtures/mode/example.benchmark.ts
test/config/fixtures/mode/example.test.ts
test/config/fixtures/mode/vitest.benchmark.config.ts
test/config/fixtures/mode/vitest.test.config.ts
test/config/test/mode.test.ts

Fixes #4398
I am in the process of adding tests

fix(vitest): pass correct mode in vitest config function

---

packages/runner/src/fixture.ts
packages/runner/src/types/tasks.ts
test/core/test/fixture-initialization.test.ts
test/core/test/test-extend.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/4386
Given the following test:
```
describe('fixture dependency', () => {
const myTest = test
.extend<{ a: number; b: number }>({ a: 1, b: 2 })
.extend<{ c: number }>({
c: async ({ a, b }, use) => {
await use(`${a}, ${b}`)
},
})
myTest('c => [a, b]', ({ c }) => {
expect(c).toBe('1, 2')
})
})
```
I expect the test to pass. However, the test fails with the following error:
```
AssertionError: expected 'undefined, 2' to be '1, 2' // Object.is equality
- Expected
+ Received
- 1, 2
+ undefined, 2
```
The fixture `a` is not initialised despite the fixture `c` depending upon it.
This PR amends the check when updating the list of dependencies for each fixture so that a fixture is excluded from its own dependency list by comparing the name of the …

fix: support accessing fixture at same index of dependency fixture

---

packages/runner/src/fixture.ts
test/core/test/fixture-concurrent.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/4402
When multiple tests concurrently use an asynchronous fixture, the fixture value is not necessarily isolated between tests. This leads to a race condition and unpredictable behaviour where a fixture value created in one test may or may not be attached to the context of a separate test, sometimes causing Vitest to hang as the promise returned in the call to use() is awaited but never resolved. This PR addresses the race condition by isolating fixture values between tests.

fix: make asynchronous fixtures work concurrently

---

.eslintrc
docs/.vitepress/style/vars.css
docs/advanced/metadata.md
docs/advanced/reporters.md
docs/advanced/runner.md
docs/api/mock.md
docs/api/vi.md
docs/config/index.md
docs/guide/reporters.md
docs/package.json
packages/expect/src/jest-expect.ts
packages/spy/src/index.ts
packages/vitest/src/integrations/vi.ts
packages/vitest/src/types/index.ts
pnpm-lock.yaml

This PR
- removes `EnhancedSpy` because it is an implementation detail and is no longer needed
- deprecates `SpyInstance` in favor of `MockInstance`
- adds inline documentation to "vi" object
- adds inline documentation to mock instance
- adds more documentation in general
- updates vitepress to the latest version which changes design a little bit

refactor!: remove EnhancedSpy type, deprecate SpyInstance, improve mocks and vi documentation

---

packages/runner/src/fixture.ts
test/core/test/fixture-initialization.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/4418
Currently, when extending a test function with fixtures, if the fixtures are unused within a given test or hook, when accessing non-fixture context (e.g. `task`) the test fails with an error:
`TypeError: Cannot destructure property 'isFn' of 'fixture' as it is undefined.`
Example:
```
const myTest = test.extend({ a: 1 })
myTest('accessing non-fixture context', ({ task }) => {
expect(task).toBeTruthy()
})
```
This PR addresses the above error by making `withFixtures` return early if the `pendingFixtures` array is empty after having been filtered.

fix: support accessing task from test context without accessing fixtures

---

docs/.vitepress/config.ts
docs/.vitepress/scripts/pwa.ts
docs/.vitepress/style/main.css
docs/.vitepress/style/vars.css
docs/index.md
docs/package.json
netlify.toml
pnpm-lock.yaml

- fix VP styles, css vars changed in rc10 version: missing review of #4400
- adds icons to the home features
- changes markdown theme from `vitesse-dark` and `vitesse-light` to `github-dark` and `github-light`  respectively: fix wcag aa color contrast
- includes experimental allowlist PWA feature to avoid breaking VP layout when requesting missing page: check https://github.com/vite-pwa/vitepress/issues/22
- removes SPA from Netlify
- includes VP `hashmap.json` file, required for hydration
- increases the max size asset allowed to be precached, Anthony's svg sponsor file now 2.5MB...

docs: fix VP rc24 styles

---

docs/api/expect.md
docs/api/index.md
docs/guide/migration.md

This PR makes every page in documentation consistent by removing extra spaces before _some_ paragraphs. This PR doesn't have any other changes (except removing one comment in the docs).

docs: remove extra spaces before paragraphs in documentation

---

packages/expect/src/constants.ts
packages/expect/src/jest-extend.ts
packages/expect/src/state.ts
packages/vitest/src/integrations/chai/index.ts
test/core/test/local-context.test.ts

Closes https://github.com/vitest-dev/vitest/issues/4360
~Draft PR to start with probably too quick-and-dirty ideas.
I will continue to see if there is a clear way and also see if some test breaks.~
After the investigation https://github.com/vitest-dev/vitest/issues/4360#issuecomment-1786694374, I found that custom asymmetric matchers defined on global `expect` is not propagated to local context's `expect`.
This PR fixes the issue by keeping track of asymmetric matchers object on `globalThis[ASYMMETRIC_MATCHERS_OBJECT]` then copying them over during `createExpect`.

fix: copy custom asymmetric matchers to local `expect`

---

docs/api/expect.md
docs/guide/snapshot.md
examples/mocks/test/error-mock.spec.ts
packages/vitest/src/integrations/snapshot/chai.ts
test/core/test/__snapshots__/mocked.test.ts.snap
test/core/test/__snapshots__/snapshot.test.ts.snap
test/core/test/jest-expect.test.ts
test/core/test/nested-test.test.ts
test/core/test/snapshot-custom-serializer.test.ts
test/core/test/snapshot-inline.test.ts
test/core/test/wait.test.ts
test/snapshots/test/snapshots-async.test.ts
test/utils/test/display.spec.ts

Closes https://github.com/vitest-dev/vitest/issues/3655
As explained in https://github.com/vitest-dev/vitest/issues/3655#issuecomment-1784471527, currently vitest hard-codes specific behavior to extract `Error.message` for `Error` instance when it's snapshot-ed via `toThrowErrorMatching...`, which prevents error from being applied with user-provided serializer.
This PR removes this special behavior, so that `Error` instance's snapshot is a consistent regardless of whether its snapshote-ed via `toMatchInlineSnapshot` or `toThrowErrorMatchingInlineSnapshot`.
Due to the removal of `Error.message` extraction, the default snapshot format changes in a following way
```tsx
// before
expect(() => {
throw new Error('omega')
}).toThrowErrorMatchingInlineSnapshot(`"ometa"`)
// after
expect(() => { …
```

fix: apply serializer to `Error` instance for thrown snapshot

---

docs/config/index.md
packages/vitest/src/node/config.ts
packages/vitest/src/runtime/runners/benchmark.ts
test/browser/vitest.config.mts
test/coverage-test/test/coverage.test.ts

Closes #4264
Currently this API breaks more stuff and doesn't bring _a lot_ of benefits. You can still enable it with `test.browser.slowHijackESM: true`

fix(browser): disable hijacking ES modules until vi.mock is implemented

---

docs/config/index.md
packages/browser/src/client/main.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/api/types.ts
packages/vitest/src/index.ts
packages/vitest/src/integrations/inject.ts
packages/vitest/src/integrations/vi.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/globalSetup.ts
packages/vitest/src/node/index.ts
packages/vitest/src/node/pools/child.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vm-threads.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/runtime/child.ts
packages/vitest/src/runtime/execute.ts
packages/vitest/src/runtime/vm.ts
packages/vitest/src/runtime/worker.ts
packages/vitest/src/types/general.ts
packages/vitest/src/types/rpc.ts
packages/vitest/src/types/worker.ts
packages/vitest/src/utils/global.ts
test/workspaces/globalTest.ts
test/workspaces/space_3/global-provide.space-3-test.ts
test/workspaces/space_3/localSetup.ts
test/workspaces/space_3/vitest.config.ts

Closes #4025
This PR adds `project.provide` API that allows transfering data from the main thread like global setup to tests. This API cannot be used to transfer data back to the main thread - users need to implement that themselves. If they want to keep communication inside Vitest, it's recommended to use [`task.meta`](https://vitest.dev/advanced/metadata.html) to transfer data back to the main thread alongside tests.
To get the data, you need to write `import('vitest').inject(key)` inside the test:
```ts
// globalSetup.ts
declare module 'vitest' {
export interface ProvidedContext {
dbUrl: string
}
}
export default async ({ provide }) => {
const db = new DB()
const url = db.getUrl()
provide('dbUrl', url) // has typechecking
}
// db.test.ts
import { inject } from 'vitest'
const dbUrl = …
```

feat: implement provide/inject API to transfer data from the main thread

---

docs/config/index.md
packages/vitest/src/defaults.ts
test/coverage-test/coverage-report-tests/generic.report.test.ts
test/coverage-test/src/.should-be-excluded-from-coverage/excluded-from-coverage.ts

Exclude files and directories that start with `.` from coverage reports by default. 
I just ran into out-of-memory error when using `vite-plugin-inspect` and had `provider: 'istanbul'` enabled. As `coverage.all` picks all included untested files, it picked 4MB JS file `.vite-inspect/assets/index-<hash>.js` and run into OOM while trying to instrument that file.

fix(coverage): exclude files and directories starting with dot by default

---

examples/lit/package.json
examples/lit/test/basic.test.ts
examples/lit/tsconfig.json
examples/lit/vite.config.ts
packages/browser/providers.d.ts
packages/browser/src/node/providers/index.ts
packages/browser/src/node/providers/none.ts
packages/vitest/src/integrations/browser.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/types/browser.ts
packages/vitest/src/utils/env.ts
pnpm-lock.yaml

Closes #3674
Closes #3273
Lit recommends testing itself with a real browser and don't rely on polyfilled environment.

feat(browser): support "none" provider and update lit example to use it

---

packages/vitest/src/node/cli.ts

fix: throw an error when running "vitest typecheck"

---

docs/guide/cli.md
packages/snapshot/src/client.ts
packages/utils/src/error.ts
packages/vitest/src/node/cli.ts
packages/vitest/src/node/config.ts
packages/vitest/src/types/config.ts

Currently very long snapshots take a lot of space to display their diff even if there is only one change. This PR makes it so snapshots only show a small patch that actually changed. To allow restoring previous behaviour, the `--expand-snapshot-diff` flag is introduced.

fix: don't expand snapshot diff by default

---

docs/guide/environment.md

This PR is a minor docs contribution, adding a missing `expect` import in a `@vitest-environment` code snippet. Without the `expect`, a developer will see the error `ReferenceError: expect is not defined` when running that code sample directly.

docs(environment): add missing expect import

---

packages/runner/src/fixture.ts
test/fails/fixtures/test-extend/fixture-error.test.ts
test/fails/test/__snapshots__/runner.test.ts.snap

Fixes https://github.com/vitest-dev/vitest/issues/4435
When running a test with a fixture function that throws an error, the error is not handled by the test runner and the test times out. (Reproduction: https://stackblitz.com/edit/vitest-dev-vitest-72lr7i?file=test%2Ffixture-error.test.ts)
Example:
```
import { test } from 'vitest';
const myTest = test.extend<{ a: never }>({
a: async () => {
throw new Error('Error thrown in test fixture');
},
});
myTest('error in fixture causes a timeout', ({ a }) => {});
```
Instead of timing out, the test runner should handle the error immediately. This PR amends the `withFixtures` function to catch any rejected fixture promise and forwards the error so that the test fails immediately.

fix: handle errors thrown in fixtures

---

docs/guide/in-source.md

The following configuration needs to be in `vite.config.ts` instead of `vitest.config.ts`, otherwise it has no effect and the in-source unit tests are included in the production build.
```ts
define: {
'import.meta.vitest': 'undefined', // prevent unit tests from being included in other builds
},
```

docs: fix incorrect instructions for avoiding in-source tests in production builds

---

README.md
docs/guide/testing-types.md
packages/vitest/package.json
packages/vitest/src/typecheck/typechecker.ts
pnpm-lock.yaml
test/typescript/test/__snapshots__/runner.test.ts.snap
test/typescript/test/runner.test.ts

Update expect-type version to the prerelease from https://github.com/mmkal/expect-type/pull/16 - it should make error messages much better. This is hard to see in a repo where the assertions are passing, but see the snapshot update in that PR. (Note: the title is "improve expectTypeOf error messages" rather than referencing the update, since that's the net effect for end-users).
Here are what the examples of failing-test.d.ts in this repo look like:
Before:
After:
---
Related to https://github.com/vitest-dev/vitest/issues/1954 - @sheremet-va FYI. I don't think it closes it as that issue seems. to be more about how it fits into the vitest API/usage generally.
I also linked to my library in the readme.
~I've opened this as a draft as I'd like to publish v0.17.0 (rather than under the `next` …

feat: improve expectTypeOf error messages

---

packages/expect/src/jest-expect.ts
test/core/test/jest-expect.test.ts

fix(expect): print full error if promise is rejected

---

packages/vitest/src/defaults.ts

When running in CI, `vitest` will try to open the UI if you pass `-ui` because `--open` is defaulting to `true` even though it says it should default to `!process.env.CI`.
https://github.com/vitest-dev/vitest/blob/cc19117d303ad0a36721ddee01c14f04812245ae/packages/vitest/src/node/cli.ts#L22

fix: default --open to !process.env.CI

---

examples/sveltekit/package.json
package.json
packages/vite-node/src/client.ts
packages/vitest/package.json
pnpm-lock.yaml
test/core/src/aliased-mod.ts
test/core/test/file-path.test.ts
test/core/vite.config.ts

Vitest will now throw an error for non-absolute aliases following Vite's behaviour: https://github.com/vitejs/vite/commit/6a564fa92a368ae4b5f0c2392c49450d534d4b52
In the future I would like to unify externalization with Vite so we don't need to do that at runtime.

fix: throw an error if Vite wasn't able to resolve aliased path

---

docs/api/index.md
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
packages/vitest/src/types/config.ts
test/core/test/sequential-sequence-concurrent.test.ts
test/core/test/sequential.test.ts

Fixes #4480
Currently, `describe.sequential` has no effect as `describe` does not correctly inherit the `concurrent` option from the parent suite ([reproduction](https://stackblitz.com/edit/vitest-dev-vitest-ri5bfg?file=nested-concurrent.test.ts)). This PR fixes the inheritance of `concurrent`/`sequential` options so that tests within `describe` nested within `describe.concurrent` run concurrently.

fix: inherit concurrent/sequential in nested suites

---

docs/api/expect.md
packages/expect/src/jest-expect.ts
test/core/test/environments/jsdom.spec.ts

feat(expect): toContain can handle classList and Node.contains

---

docs/config/index.md

This PR capitalises a few sentences on the /config page that should be capitalised on a new line. 
Before:
After:

style: capitalise a few sentences for consistency

---

packages/browser/src/client/main.ts
packages/browser/src/client/utils.ts
packages/browser/src/node/index.ts

fix(browser): add vitest/ imports to entries

---

docs/api/index.md
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
test/core/test/sequential-sequence-concurrent.test.ts
test/core/test/sequential.test.ts

Implements #4511 
This PR adds `.sequential()` to the chainable test API so that individual tests can be marked as sequential within a concurrent suite in the same way that individual tests can be marked as concurrent within a sequential suite.
Usage example:
```ts
// with config option { sequence: { concurrent: true } }
test('concurrent test 1', async () => { /* ... */ })
test('concurrent test 2', async () => { /* ... */ })
test.sequential('sequential test 1', async () => { /* ... */ })
test.sequential('sequential test 2', async () => { /* ... */ })
// within concurrent suite
describe.concurrent('suite', () => {
test('concurrent test 1', async () => { /* ... */ })
test('concurrent test 2', async () => { /* ... */ })
test.sequential('sequential test 1', async () => { /* ... */ }) …
```

feat: add test.sequential() api

---

docs/.vitepress/components/ListItem.vue
docs/.vitepress/scripts/fetch-avatars.ts
docs/.vitepress/style/main.css
docs/package.json
pnpm-lock.yaml

- download only team avatars on build: from this comemnt https://github.com/vitest-dev/vitest/pull/4523#pullrequestreview-1736467012
- bump to VP rc.27, hoisting css styles fixed, I've reverted changes on my last PR to fix the animations in features page
I've kept contributor avatars logic, we can remove the vue sfc, the json file and the logic.

docs: download only team avatars on build

---

docs/guide/mocking.md

Minor fix to update an outdated import in the docs. It looks like there are some other changes to this file that have addressed most of the [out of date usage from `msw` on the current site](https://vitest.dev/guide/mocking.html#configuration), however the import itself seems to have been missed.
Note: The other changes to this example from https://github.com/vitest-dev/vitest/pull/4502 should probably be released soon.

docs: Update incorrect import in request mocking example

---

packages/coverage-istanbul/src/provider.ts

While looking into https://github.com/vitest-dev/vitest/issues/4476 I noticed that `@vitest/coverage-istanbul` instruments files that are already instrumented when using `coverage.all: true`. In practice it means that once coverage counters are added to source files, we re-run instrumentation and instrument **all** of those coverage counters too. This is really expensive process and leads to out-of-memory errors easily.
`vitenode.transformRequest` runs transforms for the requested file, which includes the `vitest:coverage-transform` Vite plugin.
https://github.com/vitest-dev/vitest/blob/cc19117d303ad0a36721ddee01c14f04812245ae/packages/coverage-istanbul/src/provider.ts#L213
Then we take that transformed + instrumented code and instrument it again: …

perf(coverage-istanbul): `all: true` instruments already instrumented files

---

packages/vitest/src/integrations/wait.ts
test/typescript/test-d/vi.test-d.ts

fix(vitest): improve vi.waitUntil type to excude falsy types

---

examples/react-testing-lib-msw/vite.config.ts
package.json

The `msw` tests use `fetch` which is unstable on `node:worker_threads`. Example failure on `main` CI: https://github.com/vitest-dev/vitest/actions/runs/6926748073/job/18839404982
Worker seems to get completely stuck. When CI terminates the job following error is shown.
```
vitest "--allowOnly" "--pool" "vmThreads"
RUN  v1.0.0-beta.5 /home/runner/work/vitest/vitest/examples/react-testing-lib-msw
✓ src/App.test.tsx  (2 tests) 301ms
Tests  2 passed (2)
Start at  07:22:36
Duration  3.59s (transform 779ms, setup 253ms, collect 1.43s, tests 301ms, environment 662ms, prepare 831ms)
file:///home/runner/work/vitest/vitest/node_modules/.pnpm/tinypool@0.8.1/node_modules/tinypool/dist/esm/index.js:532
const timer = timeout ? setTimeout(() => reject(new Error("Failed to …
```

test: `msw` to use `--pool=forks`

---

docs/guide/coverage.md
packages/coverage-v8/package.json
pnpm-lock.yaml
test/coverage-test/src/utils.ts

Adds support for ignoring code using `/* v8 ignore...` ignore hints instead of `/* c8 ignore...` ones when using `@vitest/coverage-v8` provider. The old `c8` ignore hints were confusing as Vitest does not use `c8` at all.
- Ref. https://github.com/istanbuljs/v8-to-istanbul/pull/228

feat(coverage): support `/* v8 ignore...` ignore hints

---

docs/guide/cli.md
docs/guide/index.md
docs/guide/workspace.md
packages/vitest/src/node/cli.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/stdin.ts
packages/vitest/src/types/config.ts

feat: add --project option to limit what projects are running

---

packages/browser/src/node/esmInjector.ts
packages/browser/src/node/index.ts

Solves #4570 by adding a missing dependency of `@vitest/snapshot` to the dependency optimization.

fix(browser): allow for `pretty-format` as a sibling dependency

---

packages/runner/src/suite.ts
test/core/test/fixture-initialization.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/4585
Currently, calling `test.runIf()` and `test.skipIf()` does not propagate the test's context through the method chain. This causes test fixtures to become unavailable after calling `runIf` or `skipIf`. This PR fixes the issue by making the `runIf` and `skipIf` functions return the same instance of the test object instead of returning the base test object, preserving the test context.

fix(runner): preserve fixtures when calling runif and skipif (fix #4585)

---

docs/guide/coverage.md

Small correction of the docs. The vitest config parameter should be `test.coverage.reporter` not `reporters`. This may be confusing because there is also a `test.reporters` parameter.
Appreciate your checklist, but given this is a docs-only change and only 1 character, I'm unable to link an issue or write a new test for this.

docs: correction to configuration parameter

---

packages/vitest/src/node/workspace.ts

This PR fixes #4539.
Pass the `this.config.server` to `ViteNodeServer` instead of `this.config`.
I suspect that the workspace version was simply left not to modified in #3725 because the workspace feature had been implemented in parallel at that time.

fix(vitest): pass correct server options in workspace (#4539)

---

packages/vitest/src/types/benchmark.ts

This PR extracts a new type `ChainableBenchmarkAPI` from `BenchmarkAPI`. This prevents display of incorrect type hints for `bench.runIf.runIf`, `bench.runIf.skipIf`, `bench.skipIf.runIf` and `bench.skipIf.skipIf`.

chore(bench): extract ChainableBenchmarkAPI type

---

packages/runner/src/run.ts
pnpm-lock.yaml
test/empty-test/package.json
test/empty-test/test/one.test.ts
test/empty-test/vitest.config.ts

fix(runner): passWithNoTests option not work

---

docs/config/index.md
packages/coverage-istanbul/package.json
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
packages/vitest/src/defaults.ts
packages/vitest/src/types/coverage.ts
pnpm-lock.yaml
test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
test/coverage-test/test/configuration-options.test-d.ts

- Fixes https://github.com/vitest-dev/vitest/issues/4476
- Adds new option `coverage.processingConcurrency` for controlling concurrency limit of coverage file processing. Default value is likely good for most users. This option is only exposed for issues like [nyc#1424](https://github.com/istanbuljs/nyc/issues/1424) and [nyc#1309](https://github.com/istanbuljs/nyc/issues/1309).
- Adds support for debugging coverage report processing by using `DEBUG=vitest:coverage` environment variable. This is useful when debugging slow coverage generation, e.g. cases where `coverage.all: true` picked minified Javascript files. This will also help maintainers when debugging bug reports.
- Let's add test case to ecosystem so whole Vitest pipeline won't slow down …

fix(coverage): improve memory usage by writing temporary files on file system

---

packages/browser/src/client/main.ts
packages/browser/src/client/utils.ts

fix(browser): don't go into an infinite reload loop, don't fail if "error" event is caught

---

packages/expect/src/jest-utils.ts
test/core/test/jest-expect.test.ts

Change the "equal comparison" logic (as used by `toEqual`, `toStrictEqual`, etc.) to compare `URL` objects by their `href` property.
Closes #4614.

feat(expect): compare URL objects by href

---

docs/config/index.md
packages/vitest/src/types/coverage.ts

`os.cpu()` should be `os.cpus()` in config docs.

docs: `os.cpu()` should be `os.cpus()`

---

packages/vitest/src/runtime/child.ts

- Ref. https://github.com/vitest-dev/vitest/pull/4191
The `init()` of `runtime/child.ts` is called only once tasks are started. However Tinypool imports the handler of workers when preparing them. In practice, without this change there can be Vitest forks running idle, but process name is not set for them. By moving the `process.title` override to module level it will be set as soon as Tinypool imports the worker entrypoint.
Tested manually by running Vitest in watch mode and checking running processes once tests had succeeded and Vitest was waiting for re-runs.

fix: set process name for idle workers

---

packages/browser/package.json
packages/coverage-istanbul/package.json
packages/coverage-v8/package.json
packages/ui/package.json
packages/vitest/package.json
packages/web-worker/package.json
pnpm-lock.yaml

fix: bump vitest packages `peerDependencies` versions

---

packages/vitest/LICENSE.md
packages/vitest/package.json
pnpm-lock.yaml

- Fixes https://github.com/vitest-dev/vitest/issues/4589
After updating `@antfu/install-pkg@0.2.0` the Rollup build fails to resolve `find-up > unicorn-magic`. There is `node` condition in its exports: https://github.com/sindresorhus/unicorn-magic/blob/67bb2fd1da1eecb252ba14284df14c0d234a8cfa/package.json#L16

fix(cli): prompted packages fail to install

---

packages/vitest/src/node/cli-api.ts

close #4656
vite is installed as a direct dependency of vitest, so there's no way for it to be missing.

fix: don't check if vite is installed

---

packages/vitest/src/node/pkg.ts

close #899
close #4575
partially #4413
This PR adds a special case for Yarn PnP inside ensurePackageInstalled to work around https://github.com/antfu/local-pkg/issues/2, making Vitest possible to use with Yarn PnP again.

fix: fix ensurePackageInstalled on Yarn PnP

---

packages/vitest/src/integrations/snapshot/chai.ts
test/core/test/snapshot-inline.test.ts

Closes https://github.com/vitest-dev/vitest/issues/4662
I think the difference between `toMatchInlineSnapshot` and `toThrowErrorMatchingInlineSnapshot` was due to the lack of `stripSnapshotIndentation`. It seems to work fine after adding it to `toThrowErrorMatchingInlineSnapshot`.
Actually I'm a little puzzled by why the following case was working fine without this change. I might be still missing something ...
https://github.com/vitest-dev/vitest/blob/4a8714e00c83adba1f509861f031f5489e82dfb0/test/core/test/snapshot-inline.test.ts#L94-L101

fix: apply `stripSnapshotIndentation` for thrown snapshot

---

packages/expect/src/jest-utils.ts
test/core/test/jest-expect-no-url.test.ts

As per @sheremet-va 's comment https://github.com/vitest-dev/vitest/discussions/4667#discussioncomment-7762415, I added `typeof URL` check to support environment where standard `URL` is not available.

fix(expect): apply `URL` equality check only when `URL` is available

---

packages/vitest/src/runtime/mocker.ts
test/core/src/mockedC.ts

Closes https://github.com/vitest-dev/vitest/issues/4676
Follow up https://github.com/vitest-dev/vitest/pull/4564
I found a previous discussion regarding getter/setter mocking in https://github.com/vitest-dev/vitest/pull/1903#discussion_r953359135. Based on that, I think just skipping getter entirely is a desired behavior.
Actually I wonder what's the current behavior with setter (setter only case?), but maybe it can be followed up separately since this getter bug could be a huge blocker for many users trying v1.
Please let me know what you think.

fix(vitest): skip processing getter in auto-mocked constructor call

---

packages/browser/package.json
packages/ui/package.json

While experimenting with browser package code, I noticed that `pnpm dev` is not picking up the change of some files.
I assumed `--watch.include` hasn't been updated after getting more files there, so I updated the options to align with other places such as:
https://github.com/vitest-dev/vitest/blob/f13fa9c1e7289f6d5988df8e70058b21abd51e60/packages/coverage-istanbul/package.json#L41

chore: fix `--watch.include` option of `dev` scripts

---

docs/guide/mocking.md

Hey! Thank you so much for recommending MSW in the Vitest docs! 
I was reading through the docs and found a few issues/outdated links so I opened this pull request. 
- Changes `node-request-interceptor` mention to `@mswjs/interceptors`. That mention references a rather old library name. Let's stay up-to-date!
- Updates the link to learn more about MSW to point to the `/docs` instead of `/docs/recipes` (which doesn't exist anymore).
- Updates the `graphql.query()` example because that request handler expects an _operation name_, not the endpoint. Now it's correct.

docs(mocking): fix broken msw links

---

docs/api/expect.md

https://github.com/vitest-dev/vitest/blob/3413518b3a33bcbb05e5135b5f8f515fd8d15076/docs/api/expect.md?plain=1#L53
I think the intention here is that the assertion fails, but in fact the assertion passes.

docs(expect): fix soft example error

---

.github/renovate.json5
packages/vitest/package.json
pnpm-lock.yaml

- Fixes https://github.com/vitest-dev/vitest/issues/4710
Adds quick fix for the issue. In long term we should introduce a minimal project in https://github.com/vitest-tests/ for catching these issues in future. After that we can look into upgrading `log-update` back.
With these fixes @sheremet-va your real-world-project reduces test execution from 136s -> 67s on my M2 CPU.

perf(reporters): downgrade `log-update` to v5

---

packages/browser/src/node/providers/playwright.ts
packages/vitest/src/node/core.ts

Reverting https://github.com/vitest-dev/vitest/pull/4623 because public API can call start/stop at any time.
This PR will be merged non-squashed.
Fixes #4713

revert: close pool early in run-mode #4623

---

packages/vitest/src/node/cli.ts
test/config/fixtures/test/log-output.test.ts
test/config/test/failures.test.ts
test/config/test/options.test.ts
test/config/vitest.config.ts

- Fixes https://github.com/vitest-dev/vitest/issues/4694
Hopefully this is last time this boolean flag breaks. `cac` is not my favorite library.

fix(cli): `--coverage.all=false` resolved incorrectly

---

pnpm-lock.yaml
test/browser/cjs-lib/index.js
test/browser/cjs-lib/package.json
test/browser/package.json
test/browser/specs/runner.test.mjs
test/browser/test/cjs-lib.test.ts
test/browser/vitest.config.mts

I'm currently investigating cjs default import issue with `browser.slowHijackESM` (cf. https://github.com/vitest-dev/vitest/issues/4264).
I wasn't sure the future plan of supporting this use case, but I thought it might still make sense to have a test case to demonstrate the current behavior. This would also help debugging this scenario in the future.

test(browser): add test case for cjs import

---

docs/advanced/pool.md

I spotted a few dead links while trying to familiarize myself with Vitest's pool/runtime architecture.
Before: https://vitest.dev/advanced/pool.html
After: https://deploy-preview-4756--fastidious-cascaron-4ded94.netlify.app/advanced/pool.html

docs: fix custom pool links

---

packages/vite-node/src/cli.ts

In ES modules, we can't use the traditional "require.main" method in node to figure out if the currently executing module is the main entry point for the node process. The [es-main module](https://github.com/tschaub/es-main/tree/main) provides a utility that lets us accomplish the same thing using [import.main](https://nodejs.org/api/esm.html#importmeta) metadata that is available in ES modules. You can read more about this use case in the [es-main module readme](https://github.com/tschaub/es-main/tree/main).
`es-main` expects `process.argv[1]` to be the path to the script entry point to figure out if the module is the main one, but it expects this to be an absolute path because this is how node always formats the argument. `vite-node` is extremely close to being able to support this …

feat: Add es-main compatibility to vite-node

---

packages/vitest/src/config.ts
test/config/package.json
test/config/test/config-types.test-d.ts

- Fixes typings of `defineWorkspace`
- Repro: https://stackblitz.com/edit/vitest-dev-vitest-bt4hnv?file=example.ts

fix(types): `defineWorkspace` fix intellisense and report type errors

---

packages/vitest/src/node/core.ts
packages/vitest/src/node/workspace.ts
test/config/fixtures/workspace-flags/projects/cli-config.test.ts
test/config/fixtures/workspace-flags/projects/vitest.config.js
test/config/fixtures/workspace-flags/vitest.workspace.js
test/config/test/flags.test.ts

fix(vitest): pass down CLI options to override workspace configs

---

docs/config/index.md
docs/guide/cli.md
docs/guide/performance.md
packages/vitest/src/defaults.ts
packages/vitest/src/node/cli.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/types/config.ts
test/config/test/resolution.test.ts
test/run-once/vitest.config.ts
test/stacktraces/fixtures/vite.config.ts

Inspired by https://twitter.com/ssalbdivad/status/1736133404054147082

feat: add --no-isolate flag to improve performance, add documentation about performance

---

packages/expect/src/jest-expect.ts
test/core/test/jest-expect.test.ts

Closes https://github.com/vitest-dev/vitest/issues/4732

fix(expect): fix `toHaveProperty` assertion error diff

---

packages/vitest/src/defaults.ts

Use `satisfies` to type the defaults and remove some verbose types

types: use satisfies for defaults

---

test/coverage-test/coverage-report-tests/generic.report.test.ts

I'm not sure if this is only my local issue, but when I run `pnpm test:ci`, there is always new diff left in `test/coverage-test/vitest.config.ts` and `examples/vitesse/src/auto-import.d.ts`.
For the first issue, restoring the trailing new line seems to helps, so I put that in this PR. I tested with `pnpm -C test/coverage-test test:v8`.
For the 2nd issue, maybe `auto-import.d.ts` is meant to be updated, but I'm not familiar with vue nor auto-import, so I'll leave it there for now. FYI, this is the diff I see after running `pnpm -C examples/vitesse test`:
<details><summary>Reveal git diff</summary>
```diff
diff --git a/examples/vitesse/src/auto-import.d.ts b/examples/vitesse/src/auto-import.d.ts
index 9959df65..5eb5ac52 100644
--- a/examples/vitesse/src/auto-import.d.ts
+++ …
```

chore(test): restore trailing new line in `coverage-test/vitest.config.ts`

---

examples/mocks/src/cyclic-deps/module-1.mjs
examples/mocks/src/cyclic-deps/module-2.mjs
examples/mocks/src/cyclic-deps/module-3.mjs
examples/mocks/src/cyclic-deps/module-4.mjs
examples/mocks/test/cyclic-import-actual.spec.ts
examples/mocks/test/cyclic-import-original.spec.ts
packages/vitest/src/integrations/vi.ts
packages/vitest/src/runtime/mocker.ts

Fixes #4373
The problem was that the call stack didn't contain the file that triggered the mock factory execution - in this case `importActual` should behave the same way as a dynamic `import`.

fix(vitest): don't hang when mocking files with cyclic dependencies

---

packages/runner/src/run.ts
test/core/test/skip-reset-state.test.ts

Closes https://github.com/vitest-dev/vitest/issues/4812
The tests I added are not a repro of the referenced issue, but I think this test demonstrates the fix more concisely.
I also locally verified the issue's repro is fixed. If it's desired to add such tests, then I can do that, but I felt it's a little overkill since it would probably requires a dedicated test directory and singleThread option to reproduce.

fix(runner): reset "current test" state on dynamic `skip`

---

packages/vitest/src/node/pools/browser.ts
packages/vitest/src/node/pools/child.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vm-threads.ts

- Fixes bug where test run is not cancelled when one of the registered keys is pressed. This is only present on `pool: 'vmThreads'`.
- Fixes bug where cancelled tests were shown twice by reporters

fix(vm-threads): tests not cancelled on key press, cancelled tests shown twice

---

packages/vitest/src/integrations/env/edge-runtime.ts
packages/vitest/src/integrations/env/happy-dom.ts
packages/vitest/src/integrations/env/jsdom.ts

close #4413
Fixes an issue with Vitest crashing with cryptic error:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{ type: 'Unhandled Error', stacks: [] }
```
when using happy-dom or jsdom environment on Yarn PnP workspaces (note: this is NOT happening in "just" Yarn PnP).
Similarly to #4657, this "lifts" the logic up from local-pkg in order for PnP not to complain about local-pkg accessing packages that are not declared as its dependencies or peerDependencies.
I was unsure what to do `pnpm-lock.yaml` because this PR technically adds a direct dependency (in reality, it "lifts" it, since it's already used in `local-pkg`), so lockfile had to be modified...
How I tested it:
1. Ran unit tests in my workspace using vitest + happy-dom, expecting failures, after removing …

fix: fix crash when using happy-dom or jsdom environment on Yarn PnP workspaces

---

docs/guide/cli.md
docs/guide/debugging.md
packages/vitest/src/node/config.ts
test/config/test/failures.test.ts

- closes #4830 
In certain sections of the documentation and error messages, the option `--no-file-parallelism` is incorrectly referred to as `--no-parallelism`. 
This Pull Request corrects these inconsistencies to ensure that the correct option name, `--no-file-parallelism`, is used throughout.

fix: mistyped option name(--no-parallelism)

---

packages/vitest/src/node/reporters/junit.ts
test/reporters/fixtures/suite-hook-failure/basic.test.ts
test/reporters/fixtures/suite-hook-failure/vitest.config.ts
test/reporters/tests/__snapshots__/junit.test.ts.snap
test/reporters/tests/junit.test.ts

Closes https://github.com/vitest-dev/vitest/issues/4516
This PR is an alternative of https://github.com/vitest-dev/vitest/pull/4799 to surface beforeAll/afterAll errors in junit reporter.
This approach might not be the most sound one since it "mutates" test counts when beforeAll/afterAll failed, but this will ensure such suite-level errors will be recorded in the report.
The idea came from how default reporters shows "Failed Suites" separately from "Failed Tests":
https://github.com/vitest-dev/vitest/blob/5ee041d84f1ac94c8455a31b5732391246b12771/packages/vitest/src/node/reporters/base.ts#L290-L302

fix(vitest): show `beforeAll/afterAll` errors in junit reporter

---

packages/vitest/src/node/pools/vm-threads.ts
packages/vitest/src/utils/memory-limit.ts

When I upgraded vitest to version 1.1.0 and replaced the original `experimentalVmWorkerMemoryLimit` config with `poolOptions.vmThreads.memoryLimit`, an error occurred when running `pnpm test`: "For a percentage based memory limit, a percentageReference must be provided."

fix: don't crash when memoryLimit is assumed to be a percentage of system memory

---

packages/runner/src/fixture.ts
packages/runner/src/run.ts
test/core/test/fixture-concurrent-beforeEach.test.ts

Closes https://github.com/vitest-dev/vitest/issues/4749
To properly support concurrent test with fixtures, I think "clean up array" has to be aware of "test context".
This fix is along the same line of https://github.com/vitest-dev/vitest/pull/4403 where it made "fixture value" to be aware of "test context".

fix(runner): fix fixture cleanup for concurrent tests

---

packages/browser/package.json
packages/browser/src/node/providers/webdriver.ts
test/browser/package.json
test/browser/specs/runner.test.mjs

Fixes #4706.
Removes code from node/providers/webdriver.ts causing the following error when running `vitest --browser.name=safari` on macOS:
```text
Error: There is already a Safaridriver instance running on port
undefined!
```
safaridriver.start() maintains a static reference to a safaridriver instance, and will fail with this error if start() is called again before stop().
The original node/providers/webdriver.ts calls safaridriver.start() directly, and then immediately imports and calls webdriverio.remote(). This call also eventually calls safaridriver.start(), producing the error.
The fix is to remove the direct safaridriver access, as webdriverio seems to manage safaridriver successfully now.
Since Safari can't run in headless mode, I couldn't think of a way to add a test that would …

fix(browser): avoid safaridriver collision

---

packages/browser/src/client/logger.ts
packages/browser/src/client/main.ts
packages/browser/src/client/runner.ts
packages/browser/src/client/utils.ts
test/browser/package.json
test/browser/specs/fix-4686.test.mjs
test/browser/specs/run-vitest.mjs
test/browser/specs/runner.test.mjs
test/browser/vitest.config-basepath.mts

Closes #4686.
Ensures that every import() is properly prefixed with either config.base or '/'.
Also extracted a `runVitest()` test helper to eliminate duplication in the new test. (Except that the new test file copies the first of the existing test cases.)
cc: @alexdulin
`pnpm test` passes locally on macOS; will try Linux and Windows 11 shortly. However, `pnpm test:ci` mostly passes, but eventually fails with:
```text
test/vm-threads test:  ✓ test/module.test.js  (1 test) 3ms
test/vm-threads test: Failed
/Users/msb/src/mbland/vitest/test/vm-threads:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vitest/test-vm-threads@ test: `vitest "--allowOnly"`
Exit status 129
test/workspaces test$ pnpm test:workspace && pnpm test:coverage "--allowOnly"
 ELIFECYCLE  Command failed with exit code 1.
```
I wonder …

fix(browser): handle config.base (#4686)

---

docs/guide/common-errors.md
packages/vitest/src/integrations/vi.ts
packages/vitest/src/runtime/mocker.ts
packages/vitest/src/types/mocker.ts

fix(vitest): throw an error if mock was already loaded when vi.mock is called

---

packages/vite-node/src/server.ts
test/vite-node/test/server.test.ts
test/vite-node/vitest.config.ts

Closes #3967
We have tests for watch mode that confirm everything works (previously it just skipped the cache check almost always, so it correctly loaded new value).

fix(vite-node): correctly return cached result

---

packages/vitest/src/node/reporters/benchmark/table/index.ts
packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
packages/vitest/src/node/reporters/default.ts
packages/vitest/src/node/reporters/dot.ts
packages/vitest/src/node/reporters/renderers/listRenderer.ts

- Closes https://github.com/vitest-dev/vitest/issues/4869
There were two more `const DURATION_LONG = 300` hard-coded in list/table renders. This PR does the same for these two as done in https://github.com/vitest-dev/vitest/pull/2396.
I didn't attempt to add a test yet since list renderer requires non CI environment, so I suspect it might be too difficult and also overkill to setup this scenario.
The fix can be verified locally using existing core test, which coincidentally takes 400ms and has `slowTestThreshold: 1000`:
- before (400ms > hard-coded 300ms)
```
$ pnpm -C test/core test run test-extend.test.ts 
...
✓ |core| test/test-extend.test.ts (18) 411ms
...
✓ asynchonous setup/teardown (1) 401ms
✓ quick test 401ms
```
- after (400ms < slowTestThreshold 1000ms)
```
$ pnpm -C test/core …
```

fix(vitest): apply `slowTestThreshold` to all reporters

---

package.json

I recently got eslint failing on CI with files such as `test/browser/vitest.config.mts` and `test/browser/specs/runner.test.mjs`. I updated lint-staged pattern to catch these in git hook.

chore: include `.mts` and `.mjs` in lint-staged pattern

---

packages/browser/src/node/index.ts
test/browser/specs/runner.test.mjs
test/browser/test/server-headers.test.ts
test/browser/vitest.config.mts

- Closes https://github.com/vitest-dev/vitest/issues/4888
This would align with how `server.headers` are applied to Vite's html server, which seems to be targeted for COOP/COEP headers use case. You can find relevant discussions in:
- https://github.com/vitejs/vite/pull/8481
I was wishing to simplify browser mode tests before putting more tests, but I guess adding this one is okay...

fix(browser): support vite config `server.headers`

---

packages/vitest/src/node/reporters/tap.ts
test/reporters/fixtures/custom-error/basic.test.ts
test/reporters/fixtures/custom-error/vitest.config.ts
test/reporters/tests/tap.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/4885
Currently `processError` (from @vitest/utils) returns `any`, but it looks like most of the usages expect it to be `ErrorWithDiff`. `ErrorWithDiff` requires `name: string`, but `processError` doesn't seem to guarantee this when odd things are thrown.
Fixing `processError` might be better in a long run, but for this PR, I just adjusted tap reporter to do something similar as other reporters in `printErrorMessage`:
https://github.com/vitest-dev/vitest/blob/67e321102b8f0b1a6a4cd5f54ab62656b307426c/packages/vitest/src/node/error.ts#L208-L209

fix(vitest): fix tap reporter to handle custom error

---

packages/vitest/src/node/reporters/benchmark/table/index.ts
packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
packages/vitest/src/node/reporters/dot.ts
packages/vitest/src/node/reporters/renderers/listRenderer.ts

While looking into https://github.com/vitest-dev/vitest/issues/4869, I spotted a few odd import/export, so I cleaned up them separately in this PR. I suppose these are unintended artifacts when copy-pasting some code.

refactor: minor cleanup of list/table renderer exports

---

packages/vitest/src/node/error.ts
packages/vitest/src/node/pools/rpc.ts
packages/vitest/src/runtime/child.ts
packages/vitest/src/runtime/execute.ts
packages/vitest/src/runtime/vm.ts
packages/vitest/src/runtime/worker.ts
packages/vitest/src/types/rpc.ts

fix(vitest): gracefully exit Vitest if `process.exit` is called inside the test

---

docs/config/index.md
packages/vitest/src/node/workspace.ts
packages/vitest/src/types/config.ts
test/config/test/config-types.test-d.ts
test/workspaces/space-pools/forks.test.ts
test/workspaces/space-pools/isolate.test.ts
test/workspaces/space-pools/multi-worker.test.ts
test/workspaces/space-pools/no-isolate.test.ts
test/workspaces/space-pools/single-worker.test.ts
test/workspaces/space-pools/threads.test.ts
test/workspaces/vitest.workspace.ts

- Fixes https://github.com/vitest-dev/vitest/issues/4731
Adds support for specifying following options in workspace projects configurations:
- `pool`
- `poolOptions.threads.isolate`
- `poolOptions.threads.singleThread`
- `poolOptions.vmThreads.isolate`
- `poolOptions.forks.isolate`
- `poolOptions.forks.singleFork`
Example:
```ts
import { defineWorkspace } from 'vitest/config'
export default defineWorkspace([
{
// Tests with side effects - require isolation
test: {
name: 'DOM tests',
include: ['./src/web/**'],
},
},
{
// Tests that don't have side effects - can be run without isolation
test: {
name: 'Side-effect free unit tests',
include: ['./src/utils/**'],
poolOptions: { 
threads: {
singleThread:  true,
isolate: false
}
},
},
},
{
// Tests that require forks pool for compatibility …
```

fix(workspace): support overring `pool` and `poolOptions` on project level

---

packages/utils/src/error.ts
packages/vitest/src/runtime/execute.ts
packages/vitest/src/runtime/mocker.ts

fix(vitest): throw "cannot mock" error only in isolated pools

---

packages/vitest/src/node/hoistMocks.ts
test/core/test/hoisted-async-simple.test.ts

fix(vitest): don't throw SyntaxError when "await vi.hoisted" is used

---

packages/vitest/src/node/error.ts
packages/vitest/src/node/hoistMocks.ts
packages/vitest/src/node/pools/rpc.ts
pnpm-lock.yaml
test/core/package.json
test/core/test/__snapshots__/injector-mock.test.ts.snap
test/core/test/injector-mock.test.ts

fix(vitest): show correct error when vi.hoisted is used inside vi.mock and the other way around

---

docs/guide/workspace.md

*if you have a folder with your projects named `packages`* is easy to confuse with the actual package name being "packages". 
Even though it's not impossible to understand with some thinking, we can make it clearer with this commit.
No testing required, this is just a docs commit.
- ~[ ] Run the tests with `pnpm test:ci`.~

docs: make definition clearer in workspace guide

---

docs/api/expect.md

`negotiation` should be `negation`, as the example demonstrates `not.toSatisfy()`
small copy change in the `expect().toSatisfy` documentation
on an example showing it's use with `not`, "negation" was typod as "negotiation"

docs(expect api): fix typo of negation in toSatisfy example

---

packages/utils/src/display.ts
test/config/fixtures/chai-config/test-each-title.test.ts
test/config/fixtures/chai-config/vitest.config.ts
test/config/test/chai-config.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/3955
Currently `objDisplay` from `@vitest/utils` with `truncate` option are only used for test title formatting. So the effect of this change would be minimal and probably only breaking file snapshot back to what it was before.
One more note, there is another usage of `objDisplay` but I think this one is calling into chai utils, so this change doesn't affect here:
https://github.com/vitest-dev/vitest/blob/926e633c9f61a57d70441438e37da6988cfcbf08/packages/expect/src/jest-expect.ts#L344

fix(utils): fix `objDisplay` default truncate option for `test.each` title

---

packages/vite-node/src/server.ts
packages/vitest/src/config.ts
packages/vitest/src/constants.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/plugins/index.ts
test/config/test/resolution.test.ts

Fixes #4785
This fixes the first case when changing code in dependencies with `node` environment did not trigger an HMR update.

fix(vitest): add inlined deps to ssr.noExternal so they are added to the module graph

---

packages/vitest/src/node/reporters/verbose.ts
test/reporters/fixtures/duration/basic.test.ts
test/reporters/fixtures/duration/vitest.config.ts
test/reporters/tests/verbose.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/4900
This will make the output similar to non-CI reporters which use list renderer:
https://github.com/vitest-dev/vitest/blob/883d17ed9a5c32fd1d1eb55ae89a91aaec2c19b5/packages/vitest/src/node/reporters/renderers/listRenderer.ts#L116-L119
Regarding the documentation, currently https://vitest.dev/guide/reporters.html doesn't mention anything about CI mode and the example output https://vitest.dev/guide/reporters.html#verbose-reporter shows non-CI mode output. So, probably documentation change is not necessary.

feat(vitest): show slow test duration in verbose reporter on CI

---

packages/vitest/src/node/hoistMocks.ts
test/core/test/injector-mock.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/4941
I loosened regex to match `(vi|vitest).(mock|unmock|hoisted)` anywhere in the code (not necessary assignment nor beginning of line).
Btw, it looks like currently tests are failing locally when color is enabled probably because of code frame offset not taking account highlight:
https://github.com/vitest-dev/vitest/blob/0b28f30153bce95e26cd343ad7a6a6f0c22518a2/packages/vitest/src/node/hoistMocks.ts#L259
So, for now I verified it by running with `NO_COLOR=1`.
(I tried to reproduced it but it doesn't look like highlight is enabled in user's tests https://stackblitz.com/edit/vitest-dev-vitest-nanulr?file=test%2Frepro.test.ts)

fix(vitest): handle single `await vi.hoisted`

---

docs/guide/index.md

I'm new to Vite, vitest, and JS in general.
Because I had to follow multiple tutorials, my test name was wrong, and it took me multiple hours to realize.
Coming from multiple other programing languages that works differently, and even having written some small test runners, I expected the include regex to look inside the file rather than only the file name.
I think this small tip in documentation can help neophytes to avoid that basic mistake that they can encounter for multiple reasons.
- [-] It's really useful if your PR references an issue where it is discussed ahead of time. If the feature is substantial or introduces breaking changes without a discussion, PR might be closed.
Only discution to be had is the format of the tip. I think this can be done in the PR directly as it is very …

docs(getting started): Add default test name tip 

---

packages/coverage-istanbul/package.json
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml
test/coverage-test/coverage-report-tests/generic.report.test.ts
test/coverage-test/package.json
test/coverage-test/vitest.config.ts

- Fixes https://github.com/vitest-dev/vitest/issues/4695
- Ref. https://github.com/unjs/magicast/pull/98
Extends configuration file resolving to support files that use arrow functions, e.g.:
```ts
export default defineConfig((config) => ({
test: {
coverage: {
thresholds: {
autoUpdate: true,
lines: 50,
branches: 1,
},
},
},
}));
```
There are still many cases that are not detected, as static analysis is never perfect. We can extend the support to new formats if similar bug reports come up in future.

fix(coverage): `thresholds.autoUpdate` to work with arrow function configuration files

---

packages/vitest/src/integrations/browser/server.ts
packages/vitest/src/node/workspace.ts
test/workspaces-browser/globalTest.ts
test/workspaces-browser/space_browser_inline/test-alias-to.ts
test/workspaces-browser/space_browser_inline/test/basic.test.ts
test/workspaces-browser/vitest.workspace.ts

Closes https://github.com/vitest-dev/vitest/issues/4744
For non browser project, inlined workspace project config is included into vite server config via spreading during `initializeProject`:
https://github.com/vitest-dev/vitest/blob/c9824cb3890f82e482245c5d2709dc6c6671e28c/packages/vitest/src/node/workspace.ts#L42-L53
However, browser mode's additional vite server instantiation was missing such logic, which leads to an issue when users relies on root workspace config without dedicated vite/vitest config file for the browser test project.
~In this PR, I copied over only `test: ...`, but maybe it should spread everything like `initializeProject` does above since otherwise it would still miss inlined base vite config.~ (EDIT: I did so in …

fix(browser): apply inlined workspace config to browser mode vite server

---

packages/vitest/src/node/hoistMocks.ts

- Follow up https://github.com/vitest-dev/vitest/pull/4962
Since the regex change introduced in the above PR, certain source code with a huge inline source map leads to freeze main vitest process for expensive `regexpHoistable.test(code)` quite a long time. (See comment in https://github.com/vitest-dev/vitest/pull/4855#issuecomment-1893168179)
I'm not really familiar with estimating regex perf, but the arbitrary whitespace prefix `[ \t]*` seems to be bad and it's probably redundant since `\b` already asserts word boundary.
To reproduce this, build vitest itself with `pnpm dev` (which adds inline sourcemap), then run:
```sh
pnpm -C test/browser test-fixtures run
(... it gets stuck for a while since expensive regex test takes over main thread. waiting for a while to see...) …
```

fix(vitest): simplify hoist transform check regex to avoid expensive regex match

---

packages/vite-node/src/server.ts
packages/vitest/src/node/core.ts

fix(vitest): correctly find module if it has a version query

---

examples/playwright/package.json
packages/browser/package.json
pnpm-lock.yaml
test/ui/package.json

Currently there are multiple playwright versions installed and it might be causing playwright installation issue (cache issue?) on CI (e.g. in https://github.com/vitest-dev/vitest/pull/4985):
https://github.com/vitest-dev/vitest/blob/39814357024e96b81546ec22d6aaf777b8db6cef/pnpm-lock.yaml#L21816-L21834
I thought renovate is supposed to take care of this, but for now I just ran this locally and will check CI:
```sh
pnpm update -r --latest playwright playwright-core @playwright/test
```
(CI failed but it looks like normal macos flakiness...)

chore(deps): update playwright

---

packages/vitest/src/node/pool.ts
pnpm-lock.yaml
pnpm-workspace.yaml
test/config/fixtures/conditions-pkg/index.js
test/config/fixtures/conditions-pkg/package.json
test/config/fixtures/conditions-subpackage/custom.js
test/config/fixtures/conditions-subpackage/default.js
test/config/fixtures/conditions-subpackage/development.js
test/config/fixtures/conditions-subpackage/package.json
test/config/fixtures/conditions-subpackage/production.js
test/config/fixtures/conditions-test/conditions.test.js
test/config/fixtures/conditions-test/vitest.config.ts
test/config/test/conditions-cli.test.ts
test/test-utils/index.ts

fix(vitest): use development/production conditions when resolving external modules

---

packages/vitest/src/integrations/mock/timers.ts
packages/vitest/src/utils/base.ts
test/browser/specs/runner.test.mjs
test/browser/test/timers.test.ts

fix(browser): don't fail when calling vi.useFakeTimers

---

packages/vitest/package.json
packages/vitest/src/node/hoistMocks.ts
pnpm-lock.yaml
test/core/test/__snapshots__/injector-mock.test.ts.snap
test/core/test/injector-mock.test.ts

Related: https://github.com/vitest-dev/vitest/issues/4872#issuecomment-1891793233

fix(vitest): throw a syntax error if vi.hoisted is directly exported

---

test/watch/test/stdin.test.ts

This test keeps failing locally. 
https://github.com/vitest-dev/vitest/blob/6421c2766c364a9dd37dabac432f792ff1ecc556/packages/vitest/src/node/watch-filter.ts#L106
Likely related to https://github.com/vitest-dev/vitest/pull/4733/files#diff-0f89ba66a3f72adafc990980fd1ac9deadff8da24502087c72ef11545fdcd08bR106.

test: fix `stdin.test.ts` pattern

---

package.json
packages/vite-node/src/client.ts
packages/vitest/package.json
packages/vitest/src/runtime/external-executor.ts
packages/vitest/src/runtime/vm/commonjs-executor.ts
packages/vitest/src/runtime/vm/esm-executor.ts
pnpm-lock.yaml
test/core/test/file-path.test.ts

fix(vite-node): provide import.meta.filename and dirname

---

packages/coverage-v8/src/provider.ts
test/coverage-test/coverage-report-tests/generic.report.test.ts

- Fixes bug where `coverage/.tmp` directory is left on file system after test run
- The `fs.rm` was accidentally inside `coverage.thresholds` check's if-block
- This is only on V8 provider. Istanbul provider does not have this issue
- Bug introduced in https://github.com/vitest-dev/vitest/pull/4603

fix(coverage): remove `coverage/.tmp` files after run

---

packages/vitest/src/node/core.ts
test/changed/fixtures/related/deep-related-exports.test.ts
test/changed/fixtures/related/deep-related-imports.test.ts
test/changed/fixtures/related/src/sourceC.ts
test/changed/fixtures/related/src/sourceD.ts
test/changed/tests/related.test.ts

`--changed` flag is not correctly looking up deep dependencies, as such the changed flag does not trigger specs if a sub dependency is changed.
Alters the logic to add the collected dependency after recursive `addImports` is called, otherwise the logic returns early because that dependency has already been added to the collected deps set. So it will not look deeply.
Resolves #4933 
(Also Resolves https://github.com/vitest-dev/vitest/issues/5009)

fix(vitest): test deep dependencies change detection

---

docs/guide/testing-types.md
docs/guide/workspace.md
examples/README.md
examples/typecheck/README.md
examples/typecheck/package.json
examples/typecheck/test/normal.test.ts
examples/typecheck/test/type.test-d.ts
examples/typecheck/tsconfig.json
examples/typecheck/vite.config.ts
examples/workspace/README.md
examples/workspace/package.json
examples/workspace/packages/lib1/package.json
examples/workspace/packages/lib1/test/double.test.ts
examples/workspace/packages/lib1/tsconfig.json
examples/workspace/packages/lib1/vite.config.ts
examples/workspace/packages/lib2/package.json
examples/workspace/packages/lib2/test/square.test.ts
examples/workspace/packages/lib2/tsconfig.json
examples/workspace/packages/lib2/vite.config.ts
examples/workspace/tsconfig.json
examples/workspace/vitest.workspace.ts
pnpm-lock.yaml

I'm not sure if these examples are worth inclusion in the official list, but I thought having this somewhere would be convenient to quickly spawn reproduction on stackblitz for issue authors and also for maintainers.
- https://stackblitz.com/github/hi-ogawa/vitest/tree/chore-repro-templates/examples/workspace
- https://stackblitz.com/github/hi-ogawa/vitest/tree/chore-repro-templates/examples/typecheck
_todo_

chore: add typecheck and workspace examples

---

packages/vite-node/src/source-map-handler.ts
packages/vitest/src/node/hoistMocks.ts
test/core/test/__snapshots__/injector-mock.test.ts.snap
test/core/test/injector-mock.test.ts

fix(vitest): throw an error if vi.mock is exported

---

packages/vitest/src/integrations/mock/timers.ts
test/core/test/fixtures/timers.suite.ts

- closes https://github.com/vitest-dev/vitest/issues/5027
It seems `@sinonjs/fake-timers` (inconsistently) supports faking certain timer API even when not globally available. Strict filtering for `toFake` is added in https://github.com/vitest-dev/vitest/pull/4992 for browser tests, but it looks like only `setImmediate` and `clearImmediate` have odd behavior (probably https://github.com/sinonjs/fake-timers/issues/277) and faking `requestIdleCallback` was still possible on NodeJs where it's not available natively. I found either `jsdom` or `happy-dom` exposes this, so I think it's reasonable to allow faking `requestIdleCallback` for non-browser mode testing.
I couldn't see a strong reason for filtering out except `setImmediate/clearImmediate` on Vitest side. Please let me know if I miss …

fix(vitest): allow `useFakeTimers` to fake `requestIdleCallback` on non browser

---

packages/expect/src/jest-expect.ts
test/core/test/__snapshots__/jest-expect.test.ts.snap
test/core/test/jest-expect.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/4093
- Follow up https://github.com/vitest-dev/vitest/pull/4942
Tiny improvement for rather minor use case, but I wanted to finish off that issue.
Jest example is in the same repro as the last PR:
- https://stackblitz.com/edit/github-o6sfsk?file=tests%2Fjest.test.cjs
```
Message:
expect(received).toThrow(expected)
Expected asymmetric matcher: StringNotContaining "ll"
Thrown value: "hello"
Difference:
Compared values have no visual difference.Error:
67 |
68 | test("throw error 4", () => {
> 69 |   expect(() => { throw "hello" }).toThrow(expect.not.stringContaining("ll"))
|                                   ^
70 | })
```

fix(expect): improve `toThrow(asymmetricMatcher)` failure message

---

packages/vitest/src/runtime/external-executor.ts

- https://github.com/vitest-dev/vitest/pull/5011#discussion_r1466552730
`import.meta.resolve` can be asynchronous in older Node versions like my `18.17.1`:
- https://github.com/nodejs/node/pull/43363
- https://github.com/nodejs/node/pull/43526

fix(vitest): support older NodeJS with async `import.meta.resolve`

---

packages/vitest/src/node/pools/typecheck.ts
test/typescript/fixtures/source-error/src/not-ok.ts
test/typescript/fixtures/source-error/test/ok.test-d.ts
test/typescript/fixtures/source-error/tsconfig.json
test/typescript/fixtures/source-error/vite.config.ts
test/typescript/test/runner.test.ts
test/typescript/tsconfig.json

- Closes https://github.com/vitest-dev/vitest/issues/4981
When surfacing `tsc`'s non zero exit code, it wasn't considering source errors. This is especially the case for run mode, since `tsc`'s exit code exists for this case.

fix(typecheck): fix `ignoreSourceErrors` in run mode

---

packages/vitest/src/runtime/mocker.ts

Looks like the current condition is not sufficient enough and it catches a lot of false positives. Let's disable it for now until we find a better way to handle it.
Related #4894
Fixes #4970

fix(vitest): don't throw an error if mocked file was already imported

---

packages/vitest/src/node/core.ts

- Fixes https://github.com/vitest-dev/vitest/issues/4943
Before and after videos below. Reading of coverage results from `coverage/.tmp` is intentionally delayed here so that a single read takes 1s. Test re-run is triggered with enter-key during file reading:
<details>
<summary>Before</summary/>
https://github.com/vitest-dev/vitest/assets/14806298/d0928ddd-95e0-463b-948f-524cdf3a179e
</details>
<details>
<summary>After</summary/>
https://github.com/vitest-dev/vitest/assets/14806298/d6a9b2c6-bf05-408c-833b-18d730950ebb
</details>

fix(coverage): don't crash when re-run removes earlier run's reports

---

packages/vitest/src/runtime/runVmTests.ts
test/stacktraces/test/__snapshots__/runner.test.ts.snap
test/stacktraces/test/runner.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5058
It seems `installSourcemapsSupport` is dropped from vm during the refactoring done in https://github.com/vitest-dev/vitest/pull/4441 so I added back in `runVmTests.ts`. 
For non-vm pool, this happens in `setupGlobalEnv`. The code looks very similar, so it might be possible to refactor around here, but I didn't touch unnecessary code.
https://github.com/vitest-dev/vitest/blob/89d5315d65c5ddd2a797bb959b71ea2750d58ce0/packages/vitest/src/runtime/setup-node.ts#L54-L56

fix: fix sourcemap in vm pools

---

packages/vitest/src/typecheck/collect.ts
test/typescript/test-d/nested-suite1.test-d.ts
test/typescript/test-d/nested-suite2.test-d.ts

- closes https://github.com/vitest-dev/vitest/issues/5021
- closes https://github.com/vitest-dev/vitest/issues/4964
Since `suite` is `const`, while-loop's body `lastSuite = suite.suite` doesn't change when `suite` is twice deep.

fix(typecheck): fix suite collection while-loop

---

packages/vitest/src/runtime/workers/vm.ts
test/config/test/console.test.ts

While investigating vm's sourcemap yesterday https://github.com/vitest-dev/vitest/pull/5063, I noticed `--disable-console-intercept` isn't working. I think there's no reason to not allow using global console in vm too?

fix(vm): handle `disableConsoleIntercept` config

---

packages/vitest/src/node/reporters/index.ts
packages/vitest/src/node/reporters/json.ts
test/reporters/fixtures/json-fail-import.test.ts
test/reporters/tests/html.test.ts
test/reporters/tests/json.test.ts

fix(vitest): correctly report failed test files as failures in json reporter, export json reporter types

---

docs/guide/mocking.md

Mocking guide already shows off example with `originalModule` inside of `vi.mock` so use the same pattern for the second example.
- make code examples with `vi.mock` consistent
- add types for imported modules to the examples

docs: use same pattern in examples

---

packages/browser/src/node/esmInjector.ts
packages/browser/src/node/index.ts
packages/utils/src/display.ts
pnpm-lock.yaml
test/browser/package.json
test/browser/specs/run-vitest.mjs
test/browser/specs/runner.test.mjs
test/browser/test/polyfill-lib.test.ts
test/browser/test/utils.test.ts
test/core/test/injector-esm.test.ts

Fixes #4535
Fixes #4892
Possibly fixes #5046

fix(browser): don't exclude node builtins from optimization

---

packages/browser/src/node/index.ts

- Fixes https://github.com/vitest-dev/vitest/issues/5013

fix(browser): support `coverage.reportsDirectory` with multiple directories

---

packages/ui/package.json
packages/vitest/package.json
packages/vitest/src/api/setup.ts
packages/vitest/src/node/pools/forks.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vmForks.ts
packages/vitest/src/node/pools/vmThreads.ts
packages/vitest/src/runtime/rpc.ts
packages/ws-client/package.json
packages/ws-client/src/index.ts
pnpm-lock.yaml

- Ref. https://github.com/antfu/birpc/pull/13
Improves error messages caused by `birpc` timeouts. Currently it can be difficult to track down a `birpc` timeout error as those are used in multiple modules. This PR extends the error message to include the caller in Vitest's context. The test runner's RPC also adds arguments of some known functions.

fix: rpc timeout error messages to include caller

---

docs/config/index.md

I spotted a few places still mentioning old `--threads` flag. I think the way `--threads=false` used previously has a different meaning now, so I tried to adjust it according to the usage.

docs: replace old `--threads` flag references

---

docs/guide/reporters.md
packages/ui/node/reporter.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/reporters/index.ts
packages/vitest/src/node/reporters/json.ts
packages/vitest/src/node/reporters/junit.ts
packages/vitest/src/node/reporters/utils.ts
packages/vitest/src/types/config.ts
test/reporters/src/custom-reporter.ts
test/reporters/tests/configuration-options.test-d.ts
test/reporters/tests/custom-reporter.spec.ts
test/reporters/tests/junit.test.ts
test/reporters/tests/reporters.spec.ts
test/reporters/tests/utils.test.ts
test/reporters/vitest.config.ts

- Closes https://github.com/vitest-dev/vitest/issues/5042
- Tested custom reporter with options: https://github.com/AriPerkkio/vitest-sonar-reporter/pull/154
There are now multiple different ways how to define reporters in configuration. This is similar shape as `coverage.reporters` has.
```ts
// A single reporter by name
{ reporters: "junit" },
// Inline reporter
{ reporters: { onFinished() { method(); } } },
// A single reporter with options - new option style 
{ reporters: [["junit", { classname: "some-junit-thing", outputFile: "report.xml" }]] },
// Multiple reporters - can combine any of the above
{ 
reporters: [
"verbose",
["json"],
["junit", { classname: "some-junit-thing" } ],
{ onFinished() { method(); } },
"vitest-github-actions-reporter", // Third party reporter by package name …
```

feat(reporters): support custom options

---

test/reporters/fixtures/duration/basic.test.ts
test/reporters/fixtures/duration/vitest.config.ts

On CI, it sometimes happens that the "fast" one (10 ms) is taking over `slowTestThreshold` (100 ms) possibly due to a heavy cpu load.
https://github.com/vitest-dev/vitest/actions/runs/7808613959/job/21299124920?pr=5093#step:8:811
I tweaked some numbers so that hopefully it will be less flaky.

test: fix flaky `slowTestThreshold` test

---

docs/api/index.md
packages/runner/src/context.ts
packages/runner/src/hooks.ts
packages/runner/src/index.ts
packages/runner/src/run.ts
packages/runner/src/types/tasks.ts
packages/vitest/src/index.ts
test/core/test/on-finished.test.ts

This PR adds a hook that can be called during the test execution to cleanup state:
```ts
import { onTestFinished, test } from 'vitest'
test('performs a query', () => {
const db = connectDb()
onTestFinished(() => db.close())
db.query('SELECT * FROM users')
})
```
We already had `onTestFailed` for some time now, but it was never documented so I added documentation for both.

feat(vitest): add onTestFinished hook

---

packages/vitest/src/runtime/execute.ts
packages/vitest/src/runtime/rpc.ts
packages/vitest/src/runtime/worker.ts

We don't reset the state anymore because it doesn't do anything (the state is on the global object, so resetting the reference makes no difference for gc). The same can be said for the environment.
I also noticed Vitest sometimes shows a warning that too many listeners are applied - I think we worked around it by silencing the error with `setMaxListeners` which should never be the solution 😄 
Closes #5071

fix(vitest): remove excessive listeners when running without isolation, don't reset the state

---

docs/config/index.md
packages/browser/src/client/client.ts
packages/browser/src/client/logger.ts
packages/browser/src/client/main.ts
packages/browser/src/client/public/esm-client-injector.js
packages/browser/src/client/rpc.ts
packages/browser/src/client/runner.ts
packages/browser/src/client/tester.html
packages/browser/src/client/tester.ts
packages/browser/src/client/unhandled.ts
packages/browser/src/client/utils.ts
packages/browser/src/client/vite.config.ts
packages/browser/src/node/esmInjector.ts
packages/browser/src/node/index.ts
packages/browser/src/node/providers/none.ts
packages/browser/src/node/providers/playwright.ts
packages/browser/src/node/providers/webdriver.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/api/types.ts
packages/vitest/src/node/pools/browser.ts
packages/vitest/src/node/state.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/types/browser.ts
packages/ws-client/src/index.ts
test/browser/specs/filter.test.mjs
test/browser/specs/run-vitest.mjs
test/browser/specs/runner.test.mjs
test/core/test/injector-esm.test.ts

This PR changes how Vitest runs browser tests internally. This is a successor to #3584, but without any visuals.

feat(browser): run test files in isolated iframes

---

docs/config/index.md
packages/vitest/src/integrations/env/jsdom.ts

feat(vitest): expose jsdom global if jsdom environment is enabled

---

docs/guide/reporters.md
packages/vitest/src/node/config.ts

- follow up https://github.com/vitest-dev/vitest/pull/5093
Based on the discussion on discord https://discord.com/channels/917386801235247114/1123254125191241868/1205400484530225214, this PR changes `github-actions` to be auto-enabled only when `reporters` are not explicitly provided by users.
Though I think it makes sense, this would potentially make it harder for this feature to reach some people. I still kinda want to see this feature to be enabled automatically for any condition on v1.3.0 and later consider tweaking conditions based on users feedback. So, if doing something is really necessary, then I might prefer introducing yet-another variable like  `VITEST_GITHUB_ACTIONS_REPORTER` 
https://github.com/vitest-dev/vitest/pull/5093#issuecomment-1935419295 to allow opting out. What do …

fix(vitest): auto-enable "github-actions" only where users didn't configure reporters

---

packages/vitest/src/node/cli/cli-config.ts
test/core/test/cli-test.test.ts

Follow up https://github.com/vitest-dev/vitest/pull/5126#discussion_r1484047483
I think there might be more array flags like `coverage.extension` and `coverage.reporter`, but I'm not sure if these were exposed previously. Do we want to make them as `array: true` too?

fix(vitest): support more array cli options

---

docs/config/index.md
packages/vitest/src/node/cli/cac.ts
packages/vitest/src/node/cli/cli-config.ts
test/core/test/cli-test.test.ts

This PR adds a few easy-to-justify options to the CLI:
- `--hookTimeout`
- `--teardownTimeout`
- `--slowTestThreshold`
- `--maxConcurrency`
- `--no-cache`
- `--cache.dir`

feat(vitest): add new CLI options

---

packages/ui/client/pages/index.vue

Saves the size of the splitpanes to the local storage for convenience when reloading between testing sessions

feat(ui): save splitpanes size to local storage

---

docs/config/index.md
packages/vitest/src/node/plugins/utils.ts

The optimizer is not stable enough at this point (some packages like `react` don't work with it and if all dependencies are not pre-bundled, there is a high chance users will get a "Cannot find module" error only in CI which is hard to debug). Since Vitest 1.3.0 focuses more on stability, we are disabling this option until we can figure out a good way to enable it without these hazards. If your tests are slower after this PR, you can always enable optimizer manually:
```ts
test: {
deps: {
optimizer: {
web: {
enabled: true,
},
ssr: {
enabled: true,
}
}
}
}
})
```

fix(vitest): disable optimizer by default until it's stable

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
test/coverage-test/option-tests/shard.test.ts
test/coverage-test/testing-options.mjs

- Related to https://github.com/vitest-dev/vitest/issues/5125 but does not close the issue completely

fix(coverage): `.tmp` directory conflicts with `--shard` option

---

packages/vitest/src/node/cli/cli-config.ts
test/core/test/cli-test.test.ts

- Fixes https://github.com/vitest-dev/vitest/pull/5126#issuecomment-1937005521

fix(cli): parse `--browser=<name>` correctly

---

docs/api/index.md
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
packages/runner/src/utils/chain.ts
packages/vitest/src/types/benchmark.ts
test/core/test/propagate-options-nested-suite.test.ts
test/core/test/repeats.test.ts
test/core/test/retry-only.test.ts
test/core/test/retry.test.ts
test/core/test/test-options.test.ts

feat(vitest): "test" accepts options object as the second parameter

---

docs/api/vi.md

The current doc misses its config param.

docs: add config param to `useFakeTimer`

---

packages/browser/package.json
packages/coverage-istanbul/package.json
packages/coverage-v8/package.json
packages/ui/package.json
packages/vitest/package.json
pnpm-lock.yaml

This PR makes `vitest` in `peerDependencies` as the fixed version. This enforces users to have a single version across the monorepo to have a stable and predictable behavior.
fix #4985 fix #4983

fix: requires fixed version across the monorepo

---

packages/vitest/src/node/workspace.ts
test/snapshots/test/fixtures/workspace/packages/space/test/__snapshots__/basic.test.ts.snap
test/snapshots/test/fixtures/workspace/packages/space/test/basic.test.ts
test/snapshots/test/fixtures/workspace/packages/space/vite.config.ts
test/snapshots/test/fixtures/workspace/vitest.workspace.ts
test/snapshots/test/workspace.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5194
Since `SnapshotManager` is a singleton managed by main `Vitest` instance, I think `WorkspaceProject.getSerializableConfig` needs to use the same options as:
https://github.com/vitest-dev/vitest/blob/ec55fddef66fe820c570f01b3e7be920a6d566d4/packages/vitest/src/node/core.ts#L101
I expect snapshot options to do something similar to coverage options, which is also root config only options:
https://github.com/vitest-dev/vitest/blob/ec55fddef66fe820c570f01b3e7be920a6d566d4/packages/vitest/src/node/workspace.ts#L332

fix(vitest): delegate snapshot options to workspace from root config

---

test/core/test/cli-test.test.ts

test: add test for --typecheck filter

---

packages/vitest/src/node/plugins/utils.ts
pnpm-lock.yaml
test/optimize-deps/dep-url/index.js
test/optimize-deps/dep-url/package.json
test/optimize-deps/package.json
test/optimize-deps/test/ssr.test.ts
test/optimize-deps/test/web.test.ts
test/optimize-deps/vitest.config.ts

- closes https://github.com/vitest-dev/vitest/issues/5211
- related https://github.com/vitejs/vite/pull/15184
_todo_

fix(vitest): fix `optimizeDeps.disabled` warnings on Vite 5.1

---

packages/vitest/src/node/plugins/index.ts
test/config/test/resolution.test.ts
test/run/pool-custom-fixtures/pool/custom-pool.ts
test/run/pool-custom-fixtures/vitest.config.ts
test/run/test/custom-pool.test.ts

Arrays in poolOptions are merged with themselves, resulting in duplicating the entries. This PR fixes that, by ensuring `poolOptions` is not present in the config being merged. Bug repro at https://github.com/penalosa/vitest-custom-pool-repro (just clone and run ./test.sh to see the contents of the array option being duplicated), 
See https://github.com/solidjs/vite-plugin-solid/pull/101 for a similar fix

fix: Prevent merging of `poolOptions`

---

docs/guide/test-context.md
packages/runner/src/fixture.ts
packages/runner/src/types/tasks.ts
test/core/test/fixture-options.test.ts

To close #4953, this PR adds the [automatic fixtures](https://playwright.dev/docs/test-fixtures#automatic-fixtures) feature, allowing users to explicitly initialize fixtures even they are not being used in tests.
Like Playwright, users can use the tuple syntax to pass options for each fixture through the second element. And Only if supported options (currently, only the `auto` option) are passed, we consider it as a fixture with options.
So below is an automatic fixture:
```ts
import { test as base } from 'vitest'
const test = base.extend({
fixture: [
async ({}, use) => {
// this function will run automatically
setup()
await use()
teardown()
},
{ auto: true } // Mark as an automatic fixture
],
})
test('', () => {})
``` 
And here are normal fixtures:
```ts
import { test as base, expect } …
```

feat(runner): support automatic fixtures

---

.github/workflows/publish.yml
.npmrc
scripts/publish-ci.ts

ci: update pnpm action-setup, install if after the node version is set

---

examples/lit/package.json
packages/browser/package.json
pnpm-lock.yaml
test/browser/package.json

- Related https://github.com/webdriverio/webdriverio/issues/12251
It seems like chrome download issue is fixed, but the issue is still open, so maybe other drivers got problems.
I guess we'll see how it goes on CI.

chore(deps): update webdriverio 8.32.2 to fix chrome download issue

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/utils/coverage.ts

Now that coverages packages don't have to maintain compatibility with previous `vitest` versions in same major (https://github.com/vitest-dev/vitest/pull/5208), we can move more reusable code into `vitest` package. This is only refactoring to reduce duplication.

refactor(coverage): move common parts to `vitest` package

---

packages/runner/src/utils/tasks.ts
packages/ui/client/composables/summary.ts

Closes #5234. The spread operator may result in an exceeded stack size limit for a very large number of tests.
See #5234, a very large number of tests results in an exceeded stack size limit due to the usage of the spread operator.

fix: add task tests iteratively

---

packages/ui/client/composables/client/index.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/api/types.ts
packages/vitest/src/node/core.ts
packages/vitest/src/types/reporter.ts
packages/ws-client/src/index.ts

- Closes https://github.com/vitest-dev/vitest/issues/5057
I tested a simple iframe reloading and tested by `pnpm -C examples/basic test:ui --coverage`:
<details><summary>Show demo</summary>
[스크린캐스트 2024-02-20 13-35-10.webm](https://github.com/vitest-dev/vitest/assets/4232207/d8574554-50f0-4e61-a021-b0c4f49ffa3c)
</details>
But actually I'm worrying that there might be some race condition here:
https://github.com/vitest-dev/vitest/blob/a479115913c6428dd28ed8339b9b80e7ce3ccc06/packages/vitest/src/node/core.ts#L529-L530
If `reportCoverage` takes significant time, then reloading iframe during `onFinished` might end up fetching old coverage html.
To avoid this race condition, it might be necessary to either:
- add new reporter hook (like `onReportCoverageFinished`) just for this, or
- move up …

fix(ui): auto reload coverage iframe after test run

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml
test/coverage-test/coverage-report-tests/__snapshots__/custom.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
test/coverage-test/coverage-report-tests/generic.report.test.ts
test/coverage-test/package.json
test/coverage-test/src/decorators.ts
test/coverage-test/test/coverage.test.ts
test/coverage-test/testing.mjs
test/coverage-test/tsconfig.json
test/coverage-test/vitest.config.ts

- Fixes https://github.com/vitest-dev/vitest/issues/5161
This is still quite experimental. `ts-jest` does similar hacks https://github.com/kulshekhar/ts-jest/pull/488.
Before on left, after on right:

fix(coverage): ignore generated TS decorators

---

docs/advanced/pool.md
docs/api/expect.md
docs/api/index.md
docs/api/mock.md
docs/api/vi.md
docs/config/index.md
docs/guide/browser.md
docs/guide/common-errors.md
docs/guide/coverage.md
docs/guide/features.md
docs/guide/ide.md
docs/guide/improving-performance.md
docs/guide/in-source.md
docs/guide/index.md
docs/guide/migration.md
docs/guide/mocking.md
docs/guide/reporters.md
docs/guide/snapshot.md

fix #5238
Fixed links that weren't working in documentation and badge error specified in the issue #5238
For example the link `vi.fn()` [here](https://vitest.dev/api/vi.html#vi-spyon) redirects to the main page, it is now fixed
I checked all links in documentation

docs: fix links and badges error

---

docs/guide/comparisons.md

This PR is addressing possible confusion about Web Test Runner by removing a paragraph from it's section.

docs: remove paragraph in Web Test Runner section

---

examples/nestjs/package.json
examples/nestjs/src/cats.controller.ts
examples/nestjs/src/cats.service.ts
examples/nestjs/test/nestjs.test.ts
examples/nestjs/tsconfig.json
examples/nestjs/vitest.config.ts
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml

- Fixes https://github.com/vitest-dev/vitest/issues/5252

fix(coverage): expensive regexp hangs v8 report generation

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml

We did this change in the Vite repo too. All other labels are "needs something".
After merging this PR, the label needs to be renamed.
We can also add `needs test` and `needs documentation` that are useful in the Vite repo at least.

chore: rename needs reproduction label

---

docs/api/expect.md
packages/expect/src/jest-expect.ts
test/core/test/__snapshots__/jest-expect.test.ts.snap
test/core/test/jest-expect.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5266
I went ahead and made a PR. Please let me know if I missed something or there's any concern about doing this.

fix(expect): show diff on `toContain/toMatch` assertion error

---

eslint.config.js

When I ran the lint command in the Vitest codebase, got the following result. The directory `.svelte-kit` was generated after runing `pnpm test:ci`, I thought it might be better to add it to eslint ignore list.

chore: add `.svelte-kit` to eslint ignores

---

test/browser/fixtures/server-url/vitest.config.ts
test/browser/specs/server-url.test.mjs

In #4855 https tests for browser module were introduced, but they were skipped due to self-signed certificate that basic-ssl-plugin produces. Browser automation tools usually provide a way to disable ssl protection and playwright and webdriverio are no exceptions (well, you'll see about that). I unskipped https test by configuring it via `providerOptions`
Playwright way: https://playwright.dev/docs/api/class-browser#browser-new-context-option-ignore-https-errors
WebdriverIO way: https://webdriver.io/docs/configuration/#strictssl and `acceptInsecureCerts` in `capabilities` https://webdriver.io/docs/api/browser/#properties

test(browser): unskipped https test for browser

---

packages/vitest/src/node/pools/forks.ts
packages/vitest/src/node/pools/vmForks.ts
packages/vitest/src/runtime/workers/forks.ts
packages/vitest/src/runtime/workers/utils.ts
packages/vitest/src/runtime/workers/vmForks.ts
packages/vitest/src/utils/config-helpers.ts
packages/vitest/src/workers.ts
test/core/test/define-ssr.test.ts
test/core/test/define-web.test.ts
test/core/vite.config.ts

- Fixes https://github.com/vitest-dev/vitest/issues/5273

fix(forks): wrap `defines` to support `undefined` values

---

packages/vitest/src/node/workspace.ts
test/config/fixtures/workspace/browser/workspace-with-browser.ts
test/config/test/failures.test.ts

This error is not thrown when browser mode is used with `@vitest/coverage-v8`. Browser tests start and show errors related `node:inspector` usage outside Node.
https://github.com/vitest-dev/vitest/blob/4ff7159049e4dd63501cdf512aea3366b55691cf/packages/vitest/src/node/config.ts#L142-L143
The reason is that resolved configuration is for root configuration, not the workspace configuration. Coverage options are in root config, browser config in workspace config. At this scope we don't have access to those both I think. 
```ts
// vitest.config.ts
test: {
coverage: {
enabled: true,
},
},
});
// vitest.workspace.ts
import { defineWorkspace } from "vitest/config";
export default defineWorkspace([
{
test: {
name: "Browser …
```

fix(workspace): throw error when browser mode and `@vitest/coverage-v8` are used

---

docs/api/expect.md

docs: fix some it's -> its

---

packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml
test/coverage-test/src/types.ts

- Fixes https://github.com/vitest-dev/vitest/issues/3605
- The existing test cases that validate `coverage.json` cover this feature. If the fix is removed, the new `types.ts` shows up in snapshot and it fails.

fix(coverage): v8 to ignore type-only files

---

packages/vitest/src/types/config.ts
test/web-worker/vitest.config.ts

- close https://github.com/vitest-dev/vitest/issues/5317
I think this is a minor paper cut and loosening it makes sense to allow something like:
```ts
onConsoleLog(type) {
return type !== 'stderr';
}
```
Currently users need to rewrite it into a following, which seems unnecessary restriction. Also it seems some eslint rule doesn't like this form.
```ts
onConsoleLog(type) {
if (type === 'stderr') {
return false;
}
}
```
I don't know about `void` vs `undefined`, so I kept `void` here.

fix(vitest): loosen `onConsoleLog` return type

---

packages/vitest/package.json
pnpm-lock.yaml

Closes https://github.com/vitest-dev/vitest/issues/5326
`get-tsconfig` is bundled dep, so I updated a version manually to get the fix.
Do you usually do this? or should I just wait for renovate to pick it up?
Test plan: I locally run the reproduction to confirm the fix.

fix(typecheck): update get-tsconfig 4.7.3 to fix false circularity error

---

packages/vitest/src/node/logger.ts
pnpm-lock.yaml
test/ws-api/fixtures/server-url/basic.test.ts
test/ws-api/fixtures/server-url/vitest.config.ts
test/ws-api/package.json
test/ws-api/tests/server-url.test.ts
test/ws-api/vitest.config.ts

Applied the fix with `resolvedUrls` for ws api logs and provided fallback url in case `resolvedUrls` is null.
This relates to https://github.com/vitest-dev/vscode/issues/226

fix(api): use resolvedUrls from devserver

---

docs/guide/cli.md
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/node/core.ts
test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
test/coverage-test/coverage-report-tests/changed.test.ts
test/coverage-test/coverage-report-tests/utils.ts
test/coverage-test/option-tests/changed.test.ts
test/coverage-test/src/file-to-change.ts
test/coverage-test/testing-options.mjs

- Fixes https://github.com/vitest-dev/vitest/issues/5237
I think I'll leave this part out of this PR now: https://github.com/vitest-dev/vitest/issues/5237#issuecomment-1962300345. That requires some discussion as it changes functionality of `--changed` quite much.

feat(coverage): support `--changed` option

---

docs/guide/cli.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/core.ts
packages/vitest/src/utils/base.ts
test/cli/fixtures/project/packages/project_1/base.test.ts
test/cli/fixtures/project/packages/project_2/base.test.ts
test/cli/fixtures/project/packages/space_1/base.test.ts
test/cli/fixtures/project/vitest.config.ts
test/cli/fixtures/project/vitest.workspace.ts
test/cli/test/project.test.ts

feat(cli): support wildcards in `--project` option

---

docs/config/index.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config.ts
packages/vitest/src/types/config.ts
test/config/test/shuffle-options.test.ts
test/core/test/cli-test.test.ts

- Add `shuffle.files` and `shuffle.tests` options, allowing users to shuffle tests while leveraging cache to run long-running tests earlier. 
- Closes #3568

feat(config): add `shuffle.files` and `shuffle.tests` options

---

packages/vitest/src/node/core.ts

- Closes https://github.com/vitest-dev/vitest/issues/5247
I couldn't identify the actual cause of cursor not getting back _only_ on typecheck run, so I went with using `logUpdate.done` to explicitly restore the cursor. There could be some deeper bug specific to typecheck run, but I couldn't see anything suspicious.
_additional notes_
- `log-update` is used only for reporters such as `dot` and `default` reporters on TTY, so the bug doesn't occur when using `--reporter=tap` for example.
- `log-update` internally uses [cli-cursor](https://github.com/sindresorhus/cli-cursor/blob/main/index.js), which in turn uses [restore-cursor](https://github.com/sindresorhus/restore-cursor/blob/main/index.js). Since we haven't used `logUpdate.done`, probably we're relying on `restore-cursor`'s automatic …

fix(vitest): ensure restoring terminal cursor on close

---

packages/vite-node/src/source-map.ts
packages/vitest/src/runtime/inspector.ts
packages/vitest/src/runtime/worker.ts
pnpm-lock.yaml
test/inspect/fixtures/math.test.ts
test/inspect/fixtures/vitest.config.ts
test/inspect/package.json
test/inspect/test/inspect.test.ts
test/inspect/vitest.config.ts
test/test-utils/index.ts

- Pauses code execution similarly as Node's `--inspect-brk` does
- Dev tools will stop on top of the first test file that is being run

fix: `--inspect-brk` to pause before execution

---

docs/config/index.md
packages/vitest/src/node/config.ts
test/config/test/failures.test.ts

Configuration below can remove user's whole project including local Git history from `.git`. One could accidentally use that when trying to generate coverage reports in the root of project instead of the default `./coverage`, and find out that their whole project is now wiped (that's me 🙃).
<details>
```ts
// Don't run this
test: {
coverage: {
reportsDirectory: './',
},
},
})
```
</details>

fix(coverage): prevent `reportsDirectory` from removing user's project

---

packages/browser/src/node/index.ts

- closes https://github.com/vitest-dev/vitest/issues/5263
Snapshot update works inside the repository `test/browser` but apparently it fails when installed. I still don't fully understand the intricacy of this difference, but adding `vitest > @vitest/snapshot > magic-string` seems to work.
I verified manually that this fix the issue by using `pnpm patch` in a reproduction:
https://github.com/hi-ogawa/reproductions/tree/main/vitest-5263-browser-snapshot
One thing I found is that, when running tests from `test/browser`, I see a few logs `vite:deps new dependencies found: ...` and there was previously `magic-string` in there, but it's now gone. There are a few more dependencies like that, so they might also cause some issues depending of usage?
<details><summary>Show logs with …

fix(browser): add `magic-string` to `optimizeDeps.include`

---

examples/playwright/test/basic.test.ts
packages/vitest/src/node/plugins/index.ts
test/config/test/resolution.test.ts

fix(vitest): correctly override api with --no-api flag

---

docs/config/index.md

- Related to #5337 
I noticed [`onConsoleLog`](https://vitest.dev/config/#onconsolelog) haven't been updated in the doc, thought it would be better to keep it updated.

docs: update `onConsoleLog` return type

---

docs/guide/snapshot.md

Fix rendering error:
Preview: https://deploy-preview-5403--fastidious-cascaron-4ded94.netlify.app/guide/snapshot.html#file-snapshots

docs: fix rendering error and typo

---

packages/runner/src/types/tasks.ts

fixes `describe` calls not taking generic type parameters which is a result of #5142.

fix: `describe` calls not taking generic type parameters

---

packages/vite-node/src/externalize.ts
pnpm-lock.yaml
test/vite-node/deps/dep1/esm/index.js
test/vite-node/deps/dep1/package.json
test/vite-node/deps/dep2/index.js
test/vite-node/deps/dep2/package.json
test/vite-node/package.json
test/vite-node/test/external.test.ts

- closes https://github.com/vitest-dev/vitest/issues/5404
As explained in https://github.com/vitest-dev/vitest/issues/5404#issuecomment-2014434251, current `shouldExternalize` and `isValidNodeImport` heuristics don't seem optimal.
By flipping the condition of `"type": "module"` check and `/esm?/.test(id)` (which is what `mlly` has been doing), I think this will save legitimate ESM from inlined due to the file name having `.../esm/...` like the case of `wagmi` https://publint.dev/wagmi@2.5.11.

fix(vite-node): fix `isValidNodeImport` to check `"type": "module"` first

---

packages/expect/src/jest-expect.ts
test/core/test/__snapshots__/jest-expect.test.ts.snap
test/core/test/jest-expect.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5417

fix(expect): fix `toHaveBeenNthCalledWith` error message when not called

---

packages/vitest/package.json
packages/vitest/src/runtime/workers/utils.ts
pnpm-lock.yaml
test/core/test/mocked-process.test.ts
test/coverage-test/test/coverage.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/5390
- Ref. https://github.com/tinylibs/tinypool/pull/83

fix: prevent hang when `process` is mocked

---

test/changed/tests/related.test.ts
test/changed/tests/workspaceRelated.test.ts
test/cli/test/exclude.test.ts
test/cli/test/project.test.ts
test/config/test/retry.test.ts
test/config/test/workspace.test.ts
test/reporters/package.json
test/reporters/tests/console.test.ts
test/reporters/tests/custom-reporter.spec.ts
test/reporters/tests/default.test.ts
test/reporters/tests/html.test.ts
test/reporters/tests/verbose.test.ts
test/reporters/vitest.config.ts
test/run/test/custom-pool.test.ts
test/test-utils/index.ts
test/ws-api/tests/server-url.test.ts

Attempts to fix flaky CI. Replaces usage of `runVitestCli()` with lighter `runVitest()` utility. This reduces the amount of `node:child_process` launched during tests (via `execa`). The `runVitestCli()` should only be used when tests require interactive watch mode or are explicitly testing CLI options.

test: use `startVitest` instead of `execa`

---

packages/vitest/src/node/error.ts
test/reporters/fixtures/code-frame-line-limit.test.ts
test/reporters/tests/code-frame-line-limit.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5431
ANSI-code length adds up a lot, so I think we should use un-highlighted code for this limit check.
For example, this simple line exceeds 200 chars when highlighted:
```ts
// without highlight: 76 chars
// with highlight: 236 chars
expect([{prop: 7}, {prop: 7}, {prop: 7}, {prop: 7}]).toBe([{another: 8} ])
```

fix(vitest): check unhighlighted code for code frame line limit

---

examples/playwright/test/basic.test.ts
test/reporters/tests/console.test.ts

- Related to https://github.com/vitest-dev/vitest/pull/5439

test: fix snapshot replacement

---

packages/expect/src/jest-expect.ts
test/core/test/jest-expect.test.ts

In earlier versions of vitest, the value received by toMatch supported numbers, like this:
```ts
expect(1).toMatch(/\d/)
```
After I updated to the latest version, the above test case throws the error `TypeError: actual.match is not a function`.
I think it would be more user-friendly to do type checking inside vitest and provide clearer error messages.

fix: the value received by toMatch should be a string

---

packages/vitest/src/node/workspace.ts
test/filters/test/testname-pattern.test.ts

Related: https://github.com/vitest-dev/vscode/issues/308
Fixes #5409

fix(vitest): correctly filter by parent folder

---

docs/config/index.md
docs/guide/coverage.md
package.json
packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
packages/vitest/src/defaults.ts
packages/vitest/src/types/coverage.ts
patches/v8-to-istanbul@9.2.0.patch
pnpm-lock.yaml
test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
test/coverage-test/coverage-report-tests/changed.test.ts
test/coverage-test/coverage-report-tests/empty-lines.test.ts
test/coverage-test/option-tests/empty-lines.test.ts
test/coverage-test/src/empty-lines.ts
test/coverage-test/src/untested-file.ts
test/coverage-test/testing-options.mjs

Adds new `coverage.ignoreEmptyLines` option that can be used to make `@vitest/coverage-v8` to ignore lines without runtime code.
- Fixes https://github.com/vitest-dev/vitest/issues/5423
- Applies patch from https://github.com/istanbuljs/v8-to-istanbul/pull/244 and bundles `v8-to-istanbul`

feat(coverage): v8 to ignore empty lines, comments, types

---

packages/vitest/src/node/reporters/base.ts
test/benchmark/fixtures/reporter/summary.bench.ts
test/benchmark/fixtures/reporter/vitest.config.ts
test/benchmark/test/__snapshots__/reporter.test.ts.snap
test/benchmark/test/reporter.test.ts

This fixes the summary output `NaNx faster than ...` mentioned in https://github.com/vitest-dev/vitest/issues/5475.
<details><summary>Show example</summary>
```sh
pnpm -C test/benchmark test bench -- --root fixtures/basic only
```
- before
- after
</details>

fix(benchmark): fix benchmark summary of single bench suite

---

docs/config/index.md
packages/utils/src/diff/diffLines.ts
packages/utils/src/diff/diffStrings.ts
packages/utils/src/diff/normalizeDiffOptions.ts
packages/utils/src/diff/printDiffs.ts
packages/utils/src/diff/types.ts
packages/vitest/src/types/matcher-utils.ts
test/core/test/diff.test.ts

* Closes #5073 
Add configuration options for users to truncate the diff result, enhancing not only testing performance but also improving the neatness of the output.
~TODO: add documentation~

feat: add configuration for diff truncation (#5073)

---

packages/vitest/src/node/reporters/benchmark/table/index.ts
packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
test/benchmark/fixtures/basic/base.bench.ts
test/benchmark/test/reporter.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5475
This PR implements "non incremental" table output for non TTY case by reusing benchmark `renderTree`.
The idea is similar to `verbose` test reporter, which uses `onTaskUpdate` and waits until status is ready `task.result?.state !== 'run'` then print a full result:
https://github.com/vitest-dev/vitest/blob/48f762a9865ba6c4d5bd34cab405ddc61a1c8ab6/packages/vitest/src/node/reporters/verbose.ts#L14-L20
<details><summary>Reveal screenshots</summary>
- tty
- no tty
</details>

fix(benchmark): table reporter for non TTY output

---

test/benchmark/fixtures/reporter/summary.bench.ts
test/benchmark/test/__snapshots__/reporter.test.ts.snap
test/benchmark/test/reporter.test.ts

- follow up to https://github.com/vitest-dev/vitest/pull/5489#discussion_r1554483994
The test added in the above PR had an assertion of `xxx faster than yyy`, but it looks quite unstable on CI.
- https://github.com/vitest-dev/vitest/actions/runs/8568796944/job/23483403713#step:9:322
- https://github.com/vitest-dev/vitest/actions/runs/8577751509/job/23511069656?pr=5311#step:10:341
- https://github.com/vitest-dev/vitest/actions/runs/8577739425/job/23511042842?pr=5484#step:9:316
I updated test case to hopefully fix the flakiness.

test: fix flaky benchmark summary

---

packages/runner/src/run.ts

This is not needed today but you will have to workaround an improved inference for type predicated in the upcoming TS 5.5. See the failure reported [here](https://github.com/microsoft/TypeScript/issues/58104#issuecomment-2041579302) and the discussion~ [here](https://github.com/microsoft/TypeScript/pull/57952#issuecomment-2023641553)

chore: provide explicit type param to one of the calls

---

packages/vitest/src/node/core.ts

Fixes incorrect checks that could incorrectly lead to a test rerun

chore: check for the presense of files in watch mode

---

docs/.vitepress/config.ts

~~Thou the account is not very active, I have good hope it’ll become better in the future since some Vue/Vitest core team members are active there. Maybe you can wait until you’re more active on Mastodon to merge it.~~
Just noticed the account is actually very active! 🥳 I guess I was confused by the pinned messages and did not properly scrolled down.
(Also if you need some convenience, a friend of mine created [oolatoocs](https://framagit.org/veretcle/oolatoocs), a Mastodon to Twitter bridge.)

Add Mastodon to “resources” in docs navigation

---

packages/vitest/src/runtime/inspector.ts
packages/vitest/src/runtime/runBaseTests.ts
packages/vitest/src/runtime/runVmTests.ts

fix(vitest): close inspector immediately if run is canceled

---

packages/runner/src/suite.ts

fix: increase stack trace limit for location, don't hardcode suite position

---

test/reporters/fixtures/function-as-name.bench.ts
test/reporters/package.json

These empty benchmarks are bad for CPU and memory (due to huge `samples` array), so I set the minimal bench options
```sh
$ pnpm -C test/reporters test function-as-name
...
✓ tests/function-as-name.test.ts (2) 17826ms
✓ should print function name 494ms
✓ should print function name in benchmark 17331ms
$ pnpm -C test/reporters test function-as-name
...
✓ tests/function-as-name.test.ts (2) 820ms
✓ should print function name 636ms
✓ should print function name in benchmark
```

test: faster bench fixture

---

packages/vitest/src/node/config.ts

- related to https://github.com/vitest-dev/vitest/issues/5382
It looks like `fileParallelism` becomes true by default since it's inherited in this way:
https://github.com/vitest-dev/vitest/blob/c44a15fb9027e4e9b78f2e6e2b506a83d2348762/packages/browser/src/client/main.ts#L99
I'm not sure how to test the fix. For now, I manually verified by putting `console.log` above and checking browser devtools.

fix(browser): disable `fileParallelism` by default on browser pool

---

.github/ISSUE_TEMPLATE/config.yml

Some people are reporting vscode extension bugs here, but we probably want them to open the issue downstream first, so they go through the checklist.
For the template, I copied what Vite does for react/vue plugins:
https://github.com/vitejs/vite/blob/84299f30a7244e6885e41531ffe5c4b54c8b0ed7/.github/ISSUE_TEMPLATE/config.yml#L3-L8
EDIT: Ah, I thought this issue https://github.com/vitest-dev/vitest/issues/5523 is about vscode extension, but it's actually about vscode debugger without extension. I guess it's still fine to have this link?

chore: add vscode extension to issue template links

---

patches/v8-to-istanbul@9.2.0.patch
pnpm-lock.yaml

- Fixes https://github.com/vitest-dev/vitest/issues/5532
Looks like Rollup doesn't transpile `require('fs').promises`. 
Changes in bundle:
```diff
-const compatError = Error(`requires Node.js ${require$$9.engines.node}`);
-const { readFileSync } = require$$10;
-let readFile = () => { throw compatError };
-try {
-  readFile = require('fs').promises.readFile;
-} catch (_err) {
-  // most likely we're on an older version of Node.js.
-}
+import require$$9 from 'fs';
...
+const { readFileSync, promises } = require$$9;
+const readFile = promises.readFile;
```

fix(coverage): fix bundling of `v8-to-istanbul`

---

packages/vitest/src/node/core.ts

I've been running into an issue where Vitest would hang after the testing is completed with the following output:
```
close timed out after 10000ms
Tests closed successfully but something prevents the main process from exiting
You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
```
Luckily, this repo has a reproducible setup at `test/cli/fixtures/project` -- in this directory, running `npx vitest run --project space_1` causes the error above (you may need to try multiple times, but I've been getting it consistently).
The only other report I've found is by this commenter https://github.com/vitest-dev/vitest/issues/2008#issuecomment-1933009750 (the issue itself seems to be about a different time out issue).
I've tracked this …

fix: close vite servers on all resolved projects

---

packages/vitest/src/node/workspace.ts
test/filters/fixtures-slash/test/basic-foo/a.test.ts
test/filters/fixtures-slash/test/basic.test.ts
test/filters/fixtures-slash/test/basic/a.test.ts
test/filters/fixtures-slash/test/foo-basic/a.test.ts
test/filters/fixtures-slash/vitest.config.ts
test/filters/package.json
test/filters/test/testname-pattern.test.ts

- closes https://github.com/vitest-dev/vitest/issues/5534
- follow up https://github.com/vitest-dev/vitest/pull/5408
With the current filter condition, it makes false positive in a following way
```ts
dir: /home/hiroshi/code/others/vitest/examples/basic
filter: /basic                             // looks like absolute path but users wish to use to match substring
relativePath = ../../../../../../../basic  // starts with '../..' so filter is true regardless of `testFile`
```
I'm not sure supporting a filter like `/basic` has been planned, but I OP's usage makes sense to me.

fix(vitest): fix false positive file filter match with leading slash

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/utils/coverage.ts
test/coverage-test/option-tests/thresholds.test.ts
test/coverage-test/testing-options.mjs

- Fixes https://github.com/vitest-dev/vitest/issues/5545
In following project:
```
<root>
|
├── package.json
├── vitest.config.ts
├── src
|  └── utils.ts
└── test
└── utils.test.ts
```
... users no longer need to define `**/src/utils.ts` in `coverage.thresholds[<glob>]`. A simple `src/utils.ts` works now.
```diff
test: {
coverage: {
thresholds: {
-       '**/src/utils.ts': {
+       'src/utils.ts': {
functions: 100,
},
},
},
},
});
```
Documentation is already using this pattern:
https://github.com/vitest-dev/vitest/blob/413ec5e6fc0addb2216db6104228138f8027f392/docs/config/index.md?plain=1#L1322-L1328

fix(coverage): `thresholds` to compare files relative to root

---

packages/vitest/src/node/core.ts
packages/vitest/src/node/workspace.ts
test/workspaces/cwdPlugin.d.ts
test/workspaces/cwdPlugin.js
test/workspaces/globalTest.ts
test/workspaces/space_1/test/env-injected.spec.ts
test/workspaces/space_1/vite.config.ts
test/workspaces/vitest.config.ts

Fixes https://github.com/vitest-dev/vscode/issues/359
Part of #5541
TODO

fix: resolve cwd correctly when initiating projects

---

packages/vitest/src/integrations/vi.ts
test/core/test/stubs.test.ts

fix(vitest): stubEnv casts boolean on PROD/SSR/DEV

---

packages/browser/src/client/main.ts

- closes https://github.com/vitest-dev/vitest/issues/5382
Currently iframes are not disposed and that seems to make browser mode get stuck.
We might not want to always dispose the iframe, for example, if users are expecting to view the actual browser render (cf. https://github.com/vitest-dev/vitest/issues/5568), but I think that can be implemented as a dedicated option (like `browser.retainWindow` or something) and disposing them by default for stability seems right.
_Test plan_
I tested a same patch on https://github.com/underoot/vitest-large-file-list-issue with 300 test files and it's working fine at least with `fileParallelism: false`:

fix(browser): dispose tester iframe on done

---

pnpm-lock.yaml
test/vite-node/deps/dep1/package.json
test/vite-node/deps/dep2/package.json

I simplified the test package used for https://github.com/vitest-dev/vitest/pull/5416 to just use `dependencies` instead of `peerDependencies`.
This should fix the mysterious `file:test/vite-node/deps/dep2(@vitest/test-dep1@undefined)` in a lock file.

chore: fix test fixture package

---

docs/api/index.md
docs/config/index.md
packages/runner/src/run.ts
pnpm-lock.yaml
test/core/test/on-finished.test.ts

fix: always run `onTestFinished` in reverse order

---

packages/vitest/src/node/plugins/workspace.ts
test/watch/test/workspaces.test.ts
test/workspaces/space_3/package.json
test/workspaces/space_3/vitest.config.ts

fix: use package.json name for a workspace project if not provided

---

docs/guide/mocking.md

Addresses #5631 
Problem:
The  [Cheat Sheet](https://vitest.dev/guide/mocking.html#cheat-sheet) section of the *Mocking* guide is hard to read. The section uses bullets (`- `) for each "topic" (item that the user wants to do), but these bullets show up as indented under normal paragraphs, e.g. "Examples", and thus seem to be sub-sections of the examples.
Changes:
1. Each "topic"  is a sub-heading 1 level under the  "Cheat Sheet" heading level. Examples and text are visually (and semantically) "under" the topic.
2. If there is more than 1 example for each topic, they are numbered. This makes them easy to refer to both within the documentation and during any discussion.
3. Moved *warning* sections up so they are more prominent; they are seen _before_ the code examples. (When they're after …

docs: Improve formatting and readability of the Mocking / Cheat Sheet section

---

packages/expect/src/jest-utils.ts
test/core/test/expect.test.ts

https://github.com/vitest-dev/vitest/issues/5620

fix: backport jest iterable equality within object

---

packages/vitest/src/runtime/external-executor.ts
packages/vitest/src/runtime/vm/esm-executor.ts
packages/vitest/src/runtime/vm/vite-executor.ts
test/cli/fixtures/network-imports/basic.test.ts
test/cli/test/network-imports.test.ts

fix(vm): support network imports

---

packages/runner/src/suite.ts
test/core/test/task-collector.test.ts

fix: keep order of arguments for .each in custom task collectors

---

docs/guide/migration.md

This PR aims to add a new small documentation chapter regarding the migration page [located here](https://vitest.dev/guide/migration.html#migrating-from-jest).
It will help future folks who will want to mock modules that are already mocked in their source code that they own but not mocked in external libraries that they use.
For instance, I encountered the case a couple of days ago here:
- https://github.com/vitest-dev/vitest/discussions/5589
The situation is more detailed in the above link.

docs: Updating migration guide file (jest -> vitest) for server.deps.inline property

---

packages/vite-node/src/server.ts
packages/vitest/src/integrations/env/loader.ts
packages/vitest/src/node/pools/rpc.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/runtime/execute.ts
packages/vitest/src/types/rpc.ts
packages/vitest/src/utils/base.ts
packages/web-worker/src/utils.ts
pnpm-lock.yaml

This PR makes forks pool 2 times faster on https://github.com/vuejs/core monorepo (using M1 Air):
Before:
```
threads:
Duration  16.17s (transform 5.28s, setup 740ms, collect 54.54s, tests 7.42s, environment 14.06s, prepare 13.76s)
forks:
Duration  28.68s (transform 6.17s, setup 1.30s, collect 138.67s, tests 5.53s, environment 11.92s, prepare 11.67s)
```
After:
```
threads:
Duration  16.29s (transform 6.79s, setup 1.81s, collect 55.58s, tests 6.79s, environment 12.41s, prepare 14.32s)
forks:
Duration  18.89s (transform 7.70s, setup 811ms, collect 65.05s, tests 7.40s, environment 14.14s, prepare 14.98s)
```

perf: improve performance of forks pool

---

packages/vitest/src/node/core.ts
test/cli/fixtures/create-vitest/basic.test.ts
test/cli/fixtures/create-vitest/vitest.config.ts
test/cli/fixtures/plugin/basic.test.ts
test/cli/fixtures/plugin/vitest.config.ts
test/cli/test/create-vitest.test.ts
test/cli/test/plugin.test.ts

- closes https://github.com/vitest-dev/vitest/issues/5616
`ctx.distPath` is only used by pool `runTests`, so we can move `resolveId` from `ctx.setServer` to `ctx.start`.
_todo_
- verified locally with `pnpm.overrides`

fix: call `resolveId('vitest')` after `buildStart`

---

packages/coverage-v8/src/provider.ts
test/coverage-test/coverage-report-tests/__snapshots__/istanbul.report.test.ts.snap
test/coverage-test/coverage-report-tests/__snapshots__/v8.report.test.ts.snap
test/coverage-test/src/load-outside-vite.cjs
test/coverage-test/test/coverage.test.ts

- Fixes #5639 
- This is an edge case that can happen if a file was loaded outside Vitest, e.g. using `require()`

fix(coverage): apply `vite-node`'s wrapper only to executed files

---

packages/vitest/src/runtime/runners/index.ts

- Small improvement to reduce rpc calls when we know they are unnecessary
Browser runner already does this:
https://github.com/vitest-dev/vitest/blob/bdce0a29db1b5a2766d583cef40277a2b3857659/packages/browser/src/client/runner.ts#L45-L56

perf: unnecessary rpc call when coverage is disabled

---

packages/vitest/src/node/reporters/junit.ts
test/reporters/fixtures/console-simple.test.ts
test/reporters/fixtures/ok.test.ts
test/reporters/tests/__snapshots__/junit.test.ts.snap
test/reporters/tests/junit.test.ts

- closes https://github.com/vitest-dev/vitest/issues/5657
- closes https://github.com/vitest-dev/vitest/issues/5648

feat(reporter): support `includeConsoleOutput` and `addFileAttribute` in junit

---

docs/config/index.md
packages/browser/src/client/runner.ts
packages/browser/src/client/snapshot.ts
packages/vitest/package.json
packages/vitest/rollup.config.js
packages/vitest/snapshot.d.ts
packages/vitest/src/index.ts
packages/vitest/src/integrations/snapshot/environments/node.ts
packages/vitest/src/integrations/snapshot/environments/resolveSnapshotEnvironment.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config.ts
packages/vitest/src/runtime/runBaseTests.ts
packages/vitest/src/runtime/runVmTests.ts
packages/vitest/src/runtime/setup-node.ts
packages/vitest/src/snapshot.ts
packages/vitest/src/types/config.ts
test/browser/custom-snapshot-env.ts
test/browser/vitest.config.mts
test/snapshots/test/custom-environment.test.ts
test/snapshots/test/fixtures/custom-snapshot-environment/snapshot-environment.ts
test/snapshots/test/fixtures/custom-snapshot-environment/test/snapshots.test.ts
test/snapshots/test/fixtures/custom-snapshot-environment/vitest.config.ts

feat: custom "snapshotEnvironment" option

---

docs/config/index.md
packages/browser/src/client/index.html
packages/browser/src/client/tester.html
packages/browser/src/node/index.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/index.ts
packages/vitest/src/types/browser.ts
packages/vitest/src/types/config.ts
pnpm-lock.yaml
test/browser/injected-lib/index.js
test/browser/injected-lib/package.json
test/browser/injected.ts
test/browser/package.json
test/browser/specs/runner.test.ts
test/browser/test/injected.test.ts
test/browser/vitest.config.mts

This PR adds an option to inject custom scripts via `browser.testerScripts` and `browser.indexScripts` options.
Closes #5347
TODO:

feat(browser): allow injecting scripts

---

packages/utils/src/error.ts
test/core/test/error.test.ts
test/core/test/jest-expect.test.ts

This Pull Request adds support for diffs coming nested errors. In the context of Error with cause, if the cause is an Error coming with a diff, the current version of Vitest does not render it in a diff fashion. It tends to make understanding such nested errors complex. The proposal implemented by this PR is to display the diff attached to causes.
Let's consider the following snippet:
```js
import { test, expect } from "vitest";
const value1 = { a: 1, b: 2, c: 3, e: 4, f: 5, g: 6, h: 7, i: 8, j: 9, k: 10 };
const value2 = { a: 1, b: 2, c: 3, e: 4, f: 5, g: 6, h: 7, i: 88, j: 9, k: 10 };
test("rethrown expect as cause", () => {
try {
expect(value1).toEqual(value2);
} catch (err) {
throw new Error("failed!", { cause: err });
}
});
```
| Before | After |
|----|---|
| …

feat: pretty print diffs coming from cause

---

packages/vitest/src/runtime/console.ts
packages/vitest/src/runtime/workers/vm.ts
test/cli/test/setup-files.test.ts

The console was failing due to incorrect access to the worker state, but it didn't print anything because it was overriden.

fix: print console statements in vmThreads

---

packages/vitest/src/node/reporters/json.ts
pnpm-lock.yaml
test/reporters/src/context.ts
test/reporters/src/data.ts
test/reporters/tests/__snapshots__/json.test.ts.snap
test/reporters/tests/__snapshots__/reporters.spec.ts.snap
test/reporters/tests/json.test.ts
test/test-utils/package.json

JSON reporter incorrectly gets the location from the test error. Vitest 1.4.0 introduced `--includeTaskLocation` flag and we can now reliably take it from there (which actually follows jest behaviour).
This PR adds a missing `snapshot` property to the root of the json reporter.
The `failureMessages` now includes the full stack trace.
Related: https://github.com/vitest-dev/vitest/discussions/5350
Follow-up #5435

fix!: add correct location and snapshot fields in json reporter

---

.github/workflows/ci.yml
package.json
packages/vitest/src/runtime/external-executor.ts
packages/vitest/src/runtime/vm/esm-executor.ts
packages/vitest/src/runtime/vm/file-map.ts
pnpm-lock.yaml
test/core/vite.config.ts
test/reporters/fixtures/console.test.ts
test/reporters/tests/console.test.ts

ci: run tests sequentially 

---

docs/config/index.md
packages/vitest/src/defaults.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/types/config.ts

PR to remove `watchExclude`, in favor of `server.watch.ignored`. The option should be first deprecated by https://github.com/vitest-dev/vitest/pull/5171. And this PR can be merged in the next major.

feat!: remove watchExclude

---

.pnpmfile.cjs
package.json
pnpm-lock.yaml

It prints the cyclic dependency message now, but it should be fine as long as the build actually works: https://github.com/pnpm/pnpm/issues/5568#issuecomment-1297843071
Thank you @hi-ogawa for https://github.com/vitest-dev/vitest/pull/5499#issuecomment-2050994092

chore: update pnpm to the latest 8 version

---

docs/config/index.md
docs/guide/common-errors.md
docs/guide/improving-performance.md
packages/vitest/src/defaults.ts
test/browser/vitest.config.unit.mts
test/config/test/chai-config.test.ts
test/config/test/failures.test.ts
test/watch/vitest.config.ts

Switches defaut `pool` option from `'threads'` to `'forks'`. Adds new documentation pages describing common errors with `pool: 'threads'`: segfaults and process hangs.
- Closes https://github.com/vitest-dev/vitest/issues/2008
- Closes https://github.com/vitest-dev/vitest/issues/3077
- Closes https://github.com/vitest-dev/vitest/issues/4956
Main goal is to provide stability over _small performance boosts_.
The `pool: 'threads'` runs code in `node:worker_threads`, `pool: 'forks'` runs code in `node:child_process`. While threads may be slightly faster than forks, it has been causing bugs that are very difficult to debug. Typically these errors are coming when users' test code contains native node module (e.g. Node packages that utilize C++, Go, Rust via …

fix!: change default `pool` to `'forks'`

---

packages/ui/node/reporter.ts
packages/vitest/src/index.ts
packages/vitest/src/node/cli/cac.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/index.ts
packages/vitest/src/node/reporters/html.ts
packages/vitest/src/node/reporters/index.ts
packages/vitest/src/node/reporters/junit.ts
packages/vitest/src/types/config.ts
test/config/test/failures.test.ts

This PR removes:
- `vitest typecheck` command - use `vitest --typecheck` instead 
- `VITEST_JUNIT_CLASSNAME` and `VITEST_JUNIT_SUITE_NAME` env variables (use reporter options instead)
- check for `c8` coverage (use coverage-v8 instead)
- export of `SnapshotEnvironment` from `vitest` - import it from `vitest/snapshot` instead

feat: remove deprecated options

---

examples/react/package.json
examples/react/test/basic.test.tsx
examples/react/tsconfig.json
pnpm-lock.yaml

I think people now normally use `react-jsx`, which makes esbuild to inject `react/jsx-(dev-)runtime` so `import React` is not necessary.

chore: tweak `examples/react` tsconfig

---

.github/workflows/ci.yml
packages/vitest/package.json
pnpm-lock.yaml

- Updates Tinypool to the latest breaking change release
- Adds ability to run CI manually. This is useful for forks that are not pushing to their `main` and still want to run CIs before opening PR to upstream.

chore(deps): update `tinypool`

---

test/core/test/jest-expect.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5228
This is already fixed in Chai v5.1.1, so just double checking on Vitest as we might change how we delegate to chai in the future.

test: test thrown empty string match

---

packages/vitest/src/node/plugins/index.ts
test/config/test/failures.test.ts
test/config/test/override.test.ts
test/test-utils/index.ts

An error in this function already triggers error handling here:
https://github.com/vitest-dev/vitest/blob/6a0778d09dd430e7cb0ba7cbba9def26bd76b039/packages/vitest/src/node/cli/cac.ts#L247
This affects public API - it's no longer needed to overwrite `process.exit` when initiating Vitest because there was no way to intercept this error.

fix!: don't exit process if config failed

---

packages/utils/package.json
pnpm-lock.yaml
test/core/test/utils.spec.ts

The previous version of loupe pulled within Vitest was not properly splitting strings to produce names of snapshots. The proposed PR bumps it and adds the relevant tests.
Fixes #5681
_Note: I feel the lock has changed a bit more than what I would have expected. I updated it with pnpm@8.15.8 from a GitHub Codespace. I don't really get how to properly update it if it's not the right one._

feat(utils): Produce valid snapshot names

---

packages/runner/src/suite.ts
test/core/test/concurrent-suite.test.ts

Fixes [issue #5716](https://github.com/vitest-dev/vitest/issues/5716)
This PR addresses an issue where an inner suite with { sequential: true } does not correctly override an outer suite with { concurrent: true }. Previously, the inheritance logic for options.concurrent and options.sequential led to unexpected behavior where conflicting options were not handled properly. This fix ensures that inner suites with { sequential: true } override outer suites with { concurrent: true }, providing the expected behavior for nested suite configurations.
- Adjust the logic in createSuiteCollector to properly handle conflicting concurrent and sequential options.
- Ensure that options.concurrent and options.sequential are inherited with clear default values, preventing undefined values.
- Update the …

fix(runner): Ensure inner suite { sequential: true } correctly overrides outer suite { concurrent: true }

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
test/coverage-test/option-tests/fixture.test.ts
test/coverage-test/testing-options.mjs

- Fixes https://github.com/vitest-dev/vitest/issues/5722
If built-in or third party coverage reporter doesn't emit any files in reports directory, remove that directory after coverage reporting.

fix(coverage): clean up empty coverage reports directory

---

docs/config/index.md
packages/browser/src/client/index.html
packages/browser/src/client/tester.ts
packages/browser/src/node/index.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config.ts
packages/vitest/src/types/browser.ts

This PR adds an option to hide Vitest UI during CI.

feat: add browser.ui option

---

packages/vitest/src/node/reporters/benchmark/table/index.ts

In #5398 the JSON reporter got reworked for the benchmark results. In this rework, the samples array was dropped to prevent huge output files. However, without the samples it's not possible anymore to manually calculate some extra metrics after the bench run. The median is simple enough to calculate when having acces to the samples and can provide some interesting insights (e.g. significant difference between mean and median could indicate outliers).

feat: add median to `--output-json`

---

docs/config/index.md
docs/guide/cli-table.md
packages/browser/src/client/main.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config.ts
packages/vitest/src/types/browser.ts
test/browser/specs/runner.test.ts

This PR removes `browser.fileParallelism` support that was added for a short time to experiment with the concept. The fact that it's impossible to use interactive API and module mocking makes it a large maintenance burden to support this use case so we are removing it.

fix: remove browser.fileParallelism

---

docs/api/expect.md
docs/api/mock.md
docs/guide/cli-table.md
packages/expect/src/jest-expect.ts
packages/expect/src/types.ts
packages/spy/package.json
packages/spy/src/index.ts
packages/vitest/src/node/cli/cli-config.ts
pnpm-lock.yaml
test/core/test/fn.test.ts
test/core/test/jest-mock.test.ts

Fixes #5747
Fixes #5647
This PR removes auto-awaiting of `mock.results[0].value`. To make the migration easier, we are introducing several new assertions mimicking `toHaveReturned*`:
```ts
interface Assertions {
toHaveResolved: () => void
toHaveResolvedTimes: (times: number) => void
toHaveResolvedWith: <E>(expected: E) => void
toHaveLastResolvedWith: <E>(value: E) => void
toHaveNthResolvedWith: <E>(nthCall: number, value: E) => void
}
```
I did not add simple variations (`toBeResolved` and so on) because they are supposed to be softly deprecated.
You can also still get resolved results in `mock.settledResults[0].value`:
```diff
const mock = vi.fn(() => Promise.resolve(1))
- const result = mock.results[0].value
+ const result = mock.settledResults[0].value
```

feat!: add promise-based return assertions, do not auto-resolve returned promises

---

docs/config/index.md
packages/browser/src/client/logger.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/error.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/runtime/console.ts
packages/vitest/src/types/config.ts
packages/vitest/src/types/general.ts
test/browser/specs/runner.test.ts
test/browser/specs/utils.ts
test/browser/test/logs.test.ts
test/browser/vitest.config.mts
test/cli/fixtures/console/trace.test.ts
test/cli/fixtures/console/vitest.config.ts
test/cli/test/console.test.ts

This PR add a `--print-console-stack` option to always print every console stack:
I am reusing the `printError` logic to print stack traces and hide internal ones.
TODO

feat: add an option to print console stack trace

---

packages/ui/client/components/IconAction.vue
packages/ui/client/components/TaskItem.vue

- fix new browser ui icons on dark theme: right now with light gray bg color
- add hover on dark and light theme
- use semantic markup in `ActionIcon.vue` (replace `div` with `<button type="button">`)

fix(browser): browser actions icons colors

---

docs/guide/cli-table.md
packages/vitest/src/node/cli/cli-config.ts

The documentation for `--typecheck.checker` mentions available values are `tcs` and `vue-tsc`. I think this is typo and should be `tsc` (since that is also the default value).

docs: Fix typo in description of `--typecheck.checker` (tcs -> tsc)

---

docs/guide/browser.md
packages/browser/context.d.ts
packages/browser/package.json
packages/browser/src/node/commands/click.ts
packages/browser/src/node/commands/index.ts
packages/browser/src/node/commands/utils.ts
packages/browser/src/node/index.ts
packages/browser/src/node/plugins/pluginContext.ts
packages/vitest/package.json
packages/vitest/src/utils/graph.ts
pnpm-lock.yaml
test/browser/specs/runner.test.ts
test/browser/test/click.test.ts

Addresses #5770
This PR only implements `click` method on `userEvent`:
```ts
import { userEvent } from '@vitest/browser/context'
import { expect, test, vi } from 'vitest'
test('clicks on an element', async () => {
const button = document.createElement('button')
button.textContent = 'Hello World'
const fn = vi.fn()
button.onclick = () => {
fn()
}
document.body.appendChild(button)
await userEvent.click(button)
expect(fn).toHaveBeenCalled()
})
```

feat(browser): support `click` event

---

docs/guide/browser.md
examples/lit/vite.config.ts
packages/browser/context.d.ts
packages/browser/providers.d.ts
packages/browser/src/node/plugins/pluginContext.ts
packages/browser/src/node/providers/index.ts
packages/browser/src/node/providers/preview.ts
packages/vitest/src/integrations/browser.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/types/browser.ts
test/browser/fixtures/mocking/vitest.config.ts
test/config/fixtures/bail/vitest.config.ts

feat(browser): rename none provider to preview, make it default

---

packages/ui/client/components/FileDetails.vue
packages/ui/client/components/ModuleTransformResultView.vue
packages/ui/client/components/views/ViewModuleGraph.vue
packages/vitest/src/api/setup.ts
packages/vitest/src/api/types.ts

fix(browser): print correct transformed module graph

---

docs/guide/cli-table.md
packages/vitest/src/node/cli/cli-config.ts

Correct spelling mistake from oder to order.
Fixes https://github.com/vitest-dev/vitest/issues/5830

docs: correct oder to order (fix #5830[,#5830])

---

packages/vitest/src/node/config.ts

When running in StackBlitz the provider is fixed to `none` and should be the new one `preview`.
Missing change in https://github.com/vitest-dev/vitest/pull/5826

fix(browser): use `preview` provider when running in StackBlitz

---

packages/browser/src/node/index.ts
test/browser/vitest.config.mts

fix(browser): allow iframe to load even if there is a custom CSP header

---

packages/browser/src/client/mocker.ts
packages/browser/src/client/tester.ts
packages/vitest/src/browser.ts
packages/vitest/src/integrations/browser/server.ts
packages/vitest/src/node/config.ts
packages/vitest/src/node/plugins/index.ts

fix(browser): set server.open to false and move error handling after init

---

packages/ui/client/components/FileDetails.vue
packages/ui/client/components/Navigation.vue
packages/ui/client/components/ProgressBar.vue
packages/ui/client/components/dashboard/DashboardEntry.vue
packages/ui/client/components/dashboard/ErrorEntry.vue
packages/ui/client/components/dashboard/TestFilesEntry.vue
packages/ui/client/components/dashboard/TestsEntry.vue
packages/ui/client/components/views/ViewEditor.vue
packages/ui/client/components/views/ViewReportError.vue
packages/ui/client/composables/params.ts
packages/ui/client/pages/index.vue

- load module graph only when the graph tab is selected and when the current module changes
- show file name relative to the root config in `FileDetails.vue` header (rigth now, `relativeToRoot` function using `config.root` where `config` is a vue ref, and so the full path is shown)
- added some icons to the tabs: since we've moved the details from the mid panel, we've some extra space (check screenshot below)
- normalize all composable imports using `~`  instead relative paths: I'll check next weekend to configure autoimport properly, we should remove all composable  imports from vue files
- ~~WIP: change module entry dialog header to include the project and the relative path: in the current version showing only the full path (check screenshot below)~~
- ~~added watcher …

feat(ui): load module graph on tab selection

---

packages/ui/client/pages/index.vue

We need to disable mouse events when resizing main navigation panel, when running in browser mode the browser iframe will prevent resizing it (the resizer is inside the iframe "view").

fix(ui, browser): disable mouse events when resizing main navigation panel

---

docs/api/index.md
packages/runner/src/fixture.ts
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
test/core/test/__snapshots__/test-for.test.ts.snap
test/core/test/test-for.test.ts

- closes https://github.com/vitest-dev/vitest/issues/4642
- closes https://github.com/vitest-dev/vitest/pull/4989 (supersedes)
`test.for` is an alternative API on `test.each`) (2nd one proposed in https://github.com/vitest-dev/vitest/issues/4642#issuecomment-1947507532) to simplify `TestContext` integration.
_todo_

feat(runner): implement `test.for`

---

packages/vitest/src/node/plugins/index.ts
test/config/fixtures/pool-isolation/isolated.test.ts
test/config/fixtures/pool-isolation/non-isolated.test.ts
test/config/test/pool-isolation.test.ts

- Fixes issue where `poolOptions.forks.isolate` is not resolved correctly
- Minimal reproduction at https://stackblitz.com/edit/vitejs-vite-pchfh4?file=vite.config.ts
This is working fine when using workspaces:
https://github.com/vitest-dev/vitest/blob/c79b3f1f9a591c48935b0beda5aa924ea392f02f/packages/vitest/src/node/workspace.ts#L344-L348

fix(forks): resolve `poolOptions.<name>.isolate` from `forks` options

---

packages/vitest/src/integrations/wait.ts
test/core/test/wait.test.ts

When using `vi.waitFor` in browser mode, an unsuccessful resolution of its callback will cause the wait for to run indefinitely.
A simple test like the following will cause the issue:
```ts
it.only('hangs', async () => {
await vi.waitFor(
() => {
console.log('here', performance.now())
throw new Error()
},
{
interval: 100,
timeout: 500,
},
)
})
```
I put some console logs in the waitFor code while debugging and it produced this:
After the handler timeout call, the check callback continues running because the interval is not cleared.
This PR just adds a `clearInterval` call to the `handleTimeout` function, just like in `onResolve`.

fix: vi.waitFor/vi.waitUntil interval is now cleared after it times out

---

packages/snapshot/src/client.ts
test/core/test/snapshot-file.test.ts

- closes https://github.com/vitest-dev/vitest/issues/5891
It looks like empty string snapshot is considered non-existent snapshot due to `... || undefined`.

fix(snapshot): fix `toMatchFileSnapshot` with empty file

---

packages/vitest/src/node/reporters/benchmark/table/index.ts
test/benchmark/test/basic.test.ts

word typo has been corrected. 
- `createFormattedBenchamrkReport` -> `createFormattedBenchmarkReport`
- `flattenFormattedBenchamrkReport` -> `flattenFormattedBenchmarkReport`

fix(vitest): benchmark word error change

---

packages/utils/src/error.ts
test/core/test/serialize.test.ts

Sometimes error's toJSON() method doesn't return a json-compatible object, so we have to recursively apply serialization function to reach JSON-compatible state.

fix: toJSON recursive error serialization (fix #5848)

---

packages/ws-client/src/index.ts

Right now there is no way to change reactive for each entry, if using vue reactive then filesMap and idMap also reactive.
I need this change to allow use vue reactive for state and shallowRef for filesMap and idMap: when running `test/core` with main branch, the ui blocking the main thread (vue 3.4.27), we receive a lot of ws messages, check discord screenshots.

feat(ws-client): allow change reactive for state, filesMap and idMap

---

packages/browser/src/node/index.ts
packages/ui/node/index.ts

Browser and Vitest UI crash when passing `coverage.reporter` as `string`. 
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: options.coverage.reporter.find is not a function
at resolveCoverageFolder
```
Example configuration that crashes with the two features:
```ts
coverage: { 
enabled: true,
reporter: 'json',
provider: 'istanbul'
},
```
Currently adding a test case is a bit difficult. I would rather wait for https://github.com/vitest-dev/vitest/pull/5837 and add the required tests in there.

fix(browser): resolve `coverage.reporter` from string values

---

packages/vite-node/src/constants.ts
packages/vite-node/src/externalize.ts

sync https://github.com/vitejs/vite/pull/17439

feat: image type add bmp

---

.gitignore
packages/browser/src/client/tester/runner.ts
packages/browser/src/client/tester/snapshot.ts
packages/browser/src/client/vite.config.ts
packages/browser/src/node/index.ts
packages/browser/src/node/plugin.ts
packages/browser/src/node/pool.ts
packages/snapshot/src/port/inlineSnapshot.ts
packages/snapshot/src/port/state.ts
packages/snapshot/src/types/environment.ts
packages/vitest/src/public/utils.ts
test/browser/fixtures/update-snapshot/__snapshots__/custom/my_snapshot
test/browser/fixtures/update-snapshot/basic-fixture.ts
test/browser/fixtures/update-snapshot/basic.test.ts
test/browser/fixtures/update-snapshot/vitest.config.ts
test/browser/package.json
test/browser/specs/__snapshots__/update-snapshot.test.ts.snap
test/browser/specs/update-snapshot.test.ts
test/browser/specs/utils.ts
test/browser/vitest.config.mts
test/test-utils/index.ts

fix(browser): correctly update inline snapshot if changed

---

docs/guide/browser.md
packages/browser/context.d.ts
packages/browser/providers/playwright.d.ts
packages/browser/src/client/client.ts
packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/state.ts
packages/browser/src/client/utils.ts
packages/browser/src/node/cdp.ts
packages/browser/src/node/plugin.ts
packages/browser/src/node/plugins/pluginContext.ts
packages/browser/src/node/providers/playwright.ts
packages/browser/src/node/rpc.ts
packages/browser/src/node/server.ts
packages/browser/src/node/state.ts
packages/browser/src/node/types.ts
packages/vitest/src/node/index.ts
packages/vitest/src/types/browser.ts
test/browser/specs/runner.test.ts
test/browser/test/cdp.test.ts

This PR exposes the CDP connection via `cdp` method from `@vitest/browser/context` (only works with `playwright`):
```ts
import { cdp } from '@vitest/browser/context'
cdp().on('Console.messageAdded', (data) => {
// data.message.text === 'MESSAGE ADDED'
})
await cdp().send('Console.enable')
console.error('MESSAGE ADDED')
const input = document.createElement('input')
document.body.appendChild(input)
input.focus()
await cdp().send('Input.dispatchKeyEvent', {
type: 'keyDown',
text: 'a',
})
expect(input).toHaveValue('a')
await cdp().send('Input.insertText', {
text: 'some text',
})
expect(input).toHaveValue('asome text')
```
TODO:

feat(browser): expose cdp in the browser

---

packages/ui/client/composables/explorer/collector.ts
packages/ui/client/composables/explorer/utils.ts

Todo tests inside todo suites (each) not being reported and so the running spinner in the ui: this PR updates the mode to `todo` for any tests running inside any test suite (will run at the end).

fix(ui): update running todo tests inside todo suites (each)

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/utils/coverage.ts

- Forward errors of `coverage.thresholds` to `ctx.logger` instead of global `console`
- Allows capturing these errors when using `startVitest()` Node API 
- Ref. https://github.com/vitest-dev/vitest/pull/5837, which contains the test cases too

fix(coverage): pass thresholds errors to `stderr` of `startVitest()`

---

packages/ui/client/shim.d.ts

The type for `Error.VITEST_AFTER_ENV_TEARDOWN` included in #5944 is wrong, should be a boolean not an string

chore(ui): fix teardown type in Error shim

---

packages/vitest/src/integrations/inject.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/globalSetup.ts
packages/vitest/src/node/workspace.ts

fix(api): correct `project.provide` type

---

packages/vitest/src/node/reporters/base.ts
packages/vitest/src/utils/env.ts

Over at Deno we've been constantly improving our Node compatibility layer and are trying to get `vitest` to work natively. We noticed that the test reporter looks different compared to Node.
Initially, we thought this would be a bug our compatibility layer, but it turns out that `vitest` has a check for Deno that prevents it from using the TTY mode in the reporter.
Note, that there is still more work on our side to be done to get `vitest` fully running. But one step at a time ;)

fix: use TTY reporter when running in Deno

---

.github/workflows/ci.yml
.gitignore
docs/config/index.md
packages/browser/src/client/tester/mocker.ts
packages/browser/src/client/tester/runner.ts
packages/browser/src/client/tester/tester.ts
packages/browser/src/client/utils.ts
packages/browser/src/client/vite.config.ts
packages/browser/src/node/esmInjector.ts
packages/browser/src/node/index.ts
packages/browser/src/node/plugin.ts
packages/browser/src/node/providers/playwright.ts
packages/runner/src/run.ts
packages/runner/src/types/runner.ts
packages/utils/src/source-map.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config.ts
packages/vitest/src/types/browser.ts
test/config/test/failures.test.ts

feat(browser): add an option to take screenshots if the browser test fails

---

docs/guide/browser.md
packages/browser/context.d.ts
packages/browser/src/client/tester/context.ts
packages/browser/src/node/commands/click.ts
packages/browser/src/node/commands/index.ts
test/browser/test/userEvent.test.ts

This PR includes [userEvents.tripleClick](https://testing-library.com/docs/user-event/convenience#tripleclick) for WDIO and PW:
- PW: using `click`  with  `{ clickCount: 3 }`
- WDIO: using [actions API](https://webdriver.io/docs/api/browser/actions/) to simulate moving the pointer to the target element + 3 mouse down, up and pause in a row (thx to @christian-bromann :heart: )
@sheremet-va the types in `context.ts` module for `dblClick` using `UserEventClickOptions`  instead `UserEventDoubleClickOptions`: this PR using also `UserEventClickOptions` instead the new one `UserEventTripleClickOptions` type.
related #5770

feat(browser): add `tripleClick` to interactive api

---

packages/vitest/src/defaults.ts

By default, benchmark files (`*.bench.ts` and `*.benchmark.ts`) are included in the coverage report.
Those should be excluded from the coverage collection.
This PR adds the relevant filenames to `defaultCoverageExcludes`.

fix(coverage): exclude bench files from coverage

---

packages/vitest/src/node/logger.ts

iTerm2 does not fully clear the scrollback history and the screen. The problem that clearing scrollback history removes the history, and leaves current page in the scrollback history. The correct sequence is clear the screen, so it's empty and then the scrollback history leaving the terminal nice and clear. 
Issue: https://github.com/vitest-dev/vitest/issues/5977

fix: flipped erase scrollback and clear screen to fix the issue with iTerm2 refresh

---

packages/coverage-istanbul/src/index.ts

- Mark dynamic import of provider to be ignored by Vite

fix(coverage): Vite to ignore dynamic import of provider

---

packages/browser/src/node/server.ts
packages/runner/src/collect.ts
packages/runner/src/types/runner.ts
packages/runner/src/types/tasks.ts
packages/runner/src/utils/collect.ts
packages/utils/src/source-map.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/node/error.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/github-actions.ts
packages/vitest/src/node/reporters/junit.ts
packages/vitest/src/node/reporters/tap.ts
packages/vitest/src/runtime/runners/test.ts
packages/vitest/src/types/browser.ts
test/browser/specs/runner.test.ts
test/browser/src/error.ts
test/browser/test/failing.test.ts
test/reporters/tests/__snapshots__/html.test.ts.snap

Fixes #5996
Previously the browser mode printed the correct stack trace only if the error was inside the test file because of incorrect stack trace parsing (files were resolved relative to the server (`/src/file.js`) instead of being absolute (`/home/project/src/file.js`)).
Also, I think working with `printError` is quite hard at this stage - maybe we should refactor it.

fix(browser): print correct stack trace in source files

---

packages/coverage-istanbul/package.json
packages/coverage-istanbul/src/provider.ts
pnpm-lock.yaml
test/coverage-test/fixtures/src/json-data-import.ts
test/coverage-test/fixtures/src/json-data.json
test/coverage-test/fixtures/test/import-attributes-fixture.test.ts
test/coverage-test/test/import-attributes.test.ts
test/coverage-test/vitest.workspace.custom.ts

This PR adds support for testing coverage of code with [import attributes](https://github.com/tc39/proposal-import-attributes) using Istanbul. It was previously discussed in issue #5537.

fix(coverage): support import attributes in Istanbul coverage

---

docs/config/index.md
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/defaults.ts
packages/vitest/src/node/plugins/index.ts
test/coverage-test/fixtures/src/test-that-looks-like-source-file.ts
test/coverage-test/test/allow-external.test.ts
test/coverage-test/test/include-exclude.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/5965

fix(coverage): support overriding `exclude`

---

packages/vitest/src/runtime/execute.ts
test/core/test/handled-unhandled.test.ts

fix(vitest): allow testing unandled rejection/exception

---

packages/coverage-istanbul/package.json
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/package.json
pnpm-lock.yaml
test/coverage-test/test/__snapshots__/pre-transpiled-istanbul.snapshot.json
test/coverage-test/test/__snapshots__/results-istanbul.snapshot.json

- Upstream fix for `istanbul-lib-source-maps` was fixed and released, let's remove our patch
- Ref. https://github.com/istanbuljs/istanbuljs/pull/706
- Ref. https://github.com/vitest-dev/vitest/pull/2275
Test case:
https://github.com/vitest-dev/vitest/blob/b1a27d40493301f7b135b6ba99d52c9edc28fffb/test/coverage-test/test/implicit-else.istanbul.test.ts#L5-L20

fix(coverage): remove work-around for implicit `else`

---

docs/guide/cli.md

We've moved browser to it own folder, we need to reference it using trailing slash (`/guide/browser/`)

docs: fix browser guide dead link in cli

---

packages/vitest/src/types/config.ts

The default pool was changed to `forks` in Vitest 2.0:
https://github.com/vitest-dev/vitest/pull/5047
But the JSDoc `@default` was not.
The PR fixes that discrepancy.

docs: default pool in the types of 2.0 config

---

docs/.vitepress/config.ts
docs/.vitepress/theme/index.ts
docs/guide/browser/context.md
docs/tsconfig.json

- fix types in VP theme:
-  add VP types removing hack for enhanceApp
-  use Bundler instead node10 in tsconfig file: breaks shiki twoslash client plugin type
- destructucting default VP theme removes internal VP `enhanceApp` (which has things like badge): using `extends` works
- change favicon sizes: check https://vite-pwa-org.netlify.app/assets-generator/migrations.html#from-minimal-to-minimal-2023-preset
- include missing `tripleClick` in `guide/browser/context` page code snippet

docs: update VP theme configuration

---

packages/ui/client/composables/client/index.ts
packages/ui/client/composables/explorer/collector.ts
packages/ui/client/composables/explorer/filter.ts
packages/ui/client/composables/explorer/utils.ts

This PR fixes changes included in  #6052.
This PR includes also:
- sort the files in the test explorer by name + project.
- fix small bug in `current` computed: should use `findById`
closes #6065

fix(ui): test files notified only when running

---

packages/ui/client/components/Navigation.vue
packages/ui/client/components/explorer/ExplorerItem.vue
packages/ui/client/composables/explorer/state.ts
test/ui/fixtures/task-name.test.ts
test/ui/package.json
test/ui/test/html-report.spec.ts
test/ui/test/ui.spec.ts

This PR also reduces regex number to just 1: moved to explorer state composable (we only need 1 regex for the the search string 🚀 ).
Added ui fixture and test to verify the html is there: the fixture doing dummy Vitest test.
Right now `test/ui` failing on my local (PW), we'll need #6069 merged here (no idea why CI is working 🤞 ).
closes #6061

fix(ui): encode html entities in task name

---

packages/browser/src/client/client.ts
packages/browser/src/client/public/esm-client-injector.js
packages/browser/src/client/utils.ts
packages/browser/src/node/serverOrchestrator.ts
packages/browser/src/node/serverTester.ts

fix(browser): remove `crypto.randomUUID` from the client

---

packages/browser/src/node/commands/keyboard.ts
test/browser/test/userEvent.test.ts

fix(browser): don't release keyboard automatically

---

package.json
pnpm-lock.yaml

I believe `git commit` should take a few milliseconds, not several seconds. The same eslint commands also runs in CI so we don't lose linting, just move it later to CI - everyone should have `eslint` plugin in their IDE anyway.
You need to run `rm -rf .git/hooks` after this PR is merged.

chore: remove pre-commit hooks

---

packages/spy/src/index.ts
test/core/test/vi.spec.ts

- closes https://github.com/vitest-dev/vitest/issues/6085

fix(spy): fix type error when assigning `vi.spyOn` to `MockInstance` of function overload

---

packages/ui/package.json
packages/ui/vite.config.ts
pnpm-lock.yaml

https://github.com/unplugin/unplugin-auto-import/commit/8aaec26d5776552016a33e1944b2c7fbb6c08a4d
https://github.com/unplugin/unplugin-auto-import/commit/3a27e14b85d752f4ccbf7519f0d0afd5d327cc2d
To make browse testing easier by register auto imported entries to optimizeDeps and reduce the chance of vite reload on new dep discovery

chore: bump unplugin-auto-import

---

packages/ui/client/composables/explorer/filter.ts
packages/ui/client/composables/explorer/tree.ts
packages/ui/client/composables/explorer/types.ts
packages/ui/client/composables/explorer/utils.ts

When searching and `Only Tests` unchecked, any file/suite matching the search will include its children.

feat(ui): show all suites/tests when parent matches

---

packages/browser/src/client/tester/msw.ts
packages/browser/src/node/plugin.ts
test/browser/cjs-lib/lib.d.ts
test/browser/cjs-lib/lib.mjs
test/browser/cjs-lib/package.json
test/browser/fixtures/mocking-watch/1_mocked-on-watch-change.test.ts
test/browser/fixtures/mocking-watch/2_not-mocked-import.test.ts
test/browser/fixtures/mocking-watch/vitest.config.ts
test/browser/package.json
test/browser/specs/mocking.test.ts

fix(browser): allow immidiate reinvalidation of mocked dependencies

---

packages/vitest/src/runtime/inspector.ts
test/cli/test/inspect.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/6103
This works on all platforms except Windows:
```js
const filename = resolve("./target.mjs");
const url = new URL(filename, import.meta.url).href;
session.post("Debugger.setBreakpointByUrl", { url, lineNumber: 0 });
```
This works on Windows too:
```js
const filename = resolve("./target.mjs");
const url = pathToFileURL(filename);
session.post("Debugger.setBreakpointByUrl", { url, lineNumber: 0 });
```

fix: `--inspect-brk` stop on Windows

---

docs/guide/extending-matchers.md

This PR improves the docs for setting up custom matchers. With the current guide I wasn't able to properly configure TypeScript, so I needed to take a look at [Testing LIbrary Jest DOM matchers](https://github.com/testing-library/jest-dom/blob/main/types/vitest.d.ts) how they handle it. Their approach worked for me, so I suggest updating the docs accordingly.
- change ambient declaration file to how it is configured inside [testing lib](https://github.com/testing-library/jest-dom/blob/main/types/vitest.d.ts) since the current way didn't work for me
- rename MatcherResult to ExpectationResult as this is the current name of custom matcher return type according to source code (see MatchersObject > RawMatcherFn > ExpectationResult)

docs: improve extending matchers docs

---

packages/vitest/src/utils/test-helpers.ts
test/core/test/dom-single-line-options.test.ts

Closes https://github.com/vitest-dev/vitest/issues/5104
Environment options cannot be parsed when declared like so:
```
/** @vitest-environment-options {"url": "https://vitejs.dev"} */
```
The regexp captures `{"url": "https://vitejs.dev"} */`
I would like to add tests but I get hit with the following error message when trying to run them:
```
examples/graphql test: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/benjamin/projects/vitest/packages/vitest/dist/cli-wrapper.js' imported from /home/benjamin/projects/vitest/packages/vitest/vitest.mjs
```

fix: one-line environment options

---

packages/browser/src/node/plugin.ts
packages/ui/client/components.d.ts
packages/ui/client/components/views/ScreenshotError.vue
packages/ui/client/components/views/ViewReport.vue

https://streamable.com/1o92rg
closes #5990

feat(browser): allow preview and open in the editor screenshot error from ui

---

docs/guide/browser/index.md

The documentation was inconsistent in regards to what the default browser provider is. In once place it says that `preview` is the default, in another it says that `WebdriverIO` is the default. Since it seems `preview` is now the default, I have adjusted the docs accordingly.
Since this is not exactly a bug that can be reproduced, but rather just an inconsistency in the docs, I did not make an issue.
Regardless, it would be great to have a "Documentation" issue template for these kinds of errors.
Since this just changes a sentence in a markdown file, no test is needed.

fix(docs): list default browser provider consistently

---

docs/config/index.md
packages/vitest/src/utils/coverage.ts
test/coverage-test/test/threshold-auto-update.test.ts
test/coverage-test/test/threshold-glob.test.ts

fix(coverage): global coverage includes files in glob pattern coverage rules (fix #6165)

---

packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml
test/coverage-test/test/empty-lines.v8.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/6164
During https://github.com/vitest-dev/vitest/pull/5457 the changes of https://github.com/vitest-dev/vitest/pull/5328 should have been reverted. The https://github.com/vitest-dev/vitest/pull/5457 implements type-only file detection in proper way while https://github.com/vitest-dev/vitest/pull/5328 was mostly a work-around since good solution was not available back then.
Files containing just types will show up in coverage report. But they will not have uncovered lines like they did before #5457.
> [!TIP]  
> To hide empty files from coverage reporters use reporter options:
> 
> ```js
> {
>   coverage: {
>     reporter: [
>       ['text', { 'skipEmpty': true }],
>       ['html', { 'skipEmpty': true }],
>     ]
>   }
> }
> ```
>

fix(coverage): consistent type-only file handling

---

docs/config/index.md
docs/guide/cli-table.md
packages/vitest/src/defaults.ts
packages/vitest/src/node/cli/cli-config.ts
test/coverage-test/fixtures/src/should-be-excluded-by-default.cts

- Fixes https://github.com/vitest-dev/vitest/issues/6161
Vite does not transform `*.cts` files into Javascript. This makes Istanbul's babel crash on TS syntax when untested files are picked by `coverage.all`.

fix(coverage): ignore `*.cts` files

---

docs/guide/workspace.md
netlify.toml
packages/vitest/src/config.ts

fix(vitest): improve `defineProject` and `defineWorkspace` types

---

docs/guide/mocking.md
packages/web-worker/src/shared-worker.ts
packages/web-worker/src/types.ts
packages/web-worker/src/worker.ts
packages/web-worker/tsconfig.json
test/core/src/web-worker/worker-globals.ts
test/core/test/web-worker-jsdom.test.ts
test/core/test/web-worker-node.test.ts

fix(web-worker): expose globals on self

---

docs/guide/browser/interactivity-api.md
packages/browser/context.d.ts
packages/browser/src/client/tester/context.ts
packages/browser/src/node/commands/keyboard.ts
packages/browser/src/node/commands/type.ts
packages/browser/src/node/plugins/pluginContext.ts
test/browser/test/userEvent.test.ts

fix(browser): userEvent.setup initiates a separate state for userEvent instance

---

packages/browser/src/client/tester/mocker.ts
packages/browser/src/node/rpc.ts
packages/browser/src/node/types.ts
test/browser/fixtures/mocking/import-actual-dep.test.ts
test/browser/specs/mocking.test.ts

fix(browser): correctly import optimized module in vi.importActual

---

packages/browser/src/client/public/error-catcher.js
packages/browser/src/node/rpc.ts
packages/browser/src/node/server.ts
test/browser/fixtures/unhandled/throw-unhandled-error.test.ts
test/browser/fixtures/unhandled/vitest.config.ts
test/browser/specs/unhandled.test.ts

fix(browser): print correct stack trace for unhandled errors

---

docs/api/expect.md

`expect.closeTo` has a second optional argument which is called `precision` and not `numDigits`.
I think the description has been copied from https://vitest.dev/api/expect.html#tobecloseto.
I checked the [source code](https://github.com/vitest-dev/vitest/blob/c997937bf37c0a39883bcf29d5c4188b96ae3924/packages/expect/src/jest-asymmetric-matchers.ts#L358) where it is called `precision` but it refers to the number of digits.
I have not because I quickly created this PR via the GitHub web interface.

docs: Fix argument name in expect.md

---

docs/config/index.md

Fixed a grammar error in the description of [`browser.commands`](https://vitest.dev/config/#browser-commands).
can be import -> can be imported

docs: Fix grammar error in browser config documentation

---

packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/types/coverage.ts
packages/vitest/src/utils/coverage.ts
test/coverage-test/test/reporters.test.ts

fix: don't panic when coverage.reporter is a string

---

docs/api/expect.md

Just fixing a small typo I stumbled upon when reading the `expect` docs.

docs: fix typo in expect.md

---

packages/runner/src/suite.ts

This is not a fix, but a more friendly message related to #5251

refactor: throw an error if the internal suite is not found

---

docs/api/expect.md

Spotted some minor typos in the [expects docs](https://vitest.dev/api/expect.html):
- In the [toMatchSnapshot](https://vitest.dev/api/expect.html#tomatchsnapshot) tip.
- In the [expect.unreachable](https://vitest.dev/api/expect.html#expect-unreachable) description.

docs: Address typos in expect.md

---

.github/workflows/ci.yml
packages/browser/package.json
packages/browser/rollup.config.js
packages/browser/src/client/tester/locators/index.ts
packages/browser/src/client/tester/locators/playwright.ts
packages/browser/src/client/tester/locators/preview.ts
packages/browser/src/client/tester/locators/webdriverio.ts
packages/browser/src/client/tester/public-utils.ts
packages/browser/src/client/tester/tester.html
packages/browser/src/client/tester/tester.ts
packages/browser/utils.d.ts
packages/utils/src/display.ts
packages/utils/src/index.ts
pnpm-lock.yaml
test/browser/fixtures/locators/query.test.ts
test/browser/package.json
test/browser/specs/locators.test.ts
test/browser/test/__snapshots__/utils.test.ts.snap
test/browser/test/utils.test.ts

fix(browser): keep querying elements even if locator is created with elementLocator, add pubic @vitest/browser/utils

---

docs/package.json
packages/ui/package.json
packages/vitest/src/create/browser/creator.ts
pnpm-lock.yaml
test/core/package.json
test/coverage-test/package.json

fix(browser): produce valid config file if preview provider is used

---

docs/guide/reporters.md

This PR fixes the link to the `Reporter` interface, which appears on https://vitest.dev/guide/reporters.html#custom-reporters.

docs: correct link to Reporter interface

---

docs/config/index.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/types/config.ts
packages/vitest/src/node/workspace.ts
test/workspaces/globalTest.ts
test/workspaces/space_3/global-provide.space-3-test.ts
test/workspaces/space_3/vitest.config.ts
test/workspaces/vitest.config.ts

feat(vitest): add "provide" option

---

docs/api/vi.md
docs/guide/common-errors.md

Since Vite 2.0 `vi.mock` can accept `import()` as the first argument to detect which module to be mock. This however won't work with aliased paths, which can confuse some people.
I believe this is not solvable at the moment, as this is not a Vitest, but rather TypeScript shortcoming.

docs: Update common-errors to include dynamic import aliases

---

packages/browser/src/client/tester/locators/index.ts
packages/browser/src/client/tester/locators/preview.ts
packages/browser/src/client/tester/locators/webdriverio.ts
packages/browser/src/client/tester/tester.html
packages/browser/src/node/serverTester.ts
packages/browser/utils.d.ts

This is needed so that when the `getBy*` locator fails, users won't see the content of the script

chore: remove __VITEST_APPEND__ after it was initiated

---

docs/config/index.md

Fixing a typo, the property name in `css.modules` is not called `generateScopeName`, but `generateScope<d>Name`

docs: updating a typo property name inside css.modules

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml
test/coverage-test/package.json
test/coverage-test/test/mixed-versions-warning.unit.test.ts

- Warn if test run loads different versions of `vitest` and `@vitest/coverage-*` packages
- This is just a warning as the packages still may work, but we don't support these cases. Vitest requires users to use 100% exact same versions for `vitest` and `@vitest/*` packages. This has been discussed quite much in the past.

fix(coverage): warn if `vitest` and `@vitest/*` versions don't match

---

packages/coverage-v8/src/provider.ts
test/coverage-test/fixtures/src/cjs-package/entry.js
test/coverage-test/fixtures/src/cjs-package/package.json
test/coverage-test/fixtures/src/cjs-package/target.js
test/coverage-test/test/convert-failure.v8.test.ts

- When coverage conversion using `v8ToIstanbul` fails, log warning and proceed with rest of the report instead of crashing completely
- Related to https://github.com/vitest-dev/vitest/issues/6297 but does not fix it. Though this allows users to see report in cases like that.
- These errors can happen when source maps are incorrect, or when a single file is loaded from both outside and through Vite - see test case for example. In those cases we cannot know if `vite-node`'s wrapper should be applied in coverage remapping or not.

fix(coverage): v8 to warn instead of crash when conversion fails

---

docs/config/index.md
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/defaults.ts
packages/vitest/src/node/types/coverage.ts
test/coverage-test/test/exclude-after-remap.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/3818
- Test case requires and builds on top of https://github.com/vitest-dev/vitest/pull/6120 so let's merge that one first
Example from Vitest monorepo before (left) and after:

feat(coverage): add `--exclude-after-remap`

---

docs/config/index.md

- Continues https://github.com/vitest-dev/vitest/pull/6174#discussion_r1686251309
This was accidentally released already in 2.0.4 patch release. Let's mark it into documentation correctly as 2.1.0 though.

docs: version for `coverage.thresholds.<glob>.100`

---

packages/vitest/src/constants.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/node/workspace/resolveWorkspace.ts
packages/vitest/src/public/config.ts
test/config/fixtures/workspace/invalid-duplicate-configs/vitest.workspace.ts
test/config/fixtures/workspace/invalid-duplicate-configs/vitest1.config.js
test/config/fixtures/workspace/invalid-duplicate-configs/vitest2.config.js
test/config/fixtures/workspace/invalid-duplicate-inline/vitest.workspace.ts
test/config/fixtures/workspace/invalid-non-existing-config/vitest.workspace.ts
test/config/fixtures/workspace/several-configs/test/1_test.test.ts
test/config/fixtures/workspace/several-configs/test/2_test.test.ts
test/config/fixtures/workspace/several-configs/test/vitest.config.one.ts
test/config/fixtures/workspace/several-configs/test/vitest.config.two.ts
test/config/fixtures/workspace/several-configs/vitest.workspace.ts
test/config/test/workspace.test.ts
test/test-utils/cli.ts
test/test-utils/index.ts
test/workspaces/vitest.workspace.ts

Fixes #5530 
Workspace resolution now respects the glob even if it catches both `vite` _and_ `vitest` config at the same time. You should use a different glob pattern in that case.

fix(workspace): correctly resolve workspace globs and file paths

---

test/snapshots/package.json
test/snapshots/test/custom-serializers.test.ts

I noticed `pnpm -C test/snapshots test` is failing locally and it looks like this one has been excluded on ci because `pnpm test:ci` filters only `@vitest/test-*` packages.
I added this back in by renaming it to `@vitest/test-snapshots` and also updated a failing test.

test: fix `test/snapshots` and add it to ci

---

packages/snapshot/src/port/state.ts
test/cli/fixtures/fails/inline-snapshop-inside-loop-update-all.test.ts
test/cli/fixtures/fails/inline-snapshop-inside-loop-update-none.test.ts
test/cli/fixtures/fails/inline-snapshop-inside-loop.test.ts
test/cli/test/__snapshots__/fails.test.ts.snap
test/cli/test/fails.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6327
There are some odd cases not handled well, but I think this will catch common cases and notify users effectively with an understandable error message. I tested on Jest and the behaviors of the test cases added here are same.

fix(snapshot): reject multiple `toMatchInlineSnapshot` updates at the same location

---

docs/api/vi.md
packages/vitest/src/integrations/mock/timers.ts
packages/vitest/src/integrations/vi.ts
test/core/test/fixtures/timers.suite.ts

This adds `vi.advanceTimersToNextFrame`, using sinonjs/fake-timer's [`clock.runToFrame()`](https://github.com/sinonjs/fake-timers#clockruntoframe) method, which Jest exposed as [`jest.advanceTimersToNextFrame()`](https://jestjs.io/docs/next/jest-object#jestadvancetimerstonextframe) in this [PR](https://github.com/jestjs/jest/pull/14598). Credit to @alexreardon for the feature implementation and tests there. I copied the test over exactly, as that seems to be the convention for other tests in the [timers](https://github.com/vitest-dev/vitest/blob/main/test/core/test/fixtures/timers.suite.ts) test suite.
Resolves https://github.com/vitest-dev/vitest/issues/6346

feat(vitest): add `vi.advanceTimersToNextFrame`

---

packages/browser/src/node/index.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/pool.ts
packages/vitest/src/node/pools/forks.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/typecheck.ts
packages/vitest/src/node/sequencers/BaseSequencer.ts
packages/vitest/src/node/spec.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/utils/test-helpers.ts
test/core/test/sequencers.test.ts

This PR replaces public `WorkspaceSpec` with a class implementation, but keeps `0, 1, 2` and `Symbol.iterator` for backward compatibility. It will be removed in Vitest 3.

feat(api): make spec into a class instead of a tuple

---

packages/expect/src/jest-extend.ts
packages/expect/src/types.ts

Might fix https://github.com/vitest-dev/vitest/issues/6350
Copied the typedef from jest, which is a better reflection of the fact vitest does actually use spread

fix: Align RawMatcherFn type definition with Jest

---

docs/advanced/reporters.md
packages/vitest/src/node/reporters/index.ts
packages/vitest/src/node/reporters/reported-tasks.ts
packages/vitest/src/node/state.ts
packages/vitest/src/public/node.ts
test/cli/test/reported-tasks.test.ts

This PR renames the reported task class `TestFile` to `TestModule`. This is done to potentially support virtual tests in the future.

refactor(api): rename TestFile to TestModule

---

docs/guide/workspace.md
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/utils/coverage.ts
test/coverage-test/fixtures/configs/vitest.workspace.multi-transforms.ts
test/coverage-test/fixtures/src/covered.custom-1
test/coverage-test/fixtures/src/uncovered.custom-1
test/coverage-test/fixtures/test/custom-1-syntax.test.ts
test/coverage-test/fixtures/workspaces/custom-2/src/covered.custom-2
test/coverage-test/fixtures/workspaces/custom-2/src/uncovered.custom-2
test/coverage-test/fixtures/workspaces/custom-2/test/custom-2-syntax.test.ts
test/coverage-test/test/__snapshots__/custom-file-covered-1-istanbul.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-covered-1-v8.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-covered-2-istanbul.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-covered-2-v8.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-uncovered-1-istanbul.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-uncovered-1-v8.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-uncovered-2-istanbul.snapshot.json
test/coverage-test/test/__snapshots__/custom-file-uncovered-2-v8.snapshot.json
test/coverage-test/test/all.test.ts
test/coverage-test/test/changed.test.ts
test/coverage-test/test/workspace.multi-transform.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/5856 
When picking up uncovered files (`coverage.all`) in workspace, try to find `vitenode` from a project whose `root` matches the uncovered file. If none are found, use core's `vitenode`.

fix(coverage): use project specific `vitenode` for uncovered files

---

packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/vitestResolver.ts
test/workspaces/space_3/fake-vitest/config.js
test/workspaces/space_3/fake-vitest/index.js
test/workspaces/space_3/fake-vitest/package.json
test/workspaces/space_3/package.json

fix(vitest): always resolve vitest to the root version

---

packages/vitest/package.json
pnpm-lock.yaml

Improved error handling in `@antfu/install-pkg` and `tinyexec`. Pulls in the latest version of `tinyexec` so that it can be deduped if we switch to it

chore: upgrade to install-pkg 0.4.1

---

packages/runner/src/types/tasks.ts
test/core/test/hooks.test.ts

Hey team! 👋
- Current implementation of callCleanupHooks already accepts non-function values as cleanupCallback
- Type definition currently restricts cleanupCallback to functions only
- This PR updates the type definition to allow non-function values
- No changes to the actual implementation, only type definitions are modified
```
async function callCleanupHooks(cleanups: HookCleanupCallback[]) {
await Promise.all(
cleanups.map(async (fn) => {
if (typeof fn !== 'function') {
return
}
await fn()
}),
)
}
```
Close: #6033

fix(types): Allow Callbacks Passed to before*/after* to Return Anything

---

test/watch/test/file-watching.test.ts

This test is currently skipped on CI and still seems flaky even running it locally, but this browser test was failing for a different reason:
```
Error: You've enabled headless mode for "preview" provider but it doesn't support it. Use "playwright" or "webdriverio" instead: https://vitest.dev/guide/browser/#configuration
```

test: fix browser provider

---

packages/vitest/package.json
pnpm-lock.yaml

Move `@ampproject/remapping` as dev dep. It was added as dep in https://github.com/vitest-dev/vitest/pull/5853, but then no longer needed with https://github.com/vitest-dev/vitest/pull/5924

chore: move `@ampproject/remapping` as dev dep

---

packages/browser/src/client/tester/tester.ts
packages/browser/src/node/plugin.ts
packages/ui/client/composables/explorer/collector.ts
packages/ui/client/composables/explorer/utils.ts
test/browser/specs/runner.test.ts
test/browser/src/actions.ts
test/browser/tsconfig.json
test/browser/vitest.config.mts
test/browser/vitest.config.unit.mts

fix(browser): correctly run in-source tests in the browser

---

docs/guide/browser/interactivity-api.md
docs/guide/browser/locators.md
packages/browser/context.d.ts
packages/browser/package.json
packages/browser/rollup.config.js
packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/locators/index.ts
packages/browser/src/client/tester/locators/preview.ts
packages/browser/src/client/tester/locators/webdriverio.ts
packages/browser/src/node/commands/fs.ts
packages/browser/src/node/commands/index.ts
packages/browser/src/node/commands/screenshot.ts
packages/browser/src/node/commands/upload.ts
packages/browser/src/node/plugins/pluginContext.ts
pnpm-lock.yaml
test/browser/test/userEvent.test.ts
test/ui/test/html-report.spec.ts
test/ui/test/ui.spec.ts
test/ui/tsconfig.json

feat(browser): support `userEvent.upload` in playwright provider

---

docs/guide/debugging.md
packages/browser/src/node/providers/playwright.ts
packages/vitest/src/node/config/resolveConfig.ts
test/config/test/failures.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5090
Adds support for opening debugger session on Browser mode via `vitest --inspect --browser`. This is only supported in Chromium browsers with Playwright. 
[vitest-inspect.webm](https://github.com/user-attachments/assets/ad5a1afc-756e-4c0b-a2c2-db7c350f3ce4)
Support for `--inspect-brk`, where debugger stops at the first test file is possible but not yet implemented. There's some weird going on with source maps in browser mode. Let's leave that feature to separate PR.

feat(browser): support `--inspect`

---

packages/vitest/src/runtime/worker.ts
packages/vitest/src/runtime/workers/utils.ts

fix(vitest): dispose vmForks listeners to avoid memory leak

---

packages/vite-node/src/hmr/emitter.ts

Currently vite-node is patching `server.ws.send` to intercept event, but this doesn't include server module graph's change.
As a temporary measure, we can probably try patching `server.environments.ssr.hot.send` in a similar way.
With this change, I verified `test/vite-node` passes on Vite 6.

fix(vite-node): fix watch on vite 6

---

packages/browser/package.json
packages/browser/src/node/index.ts
packages/ui/node/index.ts
pnpm-lock.yaml

fix: print unexpected error message if peer dependencies have a different version

---

packages/vitest/LICENSE.md
packages/vitest/package.json
packages/vitest/src/create/browser/creator.ts
packages/vitest/src/node/git.ts
packages/vitest/src/typecheck/typechecker.ts
pnpm-lock.yaml
test/cli/test/dotted-files.test.ts
test/config/package.json
test/config/test/console-color.test.ts
test/config/test/exec-args.test.ts
test/reporters/tests/custom-reporter.spec.ts
test/test-utils/index.ts
test/test-utils/package.json
test/watch/test/workspaces.test.ts

This PR replaces `execa` with a lighter `tinyexec` as discussed here: https://github.com/vitest-dev/vitest/pull/5713. Some notes inline as a code review, please let me know whether it'd make sense to comment the code accordingly in those places.
Not sure how to handle the third item in the checklist – should I revert the changes that remove the `execa` dependency?

chore(deps): replace `execa` with `tinyexec`

---

docs/guide/debugging.md
packages/browser/src/node/pool.ts
packages/browser/src/node/providers/playwright.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/types/browser.ts
pnpm-lock.yaml
test/browser/fixtures/inspect/math.test.ts
test/browser/fixtures/inspect/vitest.config.ts
test/browser/package.json
test/browser/specs/inspect.test.ts
test/config/test/failures.test.ts

- Continues https://github.com/vitest-dev/vitest/pull/6433
Adds support for `--browser --inspect-brk`. Compared to `--inspect`, this one waits for debugger to attach and then stops on top of the first test file. Similar experience as `vitest --inspect-brk` does on Node side. Requires CDP so only Playwright and Chromium browser are supported.
Demo below has no initial breakpoints set:
[vitest-inspect-brk.webm](https://github.com/user-attachments/assets/d6aa1045-af53-4c11-a7e7-8fcca7fa9c69)

feat(browser): support `--inspect-brk`

---

docs/package.json
package.json
packages/ui/package.json
packages/vitest/LICENSE.md
packages/vitest/package.json
packages/vitest/rollup.config.js
pnpm-lock.yaml

#6274 removed usage of the `caseSensitiveMatch` option as `tinyglobby` didn't have it at the time. It switched to a simple `(LICENSE)|(license)` matching instead. As you can imagine, this introduced an edge case that made mixed-case license files not match. Thankfully the edge case was never hit. The latest `tinyglobby` version added this option, so this PR makes usage of it, fixing this edge case.

chore: fix edge case in license files bundling

---

.github/workflows/ci.yml
packages/ui/client/components/explorer/Explorer.vue
test/ui/test/html-report.spec.ts
test/vite-node/test/server.test.ts

fix(ui): remove "filters" flickering

---

packages/vitest/src/node/core.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/vitestResolver.ts
packages/vitest/src/node/plugins/workspace.ts

fix: ignore importer when resolving Vitest

---

packages/expect/src/state.ts
packages/vitest/src/integrations/chai/index.ts
test/core/test/basic.test.ts

fix: `expect.getState().testPath` always returns correct path

---

docs/api/expect.md
packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/locators/preview.ts
packages/browser/src/node/plugins/pluginContext.ts
test/browser/fixtures/locators/blog.test.tsx

fix: userEvent works consistently between providers

---

packages/vitest/src/create/browser/examples.ts

A missing `async` threw an error in the Learn With Jason livestream on Vitest browser mode with Vladimir Sheremet.
Browser mode looks super cool!

fix: make example test callbacks async

---

packages/vite-node/src/externalize.ts
pnpm-lock.yaml
test/core/deps/dep-esm-comment/index.js
test/core/deps/dep-esm-comment/package.json
test/core/package.json
test/core/test/dual-package-hazard.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6494

fix(vite-node): fix esm false-detection inside comment

---

packages/browser/package.json

I noticed `pnpm dev` is not rebuilding when modifying `packages/browser/src/client/tester/context.ts`. To fix this, I loosened `rollup --watch.include` since some client entries are built by rollup.

chore: fix browser package dev watch

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/types/coverage.ts
test/coverage-test/test/empty-coverage-directory.test.ts
test/coverage-test/test/on-failure.test.ts
test/coverage-test/utils.ts

- Fixes https://github.com/vitest-dev/vitest/issues/6538

fix(coverage): remove empty coverage folder on test failure too

---

docs/config/index.md
packages/vitest/src/defaults.ts

- Fixes https://github.com/vitest-dev/vitest/issues/6544
```bash
RUN  v2.1.1 /x/astro-example
Coverage enabled with v8
✓ example.test.ts (1)
✓ Card with slots
Tests  1 passed (1)
Start at  08:58:34
Duration  1.11s (transform 389ms, setup 0ms, collect 708ms, tests 41ms, environment 0ms, prepare 59ms)
% Coverage report from v8
---------------|---------|----------|---------|---------|-------------------
File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------|---------|----------|---------|---------|-------------------
All files      |   21.21 |       50 |       0 |   21.21 |                   
components    |     100 |      100 |     100 |     100 |                   
Card.astro   |     100 |      100 |     100 |     100 | …
```

fix(coverage): include `*.astro` by default

---

packages/browser/src/node/plugin.ts
test/browser/fixtures/worker/src/basic.test.ts
test/browser/fixtures/worker/src/worker-dynamic-dep.ts
test/browser/fixtures/worker/src/worker.ts
test/browser/fixtures/worker/vitest.config.ts
test/browser/specs/worker.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6552
This shims `globalThis.__vitest_browser_runner__.wrapDynamicImport` for worker entry similar to how Vite injects env to `?worker_file` via `vite:worker` plugin.
Probably this is not a fundamental fix (something involving msw can break in worker?), but this seems okay as a stop gap.

fix(browser): fix dynamic import inside worker

---

packages/expect/src/jest-expect.ts
test/core/test/expect-poll.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6557
It looks like `this.not.be.undefined` is messing up `negate` state and I wasn't entirely sure what's happening. It looks like this is simply enough to not reuse chai helper, so I rewrite `toBeDefined` with our custom message.

fix(expect): fix `toBeDefined` with `expect.poll`

---

packages/runner/src/fixture.ts
test/config/fixtures/fixture-no-async/basic.test.ts
test/config/fixtures/fixture-no-async/vitest.config.ts
test/config/test/fixture-no-async.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6042

fix(runner): support fixture parsing of lowered async syntax

---

packages/browser/src/client/channel.ts
packages/browser/src/client/tester/mocker.ts
packages/browser/src/client/tester/msw.ts
packages/utils/src/index.ts
packages/utils/src/nanoid.ts
packages/vitest/src/utils/base.ts
test/browser/fixtures/mocking/mocked-factory.test.ts
test/browser/fixtures/mocking/src/mocks_factory_many.ts
test/browser/fixtures/mocking/src/mocks_factory_many_dep1.ts
test/browser/fixtures/mocking/src/mocks_factory_many_dep2.ts

- closes https://github.com/vitest-dev/vitest/issues/6483
`IframeMockFactoryRequestEvent` and `IframeMockFactoryResponseEvent` pairs are mixed up when multiple requests are on-going. I added `eventId` to identify request/response pair correctly.

fix(browser): fix browser mock factory event race condition

---

packages/vitest/src/defaults.ts
packages/vitest/src/node/config/serializeConfig.ts
packages/vitest/src/node/reporters/benchmark/table/index.ts
packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
packages/vitest/src/node/types/benchmark.ts
packages/vitest/src/runtime/config.ts
packages/vitest/src/runtime/runners/benchmark.ts
packages/vitest/src/runtime/types/benchmark.ts
test/benchmark/test/reporter.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6539
I think we should clear `BenchmarkResult.samples` by default on test runner side. I added `benchmark.includeSamples` option which allows returning samples, but it's disabled by default.
The fix is verified with this reproduction https://github.com/hi-ogawa/reproductions/tree/main/vitest-6539-bench-heap-oom
<details><summary>Plot of "used_heap_size"</summary>
</details>

fix(benchmark): clear `BenchmarkResult.samples` array to reduce memory usage

---

packages/browser/src/node/plugin.ts
test/browser/vitest.config.mts

- Closes https://github.com/vitest-dev/vitest/issues/6559
I add a middleware to serve `/__vitest__/assets` files directly to avoid Vite's transform of css. This is similar to how `@vitest/ui` serve assets.

fix(browser): serve ui assets as static

---

packages/browser/src/client/tester/locators/preview.ts

The problem using `preview` provider file upload should be fixed using `data:${mime};base64,${base64}` in the fetch url.
I guess the problem only on MacOS (kit), tested on my Windows laptop and working with or without the _data:_ protocol.
<details>
<summary>Run this code on the browser console</summary>
```js
const t = {
basename: 'button.css', 
base64: 'LndyYXBwZXIgewogIHBhZGRpbmc6IDEycHg7CiAgZm9udC1mYW1pbHk6IFJlYWRleCBQcm8sc2Fucy1zZXJpZjsKICBmb250LXNpemU6IGxhcmdlOwogIGZvbnQtd2VpZ2h0OiBib2xkOwogIHRleHQtYWxpZ246IGNlbnRlcjsKfQoKLm5vZGUgewogIGJhY2tncm91bmQtY29sb3I6ICMzZjNmM2Y7CiAgYm9yZGVyLXJhZGl1czogMTJweDsKICBoZWlnaHQ6IDMwcHg7CiAgZGlzcGxheTogZmxleDsKICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICBhbGlnbi1pdGVtczogY2VudGVyOwogIGNvbG9yOiB3aGl0ZTsKfQo=', 
mime: 'text/css'
}
const fileInstance = await …
```

fix(browser): use `data:` protocol on preview provider file upload

---

packages/ui/client/composables/client/index.ts
test/ui/test/ui.spec.ts

- Closes https://github.com/vitest-dev/vitest/issues/6574
<details><summary>Screenshots when running <code>pnpm -C examples/basic test -- --ui --standalone</code></summary>
- Before
- After
</details>

fix(ui): list tests on ui when `--standalone`

---

docs/config/index.md

Fixing a spelling mistake: "ot" to "or"

docs(config): fix spelling mistake

---

test/cli/test/__snapshots__/stacktraces.test.ts.snap
test/cli/test/setup-files.test.ts
test/cli/test/stacktraces.test.ts
test/cli/test/vm-threads.test.ts

- Similar temporary fix as https://github.com/vitest-dev/vitest/pull/6462/files
- CI with Node +22.1.0 keeps crashing on one specific file
- https://github.com/vitest-dev/vitest/pull/6452#issuecomment-2373161060

test: disable vmThreads test for now

---

docs/guide/mocking.md

The config option is called `unstubEnvs`, while the method is called `unstubAllEnvs`

docs: Mocking: Config option is called unstubEnvs, method is called unstubAllEnvs

---

docs/config/index.md
packages/vitest/src/node/types/benchmark.ts

- Closes https://github.com/vitest-dev/vitest/issues/5953
I thought we could remove it entirely, but there might be a need in the future to bring back the same code, so I only noted it's deprecated to avoid confusion.

docs: deprecate `benchmark.outputFile` option

---

packages/runner/src/fixture.ts
test/config/fixtures/fixture-no-async/basic.test.ts
test/config/test/fixture-no-async.test.ts

- follow up https://github.com/vitest-dev/vitest/pull/6531
- closes https://github.com/vitest-dev/vitest/issues/6042

fix(runner): fix fixture parsing of lowered async syntax for non arrow functions

---

packages/runner/src/hooks.ts
test/cli/fixtures/fails/hooks-fail-afterAll.test.ts
test/cli/fixtures/fails/hooks-fail-afterEach.test.ts
test/cli/fixtures/fails/hooks-fail-beforeAll.test.ts
test/cli/fixtures/fails/hooks-fail-beforeEach.test.ts
test/cli/test/__snapshots__/fails.test.ts.snap

fix(runner): guard test hook callback

---

packages/vitest/package.json
packages/vitest/src/node/error.ts
packages/vitest/src/node/reporters/benchmark/table/tableRender.ts
packages/vitest/src/node/reporters/github-actions.ts
packages/vitest/src/node/reporters/junit.ts
packages/vitest/src/node/reporters/renderers/listRenderer.ts
packages/vitest/src/node/reporters/renderers/utils.ts
packages/vitest/src/node/watch-filter.ts
pnpm-lock.yaml
test/browser/package.json
test/browser/test/commands.test.ts
test/browser/test/utils.test.ts
test/browser/vitest.config.mts
test/core/package.json
test/core/test/diff.test.ts
test/core/test/environments/jsdom.spec.ts
test/core/test/injector-mock.test.ts
test/core/test/jest-expect.test.ts
test/core/test/mocked.test.ts
test/coverage-test/package.json
test/coverage-test/test/mixed-versions-warning.unit.test.ts
test/coverage-test/utils.ts
test/reporters/package.json
test/reporters/tests/html.test.ts
test/test-utils/cli.ts
test/test-utils/package.json

- TIL ⭐ from this friendly comment that `strip-ansi` has Node built-in replacement: https://github.com/vitest-dev/vitest/discussions/6587#discussioncomment-10801808
- Removes `strip-ansi` from direct dependencies. It's still a transitive dependency of other transitive dependencies from the same author.
https://github.com/vitest-dev/vitest/blob/9edfa19ff172180143ae66c6f61357f2bfa380f0/packages/vitest/package.json#L117-L119
```sh
ari ~/Git/vitest (chore/strip-ansi) $ node
Welcome to Node.js v18.0.0.
Type ".help" for more information.
> util.stripVTControlCharacters
[Function: stripVTControlCharacters]
>
ari ~/Git/vitest (chore/strip-ansi) $ node
Welcome to Node.js v20.0.0.
Type ".help" for more information.
> util.stripVTControlCharacters
[Function: stripVTControlCharacters]
> 
```

refactor: replace `strip-ansi` with `stripVTControlCharacters` from `node:util`

---

packages/runner/src/run.ts
test/core/test/on-finished.test.ts

- closes https://github.com/vitest-dev/vitest/issues/5869
I just hit this issue when writing e2e on Vite.
I moved `callTaskHooks` inside retry/repeat for-loops and it seems okay.

fix(runner): run `onTestFinished` and `onTestFailed` during `retry` and `repeats`

---

docs/config/index.md
packages/browser/src/client/tester/runner.ts
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/public/index.ts
packages/vitest/src/runtime/runners/index.ts
packages/vitest/src/types/general.ts
test/coverage-test/fixtures/test/clean-on-rerun-fixture.test.ts
test/coverage-test/test/changed.test.ts
test/coverage-test/test/clean-on-rerun.test.ts
test/coverage-test/test/custom-provider.custom.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/5521
- Fixes https://github.com/vitest-dev/vitest/issues/6225
- Fixes https://github.com/vitest-dev/vscode/issues/336
Store raw coverage results in filesystem per testfile. When `cleanOnRerun` is disabled, the previous results are overwritten. This invalidates the previous results of the changed files, while preserving previous results of unchanged files.

fix(coverage): `cleanOnRerun: false` to invalidate previous results

---

docs/guide/index.md
packages/vitest/src/node/cli/cli-api.ts
packages/vitest/src/node/packageInstaller.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/reporters/utils.ts
packages/vitest/src/node/workspace.ts

fix(vitest): install dependencies with the same version when prompted

---

packages/vitest/src/runtime/runVmTests.ts
test/core/test/environments/jsdom.spec.ts
test/core/test/environments/node.spec.ts
test/core/vitest.workspace.ts

Fixes #5562
Checked locally that `vmThreads` works on Node.js <21

fix(vitest): make env.SSR consistent between different pools

---

docs/guide/mocking.md
test/core/test/jest-mock.test.ts

docs: document how to mock class and its methods

---

packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/workspace.ts

Fixes #5474
This requires Vite 5.3.0 or higher to work.
Checked locally that it works in `examples/basic`. The `test/core` started the ws server because it always has `api` enabled.

fix(vitest): don't start a websocket server if api is disabled

---

packages/expect/src/jest-expect.ts
packages/expect/src/jest-utils.ts
test/core/test/jest-expect.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6580

fix(expect): preserve prototype in `toMatchObject` diff

---

test/browser/specs/fix-4686.test.ts
test/browser/specs/runner.test.ts
test/browser/specs/server-url.test.ts
test/browser/specs/unhandled.test.ts
test/browser/specs/utils.ts

Currently `runBrowserTests` utility is relying on json reporter output `browser.json`, which is causing a cryptic CI error in https://github.com/vitest-dev/vitest/pull/6512. I rewrote this part to use assertions based on vitest state API.

test: refactor browser test utils

---

packages/vitest/src/public/config.ts
test/config/test/bail.test.ts
test/config/test/failures.test.ts
test/config/test/mixed-environments.test.ts
test/config/test/override.test.ts
test/config/test/shard.test.ts
test/config/test/shuffle-options.test.ts
test/config/test/workers-option.test.ts

Vitest exports its own `UserConfig` from `vitest/node`. Maybe in the future it should replace this export.

fix(vitest): deprecate UserConfig in favor of ViteUserConfig

---

packages/vitest/src/node/config/resolveConfig.ts
test/config/test/failures.test.ts
test/config/vitest.config.ts

fix(vitest): don't hang with maxConcurrency 0

---

examples/lit/package.json
examples/lit/test/basic.test.ts
examples/lit/tsconfig.json
examples/lit/vite.config.ts
examples/workspace/packages/client/test/basic.test.tsx
package.json
pnpm-lock.yaml

chore: update lit example to use the new locators API

---

packages/runner/src/types/tasks.ts
packages/vitest/src/public/index.ts
packages/vitest/src/types/rpc.ts

fix(vitest): deprecate old task types and node-reliant types

---

packages/vitest/src/runtime/console.ts
test/reporters/fixtures/console-interleave.test.ts
test/reporters/tests/console.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6621

fix(vitest): fix `<empty line>` logs when interleaving `console.log/error`

---

packages/browser/matchers.d.ts
packages/browser/src/client/tester/expect-element.ts
packages/expect/src/jest-expect.ts
packages/expect/src/jest-extend.ts
packages/expect/src/utils.ts
packages/vitest/src/integrations/chai/poll.ts
test/browser/test/dom.test.ts

fix(browser): not.toBeInTheDocument works with locators API

---

package.json
pnpm-lock.yaml

`"@vitest/ui": "latest"` in examples is picking up a published version of the package instead of `workspace:*` (see lockfile diff).
Probably it was fine on pnpm v8, but pnpm changed default `link-workspace-packages=false` in v9 https://github.com/orgs/pnpm/discussions/6628, so we need to either explicitly set `pnpm.overrides` or use `link-workspace-packages=true`.

chore: fix `@vitest/ui` overrides

---

.vscode/settings.json
vitest.workspace.vscode.ts

The Vitest monorepo has a lot of configs in tests that the extension picks up. Some of them fail because the test that checks it expects it to fail.
This PR creates a separate workspace config file that should always be picked up by the extension. Feel free to add new projects when testing. I think this is a good way to dogfood the extension.

chore: make Vitest monorepo work with the vscode extension

---

packages/vitest/src/node/reporters/reported-tasks.ts
test/cli/test/reported-tasks.test.ts
vitest.workspace.vscode.ts

Based on how @userquin did this in #6649

perf: reuse full name in reported tasks, update generator types

---

docs/config/index.md

Updates the default `browser.provider` in the docs.

docs: update the default `browser.provider`

---

packages/coverage-istanbul/package.json
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
packages/vitest/src/utils/coverage.ts
pnpm-lock.yaml
test/coverage-test/test/threshold-auto-update.unit.test.ts

- Refactors v8 and istanbul coverage providers by moving re-usable logic into base provider
- Note that we cannot move parts where dependencies of coverage providers are used as we don't want to bring those into `vitest` package

refactor(coverage): move re-usable parts to base provider

---

packages/browser/src/client/tester/msw.ts
packages/browser/src/node/plugin.ts

This change allows users to reuse the established Vitest msw worker instead of overriding it
Fixes #6633

fix(browser): use `/mockServiceWorker.js` instead of `/__vitest_msw__`

---

packages/vitest/src/node/error.ts
packages/vitest/src/node/pools/rpc.ts
test/config/fixtures/rollup-error/not-found-export.test.ts
test/config/fixtures/rollup-error/not-found-package.test.ts
test/config/fixtures/rollup-error/vitest.config.ts
test/config/test/rollup-error.test.ts

- closes https://github.com/vitest-dev/vitest/issues/4011
<details><summary>fixture test run</summary>
- environment: happy-dom
```sh
$ pnpm -C test/config test -- --root fixtures/rollup-error --environment happy-dom
> @vitest/test-config@ test /home/hiroshi/code/others/vitest/test/config
> vitest --typecheck.enabled "--root" "fixtures/rollup-error" "--environment" "happy-dom"
Testing types with tsc and vue-tsc is an experimental feature.
Breaking changes might not follow SemVer, please pin Vitest's version when using it.
DEV  v2.1.2 /home/hiroshi/code/others/vitest/test/config/fixtures/rollup-error
❯ not-found-export.test.ts (0)
❯ not-found-package.test.ts (0)
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
FAIL …
```

fix(vitest): show rollup error details as test error

---

docs/config/index.md
docs/guide/browser/index.md
packages/browser/src/node/plugin.ts

Mention that the browser mode uses 63315 port to not clash with the dev server
Related #6677

docs: mention that the browser mode uses 63315 port

---

packages/vitest/LICENSE.md
packages/vitest/package.json
packages/vitest/rollup.config.js
packages/vitest/src/node/workspace.ts
packages/vitest/src/node/workspace/resolveWorkspace.ts
pnpm-lock.yaml
test/cli/test/__snapshots__/list.test.ts.snap

The team decided to revert to `fast-glob` until the symlink issue is resolved.
We are keeping the `tinyglobby` package in other dependencies.

fix(vitest): use `fast-glob` instead of `tinyglobby` in Vitest

---

packages/expect/src/jest-expect.ts
test/core/test/__snapshots__/jest-expect.test.ts.snap
test/core/test/jest-expect.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6619

 fix: fix error diff of `toBeNaN, toBeUndefined, toBeNull, toBeTruthy, toBeFalsy`

---

packages/browser/src/node/plugin.ts
test/browser/fixtures/server-url/vitest.config.ts
test/browser/specs/server-url.test.ts

Related: https://github.com/vitest-dev/vitest/issues/6677
`resolveApiServerConfig` is not working here and `defaultBrowserPort` is not used as default.

fix(browser): fix default browser port

---

test/ui/playwright.config.ts

It looks like `test/ui` playwright tests are flaky https://github.com/vitest-dev/vitest/actions/runs/11330854757/job/31509575992#step:8:1005 Globally adding retires should be fine for this e2e.

test: add retries to playwright ui tests

---

packages/vitest/src/integrations/css/css-modules.ts
packages/vitest/src/node/cache/index.ts
packages/vitest/src/node/hash.ts
packages/vitest/src/node/pools/rpc.ts
packages/vitest/src/node/sequencers/BaseSequencer.ts
packages/vitest/src/utils/index.ts

`crypto.hash` seems to be faster than `crypto.createHash`.
https://nodejs.org/docs/latest-v20.x/api/crypto.html#cryptohashalgorithm-data-outputencoding)
I did a simple test and `crypto.hash` seems to be 1.6 times faster.

perf: use `hash` to replace `createHash`

---

packages/browser/src/node/plugin.ts
test/browser/specs/runner.test.ts
test/cli/test/server-url.test.ts

fix(browser): optimize expect-type

---

docs/advanced/reporters.md
docs/config/index.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/reported-tasks.ts
test/reporters/tests/merge-reports.test.ts

fix(vitest): clarify slowTestThreshold, print slow tests in non-TTY mode

---

packages/browser/src/node/index.ts
packages/browser/src/node/plugin.ts
packages/vite-node/src/cli.ts
packages/vitest/src/node/create.ts
packages/vitest/src/node/packageInstaller.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/utils.ts
packages/vitest/src/node/plugins/workspace.ts
packages/vitest/src/node/vite.ts
packages/vitest/src/node/viteLogger.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/public/node.ts
test/coverage-test/utils.ts

Fixes #6598
I decided to specify a custom Vite logger by reusing our own. This allows us to reuse the same stdout/stderr. Ideally, Vite should accept the console in the options so we don't need to copy-paste the implementation 😄 
I am keeping `error` in vite-node because it might be a breaking change depending on how it's used

fix(vitest): print warnings form Vite plugins

---

test/reporters/src/data.ts

I'm not sure what exactly Node changed, but our use of artificial `AssertionError` seems affected and ubuntu/node-22 CI is failing https://github.com/vitest-dev/vitest/actions/runs/11397153823/job/31712854371?pr=6732#step:8:1098
I replaced it with a plain error result object.

test: fix test for node 22.10

---

docs/guide/browser/context.md
packages/browser/context.d.ts
packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/runner.ts
packages/browser/src/client/tester/tester.ts
packages/browser/src/node/commands/index.ts
packages/browser/src/node/commands/keyboard.ts
packages/browser/src/node/plugins/pluginContext.ts
test/browser/fixtures/user-event/cleanup1.test.ts
test/browser/fixtures/user-event/cleanup2.test.ts
test/browser/fixtures/user-event/vitest.config.ts
test/browser/specs/runner.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6693
I added `userEvent.cleanup` to reset keyboard state and hooked into ~tester cleanup~ runner `onAfterRunTask`.

fix(browser): cleanup keyboard state

---

docs/guide/profiling-test-performance.md

Just noticed this while reading the docs.
This is a one-line fix, from the sentence "Time spent for colleting all tests in the test files" to "Time spent for collecting all tests in the test files"

Fix minor typo: colleting -> collecting

---

packages/browser/src/client/tester/runner.ts
packages/browser/src/client/tester/tester.ts
test/browser/fixtures/setup-file/browser-setup.ts
test/browser/fixtures/setup-file/module-equality.test.ts
test/browser/fixtures/setup-file/source.ts
test/browser/fixtures/setup-file/vitest.config.ts
test/browser/package.json
test/browser/specs/setup-file.test.ts
test/browser/specs/utils.ts

Fixes https://github.com/vitest-dev/vitest/issues/6690

fix(browser): don't add `v=` queries to setup files imports

---

packages/browser/src/client/tester/runner.ts
packages/browser/src/client/tester/tester.ts
test/browser/fixtures/user-event/cleanup-retry.test.ts
test/browser/specs/runner.test.ts

- related https://github.com/vitest-dev/vitest/pull/6731#issuecomment-2426582220
I just realized it's not cleaning up on retry when using `onAfterRunTask`. I moved it to `onBeforeTryTask` but this fails to cleanup playwright page keyboard on the server, so I also added cleanup in tester level.

fix(browser): user event cleanup on retry

---

docs/config/index.md
packages/browser/rollup.config.js
packages/browser/src/client/public/esm-client-injector.js
packages/browser/src/client/tester/tester.html
packages/browser/src/node/plugin.ts
packages/browser/src/node/pool.ts
packages/browser/src/node/server.ts
packages/browser/src/node/serverOrchestrator.ts
packages/browser/src/node/serverTester.ts
packages/browser/src/node/utils.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/types/browser.ts
test/config/fixtures/browser-custom-html/browser-basic.test.ts
test/config/fixtures/browser-custom-html/browser-custom.test.ts
test/config/fixtures/browser-custom-html/custom-html.html
test/config/fixtures/browser-custom-html/vitest.config.correct.ts
test/config/fixtures/browser-custom-html/vitest.config.custom-transformIndexHtml.ts
test/config/fixtures/browser-custom-html/vitest.config.default-transformIndexHtml.ts
test/config/fixtures/browser-custom-html/vitest.config.error-hook.ts
test/config/fixtures/browser-custom-html/vitest.config.non-existing.ts
test/config/test/browser-html.test.ts
test/test-utils/index.ts

Closes #6394
Closes #6768
This PR adds an option to specify your own HTML file for the Browser Mode. Now Vitest also always calls `transformIndexHtml` plugin hook when serving the tester file.
```ts
test: {
browser: {
testerHtmlPath: './component-testing.html',
},
},
})
```
Since Browser Mode is experimental, this PR can be merged with fixes and doesn't need to follow semver.
TODO
- Non-existing file path 
- Error during `transformIndexHtml`
- Valid HTML
- Valid custom `transformIndexHtml` hook

feat(browser): allow custom HTML path, respect plugins `transformIndexHtml`

---

packages/vitest/src/node/create.ts

fix: don't normalize drive case letter in root

---

packages/browser/src/client/vite.config.ts

Looks like on my Windows laptop the browser build plugin is finishing before Vite finish building the UI and so there is no UI entry point in the dist folder.
With this PR we ensure the `browser/dist/client/__vitest__` folder will always have at least the UI entry point.
/cc @patak-dev IIRC Vite will copy the entry point after building the assets, please confirm this (I think it is true: I deal this it in the PWA plugin)
✔️  confirmed (check step 10 here ;) ) https://vite-pwa-org.netlify.app/guide/cookbook.html#vite-build-cli
Vitest hanging when running any browser test with the UI in my local, running the `test:browser:preview` script  with `--reporter=hanging-process`:

chore: fix browser build plugin

---

packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/workspace.ts
packages/vitest/src/node/viteLogger.ts
test/core/src/relative-import.ts
test/core/test/imports.test.ts

Alternative to https://github.com/vitest-dev/vitest/pull/6784
Arbitrary dynamic import might be fairly common for Vitest users, so we can filter out this specific message from our logger.

fix(vitest): silence import analysis warning

---

packages/vitest/src/node/core.ts
packages/vitest/src/node/pools/rpc.ts
packages/vitest/src/node/reporters/base.ts
test/config/fixtures/dangerously-ignore-unhandled-errors/tests/throw-errors.test.ts
test/config/test/dangerously-ignore-unhandled-errors.test.ts

- `dangerouslyIgnoreUnhandledErrors` should work even when base reporter is not used

fix: `dangerouslyIgnoreUnhandledErrors` without base reporter

---

packages/vitest/src/node/logger.ts
packages/vitest/src/node/reporters/base.ts
test/config/fixtures/unhandled-rejections/setup-unhandled-rejections.ts
test/config/fixtures/unhandled-rejections/tests/example.test.ts
test/config/test/unhandled-rejections.test.ts

- Users should see Vitest handling main thread's `unhandledRejection` even when their custom reporters are not extending Vitest's base reporter
- Basically this moves handling of `unhandledRejection` errors from reporter's responsibility to logger's
This is all preparations for larger reporter improvements.

fix: capture `unhandledRejection` even when base reporter is not used

---

docs/guide/reporters.md

- Environment variables were removed in V2 in favor of reporter options:
https://github.com/vitest-dev/vitest/blob/1a8d67090f00917cb4f31a41df9d7fd4d94277d9/docs/guide/migration.md?plain=1#L137-L142

docs(reporters): junit env variables removed in v2

---

packages/vitest/src/node/core.ts
test/coverage-test/test/all.test.ts

- Fixes bug reported on Discord:
> Reproduction: https://stackblitz.com/edit/vitest-dev-vitest-mxhjvd 
> 
> In this reproduction, basic2.ts is not covered by tests, but also not imported by any file in the repo (the only imported is commented-out). 
> 
> Do the following:
> 
> 1. Stop the command line script
> 2. Run npx vitest --coverage
> 3. Observe that basic2.ts is red (uncovered)
> 4. Press Enter to re-run the test
> 5. Observe that basic2.ts is not in the list anymore and coverage is green.
This has broken in `1.6.0`:

fix(coverage): report uncovered files when re-run by `enter` or `'a'`

---

packages/vite-node/src/hmr/hmr.ts
test/vite-node/src/hmr-throw.js
test/vite-node/test/hmr.test.ts

A `throw` statement in a watched module can sometimes cause `vite-node` itself to crash (when trying to report that error), leading to the original error being lost.
Here is an example of this happening:
https://stackblitz.com/edit/vitest-dev-vitest-agi4oq?file=basic.ts
If you edit the file after the `ready` message is printed, `vite-node` will print the following error:
```
[vite-node] Failed to execute file: 
TypeError: Cannot read properties of undefined (reading 'match')
at warnFailedFetch (file:///home/projects/vitest-dev-vitest-agi4oq/node_modules/vite-node/dist/chunk-hmr.mjs:149:20)
at fetchUpdate (file:///home/projects/vitest-dev-vitest-agi4oq/node_modules/vite-node/dist/chunk-hmr.mjs:137:7)
at async queueUpdate (file:///home/projects/vitest-dev-vitest-agi4oq/node_modules/vite-node …
```

fix(vite-node): top-level throw in module is not reported properly

---

packages/browser/src/node/index.ts
packages/vitest/src/node/workspace/resolveWorkspace.ts
test/workspaces/space_1/test/env-injected.spec.ts

Closes #6706
Fixes #6832
This behaviour is inconsistent with how the CWD works everywhere else (global setup files keep the original one; the plugin callbacks will also keep the original CWD). The team decided to revert it. 
We might explore loading projects in a separate process with a different `CWD` in the future.

fix: don't change the working directory when loading workspace projects

---

packages/browser/src/client/tester/tester.html
packages/browser/src/node/plugin.ts
packages/browser/src/node/serverTester.ts

fix(browser): don't process the default css styles

---

packages/vitest/src/node/workspace/resolveWorkspace.ts

perf: limit workspace project concurrency to available cores

---

packages/vitest/src/node/cli/cli-api.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/workspace.ts
test/test-utils/index.ts
test/watch/test/config-watching.test.ts
test/watch/vitest.config.ts
test/workspaces-browser/space_browser/vitest.config.ts
test/workspaces-browser/vitest.workspace.ts
test/workspaces/vitest.config.ts

fix: stop the runner before restarting, restart on workspace config change

---

packages/browser/src/node/commands/keyboard.ts
test/browser/fixtures/user-event/keyboard.test.ts
test/browser/specs/runner.test.ts

- closes https://github.com/vitest-dev/vitest/issues/6871
_todo_
- workaround by `Input.insertText` like playwright
- webdriverio doesn't support it at all even for `fill` (aka `setValue`).
- for playwright, we can support this by patching `parseKeyDef`, but probably that's too much and users should just use `fill` for emojis.

fix(browser): support non US key input

---

packages/vitest/src/node/logger.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/default.ts
packages/vitest/src/node/reporters/renderers/utils.ts
test/config/test/console-color.test.ts
test/reporters/tests/merge-reports.test.ts

- Improves readability of base reporter's code
- While building other reporter related feature, I had to study base reporter throughly. The code wasn't easy to read so I did some improvements while looking into it. Let's merge these improvements here as their own PR in order to reduce changes of the actual up-coming feature PR.
"Readability" is opinionated term so feel free to suggest changes if some lines don't make sense.

refactor(reporters): base reporter readability improvements

---

packages/vitest/src/node/pools/rpc.ts

- closes https://github.com/vitest-dev/vitest/issues/6882
- requires https://github.com/vitejs/vite/pull/18621
This also needed change on Vitest side since it only checked `error.plugin`. I widen the condition to cover the case without `plugin` for ssrTransform parse error.
Example: https://stackblitz.com/edit/vitest-dev-vitest-reyqqz?file=test%2Fsuite.test.js

fix: print ssrTransform error

---

packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/workspace.ts

Since https://github.com/vitejs/vite/pull/18395, `ssr.resolve.conditions`/`ssr.resolve.mainField`(this does not exist yet, maybe needed?) does not inherit `resolve.conditions`/`resolve.mainFields` anymore.
This PR sets those values by `environments.ssr.resolve.conditions`/`environments.ssr.resolve.mainFields`.
This PR should fix the ecosystem-ci fail for vite-plugin-react.

chore: set `resolve.mainFields` and `resolve.conditions` for SSR environment

---

packages/browser/src/node/pool.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/types/browser.ts

Related #6738
This is not a fix, but it does make the behaviour more consistent.

fix(browser): stop the browser rpc when the pool is closed

---

docs/guide/browser/index.md
packages/browser/src/node/pool.ts
packages/browser/src/node/providers/preview.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/stdin.ts
packages/vitest/src/node/workspace.ts
test/browser/specs/runner.test.ts
test/browser/specs/server-url.test.ts
test/cli/fixtures/browser-multiple/basic.test.js
test/cli/fixtures/browser-multiple/vitest.workspace.ts
test/cli/test/browser-multiple.test.ts
test/config/test/browser-html.test.ts

This PR changes when the vite server is started. Previously, every project initialised a server before the `onInit` hook was called. Now it's initialised right before the tests are queued to run. 
For example, this avoids creating the server when the `--project` filter is used. This also won't start a server in `--standalone` mode until the tests are actually running

fix(browser): init browsers eagerly when tests are running

---

docs/guide/reporters.md
packages/vitest/src/node/reporters/json.ts
test/workspaces/globalTest.ts

feat(vitest): include `coverageMap` in json report

---

docs/config/index.md
packages/vitest/src/node/core.ts
packages/vitest/src/node/globalSetup.ts
packages/vitest/src/node/workspace.ts
packages/vitest/src/public/node.ts
packages/vitest/src/types/general.ts
test/watch/fixtures/global-setup.ts
test/watch/fixtures/vitest.config.ts
test/watch/test/global-setup-rerun.test.ts

feat(vitest): add `onTestsRerun` method to global setup context

---

packages/mocker/src/node/hoistMocksPlugin.ts
test/core/test/injector-mock.test.ts
test/public-mocker/test/mocker.test.ts
test/public-mocker/vite.config.ts

This PR improves source map generation when `vi.mock` is detected. The mock is now present in the source map.
Fixes #6829

fix(browser): improve source maps when `vi.mock` is present

---

packages/runner/src/context.ts
packages/runner/src/errors.ts
packages/runner/src/run.ts
packages/runner/src/types/tasks.ts
packages/vitest/src/node/reporters/renderers/listRenderer.ts
packages/vitest/src/node/reporters/reported-tasks.ts
packages/vitest/src/node/reporters/verbose.ts
packages/vitest/src/node/state.ts
test/cli/fixtures/skip-note/basic.test.ts
test/cli/test/skip-note.test.ts

Fixes #6212 
TODO
Maybe we should rethink the Vitest CLI output? 🤔 I feel like https://playwright.dev/docs/test-annotations#annotate-tests might be quite useful

feat: allow a custom note when calling `ctx.skip()` dynamically

---

docs/guide/test-context.md
packages/runner/src/fixture.ts
packages/runner/src/suite.ts
packages/runner/src/types/runner.ts
packages/vitest/src/runtime/runners/test.ts
test/workspaces/globalTest.ts
test/workspaces/space_shared/test.spec.ts
test/workspaces/vitest.workspace.ts

Continuation of #6253
Related to #6226
This PR allows defining a context value that can be overridden by the project config:
```ts
// vitest.workspace.ts
export default defineWorkspace([
{
test: {
environment: 'jsdom',
provide: {
myValue: 'injected',
},
},
},
{
test: {
environment: 'node',
},
},
])
```
```ts
const test = baseTest.extend({
myValue: ['default', { injected: true }]
})
test('some test', ({ myValue }) => {
// for the jsdom environment
expect(myValue).toBe('injected')
// for the node environment
expect(myValue).toBe('default')
})
```
TODO

feat(runner): test context can inject values from the config's `provide`

---

docs/api/expect.md
packages/expect/src/jest-expect.ts
packages/expect/src/types.ts
pnpm-lock.yaml
test/core/test/jest-expect.test.ts

fix #6045
Hello 👋,
This is my first contribution to Vitest so I really appreciate your feedback.
This PR adds two new test APIs:
- `toHaveBeenCalledBefore` - checks if a spy was called before another spy
- `toHaveBeenCalledAfter` - checks if a spy was called after another spy
The implementation will take a look at the invocation order (first call) of the spies and compare them to determine if the spies were called in the correct order.
I add them to `packages/expect/src/jest-expect.ts` but I'm not sure if this is the best place for them. I also update types but I'm not sure if I did it correctly so I would appreciate your feedback on that.
I add related tests to for these new APIs.
Once everything is ok for you, I will add related documentation!

feat(expect): add `toHaveBeenCalledAfter` and `toHaveBeenCalledBefore` utility

---

packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/optimizer.ts
packages/vitest/src/node/plugins/utils.ts
test/config/test/cache.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6733
- Related https://github.com/vitest-dev/vitest/pull/6902

fix: respect `cacheDir` when optimizer is enabled

---

packages/coverage-v8/src/browser.ts
test/coverage-test/test/bundled-sources.test.ts
test/coverage-test/test/include-exclude.test.ts
test/coverage-test/test/pre-transpiled-source.test.ts
test/coverage-test/test/results-snapshot.test.ts
test/coverage-test/vitest.workspace.custom.ts

- Fixes https://github.com/storybookjs/storybook/issues/29597

fix(coverage): exclude browser mode iframe results

---

packages/pretty-format/package.json
packages/pretty-format/src/plugins/ReactElement.ts
pnpm-lock.yaml
test/core/package.json
test/core/test/snapshot-react-19.test.jsx
test/core/test/snapshot-react.test.jsx

- closes https://github.com/vitest-dev/vitest/issues/6908
I bundled `npm:react-is@19.0.0-rc-b01722d5-20241114` to cover React 19 case out of the box.

fix(pretty-format): support react 19

---

docs/guide/cli-generated.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/utils/base.ts
test/config/test/project.test.ts

This PR allows a leading `!` to negate patterns in the `--project` option, making it possible to exclude certain projects when running `vitest`.

feat(cli): support excluding projects with `--project=!pattern`

---

docs/advanced/api.md
docs/config/index.md
docs/guide/workspace.md
packages/browser/src/node/pool.ts
packages/browser/src/node/server.ts
packages/vitest/src/node/cache/files.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/pools/forks.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vmForks.ts
packages/vitest/src/node/pools/vmThreads.ts
packages/vitest/src/node/project.ts
packages/vitest/src/node/reporters/blob.ts
packages/vitest/src/node/types/config.ts
packages/vitest/src/node/workspace/resolveWorkspace.ts
packages/vitest/src/typecheck/collect.ts
test/config/fixtures/workspace/api/basic.test.ts
test/config/fixtures/workspace/api/vite.custom.config.js
test/config/test/workspace.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/6913
This PR allows specifying an array in `test.workspaces` option. This will override the `vitest.workspace` file if there is one:
```ts
import { defineConfig } from 'vitest'
test: {
workspace: [
'./packages/*',
{
test: {
name: 'inline',
},
},
],
},
})
```

feat: allow inline workspace configuration

---

test/core/test/jest-expect.test.ts
test/core/test/mocked.test.ts
test/core/test/snapshot-file.test.ts
test/core/test/wait.test.ts

I fixed the warning in core test suite.

test: fix async assertion warning

---

docs/config/index.md
docs/guide/browser/assertion-api.md
docs/guide/browser/commands.md
docs/guide/browser/index.md
docs/guide/browser/interactivity-api.md
packages/browser/context.d.ts
packages/browser/matchers.d.ts
packages/browser/package.json

This PR adds more examples on how to make TS see `expect.*` types and also adds missing asymmetrict matchers type definitions:
```ts
expect(elements).toEqual([
expect.toHaveTextContent('First'),
expect.toHaveTextContent('Second'),
])
```
(Asymmetric definitions only support Elements, they don't support locators yet)

fix(browser): explain TypeScript support in docs and add asymmetric matchers to types 

---

docs/config/index.md
packages/vitest/src/node/globalSetup.ts
packages/vitest/src/node/project.ts
test/watch/fixtures/global-setup.ts

feat: provide the current project to the global setup

---

packages/vitest/src/node/reporters/base.ts
test/reporters/tests/default.test.ts
test/reporters/tests/verbose.test.ts

- Fixes `--hideSkippedTests` flag that broke in https://github.com/vitest-dev/vitest/pull/6893

fix(reporters): check `--hideSkippedTests` in base reporter

---

packages/browser/providers/playwright.d.ts
packages/browser/src/node/commands/hover.ts

Currently, when selecting Playwright as the provider, type completion for the options parameter of the click method from @vitest/browser/context's userEvent is not working. This is because when fetching the types for Playwright's options, the possibility of undefined is not eliminated, resulting in a missing interface type. Therefore, I have wrapped it with NonNullable to remove the potential for undefined, which fixes the issue so that type completion now works.
before
after

fix(types): make parameters non-nullable for Playwright options

---

packages/vitest/LICENSE.md
packages/vitest/src/node/core.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/renderers/utils.ts
pnpm-lock.yaml
test/cli/test/__snapshots__/stacktraces.test.ts.snap
test/cli/test/custom-pool.test.ts
test/cli/vitest.config.ts
test/config/test/dangerously-ignore-unhandled-errors.test.ts
test/reporters/tests/indicator-position.test.ts
test/reporters/tests/merge-reports.test.ts
test/test-utils/index.ts
test/test-utils/package.json
test/typescript/test/__snapshots__/runner.test.ts.snap
test/typescript/test/runner.test.ts
test/watch/test/workspaces.test.ts

This PR changes the output to use labels instead of `|` delimiter. We still keep the `|` delimiter if the colours are disabled to have a clear separation.
Related #6481

feat: print project name as a label

---

.gitignore
packages/browser/matchers.d.ts
pnpm-lock.yaml
test/dts-playwright/package.json
test/dts-playwright/src/basic.test.ts
test/dts-playwright/tsconfig.json

While checking the repro for https://github.com/vitest-dev/vitest/pull/6989, I spotted another red squiggles:
It looks like we can catch this issue by tsc without `skipLibCheck`, so I added `test/dts-playwright` for this:
```
$ pnpm -C test/dts-playwright test
> @vitest/test-dts-fixture@ test /home/hiroshi/code/others/vitest/test/dts-playwright
> tsc -b
../../packages/browser/matchers.d.ts:20:66 - error TS2304: Cannot find name 'ExpectPollOptions'.
20     element: <T extends Element | Locator>(element: T, options?: ExpectPollOptions) => PromisifyDomAssertion<Awaited<Element | null>>
~~~~~~~~~~~~~~~~~
Found 1 error.
```

fix(browser): fix matchers.d.ts

---

packages/browser/matchers.d.ts
packages/browser/providers/playwright.d.ts
packages/browser/src/node/commands/clear.ts
packages/browser/src/node/commands/click.ts
packages/browser/src/node/commands/dragAndDrop.ts
packages/browser/src/node/commands/fill.ts
packages/browser/src/node/commands/hover.ts
packages/browser/src/node/commands/screenshot.ts
packages/browser/src/node/commands/select.ts
packages/browser/src/node/providers/playwright.ts
test/browser/fixtures/timeout/timeout.test.ts
test/browser/fixtures/timeout/vitest.config.ts
test/browser/specs/runner.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6983

 feat(browser): support `actionTimeout` as playwright provider options

---

docs/.vitepress/config.ts
docs/config/index.md
docs/guide/index.md
docs/guide/mocking.md
docs/guide/testing-types.md

1. Remove `vitest.config` titles on the "Config Reference" page because it is implied. I kept the names in code groups where we have several files in a single code group
2. Moved Workspace guide after "CLI" and "Test Filtering" since they are arguebly more important to run tests
3. "Performance" is split in two guides in the sidebar now for better visual representation

docs: remove irrelevant `vitest.config` references and update the sidebar

---

packages/vitest/src/node/reporters/base.ts
test/reporters/fixtures/repeats.test.ts
test/reporters/fixtures/retry.test.ts
test/reporters/tests/default.test.ts
test/reporters/tests/verbose.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/7001

fix(reporters): show `retry` and `repeats` counts

---

packages/vitest/src/node/reporters/junit.ts
test/reporters/tests/__snapshots__/reporters.spec.ts.snap
test/reporters/tests/junit.test.ts

not the total time of execution
This addresses 2 problems, one that is general to junit reporter itself, but more debatable, and the other one is merge-reports specific, but is clearly a bug. Let's start with the first one.
1. I haven't found an official junit.xml spec (and I'm not sure if it exists at all), but this document https://github.com/testmoapp/junitxml?tab=readme-ov-file#complete-junit-xml-example suggests that `testsuites.time` is an
> time        Aggregated time of all tests in this file in seconds
which makes sense
But the current implementation uses `new Date().getTime() - this._timeStart.getTime()`, so like, total execution time, including transform, prepare and so on. Which IMO should be changed to aggregated sum
2. When using `--merge-reports --reporter=junit` the …

fix(junit): fix testsuites time to be sum of all testsuite items

---

docs/api/mock.md
docs/api/vi.md
docs/config/index.md
docs/guide/migration.md
packages/mocker/src/automocker.ts
packages/spy/src/index.ts
packages/vitest/src/integrations/vi.ts
test/core/test/jest-mock.test.ts

> [!WARNING]
> This is a breaking change.
See #6378, #6308 
This PR changes the behaviour of `mockReset` to the proposed behaviour of `mockRevert` in #6378.
That is, `spy.mockReset()` will reset the inner implementation of `spy` to its original.
Previously, `spy.mockReset` would reset the inner implementation of `spy` to `() => undefined`.

feat!: `spy.mockReset` changes

---

docs/config/index.md
packages/vitest/src/defaults.ts
patches/@types__sinonjs__fake-timers@8.1.5.patch
pnpm-lock.yaml

This PR removes `toFake` from the default `fakeTimers` options because it forces fake methods that might not be available and leaves out methods that are actually available (like `performance`)
Fixes #4004

fix(vitest)!: don't expose default toFake config

---

docs/api/index.md
packages/runner/src/collect.ts
packages/runner/src/run.ts
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
test/config/fixtures/shuffle/basic.test.ts
test/config/fixtures/shuffle/vitest.config.ts
test/config/test/shuffle-options.test.ts
test/core/test/random.test.ts

- closes https://github.com/vitest-dev/vitest/issues/3922
This PR adds `TestOptions.shuffle` to allow "unshuffling" by `describe("...", { shuffle: false })`.
I noticed that `describe.shuffle` is not inherited to inner suites now, but probably changing this behavior would make sense to align with how `concurrent` works, so this change will be breaking.
One thing to note, when using `config.sequence.shuffle: true`, it's already shuffling all tests (as complained in  https://github.com/vitest-dev/vitest/issues/3922), so this use case is unchanged. What's breaking is when using `describe.shuffle` and using normal `describe` inside like in `test/core/test/random.test.ts`.
_todo_

feat(runner)!: support `describe(..., { shuffle: boolean })` and inherit from parent suite

---

packages/runner/src/collect.ts
packages/runner/src/run.ts
packages/runner/src/suite.ts
packages/runner/src/test-state.ts
packages/runner/src/types.ts
packages/runner/src/types/runner.ts
packages/runner/src/types/tasks.ts
packages/runner/src/utils/index.ts
packages/runner/src/utils/tasks.ts
packages/ui/client/components/views/ViewReport.vue
packages/ui/client/composables/explorer/collector.ts
packages/ui/client/composables/explorer/types.ts
packages/ui/client/composables/explorer/utils.ts
packages/vitest/src/node/reporters/dot.ts
packages/vitest/src/node/reporters/reported-tasks.ts
packages/vitest/src/node/reporters/summary.ts
packages/vitest/src/node/reporters/task-parser.ts
packages/vitest/src/public/index.ts

The `Custom` has beed scheduled for deprecation, but it's not used much. Vitest 3 is a good opportunity to remove it.
Let's remove the type itself in Vitest 4, so it's easier to migrate (the deprecation message is visible in the IDE)

fix: don't use `Custom` type internally

---

docs/api/index.md
docs/guide/migration.md
packages/runner/src/context.ts
packages/runner/src/run.ts
packages/runner/src/types/tasks.ts

Closes https://github.com/vitest-dev/vitest/issues/6132

feat!: pass down context to test hooks

---

packages/vite-node/package.json
packages/vitest/package.json

Yet again, we are using `"^5.0.0 || ^6.0.0"` in `dependencies` because Vitest _requires_ the Vite dependency to be installed. This means that if you don't have Vite installed, Vitest will use the latest Vite 6. Otherwise, it depends on how your package manager works.

feat!: support Vite 6

---

docs/guide/cli-generated.md
packages/vitest/src/node/cli/cli-config.ts

Fixes #7035
The CLI docs state the wrong default value for the --pool option. It was changed from threads to forks in 2.0:
https://vitest.dev/guide/migration.html 
https://vitest.dev/guide/cli.html#pool

docs: Fix documentation default value for the --pool option

---

docs/advanced/api.md
docs/advanced/pool.md
docs/api/expect.md
docs/api/vi.md
docs/config/index.md
docs/guide/browser/locators.md
docs/guide/environment.md
docs/guide/filtering.md
docs/guide/reporters.md
docs/guide/test-context.md
docs/guide/workspace.md

We usually remove "Since Vitest *" when releasing a new major, but lets keep it for changes that were scheduled for Vitest 2.2 because they were not announced
This PR however removes other instances of "Since Vitest" for older versions

docs: replace Vitest 2.2 mentions

---

packages/runner/src/utils/collect.ts
packages/vitest/LICENSE.md
test/cli/test/location-filters.test.ts

Closes #5445.
This is a continuation on my previous PR #6411, with support for matching location of suite.

feat(cli): Support location filters for suites

---

docs/config/index.md
packages/utils/src/diff/normalizeDiffOptions.ts
test/config/test/__snapshots__/diff.test.ts.snap
test/config/test/diff.test.ts
test/core/test/__snapshots__/jest-expect.test.ts.snap
test/core/test/__snapshots__/mocked.test.ts.snap
test/core/test/diff.test.ts
test/core/test/jest-expect.test.ts
test/reporters/tests/__snapshots__/junit.test.ts.snap

- follow up to https://github.com/vitest-dev/vitest/pull/6504#discussion_r1764478255
We've been using `printBasicPrototype: false` for snapshot, but diff formatting was still `true` for some reason.
Before
After

feat: `diff.printBasicPrototype: false` by default

---

packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/locators/preview.ts
test/browser/fixtures/user-event/keyboard.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7007
I moved a preview user event wrapper as `createPreviewUserEvent`, which is uniformly used for `userEvent` API and `Locator` API.

fix(browser): fix user event state on preview provider

---

packages/vitest/src/node/core.ts
packages/vitest/src/node/reporters/base.ts
test/watch/test/stdin.test.ts

- fixes https://github.com/vitest-dev/vitest/discussions/6954
Probably this behavior makes more sense? Currently `-t` cli option also becomes `this.testNamePattern`.

fix: persist cli filters as watch mode file filter

---

packages/browser/src/client/tester/tester.ts
packages/coverage-istanbul/src/index.ts
packages/coverage-v8/src/browser.ts
packages/coverage-v8/src/index.ts
packages/vitest/src/integrations/coverage.ts
packages/vitest/src/node/types/coverage.ts
packages/vitest/src/runtime/runBaseTests.ts
packages/vitest/src/runtime/runVmTests.ts
test/coverage-test/fixtures/setup.isolation.ts
test/coverage-test/fixtures/src/branch.ts
test/coverage-test/fixtures/test/isolation-1-fixture.test.ts
test/coverage-test/fixtures/test/isolation-2-fixture.test.ts
test/coverage-test/test/isolation.test.ts
test/coverage-test/utils.ts
test/coverage-test/vitest.config.ts
test/coverage-test/vitest.workspace.custom.ts

- Fixes https://github.com/vitest-dev/vitest/issues/6736
- Istanbul: Preserve files in coverage state, reset just the counters
- V8: Don't restart coverage collection when same runtime instance is re-used between tests

fix(coverage): correct coverage when `isolate: false` is used

---

packages/mocker/package.json

This avoids warnings like:
```
└─┬ vitest 3.0.0-beta.2
└─┬ @vitest/mocker 3.0.0-beta.2
└── ✕ unmet peer vite@^5.0.0: found 6.0.3
```
when using v3 beta with Vite v6 and pnpm.

feat: support Vite v6 in mocker package

---

packages/vitest/src/node/reporters/base.ts

Before:
After:
The "pass" is especially unnoticeable if there are a lot of skipped tests surrounding it

fix: don't use dim color for succeeded tests

---

packages/vitest/src/node/config/resolveConfig.ts
test/benchmark/fixtures/basic/should-not-run.test-d.ts
test/benchmark/test/basic.test.ts
tsconfig.check.json

- Type tests should be disabled when running `vitest bench`
- Noticed while testing https://github.com/vitest-dev/vitest/pull/7019 against https://github.com/radashi-org/radashi

fix(benchmark): disable type testing while benchmarking

---

docs/api/index.md

The comma in these warnings is not needed and actually disruptive since it breaks up the two clauses even though they're subordinate.

docs: remove disruptive comma

---

packages/vite-node/src/utils.ts
test/core/test/resolve-file-url.test.ts
test/core/test/resolve-file-url~dep.js

- Closes https://github.com/vitest-dev/vitest/issues/7084

fix(vite-node): properly normalize file url import

---

packages/vitest/src/typecheck/parse.ts
test/typescript/test/__snapshots__/runner.test.ts.snap

**Context:**
This PR addresses an edge case outlined in issue #7107 (which also contains a reproduction example). The issue arises when a directory contains multiple tsconfig*.json files, each corresponding to different test workspaces. Merging this may fix #7107 
Example:
In this scenario, each tsconfig file is linked to a separate workspace. However, Vitest might behave undeterministically, because for each tsconfig file found in the same directory, it attempts to write to the same temporary configuration file, `tsconfig.vitest-temp.json`.
This can lead to flaky test results due to broken temp tsconfig files (different content written on top of each other) or wrong config being applied.
---
This PR changes Vitest's temp tsconfig and tsbuildinfo files generation to be unique for each …

fix(typecheck): use unique temp and tsbuildinfo file for each tsconfig file (fix #7107)

---

docs/api/assert.md

docs: fix `increasesBy` description

---

packages/utils/src/diff/index.ts

I fixed `printDiffOrStringify` since `received/expected` perspective is flipped compared to its usage.
https://github.com/vitest-dev/vitest/blob/a37d81c315904d0b0f87d6e6b6b8b2ce6499eab5/packages/utils/src/error.ts#L139
https://github.com/vitest-dev/vitest/blob/a37d81c315904d0b0f87d6e6b6b8b2ce6499eab5/packages/utils/src/diff/index.ts#L293-L295

refactor: correct argument names

---

packages/utils/src/diff/index.ts
test/core/test/diff.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7009
This isn't fool-proof for all situations, but it seems to help dealing with some cases.
For playwright's case, the large formatting happens because of `callToJSON: false`, which is used only when comparing against two different "types" of objects (`ElementHandle` vs `null` in the repro's case). `ElementHandle.toJSON` is something compact like this:
```
Object {
"_guid": "handle@c697bfba7ffbd40d2511ee19416963a8",
"_type": "ElementHandle",
}
```
https://github.com/vitest-dev/vitest/blob/f9a628438a5462436b59dd9bdeffddada19a9e81/packages/utils/src/diff/index.ts#L58-L62
I also noticed `prettyFormat` actually succeeds, but large memory consumption happens probably later when going through RPC etc... So the fix here is to just truncate …

fix(diff): truncate to avoid crash on diff large objects

---

packages/vitest/src/node/core.ts
test/snapshots/test/fixtures/summary-removed/.gitignore
test/snapshots/test/fixtures/summary-removed/basic.test.ts
test/snapshots/test/summary.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7128
It looks like this is a bug since summary's option isn't updated on watch update re-run
https://github.com/vitest-dev/vitest/blob/87c3c4aff63a861431e0a2e44c58ab94aa44791f/packages/snapshot/src/manager.ts#L61

fix(snapshot): fix "obsolete" message on snapshot update re-run

---

packages/utils/src/source-map.ts
packages/vitest/src/typecheck/typechecker.ts
test/typescript/failing/expect-error.test-d.ts
test/typescript/test/__snapshots__/runner.test.ts.snap
test/typescript/vitest.config.fails.ts

- Cherry-picked a fix from https://github.com/vitest-dev/vitest/pull/7124
The bugs is reproducible on Vite 5 as well, so I extracted the fix in a separate PR.

fix(typecheck): fix error test case mapping for `@ts-expect-error`

---

test/cli/test/__snapshots__/fails.test.ts.snap
test/cli/test/fails.test.ts

I replaced `toMatchSnapshot(file)` with a simpler `toMatchSnapshot()` since `file` already appears in a `test.each` title.
Also, `toMatchSnapshot("...")` API has an issue with skipped tests (see https://github.com/vitest-dev/vitest/issues/7113), so it's better to avoid that for now.

test: remove redundant snapshot name

---

packages/vitest/package.json
pnpm-lock.yaml
test/config/package.json
test/config/test/exec-args.test.ts
test/test-utils/package.json

- In https://github.com/vitest-dev/vitest/pull/7019/commits/9c9e69b1f6b089555e5d7ffb570e5efd9f688c9b I had to replace `tinyexec` with `node:child_process`. This PR reverts the change.
- Related upstream fix: https://github.com/tinylibs/tinyexec/pull/41

test: use `tinyexec` for `execArgv` tests

---

packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
pnpm-lock.yaml

- Fixes https://github.com/vitest-dev/vitest/issues/5329

fix(coverage): prevent crash when v8 incorrectly merges static_initializer's

---

packages/snapshot/src/client.ts
packages/snapshot/src/port/state.ts
test/core/test/snapshot-1.txt
test/core/test/snapshot-2.txt
test/core/test/snapshot.test.ts
test/snapshots/test/file.test.ts
test/snapshots/test/fixtures/file/basic.test.ts
test/snapshots/test/fixtures/file/snapshot-1.txt
test/snapshots/test/fixtures/file/snapshot-2.txt

- closes https://github.com/vitest-dev/vitest/issues/6107

fix(snapshot): preserve white space of `toMatchFileSnapshot`

---

packages/browser/src/client/tester/expect-element.ts
packages/vitest/src/integrations/chai/poll.ts
test/browser/specs/runner.test.ts
test/browser/test/expect-element.test.ts
test/core/test/expect-poll.test.ts

Fixes memory leak caused by multiple prettyDOM calls during expect.element retries.
ref: https://github.com/vitest-dev/vitest/issues/7139

fix: only use locator.element on last expect.element attempt (fix #7139)

---

packages/runner/src/utils/collect.ts
test/cli/fixtures/reported-tasks/1_first.test.ts
test/cli/test/reported-tasks.test.ts

- Test cases inside `describe.todo` have `options.mode` as `'run'` after tests have finished. Tests inside `describe.skip` have correct `'skip'` mode.

fix(runner): mark tests of `describe.todo` as `'todo'`

---

packages/browser/context.d.ts

This is a follow-up to #7137 which adds typings to the public interfaces of `@vitest/browser`, ensuring that end users' test files will cleanly pass type checking & IDEs.
I think we could prevent a recurrence of this by adding a type-check step to the `test/browser` job.
Currently, `pnpm exec tsc` is broken when I invoke it under `test/browser`; we would need to fix the issues listed below, which are actually type errors in various other files within the project, or possibly false errors due to local ts mis-configuration. We'd need to fix all nine existing issues, whatever the cause, before adding a type check to CI.
We would also need to add some negative test cases to ensure that _omitting_ the typing of a command actually causes errors.
```
Found 9 errors in 4 files.
Errors  Files
3 …
```

fix: Add Locator typings for nth, first and last.

---

test/browser/fixtures/mocking/import-actual-in-mock.test.ts
test/browser/tsconfig.json

Related https://github.com/vitest-dev/vitest/pull/7176
On my vscode, `blog.tsx` was all red as `.tsx` wasn't included. 
<details>
</details>
After changing `include`, there's still some issues with `pnpm exec tsx` probably because it references internal types. Hopefully they aren't visible to users.
<details>
```
../../packages/browser/utils.d.ts:12:18 - error TS2304: Cannot find name 'Locator'.
12   el?: Element | Locator | null | (Element | Locator)[],
~~~~~~~
../../packages/browser/utils.d.ts:12:46 - error TS2304: Cannot find name 'Locator'.
12   el?: Element | Locator | null | (Element | Locator)[],
~~~~~~~
../../packages/browser/utils.d.ts:17:19 - error TS2304: Cannot find name 'Locator'.
17   dom?: Element | Locator | undefined | null,
~~~~~~~
../test-utils/index.ts:133:19 - error …
```

test: fix some types in `test/browser`

---

packages/utils/src/timers.ts
packages/vitest/src/runtime/console.ts
test/config/fixtures/console-batch/basic.test.ts
test/config/test/console.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7153
It turns out separation between `before/after/test` logs are effectively fixed by https://github.com/vitest-dev/vitest/pull/6944, which added `setTimeout` wrapper. I'm not sure whether this changes is needed but maybe we can discuss. Also having a test like this is nice to have regardless.

fix: batch console logs by microtask

---

packages/snapshot/src/port/state.ts
test/snapshots/test/fixtures/skip-test-custom/__snapshots__/basic.test.ts.snap
test/snapshots/test/fixtures/skip-test-custom/basic.test.ts
test/snapshots/test/skip-test.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7113
Previously only `... \d+` (e.g. `test name 1`) is skipped. I added `... > ...` (e.g. `test name > custom message`) to cover `toMatchSnapshot("...")` case.

fix(snapshot): fix obsoleteness check of `toMatchSnapshot("...")`

---

docs/guide/browser/config.md

docs: fix browser testerhtmlpath link

---

packages/ui/node/reporter.ts

When using html reporter with browser mode, the module graph is using server instead client graph: when serving static html folder the module graph tab not displaying the graph since it is not being generated correctly.

fix(ui): wrong module graph when generating html.meta.json.gz in browser mode

---

packages/ui/client/components/FileDetails.vue
packages/ui/client/components/views/ViewModuleGraph.vue

closes #5363
By default the new `Hide node_modules` check checked. Check screenshots below using https://github.com/vitest-tests/browser-examples/tree/main/examples/react (using ui and browser package from this PR and latest Vitest 3 alpha version).
This PR removes the modules from node_modules in both inlined and externalized entries when `Hide node_modules` enabled before loading the ui (ignores inlined and externalize check states when filtering, `Hide node_modules` is global).
<details>
<summary>Screenshots</summary>
_Hide node_modules_
_Show node_modules_
</details>

feat(ui): allow hide/show node_modules in module graph tab

---

.gitignore
packages/ui/client/composables/client/static.ts
packages/ui/client/composables/explorer/search.ts
packages/ui/client/global-setup.ts
packages/ui/client/test.ts
test/browser/package.json
test/browser/vitest.config.mts
test/core/package.json
tsconfig.check.json

The static module doesn't include the new `rerunTask` added to run individual tests in the new UI, and the `openPromise` not being initialized (`Variable openPromise is used before being assigned.`).
This PR also includes:
- html reporter script in `test/core` and `test/browser`
- add `test/core/html` and `test/browser/html` to `.gitignore`
- include `packages/ui/client` folder in `tsc` typecheck script: fixed failing modules
**FIXED**: We need to check why running the html reporter on `test/browser` doesn't generate the html folder, it is generating the app inside the `test/browser` folder. using `json` reporter and `outputFile: './browser.json`
I'm going to send 2 new PR for:
- ~~fix html reporter output folder when running browser mode~~
- use `vue-tsc` to validate also vue files in …

chore(ui): fix static ui client types

---

packages/ui/client/composables/client/index.ts
packages/ui/client/composables/client/static.ts
packages/ui/client/composables/explorer/tree.ts
packages/ui/node/reporter.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/api/types.ts
packages/vitest/src/node/core.ts
test/reporters/tests/__snapshots__/html.test.ts.snap

The changes in the UI will require the project names in this PR #7157, right now we need to traverse all the files to collect the project names, with this PR we can get them without any async operation.
This PR includes the project names in the UI statically, if there is some change (adding/removing/updating workspace/project), the UI will not reflect the changes (will require page refresh), maybe we can check later if we can expose some method.
**NOTE**: on my local running `test:ci` is failing

feat: add resolved project names to the reporter API

---

packages/browser/src/client/tester/logger.ts
test/browser/specs/runner.test.ts
test/browser/test/timers.test.ts

`performance` used by console wrapper is referencing a global one, which might be mocked. 
I'm not sure if this is intended and actually it might be fine either way since Node's `console.time` implementation seems to actually pick up the mocked `performance` internally (regardless of `--disable-console-intercept`) while Browser devtools console won't get affected by mock. I chose browser devtools behavior.
```js
import { vi, test } from "vitest"
test('console.time', () => {
vi.useFakeTimers()
console.time('test')
console.timeEnd('test')
// on node -> 0ms
// on browser devtools -> 0.09999999962747097
})
```

fix(browser): fix `console.time` with fake timers

---

docs/guide/ui.md

Added more description for connecting UI with right mode to avoid confusion.
While reading the [guide](https://vitest.dev/guide/ui) about Vitest UI, most of us try to run it with `vitest run` and the UI never connects. It is made for `watch` mode. I have added a `warning` about this usage and also mentioned the area where information about `HTML` reported is given for `run` mode.
It's an old issue. I am not creating a new issue for the same. Instead, referencing the previous one which asks for a documentation update to avoid confusion.
Details: #2897

docs: added more description about connecting UI with right mode.

---

docs/advanced/reporters.md
docs/guide/migration.md
packages/vitest/src/node/cli/cli-api.ts
packages/vitest/src/node/reporters/benchmark/index.ts
packages/vitest/src/node/reporters/index.ts
packages/vitest/src/node/specifications.ts
packages/vitest/src/node/types/tests.ts
packages/vitest/src/node/watcher.ts
packages/vitest/src/public/node.ts
packages/vitest/src/public/reporters.ts
test/reporters/tests/task-parser.test.ts

fix: cleanup `vitest/reporters` entrypoint

---

packages/browser/package.json
packages/coverage-istanbul/package.json
packages/coverage-v8/package.json
packages/expect/package.json
packages/pretty-format/package.json
packages/ui/package.json
packages/utils/package.json
packages/vite-node/package.json
packages/vitest/package.json
packages/vitest/src/node/pool.ts
pnpm-lock.yaml
test/config/test/console-color.test.ts
test/core/package.json
test/test-utils/package.json

- Fixes https://github.com/vitest-dev/vitest/issues/7042
- Requires https://github.com/tinylibs/tinyrainbow/pull/3
This should probably be ported to v2 as colors are not working in latest there.

fix: colors on `forks` pool

---

packages/ui/client/components/CodeMirrorContainer.vue
packages/ui/client/components/FileDetails.vue
packages/ui/client/components/views/ViewEditor.vue
packages/ui/client/composables/client/index.ts
packages/ui/client/composables/explorer/collector.ts
packages/ui/client/styles/main.css

We have a regression somewhere, maybe updating Vue dependency, I'm not sure. The problem is that changes included in these 2 PR missing in current version:
- https://github.com/vitest-dev/vitest/pull/1131
- https://github.com/vitest-dev/vitest/pull/1039
This PR adds the draft indicator and the line error to the code editor: tested with test/core and test/browser (only preview).
This PR also includes:
- codemirror optimizations when registering/unregistering the errors entries to remove memory leaks: looks like `destroy` method is missing in v6
- changes the cursor to `wait` when saving the file: [Video showing the cursor](https://streamable.com/27q83g)
- registers the span listener to open the file in the editor (at line and column error), missing in the original PR #1131

fix(ui): add errors and draft state (*) to the code editor

---

test/config/fixtures/exec-args-fixtures/vmThreads.test.ts
test/config/test/exec-args.test.ts
test/dts-fixture/package.json
test/snapshots/generate.mjs
test/snapshots/package.json

Running `test:ci` script on Windows (using Command Prompt or Power Shell) getting the following errors (check screenshots errors below):
- `test/config/test/exec-args.test.ts`: running `vmThreads`  the args using `\\` in the path
- `test/dts-fixture`: the test script running the build command => `rm -rf dist && tsc -p tsconfig.json`
- `test/cli/test/git-changed.test.ts`: I have still no idea  why it is failing (maybe ESLint Service in my WebStorm IDE, now it is working)
- `test/snapshots`: the test script running the build command => `"test:generate": "rm -rf ./test-update && cp -r ./test/fixtures/test-update ./test-update"`
<details>
<summary>test/config/test/exec-args.test.ts error</summary>
This screenshot writting arguments to the console …

chore(test): fix test:ci errors on Windows

---

docs/api/index.md
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
test/core/test/__snapshots__/test-for-suite.test.ts.snap
test/core/test/test-for-suite.test.ts

- Related https://github.com/vitest-dev/vitest/pull/5861
I didn't add `describe.for` initially since test context feature was irrelevant, but I think we said we can still add this for consistency. Also typing `describe.each` is more complicated and I tend to prefer simple `.for` style types.

feat: add `describe.for`

---

packages/runner/src/suite.ts

We're using a custom runner that stores test function results and allows using them in different tests. This works great but recently it stopped working.
I looked into adding a test but couldn't find where the runner is tested. Please let me know.

fix: return test fn result to runner

---

examples/lit/package.json
examples/lit/vite.config.ts
packages/browser/src/client/client.ts
packages/browser/src/client/public/esm-client-injector.js
packages/browser/src/client/utils.ts
packages/browser/src/node/rpc.ts
packages/browser/src/node/serverOrchestrator.ts
packages/browser/src/node/serverTester.ts
packages/vitest/src/node/pools/forks.ts
packages/vitest/src/node/pools/rpc.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vmForks.ts
packages/vitest/src/node/pools/vmThreads.ts
packages/vitest/src/types/rpc.ts
test/cli/fixtures/list/math.test.ts
test/cli/test/list.test.ts

fix(api): don't report events during `vitest list`

---

docs/config/index.md
docs/guide/migration.md
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/plugins/index.ts
test/coverage-test/test/include-exclude.test.ts

- Exclude test files from coverage even when custom `coverage.excludes` is set
cc. @yannbf

fix(coverage)!: always exclude test files

---

docs/guide/mocking.md

File system mocking example would not run as `readHelloWorld` returns a buffer with test assertions expecting a text instead. It seems that the returned value should be a string, which is a simpler solution that to call `.toString()` in the tests. The name of the variable also suggests that text is expected to be returned.

Changed readHelloWorld in exampele 3 to return a string

---

docs/.vitepress/contributors.ts

Proposal to bump @hi-ogawa to better recognize his current work on Vitest. Also added his sponsor link that was missing.

chore: update Hiroshi info in team

---

packages/runner/src/context.ts
test/cli/test/__snapshots__/fails.test.ts.snap
test/cli/test/fails.test.ts

Fixes #7275
- reduce the amount of promises created form 4 to 1
- remove empty `setTimeout`

fix: don't await an empty timeout after every test

---

packages/vitest/src/node/reporters/dot.ts
packages/vitest/src/node/reporters/renderers/windowedRenderer.ts
packages/vitest/src/node/reporters/summary.ts

- Fixes https://github.com/vitest-dev/vitest/issues/7285
- Summary (and dot reporter) now instruct window renderer when an update is needed to render. Window rendered also schedules updates every 1s. In `v3.0.2` and `^v2` Vitest was updating whole terminal every 16ms. 
I'm unable to reproduce this using repro from #7285, but generated artificial test setup inside Windows VM. Using `cmd.exe` the execution time dropped from 50s to 38s in that setup. With Git Bash or Powershell there were no performance issues or any changes. On MacOS I'm unable to reproduce this at all.

perf(reporters): update summary only when needed

---

packages/vitest/src/node/config/resolveConfig.ts
test/config/test/browser-configs.test.ts
test/config/test/failures.test.ts

fix(browser): don't fail when running --browser.headless if the browser projest is part of the workspace

---

.github/workflows/ci.yml

I need to removed this for v1 and v2 backport. I think it's fine to allow this. Vite also does the same https://github.com/vitejs/vite/blob/9654348258eaa0883171533a2b74b4e2825f5fb6/.github/workflows/ci.yml#L28.

ci: allow ci on non main PR

---

packages/browser/jest-dom.d.ts
packages/browser/utils.d.ts
packages/vitest/package.json
packages/vitest/src/utils/debugger.ts

I'm trying to move to vitest browser, and have encountered a few type errors in vitests types.
Some of these may have been caught with `skipLibCheck: false`; I tried that but it opened up a bit of a can of worms, as many other `.d.ts` files contain type errors, both compiled and handwritten, along with third party deps suggesting we're missing some type packages.
This PR at least fixes the issues I've encountered in the field.

fix(types): Fix public types

---

packages/browser/src/node/plugin.ts
packages/ui/client/components/views/ViewReport.vue

I manually tested since we don't have a way to test browser mode UI yet.

fix(browser): restrict served files from `/__screenshot-error`

---

packages/browser/src/node/plugin.ts
packages/ui/client/components/views/ViewReport.vue

fix(browser): (backport #7340 to v2) restrict served files from `/__screenshot-error` 

---

packages/browser/src/node/pool.ts
packages/utils/src/source-map.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/errors.ts
packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/publicConfig.ts
packages/vitest/src/node/plugins/workspace.ts
packages/vitest/src/node/project.ts
packages/vitest/src/node/stdin.ts
packages/vitest/src/node/types/config.ts
packages/vitest/src/node/workspace/resolveWorkspace.ts
test/browser/specs/browser-crash.test.ts
test/cli/fixtures/git-changed/workspace/vitest.workspace.js
test/cli/test/list.test.ts
test/config/fixtures/workspace/config-empty/vitest.config.js
test/config/test/browser-configs.test.ts
test/config/test/failures.test.ts
test/config/test/workspace.test.ts
test/core/test/cli-test.test.ts
test/test-utils/index.ts
test/watch/test/change-project.test.ts

Fixes #7303
Fixes #7308
Fixes #7286
Accidentally fixes #7131
Closes #7146
The idea is to filter out the project during its `config` resolution instead of creating a project and then filtering it. This should make `vitest --project={name}` run faster if you have a lot of projects.

fix: filter projects eagerly during config resolution

---

docs/config/index.md

Thanks for the great testing framework!
I found a mismatch between docs and code for the default `exclude` config.
The current documentation is missing `eslint` and `prettier` in the default exclude patterns. This PR updates the documentation to match the actual implementation.
Reference to actual implementation:
https://github.com/vitest-dev/vitest/blob/v3.0.4/packages/vitest/src/defaults.ts#L13-L19

docs: fix missing eslint and prettier in exclude default config

---

packages/ui/client/components/ProgressBar.vue
packages/ui/client/components/dashboard/TestsFilesContainer.vue

closes #7256 
- Remove progressBar when no tests found.
- Insert message "no testes found" in UI.
[no_tests_found.webm](https://github.com/user-attachments/assets/ff39bc67-114a-4fdf-9ae3-639225937fed)

feat(ui): insert message "no tests found" in ui

---

packages/vite-node/src/utils.ts
test/core/test/resolve-file-url.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7361
I copied `splitFileAndPostfix` from Vite https://github.com/vitejs/vite/blob/2bea7cec4b7fddbd5f2fb6090a7eaf5ae7ca0f1b/packages/vite/src/shared/utils.ts#L36-L42. Vite uses this utility to put back a hash/query for asset urls for example.

fix(vite-node): differentiate file url with hash and query

---

packages/mocker/src/browser/interceptor-msw.ts
packages/mocker/src/browser/mocker.ts
packages/mocker/src/node/resolver.ts
test/browser/fixtures/mocking-out-of-root/project1/basic.test.js
test/browser/fixtures/mocking-out-of-root/project1/vitest.config.ts
test/browser/fixtures/mocking-out-of-root/project2/index.js
test/browser/specs/mocking.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7411
Vite import analysis rewrites workspace linked dep into `/@fs/abs-path/out-side-of-root/some-file.js`, but mock registry contains `/abs-path/out-side-of-root/some-file.js` and thus MSW skips mocking.

fix(browser): fix mocking modules out of root

---

packages/browser/jest-dom.d.ts
test/browser/test/dom.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7380
I think there's some dts specific magic going on as to why standard overload is not working. I couldn't figure that out, so I went for a different way and made a union on argument types, which should achieves the same for user's type safety.

fix(browser): fix `toHaveClass` typing

---

packages/vitest/src/node/workspace/resolveWorkspace.ts
test/browser/fixtures/inspect/vitest.config.ts
test/browser/fixtures/inspect/vitest.config.with-workspace.ts
test/browser/specs/inspect.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/7368

fix(workspace): forward `inspect` related cli options

---

docs/guide/migration.md

I noticed that some parts of the migration guide referred to Vitest 4.0, which I believe should be Vitest 3.0. Then, I’ve updated it.
---
If you have any feedback or suggestions, please let me know.

docs: update wording to Vitest 3.0

---

docs/api/expect.md

close #6558
In #6558 it was mentioned to add a note to `expect.toThrowError`([live](https://vitest.dev/api/expect.html#tothrowerror), [preview](https://deploy-preview-7381--vitest-dev.netlify.app/api/expect.html#tothrowerror)) about the TIP being "sync only".

docs: Add sync-only info to `expect.toThrowError` TIP

---

packages/vitest/src/node/project.ts
packages/vitest/src/node/watcher.ts
test/watch/test/file-watching.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/7398

fix(watch): properly remove cache after removing existing test files

---

packages/ui/client/utils/task.ts
packages/vitest/src/node/reporters/renderers/utils.ts

In terminals using a color scheme with a dark background, project names could end up being unreadable because one of the hard-coded background colors used for project names was black. ~Replacing black with blue~ Setting an explicit foreground color as described in [this comment](https://github.com/vitest-dev/vitest/pull/7371#discussion_r1940082951) solves this problem while also ensuring that project names remain readable in terminals with light backgrounds.
This mitigates an issue that's described in the comments of #6481, although it doesn't implement fully customizable colors, which is the main topic of that issue.
**After:**
**Before:**
There doesn't seem to be any existing test coverage for the colors defined in `formatProjectName()`. It's not immediately obvious to me how I might …

fix: ensure project names are readable in dark terminals

---

packages/browser/src/node/pool.ts

- Fixes #7446 
Allow users to define thread count in browser mode. This is useful when you don't want to allocate all CPUs to Vitest, see linked issue. 
```ts
test: {
minWorkers: 4,
maxWorkers: 4,
browser: {
enabled: true,
headless: true,
provider: "playwright",
instances: [{ browser: "chromium" }],
},
},
});
```

fix(browser): resolve thread count from `maxWorkers`

---

test/coverage-test/fixtures/configs/vitest.config.ts
test/coverage-test/setup.ts
test/coverage-test/test/changed.test.ts
test/coverage-test/test/file-outside-vite.test.ts
test/coverage-test/test/include-exclude.test.ts
test/coverage-test/test/isolation.test.ts
test/coverage-test/test/setup-files.test.ts
test/coverage-test/test/vue.test.ts
test/coverage-test/utils.ts
test/coverage-test/vitest.workspace.custom.ts

- Custom snapshot serializers to simplify outputs of coverage maps

test(coverage): format snapshots with `formatSummary`

---

packages/vitest/src/runtime/workers/base.ts
test/coverage-test/test/isolation.test.ts

- Reverts https://github.com/vitest-dev/vitest/pull/7485
Caused by https://github.com/vitest-dev/vitest/pull/7417. Luckily the completely extra test refactoring PR https://github.com/vitest-dev/vitest/pull/7482 made the summary comparisons more accurate - without this I would have completely missed this. 😰

fix(coverage): preserve moduleExecutionInfo in non-isolated runs

---

docs/config/index.md
packages/vitest/src/node/types/config.ts

The docs haven't been updated to reflect Vitest 2 breaking change of https://github.com/vitest-dev/vitest/pull/5609.

docs: fix `sequence.hooks: 'stack'` as default

---

docs/api/vi.md
docs/config/index.md
packages/vitest/src/integrations/mock/timers.ts
test/core/test/timers-queueMicrotask.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7288

fix: exclude `queueMicrotask` from default fake timers to not break node fetch

---

packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/verbose.ts
test/reporters/fixtures/verbose/example-1.test.ts
test/reporters/fixtures/verbose/example-2.test.ts
test/reporters/tests/default.test.ts
test/reporters/tests/merge-reports.test.ts
test/reporters/tests/verbose.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/7435
Before-after:
Note that this is how it looked like in V2:

fix(reporters): render tasks in tree when in TTY

---

packages/expect/src/types.ts
test/core/test/jest-expect.test.ts

fixes #6967 
This PR fixes a TypeScript error where generic functions passed to `expect.extend` receive an incorrect `this` type. The issue was caused by the missing `& ThisType<T>` in the `MatchersObject` type definition.
I try to add a regression test, but I couldn't find an appropriate test example, so I've attached an image below.
<table>
<tr>
<td align="center"><strong>Current</strong></td>
</tr>
<tr>
<td align="center">
</td>
</tr>
<tr>
<td align="center"><strong>Fixed</strong></td>
</tr>
<tr>
<td align="center">
</td>
</tr>
</table>
---

fix(expect): Correct generic MatchersObject this type in expect.extend

---

packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/locators/index.ts
packages/browser/src/client/tester/runner.ts
packages/browser/src/client/tester/tester.ts
packages/browser/src/client/utils.ts
packages/browser/src/node/commands/keyboard.ts
packages/browser/src/node/plugins/pluginContext.ts
packages/browser/src/node/providers/webdriver.ts
packages/browser/src/node/rpc.ts
packages/browser/src/node/types.ts
packages/vitest/src/node/types/browser.ts

perf(browser): do wdio context switching only once per file

---

test/cli/test/__snapshots__/stacktraces.test.ts.snap
test/cli/test/stacktraces.test.ts

I just noticed I forgot to re-enable these skipped tests. I also replaced `toMatchSnapshot(file)` with `toMatchSnapshot()` since the former cannot track obsolete snapshots.

test: re-enable skipped test for Vite 6

---

packages/browser/src/node/projectParent.ts
packages/utils/src/source-map.ts
pnpm-lock.yaml
test/browser/bundled-lib/package.json
test/browser/bundled-lib/src/a.js
test/browser/bundled-lib/src/b.js
test/browser/bundled-lib/src/index.d.ts
test/browser/bundled-lib/src/index.js
test/browser/package.json
test/browser/specs/runner.test.ts
test/browser/test/failing.test.ts
test/browser/vitest.config.mts

fix(browser): improve source map handling for bundled files

---

packages/vitest/src/integrations/vi.ts
packages/vitest/src/public/browser.ts
packages/vitest/src/public/index.ts

- Fixes #7571
The `integration/spy.ts` file has been vestigial since #2575. It seems to be confusing `rollup-dts-plugin`. Rather than bang our heads against a wall fixing that, remove it and just import/export from `@vitest/spy` directly where referenced.
This appears to fix the output `.d.ts` files.

fix: remove vestigial spy stub, import directly from `@vitest/spy`

---

docs/.vitepress/config.ts

This PR will verify [vitest’s profile on webtoo.ls](https://m.webtoo.ls)
See:
- [how it is set for vite.dev](https://github.com/vitejs/vite/blob/2c51565ec044904a080ef5649034c37f02212c7b/docs/.vitepress/config.ts#L108)
- [verified vite profile](https://m.webtoo.ls/@vite)

docs: verify webtoo.ls profile

---

packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/utils.ts
packages/vitest/src/node/plugins/workspace.ts

Removed `hijackVitePluginInject` so that Vite can remove this compat code in the next major.
https://github.com/vitejs/vite/blob/42ff9b3562d495337036365aba7575f52c4c0209/packages/vite/src/node/plugins/clientInjections.ts#L98-L99
Instead I added `define: { 'process.env.NODE_ENV': 'process.env.NODE_ENV' }`.
Disabling the `process.env.NODE_ENV` replacement with `define: { 'process.env.NODE_ENV': 'process.env.NODE_ENV' }` is supported by Vite 3.0.0+ (https://github.com/vitejs/vite/commit/ec52baa17ef2cf35d8133ddec2a7f6970be6c913).

chore: remove hijackVitePluginInject

---

docs/guide/index.md

According to this page it is first in Vitest 4:
https://vitest.dev/config/#configuring-vitest

Fix wrong reference version.

---

docs/.vitepress/config.ts

Netlify build is failing 
- https://github.com/vitest-dev/vitest/pull/7609/checks?check_run_id=38344680615
- https://app.netlify.com/sites/vitest-dev/deploys/67ca2d036c11e50008038553
<details>
```
8:19:24 AM:   vitepress v2.0.0-alpha.3
8:19:24 AM: - building client + server bundles...
8:19:28 AM: ✗ Build failed in 3.54s
8:19:28 AM: ✗ building client + server bundles...
8:19:30 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
8:19:30 AM: build error:
8:19:30 AM: [vite-plugin-pwa:build] Language `js` not found, you may need to load it first
8:19:30 AM: file: /opt/build/repo/docs/advanced/reporters.md
8:19:30 AM: [vite-plugin-pwa:build] Language `js` not found, you may need to load it first
8:19:30 AM: file: …
```

docs: fix shiki twoslash build error

---

packages/vitest/src/node/plugins/publicConfig.ts
test/config/test/browser-configs.test.ts
test/config/test/override.test.ts
test/config/vitest.config.ts

Currently we get a huge wall of logs like this https://github.com/vitest-dev/vitest/actions/runs/13711813132/job/38349623334?pr=7621#step:8:458
```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
Error: intentional unhandled rejection
❯ fixtures/unhandled-rejections/setup-unhandled-rejections.ts:2:42
❯ Object.setup fixtures/unhandled-rejections/setup-unhandled-rejections.ts:2:8
❯ TestProject._initializeGlobalSetup ../../packages/vitest/dist/chunks/cli-api.DIBEqC3b.js:10464:53
❯ Vitest.initializeGlobalSetup ../../packages/vitest/dist/chunks/cli-api.DIBEqC3b.js:12943:7
❯ ../../packages/vitest/dist/chunks/cli-api.DIBEqC3b.js:12854:9
❯ Vitest.runFiles ../../packages/vitest/dist/chunks/cli-api.DIBEqC3b.js:12883:12
❯ Vitest.start ../../packages/vitest/dist/chunks/cli-api.DIBEqC3b.js:12764:21
❯ startVitest …
```

fix: cleanup vitest in public `resolveConfig` API

---

test/config/test/unhandled-rejections.test.ts

Modifying the test case since source map isn't handled for global setup error, which have manifested in https://github.com/vitest-dev/vitest/pull/7509 and https://github.com/vitest-dev/vitest/pull/7621.

test: ignore broken unhandled rejection error stack test

---

packages/expect/src/jest-expect.ts
test/core/test/jest-expect.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7573#issuecomment-2705573743

fix: fix `toHaveBeenCalledWith(asymmetricMatcher)` with `undefined` arguments

---

packages/vitest/src/node/pools/rpc.ts

This fixes https://github.com/vitest-dev/vitest/issues/6976. `writeFile` does not atomically write the file, and when the file is read by the other thread, it can (if the timing is _just wrong_), read an empty file. In the most common case, the `/@vite/env` module empty, and defines don't show up. In principle, however, I believe it can happen with any file.
- There is a test case repository (https://github.com/timothympace/vitest-define-bug), which fails on master, and runs for hours and hours with this fix. I don't think it'll be easy to create a test case that causes the error reliably in this repository.
- there are some errors locally that appear to be environment related, not related to my change.

fix: Race condition in RPC filesystem cache.

---

packages/browser/package.json
packages/browser/src/node/plugin.ts
pnpm-lock.yaml

This reverts commit 5387a5b3bfc62048dd5210bd65f894b43367563a.
It is actually used by `user-event`. Removing it from dependencies breaks certain package managers like Yarn PnP even if preview provider is not used.

Revert "fix(browser): remove @testing-library/dom from dependencies #7555)"

---

packages/web-worker/src/shared-worker.ts
packages/web-worker/src/worker.ts
test/core/src/web-worker/eventListenerWorker.ts

In jsdom + vitest web-workers, I get issues when calling `removeEventListener` from `self`.
`'removeEventListener' called on an object that is not a valid instance of EventTarget`
I tracked this down to the inserted `context` that web-worker inserts. This PR fixes it.
^ Test that fails before my patch

fix(web-worker): ensure `removeEventListener` is bound to worker

---

test/vite-node/src/deps.ts
test/vite-node/test/hmr.test.ts

Related
- https://github.com/vitest-dev/vitest/pull/7480
- https://github.com/vitejs/vite/pull/19624
- https://github.com/vitest-dev/vitest/pull/7652
There were some files importing css, but weren't used as tests. This verifies css import is working on vite-node.

test(vite-node): test css import

---

test/cli/fixtures/fails/hooks-timeout-before-hook-cleanup-callback.test.ts

- Related https://github.com/vitest-dev/vitest/pull/7500
Oops, I just noticed the test case added in https://github.com/vitest-dev/vitest/pull/7500 wasn't actually timing out during cleanup.

test: test hook cleanup timeout correctly

---

packages/utils/src/display.ts
test/core/test/utils-display.spec.ts

Closes #7634
```bash
%s: Objects that have no user defined toString function are inspected using util.inspect() 
```

fix: support custom toString method in %s format

---

packages/ui/client/components/FileDetails.vue
packages/ui/client/components/explorer/ExplorerItem.vue
packages/ui/client/composables/explorer/collector.ts
packages/ws-client/rollup.config.js
packages/ws-client/src/index.ts

- Related https://github.com/vitest-dev/vitest/pull/7609
`export * from '../../vitest/src/utils/tasks'` was the blocker, but the usage seems pretty low, so it's probably fine to remove it. Not sure if this should be marked as breaking change though. At least, there's no package level dependent on npm https://www.npmjs.com/package/@vitest/ws-client?activeTab=dependents.

refactor(ws-client): remove utils re-export

---

docs/api/mock.md
test/core/test/jest-mock.test.ts

I got still confused with the difference between `mockReset` and `mockRestore`, so I added an example to highlight the difference.

docs: add mockClear/mockReset/mockRestore examples

---

.github/actions/setup-and-cache/action.yml
.github/renovate.json5
.github/workflows/ci.yml
.github/workflows/cr.yml
.github/workflows/ecosystem-ci-trigger.yml
.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/lock-closed-issues.yml
.github/workflows/publish.yml
docs/guide/improving-performance.md

Closes https://github.com/vitest-dev/vitest/issues/7686
Picked the latest commits that match the current versions. See changelogs below for matching commits. I did not read source codes (or the compiled minified `dist/index.js`) of each action, so if they are already compromised somehow we'll now lock into those versions. 🤷 
- https://github.com/pnpm/action-setup/releases
- https://github.com/browser-actions/setup-chrome/releases
- https://github.com/tibdex/github-app-token/releases
- https://github.com/browser-actions/setup-firefox/releases
- https://github.com/dessant/lock-threads/releases

ci: pin third party actions to commit shas

---

docs/api/index.md
packages/runner/src/suite.ts
test/core/test/each.test.ts
test/reporters/fixtures/default/print-index.test.ts
test/reporters/tests/default.test.ts

Jest v30 planned to introduce `%$` option which adds the number of the test to its title within `each()` method by https://github.com/jestjs/jest/pull/14710. This PR imports this feature into Vitest.

feat: Introduce `%$` option to add number of the test to its title

---

docs/config/index.md
docs/guide/cli-generated.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/default.ts
packages/vitest/src/node/reporters/dot.ts
packages/vitest/src/node/types/config.ts
test/reporters/fixtures/console-some-failing.test.ts
test/reporters/tests/github-actions.test.ts
test/reporters/tests/json.test.ts
test/reporters/tests/silent.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/6272
Adds `--silent=passed-only` that can be used to print logs from failing tests only.

feat(reporter): `--silent=passed-only` to log failed tasks only

---

docs/api/index.md
packages/runner/src/suite.ts
test/reporters/fixtures/test-for-title.test.ts
test/reporters/tests/default.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7511
This would be a bit of breaking change since `$0`, `$1`, ... weren't replaced previously.

feat: allow array element for `test.each/for` title formatting

---

docs/api/index.md
packages/runner/src/context.ts
packages/runner/src/types/tasks.ts
test/cli/fixtures/fails/skip-conditional.test.ts
test/cli/test/__snapshots__/fails.test.ts.snap
test/reporters/fixtures/default/a.test.ts
test/reporters/tests/default.test.ts
test/reporters/tests/junit.test.ts

I was writing tests and notice that it would be nice to have this during the test in case users provide `text.extend` overrides and can't use `test.skipIf()` during collection:
```ts
test('some test', { custom, skip } => {
skip(custom === 'value', 'not supported')
})
```

feat(vitest): allow conditional `context.skip(boolean)`

---

packages/vitest/src/node/reporters/base.ts
test/reporters/fixtures/pass-and-skip-test-suites.test.ts
test/reporters/tests/default.test.ts
test/reporters/tests/verbose.test.ts

- Skipped suites should be hidden when `--hideSkippedTests` is used.
Noticed this verbose noise in my project even when using `hideSkippedTests: true`:
With this fix it becomes much easier to read:

fix(reporter): `--hideSkippedTests` should hide suites too

---

packages/runner/src/run.ts

- Closes https://github.com/vitest-dev/vitest/issues/7698
<details><summary>Comparison screencasts</summary>
Before
https://github.com/user-attachments/assets/35027792-7343-48a4-9b60-f0bf76398180
After
https://github.com/user-attachments/assets/d369446c-1bd0-432a-bddf-4ac979a3c653
</details>

fix: update test stats regularly

---

package.json
pnpm-lock.yaml
pnpm-workspace.yaml
test/browser/package.json
test/cli/package.json
test/cli/test/inspect.test.ts

(Supersedes) Closes https://github.com/vitest-dev/vitest/pull/7716

chore(deps): use catalog for ws in tests

---

.github/renovate.json5

This should not be picked up by renovate. see https://github.com/vitest-dev/vitest/pull/7180

chore: ignore react-is-18 on renovate

---

packages/runner/src/types/tasks.ts
packages/vitest/src/runtime/external-executor.ts
packages/vitest/src/runtime/vm/commonjs-executor.ts
packages/vitest/src/runtime/vm/esm-executor.ts
packages/vitest/src/runtime/vm/vite-executor.ts
test/cli/test/setup-files.test.ts
test/cli/test/stacktraces.test.ts
test/cli/test/vm-threads.test.ts
test/core/test/diff.test.ts
test/core/test/env.test.ts
test/core/test/timeout.spec.ts
test/core/vitest.workspace.ts
test/coverage-test/test/isolation.test.ts

Vitest did not properly cache synthetic modules. After adding the cache, flakiness disappears. I wasn't able to reproduce this with a simple setup, unfortunately, so I am still not sure what exactly caused the crashes to happen.

fix: fix vm tests flakiness

---

docs/guide/browser/index.md
packages/vitest/src/create/browser/creator.ts
packages/vitest/src/create/browser/examples.ts

As discussed in #7696, I've made a package for rendering Lit components in Vitest Browser mode.
This PR updates the docs and `vitest init browser` to include this as an option.
- _Doesn't seem to be tests for the creator command line - if I just missed it let me know_

feat: Added `vitest-browser-lit` to `vitest init browser` and docs

---

packages/utils/src/diff/normalizeDiffOptions.ts
test/config/test/__snapshots__/diff.test.ts.snap
test/config/test/diff.test.ts
test/core/test/jest-expect.test.ts

- https://github.com/vitest-dev/vitest/issues/4385
- follow up to https://github.com/vitest-dev/vitest/pull/6740
I just saw a huge useless diff and remembered we didn't change the default yet. I'm not sure if we discussed about the default. Starting this PR to revive the discussion if we haven't.

fix: set `diff.expand: false` as default

---

packages/runner/src/run.ts
packages/vitest/src/node/test-run.ts
packages/vitest/src/utils/tasks.ts
test/reporters/tests/test-run.test.ts

Noticed in #7738 and it buggs me a lot

fix(reporter): report tests in correct order

---

packages/vitest/globals.d.ts

Adds a new global variable `chai` declared inside `packages/vitest/globals.d.ts`
Closes #7474

fix: add global `chai` variable in `vitest/globals` (fix: #7474)

---

packages/vitest/src/node/config/resolveConfig.ts
test/config/test/public.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/7772

fix: prevent modifying `test.exclude` when same object passed in `coverage.exclude`

---

packages/runner/src/run.ts
test/cli/test/skip-note.test.ts
test/core/test/hooks.test.ts

fix(runner): correctly call test hooks and teardown functions

---

packages/vitest/src/node/project.ts
test/browser/vitest.config.mts

Fixes https://discord.com/channels/917386801235247114/1356658374317445311
Fixes #7784
The following code (introduced in https://github.com/vitest-dev/vitest/pull/7605) fails when `transform` is called before full server initialization (e.g. `configureServer(server) { server.ssrLoadModule }` like sveltekit https://github.com/sveltejs/kit/blob/f4ce1856ad9ea446c424bd818b25ae89e34a0692/packages/kit/src/exports/vite/dev/index.js#L400).
```js
const browser = await createBrowserServer({
...
filter() {
// Cannot access 'browser' before initialization
id.includes(browser.vite.config.cacheDir))
}
})
```
I changed this to obtain `cacheDir` through a separate `configResolved` hook, which should be guaranteed to be defined earlier.

fix(browser): fix transform error before browser server initialization

---

packages/runner/src/suite.ts
test/core/test/test-extend.test.ts

- Closes https://github.com/vitest-dev/vitest/issues/7813
- Closes https://github.com/vitest-dev/vitest/issues/7793

fix: fix test.scoped inheritance

---

packages/ui/client/pages/index.vue

This PR fixes a bug I just found where if you resize the left panel (the one with the list of tests), it adds pointer-events: none; to the tester-ui div which removes the ability to click on whatever you are testing. I have not tested this but I think this change will fix it. 
To reproduce :
1. Open vitest browser UI with a clickable component (like the react example) 
2. Click on the component (should work)
3. Resize the left panel
4. Click on the component (should not work since there is a pointer-events: none; )

fix: remove pointer-events-none after resizing the left panel

---

packages/runner/src/suite.ts
test/config/fixtures/hook-timeout/basic.test.ts
test/config/test/__snapshots__/hook-timeout.test.ts.snap

- Related https://github.com/vitest-dev/vitest/pull/7502
https://github.com/vitest-dev/vitest/pull/7502 added error stack for hooks, but I forgot to use it for test function. This still avoids unconditionally accessing `stackTraceError.stack` since that's where custom `prepareStackTrace` kicks in and it might be costly. It's only accessed either when `includeTaskLocation` enabled or actually timeout error occurs.

fix(runner): show stacktrace on test timeout error

---

docs/guide/coverage.md
docs/guide/profiling-test-performance.md
packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
packages/vitest/src/node/coverage.ts

- Expose code coverage debug timers via `DEBUG=vitest:coverage` environment variable
- Adds documentation for code coverage performance profiling
I've seen and heard reports about slow code coverage report generation in past. Always user's projects have been picking some minified JS due to agressive `coverage.all` (to be fixed in https://github.com/vitest-dev/vitest/issues/6956), and processing those makes Vite transform and other processing really slow.
With `DEBUG=vitest:coverage` users should be able to detect such files when Vitest seems to be "stuck".

fix(coverage): expose profiling timers

---

docs/guide/improving-performance.md

The docs suggest running `vitest --merge-reports` but since the `vitest` command runs test in _watch mode_ by default, you are getting the following error:
```
Error: Cannot merge reports with --watch enabled
```
The solution here is either use explicit `vitest run` or make the `--merge-reports` flag turn off the watch mode implicitly. 
I am generally not a fan of implicit magic, so I'm proposing an easier solution to update the docs so merging the reports works as expected. This is also an incremental solution to the broken suggestion, and it doesn't require any work on Vitest itself.

docs: suggest `vitest run` in `--merge-reports` usage

---

test/test-utils/index.ts

- This mostly affects local usage where CPU count is higher than CI's 2 cores
- Vitest spawns max amount of workers always. When we run Vitest inside Vitest, we are running 2*`CPU_COUNT` the amount of workers the CPU count should handle.

test: reduce max thread count when vitest-in-vitest

---

docs/api/vi.md

A fix for at typo under the section vi.useRealTimers section of the vi.md docs

docs:  Fixed typo under vi.useRealTimers section

---

packages/vite-node/src/client.ts
test/core/test/fixtures/named-overwrite-all/dep1.js
test/core/test/fixtures/named-overwrite-all/dep2.js
test/core/test/fixtures/named-overwrite-all/main.js
test/core/test/named-overwrite-all.test.ts

- Related https://github.com/vitejs/vite/pull/19534
- Closes https://discord.com/channels/804011606160703521/1362130204595720343/1362130204595720343
Porting https://github.com/vitejs/vite/pull/19534 to fix https://github.com/vitejs/vite/issues/19525 on Vite-node. I forgot we need to have the same thing here when the fix is in runtime but not in transform.
The bug is now always happen when ssr transform hoists each named export https://github.com/vitejs/vite/pull/18983.

fix(vite-node): named export should overwrite export all

---

packages/mocker/src/node/resolver.ts
test/browser/fixtures/mocking-out-of-root/project1/basic.test.js
test/browser/fixtures/mocking-out-of-root/project1/imported-test.js
test/browser/fixtures/mocking-out-of-root/project1/lib.js
test/browser/fixtures/mocking-out-of-root/project3/imported-test.js
test/browser/fixtures/mocking-out-of-root/project3/index.js
test/browser/fixtures/mocking-out-of-root/project3/lib.js

- Closes https://github.com/vitest-dev/vitest/issues/7595
It seems like a very odd use case to call `vi.mock` from outside of root, but `join(root, importer)` also felt a bit odd. Not sure when that happens. If this is necessary, then we could also call another `resolveId` to resolve `importer` itself. (Well, it looks like this happens with custom mock server usage like in `teste/public-mocker`.)

fix(browser): fix mocking from outside of root

---

packages/vitest/optional-types.d.ts
packages/vitest/rollup.config.js
packages/vitest/src/integrations/env/jsdom.ts
packages/vitest/src/types/happy-dom-options.ts
packages/vitest/src/types/jsdom-options.ts
test/dts-config/happy-dom-patch.ts
test/dts-config/tsconfig.json
test/dts-config/tsconfig.patch.json
test/dts-fixture/tsconfig.check.json
test/dts-fixture/tsconfig.json
test/dts-playwright/tsconfig.json

- Related https://github.com/vitest-dev/vitest/discussions/7792
Using the same idea as https://github.com/vitejs/vite/pull/18460.
It looks like happy-dom's dts includes invalid types (though largely completion should work), so it's breaking `test/dts-config` which tests with `skipLibCheck: false`.
```sh
node_modules/.pnpm/happy-dom@17.4.4/node_modules/happy-dom/lib/nodes/node/ICachedQuerySelectorResult.d.ts:4:21 - error TS2344: Type 'Element | null' does not satisfy the constraint 'WeakKey'.
Type 'null' is not assignable to type 'WeakKey'.
4     result: WeakRef<Element | null> | null;
~~~~~~~~~~~~~~
```
For now, I add a hack in `test/dts-xxx` to not pick up this error.

fix: use happy-dom/jsdom types for `envionmentOptions`

---

packages/ui/client/components/BrowserIframe.vue
packages/ui/client/components/explorer/Explorer.vue
packages/ui/client/composables/navigation.ts
packages/ui/client/pages/index.vue

The problem was about restoring the sizes using `@ready` event in the root split pane: there was some race condition between local storage and the event handling.
There is also similar problem with the `Hide/Show Right Panel` button in browser mode when hidding the right panel and initial load or page refresh: showing `Hide Right Panel` button instead `Show Right Panel`.
This PR also includes:
- use resize observer in Explorer.vue to change the filter based on its width instead on main and panels sizes: on initial load or page refresh sometimes the filter with wrong grid columns (the filter will not change while resizing until resized).
- increase the navigator percentage to 15% in BrowserIFrame.vue to show the `Show Navigation Panel` button (browser mode).
closes #6678
supersedes #6679

fix(ui,browser): load panel sizes from storage on initial load

---

docs/config/index.md
docs/guide/index.md
docs/guide/workspace.md

Added more clarifications about how workspace works and moved the vitest config example to the front.
Should we outright say that users should use the `workspace` property instead of the workspace file? In that case, should we deprecate the workspace file?

docs: clarify workspace docs

---

packages/vite-node/src/client.ts
packages/vite-node/src/utils.ts
packages/vitest/src/runtime/external-executor.ts
packages/vitest/src/runtime/vm/vite-executor.ts
test/cli/fixtures/vm-threads/not-found.test.ts
test/core/test/dynamic-import.test.ts
test/core/test/imports.test.ts
test/core/test/web-worker-jsdom.test.ts

fix(vite-node): add ERR_MODULE_NOT_FOUND code error if module cannot be loaded

---

docs/guide/mocking.md

There are no issues open for this PR, I opened it directly to suggest some changes to the docs, I hope this approach is ok.  
When I was checking the documentation for mocking classes, I found out that some recommendations are incorrect, and in general, I found it a bit more convoluted than the recommendation from Jest.  
Because of that, I always refer to the [Jest docs for mocking classes](https://jestjs.io/docs/es6-class-mocks).  
I opened this PR to try to improve the docs.
When I mention "convoluted", it's more a matter of taste, and I could remove the changes from this PR if the maintainers don't think it's useful.   
What I changed is removing references to `this` and `prototype` as much as possible, which can be confusing topics in JS in general, and used a more explicit and …

docs: improve mocking classes section

---

package.json
packages/vitest/LICENSE.md
packages/vitest/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

- Closes https://github.com/vitest-dev/vitest/issues/7598
Vite already unbundles this https://github.com/vitejs/vite/pull/19487, so we should unbundle to deduplicate.

chore(deps): unbundle tinyglobby and update

---

packages/browser/src/client/client.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/plugins/workspace.ts
packages/vitest/src/node/workspace/resolveWorkspace.ts
test/config/fixtures/browser-no-config/vitest.config.ts
test/config/fixtures/no-browser-workspace/vitest.config.ts
test/config/test/browser-configs.test.ts
test/config/test/failures.test.ts
test/test-utils/index.ts

Fixes  #7521
Let's complicate config resolution even further!

fix(browser): correctly inherit CLI options

---

packages/vitest/src/node/core.ts

The cache is not mandatory. No reason to abort when it fails.
This can happen when node_modules is not writable for example.

fix: ignore failures on writeToCache

---

docs/config/index.md
docs/guide/coverage.md
packages/coverage-v8/package.json
packages/coverage-v8/src/provider.ts
packages/vitest/src/node/types/coverage.ts
pnpm-lock.yaml
test/coverage-test/fixtures/src/ignore-hints.ts
test/coverage-test/test/configuration-options.test-d.ts
test/coverage-test/test/file-outside-vite.test.ts
test/coverage-test/test/ignore-hints.test.ts
test/coverage-test/utils.ts
test/coverage-test/vitest.workspace.custom.ts

- Adds support for experimental AST-aware V8 coverage remapping
- Vitest v3 will default to old `v8-to-istanbul`, but switches to `ast-v8-to-istanbul` when `experimentalAstAwareRemapping: true` is set.
- If all goes well, we can remove `v8-to-istanbul` in Vitest v4 (https://github.com/vitest-dev/vitest/issues/7928)
- Right now the `provider.ts` is a bit of mess as it supports both remappers. Once `v8-to-istanbul` can be dropped, it will simplify quite much
- Tests start and run as fast as with previous `@vitest/coverage-v8`. Report accuracy is as good as with `@vitest/coverage-istanbul`. Report generation is slightly slower than with previous `@vitest/coverage-v8`, but faster than overall istanbul provider run. 
- Fixes https://github.com/vitest-dev/vitest/issues/6300
- Fixes …

feat(coverage): v8 experimental AST-aware remapping

---

docs/config/index.md
docs/guide/workspace.md
packages/ui/client/components/explorer/ExplorerItem.vue
packages/ui/client/composables/client/index.ts
packages/ui/client/composables/client/static.ts
packages/ui/client/composables/explorer/tree.ts
packages/ui/client/composables/explorer/utils.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/api/types.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/plugins/utils.ts
packages/vitest/src/node/plugins/workspace.ts
packages/vitest/src/node/project.ts
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/reporters/benchmark/reporter.ts
packages/vitest/src/node/reporters/renderers/utils.ts
packages/vitest/src/node/reporters/summary.ts
packages/vitest/src/node/reporters/verbose.ts
packages/vitest/src/node/types/browser.ts
packages/vitest/src/node/types/config.ts
packages/vitest/src/public/index.ts
packages/vitest/src/types/general.ts
test/core/vitest.workspace.ts
test/coverage-test/vitest.workspace.custom.ts
test/reporters/fixtures/project-name/example.test.ts
test/reporters/fixtures/project-name/vitest.config.ts
test/reporters/tests/__snapshots__/html.test.ts.snap
test/reporters/tests/default.test.ts
test/test-utils/index.ts

- Fixes https://github.com/vitest-dev/vitest/issues/6481
```ts
test: {
workspace: [
{
test: {
name: { label: "Unit", color: "green" },
},
},
{
test: {
name: { label: "Browser" }, // Uses default color picking
},
},
{
test: {
name: "Database", // Uses default color picking
},
},
],
},
});
```
_Note: Text color on CLI is terminal specific. Setting both background color and text color doesn't work at least in VSCode terminal. You can set either background or text color, not both._

feat: support custom colors for `test.name`

---

docs/guide/browser/playwright.md
packages/browser/providers/playwright.d.ts
packages/browser/src/node/providers/playwright.ts
pnpm-lock.yaml
test/browser/fixtures/playwright-connect/basic.test.js
test/browser/fixtures/playwright-connect/vitest.config.js
test/browser/package.json
test/browser/specs/playwright-connect.test.ts

This PR adds the ability to use the Playwright browser provider with remote Playwright servers. Playwright itself doesn't support running on all distributions, it is primarily tested against Debian-based distributions. Notably Playwright doesn't support running on Red Hat Enterprise Linux and derived distributions. To solve this use case Playwright allows its client and server to run on different hosts, so the server may be launched on a supported distribution (see https://playwright.dev/docs/docker#remote-connection). By offering the client connect mode as an alternative to the launch mode we make browser mode available for more distributions.

feat: Implement connect option for playwright browser provider

---

docs/advanced/api/plugin.md

This fixes a typo in the `injectTestProjects` documentation which was referencing the `configFile` attribute instead of `extends` in the instructions to inherit the user's config.
See: https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/types/config.ts#L1134

docs: use `extends` instead of `configFile` in `injectTestProjects`

---

docs/api/expect.md
packages/vitest/src/types/global.ts

The vitest docs use the term _"hint"_ in several places<sup>[[1]](https://vitest.dev/api/expect.html#tomatchsnapshot)[[2]](https://vitest.dev/guide/snapshot.html#_3-chevron-is-used-as-a-separator-instead-of-colon-for-custom-messages)</sup>, and other libraries like [eslint-plugin-vitest](https://github.com/vitest-dev/eslint-plugin-vitest) also use _"hint"_<sup>[[3]](https://github.com/vitest-dev/eslint-plugin-vitest/blob/main/docs/rules/prefer-snapshot-hint.md)</sup>. 
However, the method signatures currently use `message` instead of `hint`. This can be a source a confusion, since IDEs show the parameter names as you type, and it's not clear if `message` and `hint` are the same thing.
This PR aligns the wording in the method signature with the documentation.

chore(snapshots): rename `message` to `hint` in method signatures

---

packages/vitest/src/node/pools/vmForks.ts
packages/vitest/src/node/pools/vmThreads.ts
packages/vitest/src/utils/memory-limit.ts
test/core/test/memory-limit.test.ts

closes #7952
- Prioritize `poolOptions.vmForks.memoryLimit` over `vmThreads`
---

feat(memory-limit): adjust getWorkerMemoryLimit priority for vmForks

---

README.md
docs/.vitepress/components/FeaturesList.vue
docs/guide/features.md
packages/vitest/src/runtime/execute.ts
test/cli/fixtures/fails/unhandled-suite.test.ts
test/cli/test/__snapshots__/fails.test.ts.snap
test/core/test/unhandled.test.ts

fix: try to catch unhandled error outside of a test

---

docs/guide/browser/index.md

There are two typos in `docs/guide/browser/index.md` where it says ~~baed~~ instead of **based**.
----
From the [deploy preview](https://deploy-preview-7983--vitest-dev.netlify.app/)

docs: typos in docs/guide/browser/index.md

---

docs/config/index.md

I had issues adding `vitest/globals` here: https://github.com/vitest-dev/vitest/issues/7972 because I had redefined my typeRoots in tsconfig.json, so node_modules was not discoverable. I think a word in the doc is appreciable :D

docs: word about typeRoots for typescript configuration

---

docs/guide/cli-generated.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/reporters/index.ts
test/core/test/cli-test.test.ts

closes #7907
- dynamically pulls the names of all build-in reporters from the `ReportersMap`
<div align="center">
<table>
<tr>
<th>--reporter <name></th>
</tr>
<tr>
<td valign="top">
</td>
</tr>
</table>
</div>
---

fix(cli): add built-in reporters list to --help output

---

packages/vitest/src/create/browser/creator.ts
test/cli/fixtures/browser-init/package.json
test/cli/test/init.test.ts

fix: generate a separate config for "vitest init browser" instead of a workspace file

---

docs/api/vi.md
packages/spy/src/index.ts
test/core/test/jest-mock.test.ts

Support [explicit resource management](https://github.com/tc39/proposal-explicit-resource-management) with mocked functions, meaning mockRestore can be called automatically once scope is exited.
```ts
using consoleSpy = vi.spyOn(console, "spy")
// is like
const consoleSpy = vi.spyOn(console, "spy")
try {
// ...
} finally {
consoleSpy.mockRestore()
}
```
This is very convenient, but also good for Jest parity - Jest added it here https://github.com/jestjs/jest/pull/14895 and released in [v30.0.0-alpha.3](https://github.com/jestjs/jest/releases/tag/v30.0.0-alpha.3).

feat: Explicit Resource Management support in mocked functions

---

docs/guide/browser/context.md
docs/guide/browser/locators.md
packages/browser/context.d.ts
packages/browser/src/node/commands/screenshot.ts
test/browser/test/dom.test.ts

feat(browser): add `screenshot.save` option

---

docs/config/index.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/pools/typecheck.ts
packages/vitest/src/node/types/config.ts
packages/vitest/src/typecheck/typechecker.ts
test/typescript/test/runner.test.ts

fix: throw an error if typechecker failed to spawn

---

packages/expect/src/jest-utils.ts
pnpm-lock.yaml
test/core/package.json
test/core/test/expect.test.ts

Fixes https://github.com/vitest-dev/vitest/issues/7991

feat: initial support for Temporal equality

---

docs/guide/reporters.md
packages/vitest/src/node/reporters/github-actions.ts
test/reporters/tests/github-actions.test.ts

This PR adds support for an `onWritePath` option for the GitHub Actions reporter. This can be used to customize the path that's written in [GitHub's annotation command format](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-error-message). This names was taken from `vitest-sonar-reporter` as suggested by this comment: https://github.com/vitest-dev/vitest/issues/8008#issuecomment-2896741513.
This is useful for situations where tests might be run such that their paths don't match the paths that GitHub sees. For instance, if the tests are being run in a container, the paths might start with `/app/`, which GitHub can't map to a specific file in order to attach the annotation.
Closes …

feat(reporter): add `onWritePath` option to `github-actions`

---

packages/vitest/src/node/cli/cli-config.ts
test/core/test/cli-test.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8046

fix(cli): parse `--silent` values properly

---

packages/coverage-istanbul/src/provider.ts
packages/coverage-v8/src/provider.ts
test/coverage-test/fixtures/src/in-source.ts
test/coverage-test/test/in-source.test.ts
test/coverage-test/test/vue.test.ts
test/coverage-test/vitest.workspace.custom.ts

- Exclude in-source tests' `if (import.meta.vitest)` contents from coverage
- Applied to Istanbul and AST-aware V8 only
- the old V8 would require hacky solutions and is being deprecated soon so leaving it out of scope
Before-after:

fix(coverage): in-source test cases excluded

---

packages/expect/index.d.ts
packages/expect/package.json
test/dts-config/tsconfig.json

- Closes https://github.com/vitest-dev/vitest/issues/8076
I forgot about chai import when removing chai patch https://github.com/vitest-dev/vitest/pull/7937. We have `test/dts-config`, but it didn't catch without `compilerOptions.noUncheckedSideEffectImports`.

fix(expect): fix chai import in dts

---

docs/guide/profiling-test-performance.md
packages/browser/src/client/channel.ts
packages/browser/src/client/orchestrator.ts
packages/browser/src/client/tester/tester.ts
packages/browser/src/node/pool.ts
packages/vitest/src/types/browser.ts

The `prepare` time is now very big! (It takes _a long_ time to load the iframe, mostly because of the waterfall)

fix(browser): calculate prepare time from `createTesters` call on the main thread

---

packages/browser/src/client/orchestrator.ts
packages/browser/src/node/middlewares/orchestratorMiddleware.ts
packages/browser/src/node/middlewares/testerMiddleware.ts
packages/browser/src/node/pool.ts
packages/browser/src/node/projectParent.ts
packages/vitest/src/node/logger.ts
test/browser/fixtures/mocking-out-of-root/project1/vitest.config.ts

feat(browser): use base url instead of __vitest__

---

packages/vitest/src/node/reporters/base.ts
test/reporters/fixtures/metadata/metadata.test.ts
test/reporters/fixtures/metadata/vitest.config.ts
test/reporters/tests/default.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8018

fix(reporter): `task.meta` should be available in custom reporter's errors

---

test/reporters/tests/test-run.test.ts

- Related to https://github.com/vitest-dev/vitest/pull/8121, especially this part:
> Note:
> - As `onUserConsoleLog` is not throttled, it's still possible that reporters see test case's console logs before `onTestCaseReady`, if logs happen 100ms within the start. 
> 
This seems to be happening on CI. Let's increase the timeout a bit.

test: flaky test-run timing

---

docs/config/index.md

This fixes the tiniest typo in the documentation (`testToRun` => `testsToRun`).
Since this is in a copy-pasteable code block, it is still annoying for users to debug why their copy-pasted config isn't working.

docs: Typo in doc for `watchTriggerPatterns`

---

docs/guide/migration.md
docs/guide/test-context.md

This pull request corrects minor typos in the documentation:
- Replaces "replaying" with "replaying" in migration guide.
- Fixes "Infering" to "inferring" in test context guide.

Fix Typos in Documentation: "replaying" and "infering"

---

packages/vitest/src/node/pool.ts
test/config/test/failures.test.ts
test/coverage-test/test/shard.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8100

fix(cli): throw error when `--shard x/<count>` exceeds count of test files

---

docs/guide/browser/index.md
eslint.config.js
packages/spy/src/index.ts
test/browser/specs/runner.test.ts
test/browser/test/mocking.test.ts

fix(browser): show a helpful error when spying on an export

---

packages/vitest/src/node/pools/rpc.ts
packages/vitest/src/types/rpc.ts

fix!: remove deprecated getSourceMap

---

packages/vitest/src/types/global.ts

Context: Currently TypeScript accepts code like this:
```ts
interface Foo {
foo(x: any): void;
foo: (x: any) => void;
}
```
While it does not accept code like this:
```ts
interface Foo {
foo: (x: any) => void;
foo(x: any): void;
}
```
The only difference being the ordering.
By comparison, in TypeScript Go neither of these are accepted. See https://github.com/microsoft/typescript-go/issues/1192#issuecomment-2976459707 for official confirmation by Anders Hejlsberg (lead architect of TypeScript). I noticed this effected Vitest due to its merge of `Chai.Assert.containSubset` as a callback instead of as a method, leading to a conflict with `@types/chai`.
No associated issue because it's a small types-only fix.

fix(types): ensure Chai declaration merge works with TS-Go

---

docs/config/index.md
packages/vitest/src/node/reporters/base.ts
packages/vitest/src/node/types/config.ts
test/cli/test/console.test.ts

feat: provide entity to onConsoleLog

---

docs/package.json
packages/mocker/package.json
packages/vitest/package.json

Vitest 4 will use the Module Runner instead of `vite-node`, so we need at least Vite 6. I am not touching `vite-node`'s dependencies here for now, as it will be moved into a separate project before Vitest 4 is released.

feat!: remove support for Vite 5

---

packages/vitest/src/node/stdin.ts
test/watch/test/stdin.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8249
[vitest-workspace-watch-mode-fixed.webm](https://github.com/user-attachments/assets/393e5ba0-b6f9-4f9b-87d7-c308ebcf504b)

fix(watch): filename filter runs duplicate tests in workspaces

---

docs/advanced/runner.md

The page mentions `BenchmarkNodeRunner`, but the exported class is actually called `NodeBenchmarkRunner`.
Source: https://github.com/vitest-dev/vitest/blob/c1f78d2adc78ef08ef8b61b0dd6a925fb08f20b6/packages/vitest/src/runtime/runners/benchmark.ts#L152

docs: Fix typo in Runner API page

---

packages/runner/src/suite.ts
test/core/test/test-extend.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8277

fix: use suite's timeout when `test.extend`

---

packages/vite-node/README.md

With the example of programmatic usage in the README I get the following warning:
```
(!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
Please remove optimizeDeps.disabled from your config.
```
So I updated the example to follow the advice given in the warning and set the `optimizeDeps` config to this:
```js
optimizeDeps: {
// It's recommended to disable deps optimization
noDiscovery: true,
include: undefined,
},
```
This PR also fixes a grammatical error in a comment in the same programmatic usage example
I ran the tests. 8 tests failed. But I'm pretty sure that has nothing to do with this PR

docs(vite-node): Update programmatic usage example

---

.github/PULL_REQUEST_TEMPLATE.md

- Adds reminder about "Allow edits" checkbox to avoid situations like https://github.com/vitest-dev/vitest/pull/7885#pullrequestreview-2956805546

chore: add reminder about "Allow edits" in PR template

---

docs/advanced/api/vitest.md
test/browser/specs/runner.test.ts

This PR addresses two minor typos identified in the codebase.
*   Corrected `inititalised` to `initialised` in `docs/advanced/api/vitest.md`.
*   Corrected `mesage` to `message` in `test/browser/specs/runner.test.ts`.

Fix: Correct typos in documentation and tests

---

packages/runner/src/context.ts
packages/runner/src/suite.ts
packages/runner/src/utils/collect.ts
packages/runner/src/utils/index.ts
test/cli/test/annotations.test.ts

fix: annotation location always points to the test file

---

docs/guide/cli-generated.md
docs/guide/migration.md
packages/vitest/src/node/cli/cac.ts
packages/vitest/src/node/cli/cli-api.ts
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/types/config.ts
test/cli/fixtures/standalone/basic.test.ts
test/cli/fixtures/standalone/vitest.config.ts
test/cli/test/standalone.test.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8175
This is a breaking change to improve overall user experience. It makes sense to start the test run when `--standalone` is used with CLI filename filter.

fix!: ignore `--standalone` when CLI filename filter is used

---

LICENSE
README.md
docs/.vitepress/config.ts
packages/vitest/LICENSE.md

This change reflects that we (@sheremet-va, @antfu, @patak-dev) have assigned the copyright of our code in the Vitest project over to VoidZero Inc. Copyrights of other Vitest contributors remain unaffected and governance of the project remain unchanged. Vitest remains open source under MIT license.

chore: update license copyright

---

docs/api/expect.md

expect.anything doesn't always return `true`. The value it's matching against [mustn't be `null` or `undefined`](https://github.com/vitest-dev/vitest/blob/d06013f2e1f7ebbebfbad32058fb70d51cbc09a7/packages/expect/src/jest-asymmetric-matchers.ts#L98).
See also [jest's expect.anything](https://jestjs.io/docs/expect#expectanything).

docs: clarify condition on expect.anything

---

packages/browser/providers/playwright.d.ts
packages/browser/src/client/tester/context.ts
packages/browser/src/client/tester/expect/toMatchScreenshot.ts
packages/browser/src/client/tester/utils.ts
packages/browser/src/node/commands/screenshot.ts
packages/browser/src/node/commands/screenshotMatcher/index.ts
packages/browser/src/node/commands/screenshotMatcher/utils.ts
packages/browser/src/shared/screenshotMatcher/types.ts
test/browser/fixtures/expect-dom/toMatchScreenshot.test.ts

This PR fixes the issue of masks not being applied correctly when taking a screenshot, as previously discussed in the context of #8041.
Masking elements is an important feature when handling dynamic content in Visual Regression Testing.

fix: screenshot masks with Playwright provider

---

packages/vitest/src/node/plugins/index.ts
packages/vitest/src/node/plugins/workspace.ts
test/core/test/esnext-decorator.test.ts
test/core/test/esnext.test.ts
test/core/vite.config.ts

- Closes https://github.com/vitest-dev/vitest/discussions/8375
Vitest should avoid settings `esbuild` on rolldown-vite since that would be overwritten by users or other plugins `oxc` and it causes noisy warning as more plugins started to adopt `oxc` option. When Vitest configures `oxc`, it overwrites user's `esbuild` option instead, but that's probably fine since `rolldown-vite` is opt-in and users (and ecosystem in general) should adopt to `oxc` option.
Regarding `oxc.target`, I just found it doesn't seem to affect `using` transpilation https://github.com/vitejs/rolldown-vite/issues/352. We should wait until if the behavior is expected there.

fix: configure `oxc` instead of `esbuild` on `rolldown-vite`

---

packages/vitest/src/integrations/env/jsdom-keys.ts
packages/vitest/src/integrations/env/jsdom.ts
test/core/test/environments/jsdom.spec.ts

fix(jsdom): override globals that Fetch API relies on

---

packages/ui/client/components/views/ViewReport.spec.ts
packages/ui/client/composables/error.ts
packages/utils/src/source-map.ts
packages/utils/src/types.ts
packages/vitest/src/api/setup.ts
packages/vitest/src/node/logger.ts
packages/vitest/src/node/printError.ts
packages/vitest/src/node/test-run.ts
packages/vitest/src/utils/source-map.ts
test/browser/specs/runner.test.ts
test/reporters/src/data.ts
test/reporters/tests/__snapshots__/html.test.ts.snap

fix: make sure test errors always have `stacks` property in Node.js context

---

docs/advanced/api/vitest.md
packages/browser/src/node/plugin.ts
packages/coverage-istanbul/src/provider.ts
packages/vitest/src/node/cli/cli-api.ts
packages/vitest/src/node/core.ts
packages/vitest/src/node/coverage.ts
packages/vitest/src/node/types/coverage.ts
test/coverage-test/test/mixed-versions-warning.unit.test.ts
test/coverage-test/test/run-dynamic-coverage.test.ts
test/coverage-test/test/threshold-auto-update.unit.test.ts
test/coverage-test/utils.ts

feat(api): add `enableCoverage` and `disableCoverage` methods

---

packages/utils/package.json
packages/vitest/rollup.config.js

`@vitest/utils` seem to no longer export any files for the `./ast` subpath since https://github.com/vitest-dev/vitest/pull/6289/files#diff-129321e289be10e893aad151367c2631a4cb303e6a5498794777b53bdd767b88L16
I noticed it in https://publint.dev/@vitest/utils@3.2.4

fix(utils): remove ast export

---

packages/vitest/src/integrations/chai/index.ts
packages/vitest/src/integrations/vi.ts
packages/vitest/src/node/config/serializeConfig.ts
packages/vitest/src/node/project.ts
packages/vitest/src/runtime/config.ts
packages/vitest/src/runtime/moduleRunner/moduleMocker.ts
packages/vitest/src/runtime/moduleRunner/moduleRunner.ts
packages/vitest/src/runtime/moduleRunner/startModuleRunner.ts
packages/vitest/src/runtime/runVmTests.ts
packages/vitest/src/runtime/runners/index.ts
packages/vitest/src/runtime/setup-common.ts
packages/vitest/src/runtime/workers/base.ts
packages/vitest/src/runtime/workers/vm.ts
packages/vitest/src/utils/config-helpers.ts
packages/web-worker/src/runner.ts
packages/web-worker/src/shared-worker.ts
packages/web-worker/src/worker.ts
test/coverage-test/utils.ts

This PR reduced the amount of dynamic imports during the setup. This improves the performance slightly (~10ms per test on my PC)

perf: reduce the amount of dynamic imports

---

docs/config/index.md
docs/guide/cli-generated.md
docs/guide/migration.md
docs/guide/parallelism.md
packages/vitest/src/node/cli/cli-config.ts
packages/vitest/src/node/config/resolveConfig.ts
packages/vitest/src/node/pools/forks.ts
packages/vitest/src/node/pools/threads.ts
packages/vitest/src/node/pools/vmForks.ts
packages/vitest/src/node/pools/vmThreads.ts
packages/vitest/src/node/test-run.ts
packages/vitest/src/node/types/config.ts
packages/vitest/src/node/types/pool-options.ts
test/cli/test/scoped-fixtures.test.ts
test/config/fixtures/get-state/vitest.config.ts
test/config/test/failures.test.ts
test/config/test/get-state.test.ts
test/config/test/mixed-environments.test.ts
test/config/test/workers-option.test.ts
test/core/test/web-worker-node.test.ts
test/reporters/tests/html.test.ts
test/test-utils/index.ts

Vitest tries to always keep `minWorkers` workers alive even after all tests have finished running. This adds unnecessary time at the end of the run. It also doesn't make a lot of sense to expose as an option to the users, unlike `maxWorkers` that actually has an impact on test performance.
This PR sets `minWorkers` to 0 during the run mode, reducing the time it takes for Vitest to exit the process after tests have finished running. This PR also removes the public `minWorkers` option.

perf!: remove `minWorkers` and set it automatically to 0 in non watch mode

---

packages/vitest/src/node/plugins/coverageTransform.ts
test/coverage-test/fixtures/configs/vitest.config.multi-transforms.ts
test/coverage-test/test/transform-plugin-order.istanbul.test.ts
test/coverage-test/utils.ts

- Fixes https://github.com/vitest-dev/vitest/issues/8468

fix(coverage): enforce order of `vitest:coverage-transform` plugin

---

packages/browser/src/client/orchestrator.ts
packages/browser/src/client/ui.ts
packages/runner/src/collect.ts
packages/runner/src/utils/collect.ts

Importing `collect` in `utils` blows up the bundle when anything is imported from it (in the browser orchestrator, for example)

fix(runner): don't bundle runner with utils

---

packages/vitest/src/integrations/env/node.ts

This value is only used by `vm`, but it is evaluated for every test file. It takes ~8ms to iterate over it because some properties are getters (like `FormData` that takes 8ms)

perf: delay populating node-globals

---

packages/expect/src/jest-extend.ts
test/core/test/expect.test.ts

When passing a message parameter to expect(), the custom message was not
included in the final error for matchers defined using expect.extend().
fixes #8366

fix: custom expect messages for expect.extend matchers

---

packages/utils/src/source-map.ts
packages/vitest/src/node/environments/serverRunner.ts
packages/vitest/src/node/project.ts
test/cli/fixtures/global-setup-fail/globalSetup/error.ts
test/cli/fixtures/global-setup-fail/vitest.config.ts
test/cli/test/global-setup-fail.test.ts
test/coverage-test/test/run-dynamic-coverage.test.ts

fix: process sourcemaps for stack traces from `globalSetup` files

---

packages/mocker/src/node/redirect.ts
packages/vite-node/src/utils.ts

https://nodejs.org/docs/latest-v20.x/api/module.html#moduleisbuiltinmodulename

refactor: use `isBuiltin` to replace `isNodeBuiltin`

---

packages/ui/client/components/dashboard/TestsEntry.vue
test/ui/test/ui.spec.ts

A small quality of life improvement. 
Making the dashboard summary numbers ("Passed", "Failed" and "Total") clickable.
Clicking on one of them will update the filters.

feat: clickable dashboard numbers

---

docs/guide/migration.md
packages/runner/src/run.ts
packages/runner/src/suite.ts
packages/runner/src/types.ts
packages/runner/src/types/tasks.ts
packages/vitest/src/public/index.ts
test/core/test/task-collector.test.ts
test/core/test/test-options.test.ts
test/core/test/timeout.spec.ts

This order was deprecated and printed a warning in Vitest 3:
```ts
test('hello', () => {}, { timeout: 100 }) 
```
Now it throws an error instead. It was also removed from the types. Please, use this syntax instead:
```ts
test('hello', { timeout: 100 }, () => {}) 
```

feat!: remove deprecated order from test() API

---

packages/runner/src/suite.ts
test/core/test/basic.test.ts
test/core/test/retry.test.ts

fix: correctly inherit test options on extended tests

---

docs/guide/test-context.md
packages/runner/src/suite.ts
packages/runner/src/types/tasks.ts
test/core/test/test-extend.test.ts

This PR adds hooks to the `TestAPI` (`test`), that provide type-safe `ExtraContext`.
Details can be viewed here: #8617.
Tests fail on my branch, but the same tests also fail on the `main` branch. So it doesn't seem to be related to this PR changes.

feat: add hooks with type-safe extra context to TestAPI

---

packages/runner/src/context.ts

I think it resolves https://github.com/vitest-dev/vitest/issues/8630

chore: compare `attachment.body` for `null` & `undefined`

---

packages/ui/explorer.md

I think `WebSocket` is the correct spelling. 
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

docs: correct `WebSocket` spelling
